### ISSUE TITLE
signal crashes while on video call and swiping and zooming images 

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#7344] opened 2018-01-16 07:20 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can get signal to crash while zooming and panning images, while simultaneously being on a video call. This happened 2-3 times in the past two days. The crash occurs after panning, zooming and swiping for approx.2-3 minutes or so.

### Steps to reproduce
- make a video call
- go back to signal, view  "all media" for a conversation
- swipe / zoom / pan around for a while

**Actual result:** signal crashes
**Expected result:** Signal does not crash

### Device info

**Device:** Lenovo Moto G4 Plus
**Android version:** 7.0
**Signal version:** 4.15

### Link to debug log
https://gist.github.com/anonymous/7f461a641e8a733757837211509b69c8

```
01-15 19:21:01.403 12503 12503 E AndroidRuntime: FATAL EXCEPTION: main
01-15 19:21:01.403 12503 12503 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12503
01-15 19:21:01.403 12503 12503 E AndroidRuntime: java.lang.IllegalArgumentException: pointerIndex out of range
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.MotionEvent.getX(MotionEvent.java:2122)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3065)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10162)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4446)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4314)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6257)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6196)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6157)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6360)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6331)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6383)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:613)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
01-15 19:21:01.403 12503 12503 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by pgerber** [comment] 2018-01-16 09:06
duplicate of #7335

**Comment by dcherian** [comment] 2018-01-16 09:17
Oops thanks

**Comment by dcherian** [comment] 2018-01-16 09:17
Oops thanks

**Closed** 2018-01-16 09:17 UTC
