### ISSUE TITLE
Show double check mark in the color of the contact

### ISSUE THREAD

**Issue by KonstantinSchubert** [WhisperSystems/Signal-Android#4935] opened 2015-12-20 21:06 UTC
Other than WhatsApp or Telegram, Signal does not distinguish between a received message and a seen message.

Whatsapp and Telegram indicate that a message has been seen by *coloring* the double check mark.

Signal does not color the double check mark. When I first started using Signal, this really confused me. It felt like something did not work, like the other person wasn't reading my messages.

I think it might help new users if Signal adopted the de-facto standard by coloring the double check mark in the primary color of the conversation.

**Comment by agrajaghh** [comment] 2015-12-20 21:12
duplicate of #2667

**Closed by agrajaghh** 2015-12-20 21:12 UTC
