### ISSUE TITLE
Images don't render correctly after a while

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5957] opened 2016-12-13 18:23 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I sent this file to another Signal user: http://www.xs4all.nl/~johanw/Mugsy13.jpg (I post a link to the exact image in case it matters).

It appeared to go OK, but after a few days the image shows up in the thread as a black image:

![screenshot_2016-12-13-19-08-33](https://cloud.githubusercontent.com/assets/8427572/21153007/fe3decce-c168-11e6-873c-cb0e9cf10abc.jpg)

However, when I click on the image the correct image shows:

![screenshot_2016-12-13-19-09-42](https://cloud.githubusercontent.com/assets/8427572/21153008/fe5e47f8-c168-11e6-83fd-4880099543f7.jpg)

The problem is that not ALL images show up as black rectangles.

### Steps to reproduce
- Send image to someone
- See it back in the conversaton.

### Device info

**Device:** Sony Xperia Z1 Compact
**Android version:** 4.4.4
**Signal version:** 3.24.1

### Link to debug log
https://gist.github.com/anonymous/006890938ddf25f3754577f109b37b2c

**Comment by FeuRenard** [comment] 2016-12-13 22:17
Duplicate of #4732?

**Comment by johanw666** [comment] 2016-12-13 23:07
Looks like it. Seems my search for open issues wasn't thorough enough. Shall I close it?

**Comment by FeuRenard** [comment] 2016-12-13 23:10
I think so, yes.

**Closed** 2016-12-13 23:42 UTC
