### ISSUE TITLE
Push notification reply nullified on additional incoming notification

### ISSUE THREAD

**Issue by LaughingCabbage** [WhisperSystems/Signal-Android#7351] opened 2018-01-19 15:29 UTC
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After receiving a message and entering the push notification reply feature, additional messages will push over the existing reply and the drafted message is lost. 

### Steps to reproduce
- Receive a text
- select reply in the push notification and begin drafting
- receive an additional text
- most recent text pushes over existing draft (end)

**Actual result:** draft message is lost from push notification
**Expected result:** Draft in push notification should prioritize over any additional notifications. Notification draft should mirror a new draft response in the application. 

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.14.10

**Comment by p4nci** [comment] 2018-01-19 16:11
duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6693

**Comment by LaughingCabbage** [comment] 2018-01-19 16:13
Thanks @p4nci

**Closed** 2018-01-19 16:13 UTC
