### ISSUE TITLE
Can't call Signal-iOS

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#4409] opened 2015-11-06 11:04 UTC
After upgrading to 3.3.0 I can't call to iOS anymore. When I downgrade to 3.1.1 the call works OK. I run 3.3.0 on Android 4.4.4. Log at https://gist.github.com/anonymous/e053cff378b73ee7331a

I get this screen when I call from 3.3.0:

![screenshot_2015-11-06-11-49-40](https://cloud.githubusercontent.com/assets/8427572/10995624/8139fcf4-847e-11e5-9b33-43cbfe292d28.png)

**Comment by Dyras** [comment] 2015-11-06 12:29
I can't call Signal-Android anymore. I don't see anything fancy like you when I try to do so on my mom's phone, it's just stuck "Connecting" forever. The phones are on the same WiFi and they are literally right next to each other so... I dunno.

However, when I try to calling her on my phone I see exactly the same thing as you.

From my mom's phone
https://gist.github.com/anonymous/51cf0ff0742fa59e27a8

From my phone
https://gist.github.com/anonymous/c865a3492e3fe3241f6a

**Comment by AlfonsoMuskedunder** [comment] 2015-11-06 13:44
@Dyras, your description sounds quite similar to https://github.com/WhisperSystems/Signal-Android/issues/4267. Unlike the OP, you appear to be still on 3.1.1, so your problem is probably independent from the switch from 3.1.1 to 3.3.0. I've had the problem with both versions.

**Comment by Dyras** [comment] 2015-11-06 13:53
Oh I'm on 3.3.0, I just seem to have posted the wrong log. Ah shit. Firefox isn't syncing. Will update!

**Comment by 2-4601** [comment] 2015-11-06 18:05
What I'm experiencing is most likely the same bug:
1. sometimes when I call with 3.3.0 the call is silent for both parties, i.e. everything looks fine but neither party can hear each other
2. when I end this kind of a silent call and then try to call again Signal gets stuck on the screen @johanw666 posted
3. when I swipe to kill Signal and call again everything works as expected

 Logs from two buggy calls (logs captured after the weird screen, step 2):
* _Nexus 4, 5.1.1, Signal 3.3.0_ **calls another** _Nexus 4, 5.1.1, Signal 3.1.1_
  * https://gist.github.com/anonymous/079dce2bbb03c25b88e5
* _Nexus 4, 5.1.1, Signal 3.3.0_ **calls** _iPhone 4S, iOS 8.4.1, Signal 2.1.3_
  * https://gist.github.com/anonymous/dbd3b5c60d68fa417dc9

**Comment by peterpanondrugs** [comment] 2015-11-06 18:29
Sometimes cant hear other party et vice versa.
 https://gist.github.com/anonymous/53f5456d93a3999cd94e

**Comment by johanw666** [comment] 2015-11-06 19:08
@peterpanondrugs: indeed, a restart of the phone solved the problem. I can call now with that iPhone using 3.3.0.

**Comment by peterpanondrugs** [comment] 2015-11-06 19:26
Update: Problem still occurs sporadically.
- 2nd log https://gist.github.com/10d6b68958a6ebb8bcdb

**Comment by 2-4601** [comment] 2015-11-06 19:36
Swipe to kill works for me, I didn't need to reboot.
@johanw666 This seems to affect both calls to iOS and Android. Would you mind changing the title to reflect this?

**Comment by moxie0** [comment] 2015-11-06 19:58
if anyone can confirm this is resolved in master i'd appreciate it

**Closed** 2015-11-06 19:58 UTC

**Comment by 2-4601** [comment] 2015-11-06 21:04
This is a weird bug and I don't know the exact steps to reproduce but so far I have not encountered this in master. Tested about 10-20 calls.

**Comment by moxie0** [comment] 2015-11-06 22:00
awesome, thanks so much @2-4601

**Comment by johanw666** [comment] 2015-11-06 23:07
I've not seen the bug again on that phone during some calls, master at 56a3c99 .
