### ISSUE TITLE
Annoying banner "Make your profile name and photo visible to this group?" will not go away.

### ISSUE THREAD

**Issue by toddpratt** [WhisperSystems/Signal-Android#6992] opened 2017-09-27 00:52 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I didn't set up a profile, but even if I did, I would want the option not to share my profile with a group.  I can't get rid of this banner and it takes up 33% of the available chat window space above my onscreen keyboard.

### Steps to reproduce
- Go into a group
- Refuse to share profile

**Actual result:**
Banner won't go away (I didn't try sharing because I don't want to share)

**Expected result:**
It should go away and let me talk to my friends in peace.

### Device info

**Device:** Moto G Play
**Android version:** 6.0.1
**Signal version:** 4.10.12

**Comment by FeuRenard** [comment] 2017-09-27 09:03
This is a duplicate of #6927 and/or #6966.

**Closed** 2017-09-27 16:53 UTC
