### ISSUE TITLE
Images from disappearing messages can be saved to phone

### ISSUE THREAD

**Issue by gmsl360** [WhisperSystems/Signal-Android#6636] opened 2017-05-13 15:09 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Images from disappearing messages can be saved to phone before they disappear. They are permanently available afterwards. This is problematic because many people that use the disappearing messages function trust that pictures that are sent remain confidential and cannot be shared.

**Comment by FeuRenard** [comment] 2017-05-13 15:17
Duplicate of #5757

**Comment by jtracey** [comment] 2017-05-13 15:19
If someone wants to save the photo, you can't stop them. The person could take a screenshot, or a photo of their phone, or use a modified version of Signal, etc.. The point of disappearing messages can't be to force behavior on the recipient's device, only to notify the sender's intent and make that behavior the default. If someone sees a disappearing message and still chooses to save it, it's clear they wish to ignore that intention anyway.

At least, IMO. OWS may feel differently.

**Comment by moxie0** [comment] 2017-05-14 14:45
closing as duplicate

**Closed by moxie0** 2017-05-14 14:45 UTC
