### ISSUE TITLE
Low volume and very poor quality

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4467] opened 2015-11-09 20:38 UTC
Low volume (both hands-free talking enabled and disabled) and very poor quality.

Found with Signal 3.1.1 on Samsung Galaxy Note 4 device.

The competing open source app
https://www.simlar.org/en/
is louder and clearer on the same network conditions.

**Comment by 2-4601** [comment] 2015-11-09 20:47
The low volume issue should get better with 3.3.x.

How would you describe the bad quality?

**Comment by moxie0** [comment] 2015-11-09 21:15
Duplicate of #4244

**Closed by moxie0** 2015-11-09 21:15 UTC

**Comment by Norbert80** [comment] 2015-11-09 21:42
Sorry 3.1.1 was a typo. I mean 3.3.1. So it isn't a duplicate. I have to file a new issue #4469 because I cannot re-open this one
