### ISSUE TITLE
Repeated messages in group conversation

### ISSUE THREAD

**Issue by Fuzion24** [WhisperSystems/Signal-Android#5136] opened 2016-01-27 17:12 UTC
I'm sorry for the lack of technical detail here, but just wanted to open an issue to start to address this.

Messages are being sent (or received -- I can't tell which end the error is on) multiple times and it always seems to be three times.

There are 4 participants in the group convo, all of them are using the most recent Play version of Signal-Android, and two participants are additionally using the Signal Chrome extension. 

If there is anything I can do to help debug, feel free to let me know.

**Comment by 2-4601** [comment] 2016-01-27 17:43
Closing as duplicate of #2639.
You can test #3383 if you want.

**Closed by 2-4601** 2016-01-27 17:43 UTC

**Comment by ab0032** [comment] 2016-04-07 04:55
I got a message first seven times, then some other messages from others, then again five times. Others in the group got the message multiple times too, but not 12 times.
