### ISSUE TITLE
Signal reverts back to unsecured messages

### ISSUE THREAD

**Issue by brianpgrissom** [WhisperSystems/Signal-Android#6201] opened 2017-02-09 22:28 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When an SMS message is received from a user that DOES have Signal (but doesn't want to use it at the moment, Signal reponds via SIGNAL vs SMS. It should respond in kind. 
Also, if you try to write an unsecured message to a user who has signal (but wants sms), and you leave the app and come back, or compose and mms and then cancel, signal reverts back to SIGNAL secured messaging.

### Steps to reproduce
- Receive SMS from SIGNAL user
- respond to message (SIGNAL will default to encrypted)

- open new chat with SIGNAL user
- switch to UNSECURED
- leave app
- return to signal, you will be back in secured mode

**Actual result:** SIGNAL defaults to SIGNAL
**Expected result:** SIGNAL should respond in kind when replying, should remember preferences

### Device info

**Device:** Pixel XL
**Android version:** 7.1.1
**Signal version:** 3.28.4

**Comment by haffenloher** [comment] 2017-02-09 22:54
You probably meant to say "reverts back to _Signal_ messages" in the title?

From the description this mostly sounds like a dupe of #2285.

For reasons of security, I don't think an automatic downgrade to an insecure transport is going to be implemented.

**Comment by brianpgrissom** [comment] 2017-02-09 22:56
Yes you're right, that's what I meant 

And why didn't this show up when I searched?

And I understand if not, but I also just noticed it defaults back as soon as I attach an image.

**Comment by 2-4601** [comment] 2017-02-12 18:07
Closing as duplicate

**Closed by 2-4601** 2017-02-12 18:07 UTC
