### ISSUE TITLE
[Request] Video Messaging

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6434] opened 2017-03-23 17:18 UTC
Can you please add the ability to send video messages.
Thanks

**Comment by NinebitX** [comment] 2017-03-24 14:08
Signal already allows sending videos as attachments. You are probably thinking about the ability to capture video directly from within the app. In that case, this is a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/3564 and should be closed.

**Comment by McLoo** [comment] 2017-03-25 08:55
Closing as duplicate. Thanks @NinebitX

**Closed by McLoo** 2017-03-25 08:55 UTC
