### ISSUE TITLE
Unread message divider looks terrible in dark theme

### ISSUE THREAD

**Issue by stephzylstra** [WhisperSystems/Signal-Android#6280] opened 2017-02-22 05:17 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
'New/unread message divider looks awful on black theme and is visually distracting

### Steps to reproduce
- have black/dark theme on
- open app
- open thread that contains new/unread messages

**Actual result:** Unread message divider is visually distracting and is on a white background where the actual text is very difficult to read
**Expected result:** Unread message divider can be turned off, and if shown, is consistent with the theme, and is readable

### Screenshots

![signal](https://cloud.githubusercontent.com/assets/735413/23198240/d8c5b9be-f911-11e6-921a-462806831763.png)

### Device info

**Device:** Google Pixel
**Android version:** 7.1.1
**Signal version:** 3.30.0

### Link to debug log
n/a

**Comment by PiCob** [comment] 2017-02-22 06:09
Duplicate of #6265 (closed already, fix will be included in next release)

**Closed** 2017-02-22 06:34 UTC
