### ISSUE TITLE
UI glitch (3.5.0 regression): Text input box height increases after clearing (caused by new voice message button)

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4645] opened 2015-11-21 10:01 UTC
1) Go into any chat
2) Enter any character into the text input field
3) Delete the character while watching the height of the input field: Note that the height increases slightly leading to a shift of the whole chat history.
4) Enter any character. Note that the height decreases again.
5) When deleting the character height increases again...

Note that this happens in groups and push conversations but not in SMS conversations.

Regression found in Signal 3.5.0 Android.

**Comment by 2-4601** [comment] 2015-11-21 13:20
Which device, ROM and keyboard are you using? Do you have system (Android) emojis turned on or off in Signal's Advanced settings?

Can**not** reproduce on Nexus 4, stock 5.1.1, system keyboard. Tried both system emojis turned on and off.

Can reproduce a similar behaviour with Huawei U8800, Android 4.0.4, system keyboard. But only when system emoji setting is turned off. And the text input field resizing is different than what @Norbert80 experienced. Namely:
* When I type a letter, nothing happens
* When I remove the last letter the input box grows one pixel up and down and then immediately shrinks back to normal. The chat history does not move.

Signal 3.5.0

**Comment by Norbert80** [comment] 2015-11-21 13:25
Samsung Galaxy Note 4

Latest official Samsung Firmware with Android 5.1.1

Default Samsung keyboard

**Comment by Norbert80** [comment] 2015-11-21 14:35
I think it happens when the new (in build 3.5.0 introduced) microphone button slides in and out.

**Comment by art1fa** [comment] 2015-11-22 17:58
I'm experiencing the same bug with Signal 3.5.0 (Nexus 5 / OmniRom using the AOSP keyboard):

![GIF](https://cloud.githubusercontent.com/assets/11131859/11325299/80e78ee6-914a-11e5-8271-7325d54bff54.gif)

**Comment by Norbert80** [comment] 2015-11-22 18:02
Thanks. This is exactly what I experience. It looks like the initial smaller height is the normal height while the increased height is not normal.

**Comment by Norbert80** [comment] 2015-11-23 22:04
@moxie0 in release 3.5.1 the voice message button is missing! Did you remove voice message feature intentionally?

This also suppresses this bug. So it is confirmed that thus bug is caused by the voice message button from release 3.5.0.

**Comment by McLoo** [comment] 2015-11-23 22:08
@Norbert80 see https://github.com/WhisperSystems/Signal-Android/commit/885fc88aad2b45822bfd9734012b76a36355443f

**Comment by Rolf558** [comment] 2016-11-24 22:29
This one is fixed with build 3.23.0 that introduces voice messages again. Could someone please close it?

**Comment by 2-4601** [comment] 2016-11-24 23:30
Seems to be fixed for me too. How about @Norbert80 ?

**Closed** 2016-11-25 01:34 UTC
