### ISSUE TITLE
3.25.0 branch crashes instantly on number registration screen on fresh API 23 emulator

### ISSUE THREAD

**Issue by nikwen** [WhisperSystems/Signal-Android#5954] opened 2016-12-13 14:35 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When compiling the 3.25.0 branch and launching it on my emulator, it force closes instantly.

I can have a quick glance at the number registration screen (I haven't gone through the process on the emulator yet), but then I see the "Unfortunately, Signal has stopped" message.

### Device info

**Device:** Emulator like Nexus 5
**Android version:** 6.0 (Marshmallow) - API 23 (Rev 1)
**Signal version:** 3.25.0 (compiled from development branch)

### Link to debug log
This is what shows up in Android Studio's "Android Monitor" window: https://gist.github.com/nikwen/aa87a282cf6773dc4bf43adb43a03182

**Comment by nikwen** [comment] 2016-12-13 21:58
The change causing this was introduced in https://github.com/WhisperSystems/Signal-Android/commit/1b44bdcd3cafee26f08327f4ba6d9462d5713875.

**Comment by nikwen** [comment] 2016-12-13 22:01
The breaking change seems to have been updating the gradle version to 2.2.3. When checking out 1b44bdcd3cafee26f08327f4ba6d9462d5713875 and changing the gradle version back to 2.1.3 everything seems to work fine.

Diff:

```
diff --git a/build.gradle b/build.gradle
index 9f61aff..0ccd2fc 100644
--- a/build.gradle
+++ b/build.gradle
@@ -6,7 +6,7 @@ buildscript {
         }
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:2.1.3'
         classpath files('libs/gradle-witness.jar')
     }
 }
```

**Comment by nikwen** [comment] 2016-12-13 23:19
This issue is really, really strange. What I've found to happen so far:

When launching the app, it force closes with the following stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: JobConsumer-3
                  Process: org.thoughtcrime.securesms, PID: 19181
                  com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                      at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                      at org.whispersystems.libsignal.state.StorageProtos$SignedPreKeyRecordStructure$Builder.build(StorageProtos.java:7521)
                      at org.whispersystems.libsignal.state.SignedPreKeyRecord.<init>(SignedPreKeyRecord.java:33)
                      at org.thoughtcrime.securesms.crypto.PreKeyUtil.generateSignedPreKey(PreKeyUtil.java:76)
                      at org.thoughtcrime.securesms.jobs.CreateSignedPreKeyJob.onRun(CreateSignedPreKeyJob.java:51)
                      at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
                      at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                      at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

This shows that the last method from the `Signal-Android` project which is called is [`PreKeyUtil#generateSignedPreKey()`](https://github.com/WhisperSystems/Signal-Android/blob/1b44bdcd3cafee26f08327f4ba6d9462d5713875/src/org/thoughtcrime/securesms/crypto/PreKeyUtil.java#L69). In that method a new `SignedPreKeyRecord` object is created. That class is being imported from the [`signal-service-java` library](https://github.com/WhisperSystems/libsignal-service-java). A few function calls down the road (involving the [`signal-protocol-java` library](https://github.com/WhisperSystems/libsignal-protocol-java)), a [StorageProtos.SignedPreKeyRecordStructure](https://github.com/WhisperSystems/libsignal-protocol-java/blob/87fae0f98332e98a32bbb82515428b4edeb4181f/protobuf/LocalStorageProtocol.proto) object is created (the class being created by the [`protobuf` library](https://github.com/google/protobuf)) and its [build() method is being called](https://github.com/WhisperSystems/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/state/SignedPreKeyRecord.java#L33). In that call, a `com.google.protobuf.UninitializedMessageException` is being thrown.

At this point we see that the code that fails

1) is crypto code,
2) hasn't been modified by 1b44bdc and
3) involves calls to the [`signal-service-java`](https://github.com/WhisperSystems/libsignal-service-java), [`signal-protocol-java`](https://github.com/WhisperSystems/libsignal-protocol-java) and [`protobuf`](https://github.com/google/protobuf) libraries.

Given that the following change introduced this regression:

```
diff --git a/build.gradle b/build.gradle
index 9f61aff..0ccd2fc 100644
--- a/build.gradle
+++ b/build.gradle
@@ -6,7 +6,7 @@ buildscript {
         }
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:2.1.3'
         classpath files('libs/gradle-witness.jar')
     }
 }
```

I believe that the issue lies somewhere in the gradle files of the [`signal-service-java`](https://github.com/WhisperSystems/libsignal-service-java) and [`signal-protocol-java`](https://github.com/WhisperSystems/libsignal-protocol-java) libraries.

Maybe we need to update the gradle version or some other Android-related versions there as well.

**Comment by moxie0** [comment] 2016-12-15 00:24
I can't reproduce this (or #5955). Both seem to indicate you've got some weird stuff happening with your build environment. Are you sure both of these hold true in a clean environment?

**Comment by nikwen** [comment] 2016-12-16 14:02
@moxie0 #5955 was fixed for me by the photoview update. So we're left with this issue.

I tested it on my laptop (been previously working on my desktop) and I'm experiencing exactly the same issue there.

Have you tried _exactly_ the following to reproduce it?

1) Open the Android SDK manager and install all updates.
2) Open the AVD manager and create a _new_ virtual device with the following specs:
    **Device definition:** Nexus 5, 4.95", 1080x1920, xxhdpi
    **System image:** Marshmallow, API level 23, ABI x86, target: Android 6.0 (with Google APIs)
3) Clone the master branch without any modifications.
4) Build the master branch using Android Studio (make sure to do the gradle sync Android Studio suggests before that) and run it on the newly created emulator.

**Expected result:** The app opens and I am able to register a phone number.
**Actual result (for me):** I instantly get a popup saying "Unfortunately, Signal has stopped."

![Screenshot](https://cloud.githubusercontent.com/assets/3309657/21265192/85a6e718-c3a0-11e6-82ed-af281c25ad1d.png)

**Comment by moxie0** [comment] 2016-12-16 17:18
I did exactly that, except I built in a completely clean virtualized environment using gradle, and can't reproduce.  The only thing I can think is that you modified some proguard settings to try to fix #5955 and introduced this?  Are you running this in a completely unmodified branch?

**Comment by moxie0** [comment] 2016-12-16 18:40
@nikwen Another bug is that this job shouldn't be running on install anyway. I've changed the code so that it no longer runs on install, which means you'd have to go further into the registration process to reproduce on the latest master.

**Comment by nikwen** [comment] 2016-12-18 16:38
@moxie0 I was using a completely clean master branch. To fix #5955 I suppressed some warnings using ProGuard, but the branch I used did not include these changes.

Given that I am able to reproduce this in two different machines, I'll try setting up a virtual machine and reproducing it in there. If that works, I'll send you the VM so that you can debug the issue.

**Comment by moxie0** [comment] 2016-12-18 18:10
@nikwen Also please try building from the command line: ./gradlew clean assembleDebug

**Comment by nikwen** [comment] 2016-12-18 20:33
@moxie0 Wow, that worked! Using an apk built from the command line allowed me to register my phone number perfectly fine. Going back into Android Studio and building it there brought up the same issue again. I'll investigate further. 😊 

Thanks!

**Comment by moxie0** [comment] 2016-12-18 20:36
Alright I'm going to close this for now, then. Seems like an environment/configuration issue if gradle works. Thanks!

**Closed by moxie0** 2016-12-18 20:36 UTC

**Comment by nikwen** [comment] 2016-12-18 21:32
:tada: :tada: :tada:

I found out why I was having the issue: https://github.com/google/protobuf/issues/2217

Apparently, it's a bug related to the Instant Run feature in Android Studio.

Upgrading Android Studio to 2.3 Beta 1 and the gradle wrapper to Gradle 3.2 as well as using `classpath 'com.android.tools.build:gradle:2.3.0-beta1'` and `buildToolsVersion '25.0.2'` in build.gradle fixed the issue for me, although it cannot be used as a real fix yet.

Alternatively, one can disable Instant Run in the settings. I will create a PR that adds a warning for that to BUILDING.md. I guess someone else will run into the issue again in the future.
