### ISSUE TITLE
Messages in group chats delivered multiple times

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#1771] opened 2014-07-31 10:17 UTC
Hello,
I have a problem with group chats. When I send messages in a group, some of the receipients get the same message multiple times, for apparently no reason.
Is this a known bug? Is there a fix?

**Comment by manhole11** [comment] 2015-03-26 15:27
This is not about mms, but push messages

**Comment by onny** [comment] 2015-03-27 09:39
I also experience this issue. Don't know how to reproduce yet but it might depend on the sender to be online after messaging to a group. Because friends experienced this issue in group chat when I turned my phone into airplane mode after sending to a group ...

**Comment by volcano99** [comment] 2015-04-02 07:21
The problem is indeed with the connection. In a group chat, when you send a message TS sends one copy of that message to every member of the group (instead of sending just one message to "the group"). So when your phone disconnect even for just a few seconds, TS restarts sending the messages from the first recipient -- which may have already received the message. That's why some people get messages ten times, some other just 3, and some others one

**Comment by 2-4601** [comment] 2015-12-23 20:08
Closing this in favour of #2639 as that seems to be _**the**_ issue for this infamous resend bug.

**Closed by 2-4601** 2015-12-23 20:08 UTC
Labels: bug
