### ISSUE TITLE
Add "delivery delay" feature

### ISSUE THREAD

**Issue by jersten** [WhisperSystems/Signal-Android#5278] opened 2016-02-22 18:25 UTC
In CyanogenMod 12/13 Messaging app there is a delivery delay feature.

It would be nice if this was in Signal.

**Comment by moxie0** [comment] 2016-02-22 18:30
Dupe of #895.  Please check existing issues before opening new ones, as the issue template that you  apparently ignored instructed.

**Closed by moxie0** 2016-02-22 18:30 UTC
