### ISSUE TITLE
Signal with Samsung Ultra Power Saving Mode

### ISSUE THREAD

**Issue by eson-schulz** [WhisperSystems/Signal-Android#4945] opened 2015-12-21 18:31 UTC
When using Ultra Power Saving mode on the S6, texts cannot be received using Signal.

After getting a bunch of my friend to install Signal, many uninstalled due to this.

**Comment by 2-4601** [comment] 2015-12-21 19:07
By texts do you mean SMS or Signal messages?

Power saving modes prevent Signal (and other similarly working apps) from receiving background data and thus receiving messages. For example stock Android's power saving mode does the same thing. So if you are not receiving Signal messages when the app is in the background and you are in power saving mode everything is working as intended by the ROM.

**Comment by eson-schulz** [comment] 2015-12-21 19:31
From my friend:

Group messages go to the Samsung texting app in ultra power saving mode, but then when opened in Signal, after ultra power saving mode is turned off, it isn't displayed. 

For sms, the phone didn't receive it until a couple hours after ultra power saving mode was turned off.

**Comment by 2-4601** [comment] 2015-12-21 21:38
Seems that Samsung's Ultra Power Saving Mode _"Ends all running processes/services"_ ([among other things](http://www.techrepublic.com/article/quick-tip-take-advantage-of-samsungs-ultra-power-saving-mode/)). This might explain why Signal can't even get SMS.

You should add Signal to the UPSM white list to be able to use it in that mode.
Closing as ROM / power saving mode issue.

**Closed by 2-4601** 2015-12-21 21:38 UTC

**Comment by Penumbra69** [comment] 2017-01-14 05:21
You do realize of course that WhatsApp and the basic messaging application both work properly in ultra power-saving mode right? That means using signal as a messaging replacement is imperfect because it does not contain the ability to be used within ultra power-saving mode like the other two messaging apps. Twitter can do it. Facebook and do it. WhatsApp can do it. Messaging can do it. Why can't signal? Closing this request seems short-sighted.  To edit the whitelist you must be rooted. Are you trying to say that we need to root our phones to use signal properly in ultra power-saving mode? No I don't think so. I think it is the application developers problem to figure out how to add itself to the whitelist.

**Comment by 2-4601** [comment] 2017-01-14 14:27
@Penumbra69 Does Samsung provide some API to circumvent the restrictions in the ultra power-saving mode? If it does, could you redirect to the documentation?

And if there is really a way for an app to circumvent those restrictions, I wonder why all apps don't do it, thus rendering the whole power-saving mode useless.
So it sounds more like Samsung is the one who has taken care that extremely popular apps like the ones you mentioned (Twitter, Facebook and WhatsApp) work (i.e. have special allowances) in the ultra power-saving mode, while smaller user base apps are forced to suffer the consequences of the battery saving mode.

**Comment by ocram** [comment] 2017-01-14 20:17
> So it sounds more like Samsung is the one who has taken care that extremely popular apps like the ones you mentioned (Twitter, Facebook and WhatsApp) work (i.e. have special allowances) in the ultra power-saving mode, while smaller user base apps are forced to suffer the consequences of the battery saving mode.

This is correct. There was also some issue with the `AlarmManager` component that required the word `alarm` to be present either in the package name or class name of your own components in order to prevent delays: https://code.google.com/p/android/issues/detail?id=194031 Not sure if this is true for other components that need to wake up the device, in which case it would be significant here.

This issue is related to https://github.com/WhisperSystems/Signal-Android/issues/5994, isn't it?
