### ISSUE TITLE
Split long messages to a few messages while you are writing or pasting them

### ISSUE THREAD

**Issue by ghsrcgh** [WhisperSystems/Signal-Android#6699] opened 2017-06-02 17:37 UTC
Please do like in Telegram messenger: remove a limit for a single message (currently it is a 2000 symbols and very annoying). Just split long messages to a few messages while you are writing them or pasting them (when you try to copy/paste long text to a Telegram, it automatically splits and sends to a few messages).

**Comment by nrizzio** [comment] 2017-06-02 17:53
Relates to #5146 and #6692

**Comment by FeuRenard** [comment] 2017-06-02 18:15
Duplicate of #4230

**Closed** 2017-06-02 19:19 UTC
