### ISSUE TITLE
no calls possible

### ISSUE THREAD

**Issue by larokine** [WhisperSystems/Signal-Android#5064] opened 2016-01-13 21:27 UTC
I can't receive or make calls. It rings once, then the line is dead and I get an Error message ("app error").
https://gist.github.com/1b7463471d613cfdd69a

**Comment by agrajaghh** [comment] 2016-01-13 21:31
could you pls try to get another log? there is nothing in it...

**Comment by larokine** [comment] 2016-01-13 21:35
https://gist.github.com/186942f4b5166eac6d69

I hope this works ...

**Comment by agrajaghh** [comment] 2016-01-13 21:51
yep, looks better:

```
01-13 22:28:23.325  1665  4749 D RtpSocket: Connected to: 176.58.114.110
01-13 22:28:23.955  1665  4749 E InitiatingCallManager: Died with unhandled exception!
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: java.lang.IllegalArgumentException: Invalid point
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.spongycastle.crypto.generators.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:73)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.generateKeyPair(KeyPairGeneratorSpi.java:155)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:253)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.<init>(ZRTPSocket.java:106)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPInitiatorSocket.<init>(ZRTPInitiatorSocket.java:56)
01-13 22:28:23.965  1665  4749 W InitiatingCallManager: 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:88)
01-13 22:28:23.965  1665  4749 E MediaPlayer: Uri is  android.resource://org.thoughtcrime.securesms/2131165187
01-13 22:28:23.975  1665  1665 W RedPhone: Got message from service: CLIENT_FAILURE
01-13 22:28:23.975  1665  4749 W RedPhoneService: termination stack
01-13 22:28:23.975  1665  4749 W RedPhoneService: java.lang.Exception
01-13 22:28:23.975  1665  4749 W RedPhoneService: 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:362)
01-13 22:28:23.975  1665  4749 W RedPhoneService: 	at org.thoughtcrime.redphone.RedPhoneService.notifyClientFailure(RedPhoneService.java:476)
01-13 22:28:23.975  1665  4749 W RedPhoneService: 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:113)
```

**Comment by justin-** [comment] 2016-01-23 21:33
Related to https://github.com/WhisperSystems/Signal-Android/issues/4563?

**Comment by agrajaghh** [comment] 2016-03-21 10:44
closing as duplicate of #5233

**Comment by agrajaghh** [comment] 2016-03-21 11:54
same exception here: https://github.com/WhisperSystems/Signal-Android/issues/5233#issuecomment-199175614
```
E/InitiatingCallManager(27949): Died with unhandled exception!
W/InitiatingCallManager(27949): java.lang.IllegalArgumentException: Invalid point
W/InitiatingCallManager(27949): 	at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
W/InitiatingCallManager(27949): 	at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
W/InitiatingCallManager(27949): 	at org.spongycastle.crypto.generators.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:73)
W/InitiatingCallManager(27949): 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.generateKeyPair(KeyPairGeneratorSpi.java:155)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:253)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.<init>(ZRTPSocket.java:106)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPInitiatorSocket.<init>(ZRTPInitiatorSocket.java:56)
W/InitiatingCallManager(27949): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:88)
W/MediaPlayer(27949): info/warning (1, 1143421776)
I/MediaPlayer(27949): Info (1,1143421776)
W/PhoneNumberFormatter(27949): Got local CC: AU
W/RedPhone(27949): Got message from service: CLIENT_FAILURE
W/RedPhoneService(27949): termination stack
W/RedPhoneService(27949): java.lang.Exception
W/RedPhoneService(27949): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:364)
W/RedPhoneService(27949): 	at org.thoughtcrime.redphone.RedPhoneService.notifyClientFailure(RedPhoneService.java:478)
W/RedPhoneService(27949): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:113)
D/LockManager(27949): Entered Lock State: PARTIAL
```

**Comment by 2-4601** [comment] 2017-03-13 21:57
Closing as RedPhone issue.

**Closed by 2-4601** 2017-03-13 21:57 UTC
Labels: bug, redphone
