### ISSUE TITLE
Call Volume

### ISSUE THREAD

**Issue by GuruEaton** [WhisperSystems/Signal-Android#5299] opened 2016-02-29 03:24 UTC
When using the call feature in the signal application. I noticed the call volume is very low compared to performing the call with the default phone application. If a debug log is necessary for this particular issue please inform me and I will have one uploaded as soon as possible.

**Comment by 2-4601** [comment] 2016-02-29 03:32
Thanks, this is a duplicate of #5004.
In the future please use the issue template :)

**Closed by 2-4601** 2016-02-29 03:32 UTC
