### ISSUE TITLE
Add support for any filetype

### ISSUE THREAD

**Issue by lope** [WhisperSystems/Signal-Android#5141] opened 2016-01-28 03:26 UTC
Why does signal place arbitrary limitations on what filetypes can be sent? It's ridiculous.
A file is a file. Signal should not be interested in what files I'm sending, it's supposed to be private?

For example it refused to send a PDF, zip, 7z and so on... :/

**Comment by agrajaghh** [comment] 2016-01-28 07:36
closing as duplicate of #993 

please search for existing issues before opening a new one. Thanks

**Closed by agrajaghh** 2016-01-28 07:36 UTC
