### ISSUE TITLE
Group chat disappears from chat list if disappearing messages is on

### ISSUE THREAD

**Issue by blokeley** [WhisperSystems/Signal-Android#6227] opened 2017-02-15 16:53 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If disappearing messages are set, the group name disappears from the chat list too.

### Steps to reproduce
- Create a new group chat
- Set disappearing messages to a short time
- Let the disappearing time expire

**Actual result:** 
The group chat is no longer in the chat list.

**Expected result:** 
The group chat should be empty but still in the chat list. Otherwise I have to recreate it every time.

### Device info
**Device:** Google Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.29.5?

**Comment by cascheberg** [comment] 2017-02-15 19:31
Duplicate of #6038

**Closed** 2017-02-16 12:49 UTC
