### ISSUE TITLE
Notications always use system emoji instead of Signal's built-in emoji

### ISSUE THREAD

**Issue by kb100** [WhisperSystems/Signal-Android#5360] opened 2016-03-20 18:55 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
If the message preview notification for a message contains an emoji, it will use the system emoji instead of Signal's built-in emoji, even when "Use system emoji" is not enabled.

### Steps to reproduce
- Make sure "Use system emoji" is not enabled
- Unlock your phone and go to your home screen
- Before your screen turns off, have a friend send you an emoji
- Look at the notification that appears, it will show the system emoji
- Pull down your notification tray to see the message preview, it will also use the system emoji there

### Device info

 **Model:** Samsung Galaxy S6

 **Android version:** 5.1.1

 **Signal version:** 3.14.2

**Comment by 2-4601** [comment] 2016-03-20 19:01
Closing as duplicate of #3278 :)

**Closed by 2-4601** 2016-03-20 19:01 UTC
