### ISSUE TITLE
Add visual indicator when a contact's key is veryfied

### ISSUE THREAD

**Issue by hwende** [WhisperSystems/Signal-Android#5339] opened 2016-03-14 14:03 UTC
Since the verification of other peoples keys is very important,
I propose adding a visual indicator to the contact display.
Something like a badge, or a star or lock symbol.
This indicator will be displayed after the user explicitely stated that
he had verified the contacts key.
This is helpful in keeping track of the contact verification status
and also would encourage new users to understand that verifiyng keys is important.

Beste regards
Henning

**Comment by 2-4601** [comment] 2016-03-14 14:05
Closing as dupe of #910.
Please use the issue template when reporting issues.

**Closed by 2-4601** 2016-03-14 14:05 UTC
