### ISSUE TITLE
Signal calls fail sometimes since upgrading to Android 7.0 Nougat on Galaxy S7 Edge

### ISSUE THREAD

**Issue by pricead** [WhisperSystems/Signal-Android#5912] opened 2016-12-02 03:50 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I recently upgraded my Galaxy S7 Edge to Android 7.0 as part of a beta program before Android 7.0 is rolled out publicly on the Samsung S7 series phones. After upgrading and doing a full factory reset, I reinstalled Signal. I am now experiencing a bug where after I make a call with Signal, future calls (either incoming or outgoing) fail. If I try to make an outgoing call, no call is placed, and I see a broken interface with no buttons (screenshot: http://imgur.com/a/IL2im), and I have to use my phone's back button to exit. Full functionality can only be restored by either rebooting my phone, or force stopping the Signal app. 

### Steps to reproduce
- Place or Receive 1st Signal call (so far, everything seems to work; I or recipient answers the call, we are able to converse)
- Call is terminated either by myself or the other party
- Try to place another Signal call
- Broken incomplete interface is displayed and I have to back out of the screen. No call is made or received. 

**Actual result:** Broken interface is displayed and no call is connected
**Expected result:** Call should connect as expected and interface should display that allows one control the call.

### Screenshots

![broken-signal-call](https://cloud.githubusercontent.com/assets/408375/20822360/1623bae4-b818-11e6-919e-9c2b9088525c.png)

### Device info
**Device:** Samsung Galaxy S7 Edge (G935T)
**Android version:** 7.0
**Signal version:** 3.24.0

### Link to debug log
https://gist.github.com/de561d15aa0b47b7398ada6f1a39b8cd

**Comment by pricead** [comment] 2016-12-02 03:53
This seems like a similar problem: https://github.com/WhisperSystems/Signal-Android/issues/5132

**Comment by 2-4601** [comment] 2016-12-02 22:05
Thanks for the report, sounds very much like a duplicate of #5132, #5660

**Closed by 2-4601** 2016-12-02 22:05 UTC
