### ISSUE TITLE
Group messages that are only sent to some of the members may be sent multiple times to all users when attempting to resend.

### ISSUE THREAD

**Issue by WTRXGamer** [WhisperSystems/Signal-Android#5648] opened 2016-08-30 19:09 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a large group chat of Signal users (12), and when a message is sent to some, but not all of the members, (likely due to intermittent internet connectivity) that message may be spammed when the user attempts to resend the message by clicking on it for details, then manually clicking "Resend" to each member, to all members, the number of times the "Resend" button was clicked, plus one if they received the message the first time.

### Steps to reproduce
- Take a group message that failed to send to some users, but not all users.
- Click "Resend" on all of the users it failed to send to the first time.
- For every time the "Resend" button is pressed, all users will receive the message again, if this time it is successful.

**Actual result:** 
So I walked around a large building that I was in, while on data, sending messages until one of them failed to send to some users, but not all. I then walked outside of the building, to where I had a good data connection, and pressed the "Resend" button on all of the users. Instead of re-sending to just the ones that were clicked, all users received the message, and those that had received it the first time, received it once more.
 
**Expected result:** 
If a message fails to send to some users, when I press the "Resend" button to a specific user, it should resend the message to ONLY that user, or to all users that failed originally, but preventing the user from pressing the "Resend" button again, unless the resend fails once more..

**Notes**
- All users that have caused the spam have been Android users.
- I believe this might be caused by rapidly pressing all of the "Resend" buttons before Signal Resends the message.

### Device info

**Device:** Galaxy Note IV
**Android version:** 5.1.1
**Signal version:** 3.17.0

### Link to debug log
https://gist.github.com/anonymous/879a9a137d8874e854b38a87d34a240b

**Comment by WTRXGamer** [comment] 2016-08-30 19:16
I think a possible solution to this would be to have one resend button at the top of the message info page, instead of placing multiple buttons, next to each user that it failed to send to.

**Comment by FeuRenard** [comment] 2016-08-30 19:37
Will be fixed by #3383.

**Comment by Trolldemorted** [comment] 2016-08-31 12:19
more like 'could be fixed'.

why do you have resend-buttons at all? shouldn't the app handle that w/o user interference?

**Comment by 2-4601** [comment] 2016-09-01 10:06
Yup, dupe of #2639, #3582

**Closed by 2-4601** 2016-09-01 10:06 UTC
