### ISSUE TITLE
problems with group transitions between devices

### ISSUE THREAD

**Issue by benmayne** [WhisperSystems/Signal-Android#4836] opened 2015-12-08 05:23 UTC
I recently changed from ATT galaxy s4 to nexus 5x. One of my old groups messaged me and I couldn't reply or type. Starting a new group works. 

https://gist.github.com/anonymous/ad4f73cf14aaa6fce0ce

Incidentally, the transition seems smooth on signal desktop as you can see from the sent message in the screenshot that I was able to send from desktop. 

![2015-12-08 05 16 49](https://cloud.githubusercontent.com/assets/3374110/11648378/bb9cba7c-9d28-11e5-9f15-f3f3b8c21f45.png)

![2015-12-08 05 16 57](https://cloud.githubusercontent.com/assets/3374110/11648381/bf560268-9d28-11e5-851b-9e7278a236c8.png)

**Comment by 2-4601** [comment] 2015-12-08 17:06
Duplicate of #2581 (and maybe #1048, #1029 among others)
Workaround: Ask someone in the group to update the group. Any kind of an update should do it.

**Closed** 2015-12-08 17:12 UTC
