### ISSUE TITLE
Signal Icon in App Drawer/Home should return the user to last viewed screen.

### ISSUE THREAD

**Issue by HunterMRose** [WhisperSystems/Signal-Android#5725] opened 2016-09-27 20:24 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When Signal is called from the "Recent Apps List", or "Overview" the user is properly returned to the window they were last using. 

However, When Signal is selected from App Drawer, or Home, the conversation list is always displayed as if first being run.

This is nonstandard from other messenger apps and does not give the user the functionality they expect.

### Steps to reproduce
- Select Signal from either Home or App Drawer
- Select a conversation
- Press the Home Key
- Select Signal from home or App Drawer

**Actual result:** 
When selecting signal from either the app drawer or home screen you are always presented with the same conversation list.

**Expected result:** 
A New user expects selecting signal from the app drawer or home screen to return to the last open window (be it the last conversation, setting screen, etc) just as if they selected it from the recent apps list.

**Comment by Dyras** [comment] 2016-09-28 16:02
Please make this optional, I actually like the way it is now.

**Comment by TimesEnemy** [comment] 2016-09-28 16:21
I would prefer this be optional as well, if at all.  I like it as is.

**Comment by FeuRenard** [comment] 2016-09-29 18:02
This is a duplicate of #1311.

**Closed** 2016-09-29 18:34 UTC
