### ISSUE TITLE
Feature Request: Ephemerous messages (local AND remote)

### ISSUE THREAD

**Issue by mazieres** [WhisperSystems/Signal-Android#4517] opened 2015-11-13 14:40 UTC
Any plans to add the same feature as Wickr ? ie. allowing one user to attach to a message a period at the end of which the message is destroyed locally and remotely (on both the sender and receiver phones).

Like you can see on this screenshot of Wickr, you set up a time bomb on every new message, and all past message have an indication of when they will be deleted:

![Wickr time bomb](http://www2.pcmag.com/media/images/434080-wickr-inline-1.jpg?thumb=y)

Signal allow this locally but not remotely such as Wickr does. With this feature, there would be no more reason to use Wickr over Signal !
Thanks !

**Comment by nono2357** [comment] 2015-11-13 14:53
+1 ! That would be very useful and nice for privacy.

**Comment by c24b** [comment] 2015-11-13 15:05
+1 would be a good improvement

**Comment by JulienPalard** [comment] 2015-11-13 15:06
:+1:

**Comment by agrajaghh** [comment] 2015-11-13 15:11
it has been said several times that these "+1" messages are annoying to the devs, because they'll get a mail for every single message. 

besides its a duplicate of #1764

**Comment by haffenloher** [comment] 2015-11-13 15:11
Please close this, it is a duplicate of #1764.
Also, in the future please refrain from adding "+1" posts to issues. For every one of these, every developer gets an email.

@mazieres: It is technically impossible to guarantee that a message you sent will be deleted from the recipient's device. If anyone tells you their software can provide that guaranty, they're selling you a false sense of security.

**Comment by nono2357** [comment] 2015-11-13 15:14
#1764 is only about manual deletion, not automatic deletion based on time-limited messages

**Comment by 2-4601** [comment] 2015-11-13 15:18
FAQ: http://support.whispersystems.org/hc/en-us/articles/213134237-Why-doesn-t-Signal-have-self-destructing-messages-or-remote-deletion-functionality-

**Comment by nono2357** [comment] 2015-11-13 15:20
That's why it should be an optional feature, user is responsible to use it or not and cannot rely only on this for privacy.

**Comment by 2-4601** [comment] 2015-11-13 15:28
https://github.com/WhisperSystems/Signal-Android/blob/master/contributing.md#development-ideology
> 1. The answer is not more options. If you feel compelled to add a preference that's exposed to the user, it's very possible you've made a wrong turn somewhere.

And most users would not understand the consequences of enabling such feature.

**Comment by nono2357** [comment] 2015-11-13 15:31
Why do you suppose most users are dumb so a desired feature is useless?

**Comment by mazieres** [comment] 2015-11-13 15:33
Sorry for the +1s

I agree with @nono2357 It's a different request.
Such feature would be understood by most users I guess, given its already quite popular among snapchat users, and [in discussion on Facebook](http://techcrunch.com/2015/11/12/facebook-messenger-ephemeral/).
It's indeed not screenshot-proof but it's phone-history-proof, which is the whole point of this feature.

**Comment by 2-4601** [comment] 2015-11-13 15:52
@nono2357 
> Why do you suppose most users are dumb so a desired feature is useless?

I did not call anyone dumb (that was your own comment). I said "most users would not understand the consequences of enabling such feature."

And the first few comments on this issue are a pretty good indicator of that. Even if the people who have learned to use GitHub think remote deletion is good ("nice for privacy") how are the majority of the user base going to understand it? Signal should not provide the user features that allow themselves to shoot on their foot.

**Comment by 2-4601** [comment] 2016-10-06 10:57
In 3.20.0

**Closed by 2-4601** 2016-10-06 10:57 UTC
