### ISSUE TITLE
In-thread notification sounds do not respect Android priority mode

### ISSUE THREAD

**Issue by whatchanged** [WhisperSystems/Signal-Android#4794] opened 2015-12-03 21:47 UTC
With Android sounds set to "Priority Mode", the incoming message notification sound is still audible when viewing an active conversation.  I believe that if priority notifications are turned off for Signal, then all notifications, including in-thread notifications, should be silenced when Android is in priority only mode.  So, these in-thread notifications should be silenced as well in "Priority" mode since they are not priority notifications.

To clarify, the android priority setting works for the other notifications from the Signal app; the issue only affects the "in-thread" notifications.  I am using Signal 3.6.1 on Android 5.1.1.  I have an LG Nexus 4 device with T-Mobile USA as the carrier.

**Comment by 2-4601** [comment] 2015-12-03 22:11
Duplicate of #3337.

**Closed** 2015-12-03 22:26 UTC
