### ISSUE TITLE
Play sound when call ends 

### ISSUE THREAD

**Issue by ByteHamster** [WhisperSystems/Signal-Android#5709] opened 2016-09-21 18:46 UTC
Especially when the internet connection is bad, Redphone calls sometimes break. It would be great to hear a sound as soon as a call ends, because I happened to continue talking quite often without noticing that the call is already over. The feature is available in normal phone calls too, so I think Signal should definitely have it.

**Comment by FeuRenard** [comment] 2016-09-21 19:53
This is a duplicate of #4319.

**Closed** 2016-09-21 19:55 UTC
