### ISSUE TITLE
Ability to force disable encryption for certain contacts

### ISSUE THREAD

**Issue by Farfie** [WhisperSystems/Signal-Android#7116] opened 2017-10-21 18:32 UTC
Not really a bug, and sorry if this is already a thing somewhere in the issues, but right now, if someone had Signal on an iphone, and got rid of it, the android app doesn't pick up on it automatically, and you have to manually send them "insecure" texts by holding down the send button first. A way to just select unsecure as a default, or perhaps a conversation setting that tells signal to just send regular old messages until changed in the future, would be great. Thanks.

**Comment by FeuRenard** [comment] 2017-10-21 22:16
Duplicate of #2285

**Closed** 2017-10-23 16:41 UTC
