### ISSUE TITLE
Feature Request: Voice messages

### ISSUE THREAD

**Issue by Delphiq** [WhisperSystems/Signal-Android#4510] opened 2015-11-13 04:25 UTC
Hi,

I could not find a similar issue.

I would love to be able to hold to speak, release to send voice messages a la telegram and whatsapp. Great app but this feature would be great.

**Comment by ChaoticMind** [comment] 2015-11-13 08:47
Duplicate of #3563

**Closed** 2015-11-13 16:23 UTC
