### ISSUE TITLE
Support direct share to conversations from other apps

### ISSUE THREAD

**Issue by superduperuser** [WhisperSystems/Signal-Android#5572] opened 2016-07-13 01:14 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Android 6.0 and above now allows messaging apps to show conversations directly in the "share" option of other apps. Of the apps that I know of, Hangouts, GroupMe, and Telegram all now support this. It's very convenient and would be a nice addition to Signal. 

This article describes the feature more in detail. http://www.androidpolice.com/2015/06/02/android-m-feature-spotlight-direct-share-can-provide-share-links-to-specific-contacts-or-conversations-inside-apps/

### Screenshots

![nexus2cee_direct-share-screen](https://cloud.githubusercontent.com/assets/20377747/16717426/fdc07be0-46e3-11e6-82b1-1be9d1176b1d.png) <img src="https://cloud.githubusercontent.com/assets/20377747/16788641/af83c076-4874-11e6-9a6c-43d2de240bf5.png" width="340"/>

### Device info

**Android version:** 6.0 & above

**Comment by Kamul-PL** [comment] 2016-07-25 18:42
AFAIK Signal doesn't let messages sharing at all. That's not good for me, because I often share ColorNote checklists with different users (and also receive shared checklists). Because Signal don't let that, I still have to use Google Messenger as main SMS app.

**Comment by superduperuser** [comment] 2016-07-25 18:50
I'm not sure about sharing ColorNotes, but it does allow sharing in general, as you can see in the second screenshot above (right after Sync Pro). Are we referring to the same thing?

**Comment by Kamul-PL** [comment] 2016-07-25 19:05
You mean it is possible in Signal to share a received message?? Could you tell me how to do that? In other apps it's usually done by long pressing on the message and then choosing "share" button. But I'm not able to find such an option in Signal.

**Comment by superduperuser** [comment] 2016-07-25 19:12
Well the bad news is that that is not we're not talking about the same thing. The good news is yes, you can. You hold down the message, then click on the three dots, and then "Forward message". You can't share to other apps, but you can share to SMS and Signal users.

**Comment by Kamul-PL** [comment] 2016-07-25 19:19
But what I need is to share to other apps. Someone share a checklist in ColorNote to his SMS app. Then I receive his SMS. The next step should be to share the received SMS content from Signal to my ColorNote.

Thanks anyway!

**Comment by FeuRenard** [comment] 2016-08-10 11:59
Is this possibly a duplicate of #4333?

**Comment by 2-4601** [comment] 2016-08-15 20:48
Closing as dupe of #4333.

**Closed by 2-4601** 2016-08-15 20:48 UTC
Labels: feature
