### ISSUE TITLE
Making multiple Signal voice calls fails on Android 7.0

### ISSUE THREAD

**Issue by mmirg** [WhisperSystems/Signal-Android#5660] opened 2016-09-02 22:05 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Making multiple Signal voice calls fails.  Tested on two different Nexus 6P phones and one Nexus 5X with identical results.
### Steps to reproduce
- Start Signal
- Place a voice call that is answered
- Hang up
- Attempt to place another call

**Actual result:** 
Attempting a second call will cause the UI to briefly hang, display an erroneous call screen and not initiate the call.
**Expected result:** 
Multiple calls should be able to be made without force closing Signal in between each placed call.
### Screenshots

![screenshot_20160902-235938](https://cloud.githubusercontent.com/assets/4317194/18219362/5df53dac-7169-11e6-8ef4-8afa3298a5da.png)
### Device info

**Device:** Nexus 6P
**Android version:** 7.0.
**Signal version:** 3.18.1
### Link to debug log

https://gist.github.com/9b044a58ac267283cd089b8652468298

**Comment by mmirg** [comment] 2016-09-08 01:51
This issue seems to have been resolved in 3.18.2.

**Comment by mmirg** [comment] 2016-10-07 22:25
While slightly alleviated on 3.20.1, I'm still seeing a variation of this bug.  It doesn't happen as frequently as simply making two consecutive calls but I notice it when my call is interrupted or otherwise unexpectedly terminated.  When I explicitly end a call (or the other party does), I seem to be able to place another call.  If not, it is as if the call never properly ended and I have to force quit and restart Signal to be able to place another call.

**Comment by francisrizzo** [comment] 2016-10-26 21:42
I can confirm this is also happening on 3.20.4 on a Nexus 5X. It normally occurs when I'm speaking with a person on an iPhone (if it matters) and their call is dropped due to receiving another call. I go to try them back and get the screen posted above. Closing the app doesn't resolve and only rebooting the phone fixes the issue and allows me to place another call. Meanwhile if the other person calls me back it just rings on their end but never on mine. It's repeatable every time their call drops.

**Comment by mmirg** [comment] 2016-10-30 16:26
I can second francisrizzo's experience.  I tend to notice this when speaking to someone else on an iPhone but I haven't tested this in a systematic fashion to know if it is an important element.  One of the people I called with an iPhone indicated that there was issue on their end as well with the call not terminating properly, but it seems that one reason that I see this phenomenon more with iPhone users is that calls are easily interrupted when on an iPhone, I am lead to believe that receiving an incoming call (or other notifications?) will silently terminate the Signal call with no notice to either party who may have been on the call.  I can't personally speak to this as I do not own an iPhone.

**Comment by khers** [comment] 2016-10-31 17:27
I see this issue when I speak to android users as well as iphone users, I don't think it is specific to the iphone client.  As an added problem, after hanging up a signal call with a user, my phone will not ring when they call me over the normal cell service either.  Force killing Signal will allow calls through again.

**Comment by 2-4601** [comment] 2016-11-03 20:15
This issue seems to be about initializing calls. There's an open issue about normal cell service becoming unavailable after a Signal call: #4703. But I don't think anyone knows how to consistently reproduce that.

**Comment by khers** [comment] 2016-11-03 21:55
I was trying to say that I see this issue as well as the one in #4703.  After hanging up a signal call.  I cannot call out to the person with signal or plain cell service and they cannot call me with either method.

**Comment by Jayman007** [comment] 2016-11-10 04:20
I have this exact same issue. 

Here are my debug logs. 

https://gist.github.com/0bea7f52bee5c955e1ebadd0e640a6ab

**Comment by 2-4601** [comment] 2016-12-02 22:06
Related or possibly dupe of #5132

**Comment by robert128** [comment] 2016-12-09 23:56
I have the same problem on my Nexus 5X with the 7.1.1 update.  I first noticed this when my calls to an iPhone suddenly die after about 5 minutes, after which I can no longer make calls.  So the inability to keep a phone call going are also part of the problem.

Here's my debug log:

https://gist.github.com/6164f1fa4f7a60b6c14ca2462408dfd0

**Comment by malkhamis** [comment] 2016-12-11 21:58
I am experiencing the same issue on my Nexus 5X device regardless of the Android version actually. The same problem also existed in previous Android versions. A Signal call would drop periodically and I would not be able to place another call unless I terminate Signal and start it again. 

This is the debug log:
https://gist.github.com/8cc85c9b81d27db4d3838c9d4847d318

**Comment by Jayman007** [comment] 2016-12-11 22:06
I forgot to mention that I also have a nexus 5x.  My debug log is issued a few posts back. Seems quite a few 5x are having this issue running different versions of Android

**Comment by Jayman007** [comment] 2016-12-11 22:14
I just tested again and pertinent still exists. 

https://gist.github.com/923c8657653db92870d795745e4faac3

**Comment by malkhamis** [comment] 2016-12-12 03:26
@Jayman007  you just reminded me that this problem was not as bad in one of my very old Sony Xperia Device.

**Comment by jnns** [comment] 2016-12-23 11:51
Issue also present on Nexus 5 (hammerhead) and CM 14.1 (Android 7.1) using Signal 3.25.3.

**Comment by petcap** [comment] 2017-01-19 10:43
Same problem here on Nexus 5X / Android 7.1.1. Also seen this problem on my older Nexus 5. Both running Signal 3.26.2. For me, it happens if the other party hangs up on me, but never if I am the one who hangs up a call. I have to force close Signal when it happens in order to be able to call or receive calls.

**Comment by ladurera** [comment] 2017-01-26 10:20
Exactly the same problem on OnePlus 3t on Oxygen OS 4.0.2 /Nougat 7.0  - calls are interrupted seemingly without any reason, new calls only possible after killing signal. (Same black screen) but only solves it temporarily. Having about 5 of these disconnections in an hour of on and off calling.
Other end is using iOS. Makes it impossible to rely on the calling feature unfortunately..
https://gist.github.com/36c914a1cebc5a0ccdfbbf645ba98693

**Comment by lukehutch** [comment] 2017-01-26 19:13
I filed the dup, #6090. I would add that there are a couple of separate, interrelated bugs here:

1. The call gets successively choppier over time, until eventually the call drops.
2. After the call drops, the call can't be re-placed. This affects both callers (which may indicate server involvement?).

**Comment by mmirg** [comment] 2017-02-01 13:49
Have any of the developers been able to reproduce this bug on their device?  I have now observed similar behavior to #4703 and am unable to receive PSTN calls after I have a call disconnected and wonder if this a dupe of that bug.  As has been mentioned by other commenters on this and related bug threads, it's effectively a show-stopping bug for using Signal for voice calls and seems to be an inability to properly terminate calls in Android 7.x.  Given the practical severity of this bug, I would actually be happier with a situation where calls were terminated over-eagerly provided that I could be reached again.  It's annoying but easy to place a second call after a disconnection but it is difficult when I am unaware that I cannot be reached by either Signal or the PSTN after a Signal voice call fails to terminate properly.

**Comment by petcap** [comment] 2017-02-15 12:45
The latest version (i.e. 3.29.6) fixes this issue for me if and only if both parties enable the new video calling feature (which also includes better audio codecs). If either (or both) parties does not enable this feature, the problem remains.

**Comment by moxie0** [comment] 2017-02-16 07:09
I have not been able to reproduce this, but if it's happening w/ the new calling code I'll take a closer look. If anyone can come up with steps to reproduce w/ the new calling code that would help.

**Comment by malkhamis** [comment] 2017-02-16 07:34
I confirm that the voice volume is WAY better now after upgrading to Signal 3.29.6 and using the video chat. I tested it on a Nexus 5X Android 7.1.1 calling another person having Nexus 5X Android 7.1.1 as well and another person using Samsung Galaxy (not certain about model);

I have noticed that at occasions, the other party wouldn't hear my voice at all right after the connection is established and after I restart my device, the other person would hear me in the new Signal call. Prior to restarting the device, I made a regular phone call and the other party was able to hear me fine.

**Comment by mmirg** [comment] 2017-02-16 14:27
The only way in which I have been able to reproduce it with the new calling code is if a new call is attempted after a failed old RedPhone call.  Otherwise, I'm unable to reproduce this bug with the new WebRTC calling code so I believe this bug would become moot once the calling system transitions completely.

**Comment by petcap** [comment] 2017-02-16 21:19
@mmirg I was actually playing around with the old system as well, so that might have been the reason why it stopped working for me too. I will keep trying and see if I can reproduce this bug.

@moxie0 This bug affects (mostly?) devices running stock Android it seems, both my Nexus 5 and my Nexus 5X are affected. My friends who use stock Android are also reporting the same issue. Never seen the bug on any other device (tested it on some Samsung devices a while back).

**Comment by petcap** [comment] 2017-02-18 20:48
I have attempted to reproduce this bug over and over with beta video calling enabled on multiple devices and so far I have not succeeded. I can also confirm that the audio volume issue is no longer a problem, calls to people that used to be horrible are now crystal clear.

**Comment by malkhamis** [comment] 2017-02-18 23:53
![screenshot_20170218-135848](https://cloud.githubusercontent.com/assets/14809569/23097783/625a7368-f5f2-11e6-8c9c-654cd17d1d69.png)

this might help
https://gist.github.com/anonymous/8a02bc09dd851ecfb1b567e322bcec60

**Comment by notMyUsername** [comment] 2017-03-15 16:47
Is this still happening or is it fixed now that the new video/voice calling is turned on by default?  I had completely stopped using Signal voice calling several months ago (Nexus 5X, stock Android 7.1.1) because I was having to force stop Signal every time I used voice calling otherwise it wouldn't work anymore and I would either not be able to make calls, or worse, would miss important calls.

I'm not criticizing... I just need to know if it's back to working reliably again or not.

**Comment by moxie0** [comment] 2017-03-15 16:53
should be fixed so long as everyone you're calling has updated. the next release will no longer do redphone calls at all

**Closed by moxie0** 2017-03-15 16:53 UTC
Labels: redphone, webrtc

**Comment by robert128** [comment] 2017-03-15 17:19
I had repeated failures yesterday on my Nexus 5X, calling to an iPhone.   Call dropped and I had to force close the app to get it to make another call.  The iPhone user says his app was the previous version to what was updated 2 days ago.

**Comment by moxie0** [comment] 2017-03-15 18:00
There was a bug with the iOS release that caused some users who updated not to get registered as having updated.  If the iPhone calls you, it should be different.

They've submitted an update and are waiting on appstore approval.  =(

**Comment by petcap** [comment] 2017-03-15 19:31
I've had no issues at all since the latest update. Most of my friends does however use Android and not iOS.
