### ISSUE TITLE
Delivery confirmation not carrying over from Signal Desktop to Android in group chats

### ISSUE THREAD

**Issue by superduperuser** [WhisperSystems/Signal-Android#5573] opened 2016-07-13 16:01 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The second checkmark that should be displayed when a message is delivered to the recipients does not show up on Signal for Android when the message is sent from Signal for Desktop. The message itself shows up, but not the delivery confirmation. Messages sent from Android do show up as confirmed delivered on the desktop, so I believe this is an issue with the Android version. This bug only happens in a group chat, private messages do not encounter this problem. This bug makes it hard to keep track of what has been delivered and what hasn't. I have confirmed that all of the messages in the screenshots were delivered by talking to the recipients in person. 

### Steps to reproduce
- Connect Signal on Android and desktop
- Send a message from the desktop version to a group chat
- Check the conversation on Android

**Actual result:** Messages don't show delivery confirmation on Android, but do show it on desktop
**Expected result:** Messages show up as delivered on both

### Screenshots
The messages sent in this first set of screenshots were sent from my desktop. Notice that the delivery confirmation is missing in the Android version. 
![screenshot1](https://cloud.githubusercontent.com/assets/20377747/16808458/9c99a018-48ea-11e6-9196-67f5ef05eb00.png)
<img src="https://cloud.githubusercontent.com/assets/20377747/16808475/a7a8b340-48ea-11e6-9fa1-935d7b70e49f.png" width="400"/>

As a comparison, these messages were sent from my Android. The delivery confirmation does transfer to my desktop. 
![screenshot2](https://cloud.githubusercontent.com/assets/20377747/16808479/ab1ef5ca-48ea-11e6-9875-3ec51f145f44.png)
<img src="https://cloud.githubusercontent.com/assets/20377747/16808483/b0c076a2-48ea-11e6-945e-0b720caa7f70.png" width="400"/>

### Device info
**Device:** Motorola Nexus 6; Windows Desktop
**Android version:** CyanogenMod 13, Android 6.0.1
**Signal version:** 3.16.0 Android; 0.16.1 Desktop

### Link to debug log
https://gist.github.com/anonymous/425ddb3e370d74bcb8948f3d9ab69b96

**Comment by Trolldemorted** [comment] 2016-07-13 16:06
Since it works the other way round, i think this might be a problem of Signal-Desktop.

Anyway, my nexus4 and everyone i asked about it has the same issue.

**Comment by superduperuser** [comment] 2016-07-13 16:14
I guess it depends on whether delivery confirmations are supposed to be forwarded by the desktop client (in which case it's Signal-Desktop's problem) or fetched by the Android client from the server/recipients (in which case it's Signal-Android's problem). I'm not familiar with the code so I can't be sure. If someone is able to demonstrate that Signal-Desktop is at fault then this issue can be closed and I'll post on the Signal-Desktop issue page instead.

**Comment by 2-4601** [comment] 2016-07-13 16:16
Thanks for the detailed bug report! :+1: 
This is a dupe of #4924.

**Closed by 2-4601** 2016-07-13 16:16 UTC

**Comment by superduperuser** [comment] 2016-07-13 16:35
Shoot, I missed that one. Sorry about the dupe!
