### ISSUE TITLE
[Feature Request] Add possibility to sign up without phone number

### ISSUE THREAD

**Issue by Hocceruser** [WhisperSystems/Signal-Android#6508] opened 2017-04-08 15:17 UTC
I would appreciate it if it would be possible to sign up without giving you a phone number. This would be another advantage over WhatsApp. 
Of course, Signal promises not to save it but I still can't understand why I should install a crypto messenger and then have my phone number transferred to some server somewhere in the world.

If it is necessary that every user has a number, users who do not want to use their own number could get  another, randomly created number (which starts with 000, for example).

There is another crypto messenger, "Hoccer", with which this is already possible.

**Comment by nrizzio** [comment] 2017-04-08 15:22
This is a duplicate of #1085.

**Comment by Hocceruser** [comment] 2017-04-08 15:57
I had not seen this, sorry.
But why has #1085 been "locked and limited to collaborators"?

**Comment by nrizzio** [comment] 2017-04-08 16:26
This repository is pretty strict about [not bumping issues](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues), which is why the other issue was locked. Additionally, discussion should go [on the forum and not on the issue tracker](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum). I highly suggest that you read through the contributing file in its entirety.

Someone already made a forum post [here](https://whispersystems.discoursehosting.net/t/registering-with-an-email-address/919).

**Comment by moxie0** [comment] 2017-04-08 22:41
Closing as duplicate

**Closed by moxie0** 2017-04-08 22:41 UTC
