### ISSUE TITLE
Image corruption when using direct capture

### ISSUE THREAD

**Issue by jtracey** [WhisperSystems/Signal-Android#3752] opened 2015-07-22 08:43 UTC
Whenever attempting to use the direct capture feature, after taking the picture, it shows up in the draft view (and in the sent picture) as noise. Whatever is going on is deterministic, as visually similar scenes create visually similar corrupted pictures, and visually different scenes create visually different images.

This is the draft of a picture of a grey wall:
![garbage draft](https://cloud.githubusercontent.com/assets/2998852/8819195/b042331a-2ffe-11e5-9d11-106eafd9aea7.png)
This is after it's sent to myself (though this happens to any recipient):
![garbage sent](https://cloud.githubusercontent.com/assets/2998852/8819204/ca1e4706-2ffe-11e5-9e2b-b688c6d4158b.png)
The loading-wheel-of-death is also probably a bug, but unrelated, and only happens when sending to myself, so not really a major concern.
The actual picture it sends:
![textsecure-2015-07-21-225416](https://cloud.githubusercontent.com/assets/2998852/8819218/fd496a34-2ffe-11e5-8ccc-37b3268a3f20.jpeg)
which is obviously a correctly formatted jpeg, it's the content that's wrong.

Happens on TextSecure 2.23 and 2.23.1. I'm using a Samsung Galaxy S II running Cyanogenmod 11 (which is Android 4.4). Sending photos via attachment (both selecting a picture and the "Take Photo" feature) works fine.

**Comment by mcginty** [comment] 2015-07-22 19:40
that looks like we're getting back image data from your camera in a format other than NV21. Or my NV21 rotate method is broken. Both are possibilities.

**Comment by jtracey** [comment] 2015-07-22 21:01
I just noticed: It only happens on my back-facing camera, my front-facing camera works fine.

**Comment by mcginty** [comment] 2015-07-23 01:25
currently don't have enough info to put a fix for this in 2.24.0. once #3760 is out we can get a hint about how to move forward with this.

**Comment by peterpanondrugs** [comment] 2015-07-24 07:06
S3 LTE int. Android 5.1
![tmp_17866-screenshot_2015-07-24-08-50-39 011219525220](https://cloud.githubusercontent.com/assets/8776733/8869322/9a3af7ce-31e2-11e5-90c8-0d5bcbe28211.png)
https://gist.github.com/30cd23ff29ee5aa81155

I just wanna say that superbeam has the same problem. They told me to use the full screen caption to prevent this bug. Gonna search for more informations

Great great app!

**Comment by mcginty** [comment] 2015-07-24 21:53
Thanks for the log, @peterpanondrugs! You're saying front camera doesn't work for you either?

We should have a release coming out soon that will make the debug output more useful for working out these issues.

**Comment by KommX** [comment] 2015-07-29 09:19
I have the same problem with my Samsung Galaxy S2 running cyanogenmod based on Android 4.4.4.
With the front camera everything's fine.

**Comment by mcginty** [comment] 2015-07-29 19:07
Sounds like Samsung's being weird again :)

**Comment by jtracey** [comment] 2015-08-02 20:37
Well, previewFormat is returning 17, which is indeed NV21.

Here's the logcat I'm getting from adb (the in-app log capture isn't working for some reason):
https://gist.githubusercontent.com/jtracey/3e737c3b718caab5bcdb/raw/3bd3afd0a2164866100332103cac53c68fd7f248/camera%2520logcat.log

**Comment by Pa9an** [comment] 2015-08-17 20:49
Same here, Samsung S2 on CM12.1 daily.

**Comment by GAS85** [comment] 2015-08-26 08:37
The same here. Galaxy S3 LTE (i9305) Android 4.4.4.
![textsec](https://cloud.githubusercontent.com/assets/6813635/9489055/743852d6-4bde-11e5-87d1-74beae7acb1d.png)

**Comment by mcginty** [comment] 2015-08-26 20:00
Wish I could reproduce this. I'm wondering if Samsung is incorrectly reporting orientation or something like that.

**Comment by jtracey** [comment] 2015-08-27 03:48
Well, assuming that the resolution is being reported correctly, rotation is as well.

upright:
W/QuickCamera( 6019): previewSize: 640x480
W/QuickCamera( 6019): previewFormat: 17
W/QuickCamera( 6019): croppingRect: Rect(0, 166 - 480, 474)
W/QuickCamera( 6019): rotation: 90

90 counter-clockwise:
W/QuickCamera( 6019): previewSize: 640x480
W/QuickCamera( 6019): previewFormat: 17
W/QuickCamera( 6019): croppingRect: Rect(0, 63 - 640, 416)
W/QuickCamera( 6019): rotation: 0

90 clockwise:
W/QuickCamera( 6019): previewSize: 640x480
W/QuickCamera( 6019): previewFormat: 17
W/QuickCamera( 6019): croppingRect: Rect(0, 63 - 640, 416)
W/QuickCamera( 6019): rotation: 180

I was going to suggest some missing normalization in the rotate code, but it doesn't even do anything at 0 degrees and the bug still happens, so I'm at a loss.

I wonder if it's not actually getting NV21 even though it says it is. Could line 75 of https://android.googlesource.com/platform/hardware/samsung_slsi/exynos5/+/idea133/libcamera/ExynosCameraHWInterface.cpp be the cause? I'd normally think a bug like that would be hacked away before userspace could be hit by it, but this is android+samsung. Weeeeeeee.

**Comment by jtracey** [comment] 2015-08-27 21:17
Ahhh, it looks like the resolution isn't being reported correctly.
Here's a photo direct capture is giving me in the rotation 0 case (i.e. 90 counter clockwise in my previous post):
![textsecure-2015-08-27-135559](https://cloud.githubusercontent.com/assets/2998852/9533117/e04acf44-4cdd-11e5-80a8-6f6eff9a6cea.jpeg)

And here's me playing with the size:
![painting 720](https://cloud.githubusercontent.com/assets/2998852/9533152/10803672-4cde-11e5-9dc1-6e0258e877c1.png)
![painting 720 offset](https://cloud.githubusercontent.com/assets/2998852/9533155/15aeca5a-4cde-11e5-9f82-3116711f383e.png)
So it appears that the photo's actual width is 720, and that there's 320 pixels missing (the "offset" is given in bytes).

**Comment by mcginty** [comment] 2015-08-28 02:03
@jtracey this is awesome work, thanks so much

**Comment by jocelynthode** [comment] 2015-10-05 06:57
I have the same problem on my Samsung i9300 on android 5.1.1. I could do some basic testing, what would you need from me ?

**Comment by mcginty** [comment] 2015-10-28 01:09
https://stackoverflow.com/questions/16002290/change-size-of-camera-preview-doesnt-work-preview-picture-is-stripped

seems related to this. I just experienced it refactoring some of the camera code - it looks like Android misreports the preview size when you set it to something that's not the default chosen by Camera.

**Comment by TheNain38** [comment] 2015-11-07 09:13
It's fixed with 3.3.1 for me

**Comment by Pa9an** [comment] 2015-11-07 11:52
You probably mean 3.1.1 ?
Not fixed here with this latest version, just checked... :(

**Comment by TheNain38** [comment] 2015-11-07 11:54
No, I mean 3.3.1, you need to become a tester to have beta versions

**Comment by Pa9an** [comment] 2015-11-07 13:08
Ah, I see. Hope to see that version hitting Play Store pretty soon.

**Comment by TheNain38** [comment] 2015-11-07 13:11
@Pa9an https://github.com/WhisperSystems/Signal-Android#joining-the-beta See this

**Comment by TheNain38** [comment] 2015-11-07 13:14
This is in the Play Store

**Comment by Pa9an** [comment] 2015-11-07 13:16
Thanks! Might consider registering... :)

**Comment by Pa9an** [comment] 2015-11-07 20:20
Well, installed 3.3.1 on my Samsung S2 i9100 to test the direct capture functionality. Instead of green garbage when taking a picture, nothing happens now! The button to take the picture is animated as if it would take a pic, but without actually taking one...it just stays on the camera screen.

**Comment by mcginty** [comment] 2015-11-07 21:17
@Pa9an debug log, please! I made a change to detect an irregularity with the resolution the Camera returns and the resolution we expect, so this kind of makes sense but I'd like to confirm and try my hand at a workaround.

**Comment by Pa9an** [comment] 2015-11-07 21:56
https://gist.github.com/41e2e72b76b41621daad

**Comment by mcginty** [comment] 2015-11-07 22:37
@Pa9an as I suspected, your hardware camera is lying about what preview size it actually chose. I'll try an idea on a fix for that and get back to you.

**Comment by TheNain38** [comment] 2015-11-13 09:07
It was fixed in 3.3.1 but no more in 3.3.2 :(
Here is the debug log: https://gist.github.com/TheNain38/0a775c6c3fb9c62f750e

**Comment by Pa9an** [comment] 2015-11-13 09:39
What I've seen since 3.3.1:
When tapping the camera icon, the default camera that is selected is now always the front-facing camera rather than the rear-facing one, which was the default before.
Is this supposed to be so?
Also, is it possible, that the default behaviour when this icon is tapped is to have the camera window already full-sized, so you don't have to select the rightmost icon with the frame first?

**Comment by TheNain38** [comment] 2015-11-13 11:08
No, It's corrected, but I have what @Pa9an had in 3.3.1

**Comment by mcginty** [comment] 2015-11-13 18:21
@TheNain38 3.3.2 reverted the new CameraView that had solved your problem because there was another bug on another device. In Android camera land, if you fix one bug you must apparently pay the price with another new bug. It is the way of this world.

**Comment by mcginty** [comment] 2015-11-24 05:13
This is hopefully resolved since 3.5. Closing, but if anyone is still experiencing this please comment or open a new issue.

**Closed by mcginty** 2015-11-24 05:13 UTC
Labels: direct capture
