### ISSUE TITLE
Thumbnail not correct

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/Signal-Android#5115] opened 2016-01-23 11:51 UTC
- i got a picture from a person 
- i typed a little and send a picture back with the quick cam. 
- >> suddenly the thumbnail from my picture was also the thumbnail for the last picture from that person

**Comment by haffenloher** [comment] 2016-01-23 13:21
If you get the wrong thumbnail, but the picture itself is correct, this is probably a duplicate of #5071 and #4732 (whose title should perhaps be changed to "Black and / or wrong image thumbnails")

**Comment by 2-4601** [comment] 2016-01-23 15:37
Yeah, most likely the same.
@peterpanondrugs could you add your steps to #4732?

**Closed by 2-4601** 2016-01-23 15:37 UTC
