### ISSUE TITLE
Allow to set and sync Contact Pictures

### ISSUE THREAD

**Issue by vascorppor** [WhisperSystems/Signal-Android#916] opened 2014-03-01 18:20 UTC
Allow users to set their own contact picture and sync it to other TextSecure users. In contrast to WhatsApp, provide those pictures to the system contact list to be used in any app, including but not limited to TextSecure.

Is this possible using a SyncAdapter ( #890 ) coupled with a ContentProvider?

**Comment by manhole11** [comment] 2015-01-11 13:06
Profile pictures are the feature that my WA friends are missing the most. They find TS a bit too... boring...

**Comment by volcano99** [comment] 2015-04-18 08:17
With the new notifications that came with the last update, this is even more important. When you get a new message and you drop down the notification bar, you can see the profile picture of the contact that sent the message -- too bad you can't set it up though, so unless it's a group avatar you're not going to see anything.
I would at least suggest setting default profile pictures showing the initial(s) of the contact, like it's being done in group chats. I think that's the approach in Signal on iOS too but I'm not sure

**Comment by bartz1** [comment] 2015-11-20 09:14
>"In contrast to WhatsApp, provide those pictures to the system contact list to be used in any app, including but not limited to TextSecure."

Actually I don't like this. If I set a profile picture within Signal I'm expecting it to be encrypted, but if other apps can use it too then how do I know they're not uploading it to their own servers? (ex facebook or hangouts etc..). Did I understand correctly what you meant?
(By the way there's a similar issue in #706 but it's locked to collaborators so I'd suggest to leave this open since no one can talk over there)

**Comment by DoS007** [comment] 2016-05-30 12:34
**Pro feature:** I know nobody who goes *through all profiles and sets a photo* (which probably should *be recent* and with the *person of profile in focus*; *does everybody has photo for each of their contacts?!*: I think no.).  I think this goes for 80% of people using signal.

**Pro setting manually:** I think there is also a legimate reason for setting a photo manually. The contact uses photos I don't want him to have (nature picture or ...). I think this goes for 20% of people using signal.

**Why not combine these features**:
1. Show the picture about a contact who uploaded it himself when both contacts have both exchanged their telephone number. 
2. Allow overwriting the picture of the contact with a custom picture.

I recommended signal to many people and all of them including me would very like this feature. This is in my eyes one of two major feature lackings of signal.

**Comment by FeuRenard** [comment] 2017-02-19 10:15
Isn't this a duplicate of #706 ?

**Closed** 2017-02-19 11:36 UTC
Labels: feature
