### ISSUE TITLE
[Feature Request] Keywords Search

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6969] opened 2017-09-16 13:57 UTC
Can you please add a keywords search, so you can search through your past messages based on specific words.
Thanks

**Comment by nrizzio** [comment] 2017-09-16 15:45
Duplicate of #1232. Please read and obey the issue template and contribution guidelines.

**Comment by moxie0** [comment] 2017-09-17 19:36
Closing as duplicate

**Closed by moxie0** 2017-09-17 19:36 UTC
