### ISSUE TITLE
Duplicate messages by all group members

### ISSUE THREAD

**Issue by kanufahrer42** [WhisperSystems/Signal-Android#5620] opened 2016-08-17 07:36 UTC
Messages in Signal group chats seem to get delivered multiple times to all group members and also by all group members.

The author of the same messages seems to change.

This behaviour seems to occur in large group chats and when some members are on a canoe tour.

**Comment by 2-4601** [comment] 2016-08-17 10:42
Thanks, this is a duplicate of #2639

**Closed by 2-4601** 2016-08-17 10:42 UTC
