### ISSUE TITLE
Add feature to allow quick video capture.

### ISSUE THREAD

**Issue by wayloncovil** [WhisperSystems/Signal-Android#6458] opened 2017-03-29 15:42 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal does not have the ability to open the camera and capture a video to send to the recipient.
Similar to WhatsApp and SnapChat.

### Steps to reproduce
Open camera or quick camera and the ability to press and hold for video doesn't exist.
If you want to send a video, you need to take the video outside of Signal, save it. Then go back in to Signal and then attach it.

**Actual result:**
Described above.
**Expected result:**
Press and hold the camera screen for Signal to capture video.

### Device info
**Device:** Moto X Pure Edition
**Android version:** 6.0.0
**Signal version:** 4.1.0

**Comment by FeuRenard** [comment] 2017-03-29 16:23
Duplicate of #3564

**Comment by McLoo** [comment] 2017-03-31 23:00
Closing as duplicate

**Closed by McLoo** 2017-03-31 23:00 UTC
