### ISSUE TITLE
Swiping to close Signal from list of running apps closes the list of apps

### ISSUE THREAD

**Issue by aaron-hanson** [WhisperSystems/Signal-Android#6747] opened 2017-06-19 19:16 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While Signal is running in dark mode, when I use the android menu button to list all running apps, and then swipe the signal app to close it, the menu of all running apps closes (crashes?).

### Steps to reproduce
- start Signal
- push the android "menu" button (that shows all running apps)
- swipe the signal app to the side to close it

**Actual result:**  The display of other running apps suddenly crashes and closes.
**Expected result:**  The display of other runnings apps should not close.

### Device info
**Device:** Samsung Galaxy S7 Edge
**Android version:** 7.0
**Signal version:** 4.6.1

### Link to debug log
https://gist.github.com/7453ef934baae926766680bd52b8730b

**Comment by nrizzio** [comment] 2017-06-19 21:49
This is a duplicate of #1037.

**Closed** 2017-06-20 04:14 UTC

**Comment by Benhgift** [comment] 2018-07-16 01:10
Why was this closed? It's still an annoying bug
