### ISSUE TITLE
Missing lock icon on message bubbles.

### ISSUE THREAD

**Issue by ByteEnable** [WhisperSystems/Signal-Android#7111] opened 2017-10-19 21:02 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The lock icon is not appearing in message bubble when texting with other Android or iOS signal users.  However, one Android user has down rev version and they are getting the lock icon while I do not.

### Steps to reproduce
- Install latest version of app; 4.11.5 onto Android 7.0.
- Text another Signal user.
- Texts will not have lock icon in message bubble.

**Actual result:** Missing lock icon in bubbles.
**Expected result:** Should have lock in message bubbles.

### Device info

**Device:** Samsung S7 Edge
**Android version:** 7.0
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/128f2b1fbe8f5e4ad366ea8ff3ae9df9

**Comment by PiCob** [comment] 2017-10-19 21:32
This is intended behavior. Version 4.11 introduced a "unlocked" icon for insecure messages (like SMS/MMS) and removed the lock icon for secure messages.

See https://github.com/WhisperSystems/Signal-Android/commit/8d08f3969a15efa0cc9104a5f4eee89364b0523e for the change.

Here's a discussion raised by that change: https://whispersystems.discoursehosting.net/t/please-dont-do-this/1311

**Comment by ByteEnable** [comment] 2017-10-19 21:50
Cool.  All the current docs state that icon still exists and it wasn't listed as a change in the Google app store.  So I have been panicking thinking someone hacked or was eavesdropping on me.

**Comment by FaizKhan5** [comment] 2017-10-20 06:51
Close this issue

**Comment by moxie0** [comment] 2017-10-20 19:42
Apologies this wasn't communicated very well, we've updated the documentation and will try to make it more clear.

**Closed by moxie0** 2017-10-20 19:42 UTC
