### ISSUE TITLE
No notifications when app is closed

### ISSUE THREAD

**Issue by thorian93** [WhisperSystems/Signal-Android#5289] opened 2016-02-24 19:39 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I don't receive any push notifications from Signal until I open the app.
I always close my apps every then and now via the task manager, NOT from the app menu.
As far I can tell  if the app is not running in background, it does not send notifications until I open the app or have it running in background.

### Steps to reproduce
- Open app, send message
- Open android task manager and close app
- Wait for a incoming notification
- Open the app after some time and see the messages that arrive just on opening the app

### Screenshots

Task manager for clarification:

![screenshot_2016-02-24-20-26-27_small](https://cloud.githubusercontent.com/assets/12239876/13298323/a180c2d6-db36-11e5-865e-9adc13846c5f.png)

### Device info

 **Model:** Samsung Galaxy S5 Neo SM-G903F

 **Android version:** 5.1.1

 **Signal version:** 3.11.1

### Link to debug log
https://gist.github.com/7a4a811d4378f0da166e

**Comment by agrajaghh** [comment] 2016-02-24 20:12
closing as dupe of #4965

**Closed by agrajaghh** 2016-02-24 20:12 UTC
