### ISSUE TITLE
Can't resend message despite being notified the message couldn't be delivered

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#6919] opened 2017-09-04 23:22 UTC
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
SOmetimes after sending a group message I get messages undelivered, even though they don't show the resend capability.  Not really sure if it's a sending error or just lack of processing received messages. 

### Steps to reproduce
-Send message to group. 

**Actual result:** Message says is wasn't delivered, but I can't resend message
**Expected result:** can resend undelivered message. 

### Screenshots
![20170904_170504](https://user-images.githubusercontent.com/4967949/30039886-66495636-9194-11e7-9c53-a66b9cff81a5.png)

### Device info
**Device:** Samsung galaxy s8 stock rom
**Android version:** 7.0
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/537972abcf37d7ed356eeaa41cbd65f0

**Comment by real-or-random** [comment] 2017-09-12 11:23
I can confirm that issue with 4.8.10 on HTC 10 stock. 

I saw this issue very rarely in the past (one in a few months) but already twice today in different groups with the new beta version 4.8.10. So far I couldn't find a recipient who didn't receive the message but I haven't heard back from all of them.

**Comment by Trolldemorted** [comment] 2017-09-12 11:30
I think this only happens when the sync message fails. The delivery is marked successfull for every regular recipient, but the exception from sending a sync message causes the message to be marked as non-successful.
Since the resend buttons are always attached to recipients (but each button resends the message to all recipients, see https://github.com/WhisperSystems/Signal-Android/issues/2639 and https://github.com/WhisperSystems/Signal-Android/pull/3383) users have no way to resend a message whose sync message delivery failed.

I assume your slave device(s) did not receive the message?

**Comment by real-or-random** [comment] 2017-09-12 11:37
Okay that was quicker than expected (and maybe we're talking about two different issues here):

For the first message, there is at least one person who did not receive the message. The slave device (desktop client) was *not turned on* at this time but received the message later.

For the second message, there is at least one person who did receive the message. I think the slave was online. And indeed, the slave device did not receive the message.

So it seems that indeed, some people don't receive the message but the resend button is missing.

When asking, people reported that they experienced the same issue in the past days (not on beta).

**Comment by Trolldemorted** [comment] 2017-09-12 12:03
So in the detail view of message 1 there is no resend button for recipient Alice, and Alice *definitely* did not receive the message?

That is odd. Which signal client is Alice using? Has Alice force-stopped signal/rebooted her phone?

**Comment by real-or-random** [comment] 2017-09-13 13:45
Yes, in the group of message 1 there are three other users, let's call them Alice, Bob, Charlie.
There is no resend button for any of them.

Alice did not receive the message and uses Signal on Android. (No beta, I assume a recent version.) Alice does not use other devices.
Bob did not receive the message and uses Signal on Android. (No beta, I assume a recent version.) In the past he also used Signal Desktop (over a year ago).
I haven't heard back from Charlie.

No force-stop or reboot (or anything else that they would consider special.)

**Comment by Trolldemorted** [comment] 2017-09-13 13:50
Do you have a debug log from the sending device after the occurrence? Were subsequent messages ok?

**Comment by real-or-random** [comment] 2017-09-13 13:53
I don't have a log sorry. I'll try to get one when I encounter the issue again. Subsequent messages were fine.

**Comment by jeremymasters** [comment] 2017-09-13 15:54
It'd really be nice if _individual_ status of resend was visible inside the details instead of just one big group.  If I hit "resend" it resends to everyone, regardless of status from what I last remember.

**Comment by janvlug** [comment] 2017-09-30 14:09
I got a Not delivered notification in a group chat. No further details in the GUI.
Here is the log. Because there are no time stamps in the log, I'm not sure whether it contains the relevant logging. For sure it contains stack traces:
https://gist.github.com/anonymous/7aed58b113caa3eba4fba7ab0077a25a

**Closed** 2017-10-02 17:36 UTC
