### ISSUE TITLE
"too many linked devices" error

### ISSUE THREAD

**Issue by markshep** [WhisperSystems/Signal-Android#5021] opened 2016-01-04 10:27 UTC
I've got the Signal Desktop beta and have linked two of my computers to my Android Signal app.  However when I try to add a third I get an error telling me I've got too many linked devices and should remove some.  Please could this very low limit of two linked devices be raised/removed?

**Comment by 2-4601** [comment] 2016-01-04 11:14
Closing as duplicate of #4997 (https://github.com/WhisperSystems/TextSecure-Server/issues/59)

**Closed by 2-4601** 2016-01-04 11:14 UTC

**Comment by arnottcr** [comment] 2016-07-07 21:46
@2-4601 I am having trouble finding the [above linked github issue](https://github.com/WhisperSystems/TextSecure-Server/issues/59) from the TextSecure-Server repo. Can you please assist, or re-open this issue to track this request?

**Comment by 2-4601** [comment] 2016-07-08 20:10
The server's issue tracker was closed because it wasn't that helpful (too much noise I guess). The limit for linked devices is two at the moment but will possibly be increased some time in the future. The developers are aware of the issue and it's tracked in their heads :)

**Comment by xai** [comment] 2017-01-07 03:47
Why is this closed when the issue is still present? I'm running into the same limitation just right now. So please mark it as wontfix or leave it open.
