### ISSUE TITLE
Received same message in a group chat 5 times; Android app prompts user to resend unsent message to group once per user

### ISSUE THREAD

**Issue by yoasif** [WhisperSystems/Signal-Android#5030] opened 2016-01-05 19:38 UTC
Device info: LG e970, Cyanogenmod 11 build M10, Signal 3.8.1

App state: Push registered, SMS enabled, linked with one device (desktop Chrome)

I received the same message in a group chat 5 times. I saw the same messages on both my desktop Signal instance and on my Android Instance. 

Android Debug log: https://gist.github.com/anonymous/248503469b6b3aed4dc4
Desktop Debug log: https://gist.github.com/02bbbe32ad48ac10061e

Person on other end of conversation (whose message was sent multiple times) said:

"I was in the subway and lost reception. Msg didn't send initially. Had to resend. You have to individually hit send to each person in the group; I hit resend to each person, 5 people total."

Seems like even though the app prompts the user whose message was not sent to each person in a group conversation, one "re-send" works within a group.

**Comment by 2-4601** [comment] 2016-01-05 19:46
Thanks for the report. This is a duplicate of #2639.

**Closed by 2-4601** 2016-01-05 19:46 UTC
