### ISSUE TITLE
Tone to indicate call has ended

### ISSUE THREAD

**Issue by Crossfire0mega** [WhisperSystems/Signal-Android#5865] opened 2016-11-16 05:46 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

There is no tone or indicator when a call ends.
Under the stock Android dialer, there is a tone to signal that the call has ended.

I think it would be beneficial to have a tone to indicate the call has ended similar to the one that dings when the call is connected.

### Device info
**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** 3.21.3

**Comment by haffenloher** [comment] 2016-11-16 07:23
Dupe of #4319, will be fixed by #5358!

**Closed** 2016-11-16 13:38 UTC

**Comment by Crossfire0mega** [comment] 2016-11-16 15:13
Oh, sorry! I searched for an existing issue but could not find one. Thanks!
