### ISSUE TITLE
From default Android 4.4 Browser, Share with Signal does not work

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#5002] opened 2015-12-30 13:24 UTC
Hi,

I'm browsing the web with the default Android 4.4.4 browser. I want to send the current URL to a friend. From the contextual menu (opened with the menu button on my phone), I select "Share" ("Partager" in French), then I select "Signal".

There I arrive on a page with only a few of my contacts (what is this page???). I the friend I want to contact is listed, then that's OK, I can create a message with the correct link. However, if the friend is not there, and I clic on the top right "+" symbol, Signal opens my whole contact list, BUT as soon as I select someone there, it creates an EMPTY message. The URL is lost :{

**Comment by 2-4601** [comment] 2015-12-30 13:58
Closing as duplicate of #4797

**Closed by 2-4601** 2015-12-30 13:58 UTC
