### ISSUE TITLE
Changing devices breaks group chat

### ISSUE THREAD

**Issue by justin-** [WhisperSystems/Signal-Android#4531] opened 2015-11-14 03:55 UTC
I recently switched from a Nexus 5 to a Nexus 5X which also required a new SIM card. Prior to the switch I was a member of a group which had both Android and iOS members. On the new phone, the group showed up as "Unnamed group" and the member list was empty. I could still receive messages from the group but I could not send any. Both phones were running Android Marshmallow.

**Comment by McLoo** [comment] 2015-11-14 05:41
Let one of the group members 
 readd you to the group

**Comment by haffenloher** [comment] 2015-11-14 11:49
Duplicate of #2581. See e.g. [this comment](https://github.com/WhisperSystems/Signal-Android/issues/2581#issuecomment-104604487) for a workaround.

**Closed** 2015-11-14 20:18 UTC
