### ISSUE TITLE
Signal Crashes When Sharing From Chrome

### ISSUE THREAD

**Issue by sweeper3000** [WhisperSystems/Signal-Android#5403] opened 2016-03-31 19:21 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes if I share something from Chrome. It only crashes if the app is locked. I tried it a few times to make sure it's not a one time deal.

### Steps to reproduce
- Go to a website in Chrome
- Tap the 3 dots in the top and tap share to Signal.
- Enter passphrase

**Actual result:** When I share from Chrome to Signal, and enter my passphrase, the app crashes.
**Expected result:** Sharing and entering passphrase should invoke contact list where the user can share.

### Device info

**Device:** Google Nexus 5x
**Android version:** 6.0.1
**Signal version:** 3.15.2

### Link to debug log

https://gist.github.com/anonymous/b2e0c8e92448f1b3fd6da2a1caff17f5

**Comment by 2-4601** [comment] 2016-03-31 19:28
Thanks for the report, appears to be duplicate of #3990

**Closed by 2-4601** 2016-03-31 19:28 UTC

**Comment by sweeper3000** [comment] 2016-03-31 19:30
Ah alright.
