### ISSUE TITLE
Message not delivered until the phone is unlocked

### ISSUE THREAD

**Issue by iampox** [WhisperSystems/Signal-Android#5548] opened 2016-06-22 14:24 UTC
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm using Signal on a Sony Xperia M2 and it works perfectly. My sister just installed Signal on her Sony Xperia M4 a few days ago but when we're sending messages to each other, the message doesn't deliver until we unlock our Android phones… Is there something we can do to avoid that? It's very annoying and I have to unlock my phone every 30 minutes or so to be sure that my sister hasn't sent me a message… And she has the exact same problem.

### Steps to reproduce
- I send her a message or she sends me a message with the Android Signal app.

**Actual result:** I don't receive the messages that my sister sends me with the Android Signal application when my phone is locked. I have to unlock my phone to receive her messages. And she has the same problem when I send her a message.
**Expected result:** I should receive her messages without having to unlock my phone, like you normally receive messages on a phone.

### Device info
**Device:** Sony Xperia M2 (for me) and Sony Xperia M4 (for my sister)
**Android version:** 4.4.4
**Signal version:** 3.16.0

### Link to debug log
There's no debug log.

**Comment by El-Cerdo** [comment] 2016-06-22 15:47
Do you have background data submission enabled for the app? Is there any energy saving/stamina mode turned on?

**Comment by iampox** [comment] 2016-06-22 16:03
The background data is enabled. Yes, I have the stamina mode turned on and I think that my sister too.
Is that the stamina mode on the Sony Xperia that prevents the encrypted messages from being delivered while the phone is locked? (But the unencrypted messages are delivered even if the phone is locked.)

**Comment by 2-4601** [comment] 2016-06-22 18:39
Something in your phone is preventing Signal from receiving the GCM notifications. Most likely your stamina mode. There's a support article that will tell the possible reasons and solutions here: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-
If that article does not help, please contact support@whispersystems.org and they'll help you further.

Duplicate of #4600, #5052, #5085, #5195, #5447.

**Closed by 2-4601** 2016-06-22 18:39 UTC

**Comment by sesse** [comment] 2016-07-13 21:22
Hi,

I'm seeing exactly the same problem with two Nexus devices (so entirely stock Android, no phone-specific funny business); Nexus 5 and Nexus 5x. It only happened on the N5 after it was upgraded to Android 6.0. It's not just about powering off; I can use the phone fully as usual, but still there's no notifications until I manually open the app.

I've gone through the entire list on the support page, to no avail. (Well, I haven't reset my Google account; it seemed a bit drastic, and I didn't really understand much about the PNF tool.) Note that the support page doesn't really tell how to exempt Signal from battery optimization; you need Settings → Battery → (dot menu) → Battery Optimization → All Apps → Signal → Don't Optimize. But that didn't make much difference either.

So, there's some sort of GCM problem indeed, but it seems to be more sweeping than vendor Android modifications.

**Comment by 2-4601** [comment] 2016-07-14 10:01
@sesse Is the problem temporary? Does it solve itself after rebooting your device?

**Comment by sesse** [comment] 2016-07-14 10:03
No, the problem is permanent, on both phones.

It might be that when I restart the device, I get outstanding notifications (I can't recall if I tested), but the ones after that are definitely delayed until I open the app.
