### ISSUE TITLE
Long press call button menu

### ISSUE THREAD

**Issue by GfEW** [WhisperSystems/Signal-Android#4896] opened 2015-12-16 09:05 UTC
It would be convenient and design consistent alike if the call button showed a menu upon long press, like:
(1) insecure call
(2) signal call,
just as the SMS button already does.

**Comment by moxie0** [comment] 2015-12-16 09:07
duplicate of #4364, please check existing issues before opening new ones

**Closed by moxie0** 2015-12-16 09:07 UTC

**Comment by GfEW** [comment] 2015-12-16 09:19
On December 16, 2015 10:07:31 AM Moxie Marlinspike 
<notifications@github.com> wrote:

> duplicate of #4364,

Sorry.

> please check existing issues before opening new ones

I would do for sure, but there doesn't seem to be any such functionality in 
mobile github. I'm on android.

Don't know what's best. Maybe delay (and possibly forget) posting until I 
encounter a desktop somewhere.
