### ISSUE TITLE
Fingerprint verification State missing...

### ISSUE THREAD

**Issue by Aeronaut** [WhisperSystems/Signal-Android#5443] opened 2016-04-16 10:52 UTC
Setting the trusted state have to be done by the user, at the moment every message is checked of in chat without the user can even know, if he can trust this fingerprint.... 

Else simply checking if the fingerprints are the same isn't enough! The way how it's implemented yet is practically unusable. If the fingerprint is altered by a man in the middle you wouldn't know until you check it again...

So doing it like in OTR: Saving each fingerprint and display its trusted state in Chat will be more appropriate in the meaning of feeling secure...

**Comment by 2-4601** [comment] 2016-04-16 11:15
Please use the issue template when opening new issues.
This is a duplicate of #910. The fingerprint verification will be completely changed in the future. The developers are aware of these issues.

**Closed by 2-4601** 2016-04-16 11:15 UTC

**Comment by Aeronaut** [comment] 2016-04-16 13:06
Sorry for not using the template. 

You are right, the issue is a dupe of the 2 years closed https://github.com/WhisperSystems/Signal-Android/issues/910 one. If you think the developers will aware on it and change this then OK - well I doubt.

There are other aspects that speaks for manual fingerprint verification:
Security is subjective process and not a objective programmed product labelled as: Signal - Sicherer Messenger (German -> English Signal - Secure Messenger). 

I can compare the actually shown fingerprint on Contact, but there is nothing where the user can see, if the received messages fingerprint is valid (ehm yes, valid with what?). 
And at least: If I got a encrypted message but the fingerprint is invalid then the user have to know it, Isn't it? 

So why not letting the user know, that his manually verified fingerprint fits the incoming message?
For me that lack of this feature (subjective) feels very suspicious -> not secure. I would not say that security is already breached but if it is so, I wont be much surprised.

So "Signal - Sicherer Messenger" - I doubt.

**Comment by Aeronaut** [comment] 2016-04-16 13:06
Wow, again Closed.

**Comment by 2-4601** [comment] 2016-04-16 13:26
If the long-term identity key of a Signal user changes, Signal will issue a warning and refuses to decrypt the following messages. This is something you could have easily tested instead of throwing accusations based on guess work.

Please read the issue template and [guidelines for contributing](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) (both shown every time you open a new issue).
