### ISSUE TITLE
Group messages are imported incorrectly from backup

### ISSUE THREAD

**Issue by puminya** [WhisperSystems/Signal-Android#5072] opened 2016-01-14 21:11 UTC
I just did a factory reset and imported a plaintext backup. Then I noticed that a group I belong to shows only my own messages. All messages from other members are displayed in their individual conversations, not in the group they were originally sent to.

Before the reset I made a plaintext backup and left the group. After the reset I imported the backup and had another member add me to the group again. New messages are displayed correctly, it's just the history from the backup that's slightly messed up. After noticing the problem I tried deleting all conversations and importing the backup again but the group history is still spread out across the conversations of the group members.

Here is the link to the debug log submitted after the second import:
https://gist.github.com/anonymous/cc20a61ee143dca2e113

I am also using the Signal Desktop beta. The registered devices seem to keep their own version of the history, even if you re-register, so obviously I did not have to import a backup there. All messages in the group and the conversations with individual contacts are displayed properly on my desktop machines.

**Comment by agrajaghh** [comment] 2016-01-14 21:37
closing as duplicate of #3024

**Closed by agrajaghh** 2016-01-14 21:37 UTC
