### ISSUE TITLE
Member kicked from group, can post but not receive group messages

### ISSUE THREAD

**Issue by benmayne** [WhisperSystems/Signal-Android#1694] opened 2014-07-12 16:55 UTC
I've been using a group message with two other TS users successfully for about a week. Today, one member appeared to leave the group. They could still send to the group and from their side, it looked like they were still in the group, but from both other participants, no messages were going through to the third person (K in the images). Messages from K to the group were seen by all, but messages from B and J were not delivered to K. Creating new groups with both the same and different participants had the same effect. K would leave the group upon sending of the first message from B or J. Screenshots are from B. 

K is using a HTC One X (ATT) with Android 4.1.1, HTC Sense version 4+, HTC SDK API 4.63. 

Here's K's log: http://hastebin.com/yimowizopu

B is using Samsung Galaxy S4 (ATT) Android 4.4.2

Here's B's log: http://hastebin.com/pinojanive

![2014-07-12 16 29 18](https://cloud.githubusercontent.com/assets/3374110/3562182/e03eb062-09e3-11e4-9cb6-492a409738f9.png)
![2014-07-12 16 30 33](https://cloud.githubusercontent.com/assets/3374110/3562183/e071b16a-09e3-11e4-86c2-73df049f68ef.png)
![2014-07-12 16 28 55](https://cloud.githubusercontent.com/assets/3374110/3562184/e07cfd86-09e3-11e4-8b22-e40842b93e38.png)

**Comment by FeuRenard** [comment] 2016-11-20 10:38
I cannot reproduce this. After I leave a group, I cannot send anything.
Maybe this issue was influenced or even fixed by https://github.com/WhisperSystems/Signal-Android/commit/2790128e9c19d289dd8c4cf155799b781aaa180f.

**Comment by 2-4601** [comment] 2016-11-20 22:18
If I understood correctly, the original issue was that a contact inadvertently exits the group when they receive a message or a group update?

> K would leave the group upon sending of the first message from B or J

**Comment by BMayneFactual** [comment] 2016-11-21 07:00
Given how old this is, I don't think I can really answer any clarifying questions about this, sorry.

**Comment by 2-4601** [comment] 2016-11-22 01:44
Ok, perhaps we can assume this has been resolved after the many related changes since then.

**Closed by 2-4601** 2016-11-22 01:44 UTC
Labels: bug
