### ISSUE TITLE
Loss of group

### ISSUE THREAD

**Issue by harishpillay** [WhisperSystems/Signal-Android#4740] opened 2015-11-28 01:59 UTC
I had created a group and added people to it. All was OK until I kept getting failures in sending messages. I rebooted my phone (N5 fully updated) and even then it could not send. I could send to one-on-one message threads, just not groups.

The group that I was trying to send to was created by me and I am not sure if I had added others to be admin as well. 

I deleted the app and reinstalled from Google Play. But I cannot get back into that group now. The group still exists and the others in the group are able to communicate. They do see my phone trying to reconnect and being told to accept me. It seems that I did get accepted but what I see on my phone *after* being accepted is a group name that is: "unamed group" and "__textscrure_grop__!9...". I cannot enter any text, image etc. I do see others posting messages but I cannot respond at all. 

What additional info can I gather to try to debug?

Thanks.

**Comment by 2-4601** [comment] 2015-11-28 02:27
Sounds like duplicate of #1048 and similar issues.

There are no admins in groups. They are egalitarian.

Ask someone in the group to update the group. Any kind of an update should fix it.

**Comment by harishpillay** [comment] 2015-11-28 02:57
Thanks for confirming that there are no admins. That's what I thought as well. 

I will get them to update the group. It seems that my number/name is in the list from the other's point. 

Will check and report.

**Comment by harishpillay** [comment] 2015-11-28 03:58
OK. it is fixed now. Followed the suggestion to add me to the group and all's well now.

**Closed** 2015-11-28 03:59 UTC
