### ISSUE TITLE
Cannot Forward SMS/MMS/Signal Message

### ISSUE THREAD

**Issue by isaacgoodman** [WhisperSystems/Signal-Android#7197] opened 2017-11-16 23:45 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Every time I attempt to forward any kind of message, Signal crashes.

### Steps to reproduce
- Open Signal
- Select a conversation
- Press and hold a message
- Tap the menu icon
- Select "Forward message"

**Actual result:** Signal freezes, then crashes.
**Expected result:** Signal should list people for me to forward the message to.

### Screenshots

![screenshot_20171116-154129](https://user-images.githubusercontent.com/19215069/32922021-17ae6748-cae5-11e7-9808-31d7fd8c1419.jpg)

### Device info

**Device:** Samsung SM-G930U
**Android version:** 7.0
**Signal version:** 4.13.0

### Link to debug log

https://gist.github.com/27910ad1b007c87df3e5c26aa68f8840

**Comment by moxie0** [comment] 2017-11-17 00:00
Thanks for being a beta tester, dupe of #7194 and #7195

**Closed by moxie0** 2017-11-17 00:00 UTC

**Comment by isaacgoodman** [comment] 2017-11-17 01:25
I don't understand how this is a duplicate. Those issues look like feature requests.
