### ISSUE TITLE
No Push-Notifications on Gigaset ME

### ISSUE THREAD

**Issue by paddyesch** [WhisperSystems/Signal-Android#4600] opened 2015-11-19 10:41 UTC
I don't receive any push notifications when display is deactivated. Only when I start the App (or sometimes when display is ON and I do something else) the message is received.

Gigaset ME Android 5.1.1

**Comment by McLoo** [comment] 2015-11-19 11:04
hey @paddyesch sounds like a duplicate of #4266
I noticed in most cases that battery safer functions turn of too many parts of the system (signal should be excluded of any action). Are other messenger fully functional?

Also see http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by paddyesch** [comment] 2015-11-19 11:54
I checked the instructions in your link and also re-registered Signal with no effect. WhatsApp for example is fully functional. However, WhatsApp was excluded from being optimized when in background. Signal was included. I excluded Signal too, but still no improvement.

**Comment by paddyesch** [comment] 2015-11-19 12:46
OK, I think I have found the issue: Signal was not allowed to start itself, it was excluded from the list of autostart apps. WhatsApp once again was included in this list.

Summarized: WhatsApp managed to do two things on install which Signal did not
(1) Excluded from the list of automatically optimized apps when in background
(2) Included in list of apps allowed to start themselves (Which seems to have fixed this issue)

**Comment by paddyesch** [comment] 2015-11-19 15:00
No, again a message didn't arrive until I opened Signal. Don't know...

**Comment by 2-4601** [comment] 2015-11-19 15:09
It's most likely something with your ROM rather than a Signal bug. Did you also check moxie's answer on the issue mcloo referred to? The reason WhatsApp works "automatically" is that it has billion users and it gets special treatment by the ROM.

**Comment by moxie0** [comment] 2015-11-19 15:52
Sounds like a ROM issue, @paddyesch you'll probably have better luck writing to support@whispersystems.org than posting here.  This is an issue tracker rather than a support forum.

**Closed by moxie0** 2015-11-19 15:52 UTC

**Comment by obifur** [comment] 2015-11-24 05:14
imo this is a big issue! Several friends are complaining about this and now want to switch to another messenger :(
