### ISSUE TITLE
Not Able To Revert Back To SMS

### ISSUE THREAD

**Issue by jsmootiv** [WhisperSystems/Signal-Android#5858] opened 2016-11-14 20:51 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can not easily SMS with friends when they uninstall signal.

### Steps to reproduce
- I install Signal
- I setup signal as my default SMS application
- I send message to a friend who is using signal
- Friend uninstalls signal (without deregistering, which is the most likely behavior)
- I send message to the friend, they do not see my message
- I need to long press send and select "send unsecured" for every message

Desired:
- Friend uninstalls
- I am able to set the default conversation to unsecured that way when a user uninstalls there aren't any issues.

### Device info
Google Pixel
Android 7.1

### Link to debug log
https://gist.github.com/anonymous/5a6285679222f6a4c0b2c9646cdd7d4b

**Comment by Dyras** [comment] 2016-11-14 21:43
I'm pretty sure this has already been reported

**Comment by FeuRenard** [comment] 2016-11-14 21:46
Dupe of #2285

**Comment by McLoo** [comment] 2016-11-14 23:19
Closing as dupe

**Closed by McLoo** 2016-11-14 23:19 UTC
