### ISSUE TITLE
Location sharing with OSM.

### ISSUE THREAD

**Issue by Stanzi97** [WhisperSystems/Signal-Android#7243] opened 2017-12-03 20:59 UTC
It'd be great if Signal had less G$$gle dependencies, so after the GCM-free version, location sharing without G$$gle Maps would be great. There is a small messenger out there named Kontalk which implemented this feature some time ago, maybe you can take some code from their GitHub to make it less effort:
https://github.com/kontalk/androidclient

**Comment by FeuRenard** [comment] 2017-12-03 22:04
This is a duplicate of #5042.
There is also some discussion in the community forum: https://whispersystems.discoursehosting.net/t/share-location-without-gapps-on-android-phone/1246

**Closed** 2017-12-04 03:19 UTC
