### ISSUE TITLE
 Low volume and very poor quality (Signal 3.3.1)

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4469] opened 2015-11-09 21:41 UTC
Low volume (both hands-free talking enabled and disabled) and very poor quality.

Found with Signal 3.3.1 on Samsung Galaxy Note 4 device.

The competing open source app
https://www.simlar.org/en/
is louder and clearer on the same network conditions.

Note: This is NOT a duplicate of #4244 since that issue is about builds earlier than 3.3.1.

**Comment by 2-4601** [comment] 2015-11-09 21:51
Duplicate of #4382?

**Comment by Norbert80** [comment] 2015-11-09 21:55
I would say it is only partially a duplicate of #4382 since that issue does not cover the low volume issue that I still experience. So please keep this one open.

**Comment by moxie0** [comment] 2015-11-09 22:31
Please post in #4244, we don't need two issues for the same thing.

**Closed by moxie0** 2015-11-09 22:31 UTC

**Comment by Norbert80** [comment] 2015-11-11 19:25
@moxie0 ok. But I think you are referring to #4382.
