### ISSUE TITLE
Android wear notifications are summarised

### ISSUE THREAD

**Issue by z0l2k** [WhisperSystems/Signal-Android#4782] opened 2015-12-02 08:58 UTC
I use signal as my main SMS app and have my phone paired with an android wear watch.

The problem is if I receive a message from more than 1 contact the notification on the watch is summarised so I only end up getting a few words of each message and can't action them individually.

I'll try to attach a photo.

**Comment by z2kZL** [comment] 2015-12-02 08:59
![20151202_215517](https://cloud.githubusercontent.com/assets/7819290/11526535/ecf73918-993f-11e5-9e4c-8ae1e18b62fb.jpg)

**Comment by agrajaghh** [comment] 2015-12-02 09:29
duplicate of #2525?

**Comment by z2kZL** [comment] 2015-12-02 09:36
Yes, it is. Sorry I tried checking but the mobile github site doesn't allow searching.

**Closed** 2015-12-02 17:17 UTC
