### ISSUE TITLE
Black or wrong image thumbnails

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4732] opened 2015-11-27 08:26 UTC
#4612 and #4599 Spin-off

Just opened a convo with last message = outgoing text+ image message 
Preview thumb in convo list showed up fine
In-convo the (attached from attachment drawer)  image thumb is black
Reproduced two times now,  on 2 tries opening the said convo

https://gist.github.com/9d319c95ba0757c7cebb

**Comment by McLoo** [comment] 2015-11-27 09:59
More info
- group message
- image MediaPreviewActivity shows the image correctly
- thumb was fine after sending (which I'm *pretty* sure of, but not 100% :disappointed:  )

maybe related:

**Comment by McLoo** [comment] 2015-11-27 10:14
- AND after forwarding that message to the same convo, the CORRECT draft preview shows up :confused: (Log and screenshot with update)
- sending that draft brings the correct preview thumb up along with the correct MediaPrievewActivity view
- The first preview thumb is still black, but now shows the correct image in MediePreview :confused: :confused: 

logs and shots follow in next comment

Play store version, stock ROM (but rooted and Xposed, NO XPrivacy!)

**Comment by McLoo** [comment] 2015-11-27 10:14
After forwarding the black thumbnail message  to the same convo 
(upper message has the black thumb) 
https://gist.github.com/213dcdf55c520767c789
![screenshot_2015-11-27-11-03-16](https://cloud.githubusercontent.com/assets/5326916/11438708/f4c194b0-94f6-11e5-8cfd-711199c444e9.png)

After sending that forward
https://gist.github.com/f3038db900a5a629726b
![screenshot_2015-11-27-11-08-10](https://cloud.githubusercontent.com/assets/5326916/11438739/2cf0c2e8-94f7-11e5-94c7-ecaabfd9fb50.png)

**Comment by mcginty** [comment] 2015-11-28 00:09
potentially fixed by https://github.com/WhisperSystems/Signal-Android/pull/4737

**Comment by 2-4601** [comment] 2015-11-28 00:43
A bit confused with these seemingly related issues so I'm just gonna leave this here.

I received a screen shot in a 1:1 conversation. I did not go to the conversation on my phone until more messages had come through and the said image was scrolled out of the view. So when I finally wanted to see the image I opened the conversation, scrolled up to get to the image and the thumbnail showed black. (Notice the cut out corners?)
![black thumb](https://cloud.githubusercontent.com/assets/174176/11449329/0e780bd2-9579-11e5-96cd-1f3769b00b71.png)

The image itself shows without any problems.
But the thumbnail is still black.

Picture dimensions 720 x 1280. It's a png screen shot taken with Moto G (2nd gen) running Lollipop.

**Comment by 2-4601** [comment] 2015-11-28 03:37
I don't have the issue with the thumbnail above any more after updating to 3.6.0. :+1:

**Comment by mcginty** [comment] 2015-11-28 04:00
:fireworks:

**Comment by merkste** [comment] 2015-12-05 14:00
I am running Signal 3.6.1 and experiencing the problem right now. Please reopen.

**Comment by merkste** [comment] 2015-12-05 14:06
Additional info: Restarting the device did the trick to make the thumbnail reappear.

**Comment by McLoo** [comment] 2015-12-05 15:02
@merkste maybe you could upload a log after you created a black thumbnail. And after you reentered the conversation that holds that black thumb.

Is the image correctly shown, when you tap/open it?
What is shown in the conversation list? Blackness or the correct thumb?

**Comment by merkste** [comment] 2015-12-05 15:59
Weird, even more thumbnails turned black now. It happens in older conversation, too.

@McLoo If I tab the thumbnail, the picture ist shown correctly. In the conversation list I did not yet see any black thumbnail.
Logs are immediately after the action described.
1. startup
https://gist.github.com/anonymous/0b0ccaa42f0e7760c9a9
2. opening a conversation. Last thumbnail is fine, older ones are black.
https://gist.github.com/anonymous/7ae8345ebd97ac1fcbab
3. composing a picture message: preview thumbnail black, thumbnail after send correct
https://gist.github.com/anonymous/67e7dd18d7b8273fe878
4. forwarding a picture message:  preview thumbnail black, thumbnail after send correct (some messages received in between)
https://gist.github.com/anonymous/edb50edc147ba51aacac

**Comment by merkste** [comment] 2015-12-07 08:45
Will this issue reopened or should I start a new one?

**Comment by 2-4601** [comment] 2015-12-07 15:07
3.7.0, Nexus 4, stock 5.1.1
I was scrolling an old conversation and encountered this again.
But it seems this happens in every conversation I have: eventually at least one thumbnail will show as black if I just scroll back enough (I don't have to go past the _See full conversation'_).

Log of one such case: https://gist.github.com/anonymous/3f795962df9fcaf4aa6b
```
...
W/MessageRetrievalService(15213): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(15213): Reading message...
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 1) ORDER BY date_received DESC LIMIT 1)
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/NotificationState(15213): Added thread: 1
W/NotificationState(15213): Pending array off intent length: 1
W/TAG     (15213): threadIds length: 1
W/MarkReadReceiver(15213): Marking as read: 1
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/PassphraseRequiredActionBarActivity(15213): onPause()
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(15213): Decrementing activity count...
W/MessageRetrievalService(15213): Active Count: 0
W/PassphraseRequiredActionBarActivity(15213): onCreate(null)
W/ExperienceUpgradeActivity(15213): getExperienceUpgrade(157)
W/PassphraseRequiredActionBarActivity(15213): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(15213): initializeClearKeyReceiver()
W/ConversationActivity(15213): onCreate()
W/QuickAttachmentDrawer(15213): updateControlsView()
W/PassphraseRequiredActionBarActivity(15213): onResume()
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 1) ORDER BY date_received DESC LIMIT 500)
W/KeyboardAwareLinearLayout(15213): rotation changed
W/KeyboardAwareLinearLayout(15213): onKeyboardClose()
W/CameraView(15213): skipping layout due to zero-width/height preview size
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(15213): Incrementing activity count...
W/MessageRetrievalService(15213): Active Count: 1
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449293971525/658, progress 0
W/AttachmentDatabase(15213): getThumbnailStream((row id: 658, unique ID: 1449293971525))
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449287209170/655, progress 0
W/AttachmentDatabase(15213): getThumbnailStream((row id: 655, unique ID: 1449287209170))
W/ThumbnailView(15213): Not re-loading slide content://org.thoughtcrime.securesms/part/1449287209170/655
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449235833544/645, progress 0
W/AttachmentDatabase(15213): getThumbnailStream((row id: 645, unique ID: 1449235833544))
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449227720878/644, progress 0
W/AttachmentDatabase(15213): getThumbnailStream((row id: 644, unique ID: 1449227720878))
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449138269165/640, progress 0
W/AttachmentDatabase(15213): getThumbnailStream((row id: 640, unique ID: 1449138269165))
W/ThumbnailView(15213): loading part with id content://org.thoughtcrime.securesms/part/1449138269165/640, progress 0
W/PassphraseRequiredActionBarActivity(15213): onPause()
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(15213): Decrementing activity count...
W/MessageRetrievalService(15213): Active Count: 0
W/PassphraseRequiredActionBarActivity(15213): onResume()
W/ResourcesManager(15213): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(15213): Incrementing activity count...
W/MessageRetrievalService(15213): Active Count: 1
D/OpenGLRenderer(15213): endAllStagingAnimators on 0xb7a0b430 (RippleDrawable) with handle 0xb8e839c0
W/PassphraseRequiredActionBarActivity(15213): onDestroy()
W/MmsSmsDatabase(15213): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 1) ORDER BY date_received DESC LIMIT 1)
I/art     (15213): Background partial concurrent mark sweep GC freed 75044(3MB) AllocSpace objects, 13(710KB) LOS objects, 25% free, 47MB/63MB, paused 1.556ms total 118.846ms
W/PassphraseRequiredActionBarActivity(15213): onPause()
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(15213): Decrementing activity count...
W/MessageRetrievalService(15213): Active Count: 0
W/PassphraseRequiredActionBarActivity(15213): onCreate(null)
W/ExperienceUpgradeActivity(15213): getExperienceUpgrade(157)
W/PassphraseRequiredActionBarActivity(15213): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(15213): initializeClearKeyReceiver()
W/PassphraseRequiredActionBarActivity(15213): onResume()
W/ResourcesManager(15213): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(15213): Incrementing activity count...
W/MessageRetrievalService(15213): Active Count: 1
W/PassphraseRequiredActionBarActivity(15213): onPause()
W/KeyCachingService(15213): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(15213): Decrementing activity count...
W/MessageRetrievalService(15213): Active Count: 0
```

This issue should be reopened.

**Comment by moxie0** [comment] 2015-12-12 06:35
@mcginty do we know what commit introduced this?

**Comment by mcginty** [comment] 2015-12-12 06:37
unfortunately no and still no repro on my install :/

**Comment by TWfromSWD** [comment] 2015-12-16 14:20
I noticed something that may be related: After browsing "All Images" in a Conversation (with lots of images), the a wrong thumbnail image is displayed for the latest post. Tapping on the post brings up the correct picture but the thumbnail remains wrong. And by wrong I mean a thumbnail belonging to an older picture posted in the conversation.
It also happened to me that the thumbnail got totally black under similar circumstances.

Don't know if my log is helpful here but: https://gist.github.com/anonymous/ee23b39dc4a347732996

**Comment by peterpanondrugs** [comment] 2015-12-22 17:31
https://gist.github.com/af1ae677033ffbdd2db0

**Comment by kb100** [comment] 2015-12-31 17:07
I'm also having this issue in 3.8.1.

**Comment by scienmind** [comment] 2016-01-09 09:16
It seems that there is something really messy going on in the database:
Today this weird thing happened:

1. receive image from A
2. reply text to A
3. send location to B
4. exit Signal (not kill, just switch to another application)
5. enter Sinal
6. open B's conversation (the one with sent location) - everything looks good
7. open A's conversation (the one with received image) - instead of received image thumbnail, location's thumbnail from B's conversation is shown. 
8. click the location thumb - correct (non-location's) image is show
9. get back to the convo - the thumb is still incorrect one (location's).

At some point the issue disappeared (unfortunately, i don't have a log for that)

Then, trying to reproduce it by jumping from convo to convo, black thumbnails appeared instead of correct ones....
Here is the log for the black thumbs (not sure though if there is anything useful inside): https://gist.github.com/anonymous/f8efa5acc8e32bc43c6f

Signal 3.9.1, Android 5.1.1

**Comment by edo0** [comment] 2016-01-15 17:10
Same problem here, this is my debug log
https://gist.github.com/7d6655a45cc85e6b74ea

**Comment by mcginty** [comment] 2016-02-01 11:30
Glide just updated to 3.7.0 with what looks like some memory leak fixes around bitmaps that are re-pooled. I'm not sure of root cause, but this is probably a good first step regardless.

**Comment by dcherian** [comment] 2016-02-16 22:23
First time seeing corrupted thumbnails.

![screenshot_2016-02-16-17-00-42](https://cloud.githubusercontent.com/assets/2448579/13093145/a26da260-d4d1-11e5-8444-127db877e879.png)

Log: https://gist.github.com/anonymous/4fdf4c5d8340651cdc04

**Comment by gerdneuman** [comment] 2016-02-17 10:42
I also see black image thumbnails from time to time. Pressing the images always displays them fine.

Yesterday, in a group of 6 people one person (sender) shared a about 7 images and one movie. Don't know if related: The messages were sent at night from the USA, we opened them next morging in Germany. So there is a "time delay" maybe.

On my phone (Samsung SIII mini), about three of these images were black as thumbnails:

![screenshot_2016-02-16-07-13-58](https://cloud.githubusercontent.com/assets/12525563/13106849/b79d1f32-d56a-11e5-882a-0d22f4fac60e.png)

Log: https://gist.github.com/anonymous/89e82480ca3157308087

----

On a friend's phone (Samsung SIII), only one image was black. Interestingly, it was another image than on my phone. That is, same images sent but different ones showed up as black at the recipients.

![106863259222047screenshot_2016-02-16-07-39-31](https://cloud.githubusercontent.com/assets/12525563/13106768/51c928e0-d56a-11e5-9b92-e8d926eef4ac.png)

Log: https://gist.github.com/0ce25f256de04a989cae

**Comment by jnachtigall** [comment] 2016-02-17 20:04
@mcginty With which Signal version comes the above mentioned glide update to 3.7.0? Signal 3.10 or Signal 3.11.1?

**Comment by agrajaghh** [comment] 2016-02-17 20:26
@jnachtigall there hasn't been a patch yet. First rule of open source projects: never ask for an ETA :stuck_out_tongue_winking_eye:

**Comment by jnachtigall** [comment] 2016-02-20 09:37
Seems like the glide update comes with Signal 3.12. moxie commited 2 days ago: https://github.com/WhisperSystems/Signal-Android/commit/170a4291dea44d7309d557e0ccfaa65b0ebf067b Thx! :heart: If the bug does not reoccur, we might close it after some time...

**Comment by 2-4601** [comment] 2016-02-20 14:38
I went through all my conversations :cold_sweat::point_right::iphone:

**Bad news:** Found a black thumbnail:
![black thumbnail](https://cloud.githubusercontent.com/assets/174176/13197234/e4ddd8ba-d7ef-11e5-8a9f-6987c10b3d98.jpg)

**Good news:** It was only one. Before there was at least one black thumbnail in every conversation

Nexus 4, stock 5.1.1, Signal 3.12.0

**Comment by cbarnsdale** [comment] 2016-02-21 22:05
I'm still getting this for about 50% of images. Low res, high res, doesn't seem to matter. This is anecdotal, but this only seems to happen in groups for me.

**Comment by jnachtigall** [comment] 2016-02-24 11:54
Same here: With Signal 3.12.0 the black image thumbnails are gone mostly (for newer images), but some older ones remain black (images sent 3 weeks ago or so). Also only ever seen it in groups.

**Comment by Dyras** [comment] 2016-03-13 15:07
Same here on two different phones!
Moto G (2015):
https://gist.github.com/anonymous/458ac938e1cd7fb7b628
Galaxy S5:
https://gist.github.com/anonymous/5053faff4fe592d2bac6

**Comment by Diapolo** [comment] 2016-03-15 19:49
I also sometimes had black pictures, when changing a groups profile picture. Not sure if related, when I want to send images, not all are shown, the preview is empty like some caching which doesn't update.

**Comment by cascheberg** [comment] 2016-03-31 07:39
Maybe check bumptech/glide#738

**Comment by piratenpanda** [comment] 2016-06-20 10:34
This just happened suddenly on 3.16.0 and spreads through all conversations. Preview is black, turns into real image after sending. Thumbnail will turn black after a while, don't know what it takes to turn it black though

**Comment by zoff99** [comment] 2016-06-20 11:34
+1 i see the same thing on 3.16. (on CM 12.1)

thumbnail was correct, after a while it suddenly turned black.
when i click the real image is correct every time

**Comment by wischi-chr** [comment] 2016-09-18 09:03
Happend to me yesterday (3.19.0) after sending some Bitmojis. Now many thumbnails are black or turn black after some time.

**Comment by btittelbach** [comment] 2016-10-19 12:35
Might be related to this bug (or might not)

Sent an PNG exported from Inkscape via desktop client to a mobile client.
png on desktop client looked fine while background of png on mobile client was black and cropped.

On Desktop
![png_desktop](https://cloud.githubusercontent.com/assets/635660/19518769/232c548e-9609-11e6-8a5f-5f4c3af6c8d3.png)

On Mobile
![png_mobile](https://cloud.githubusercontent.com/assets/635660/19518768/23283f3e-9609-11e6-8716-637fb808047d.png)

**Comment by haffenloher** [comment] 2016-10-19 13:10
@btittelbach it's probably only the thumbnail that is cropped. The black background is, I think, due to your image being transparent (not related to this issue)

**Comment by Thynix** [comment] 2016-11-19 04:08
I've been encountering (and continue to encounter) partially-black (some portion starting from the bottom) image previews within the conversation but pressing on them displays them correctly. This seems distinct from the fully-black previews others mention.

Just now I encountered the wrong image being displayed in the image preview within a conversation. (I sent an image in that message, but the thumbnail displayed is the latest image I sent in a different conversation. The target is single-recipient SMS; the source is single-target Signal.) I'm using Signal 3.22.2. Is there more information I can provide?

**Comment by motatuc** [comment] 2017-01-07 15:13
This is really bad. Happened to me just now with Signal 3.25.4.
Started right after someone send me a picture taken with his phone.
Now all my thumbnails (in all conversations) are black. How to fix this?

**Comment by motatuc** [comment] 2017-01-07 15:27
Some more findings:

1) All previews are black
2) Taking a picture from within Signal shows a black preview as well (before sending the picture)
3) Deleting the picture without sending it and repeating step 2 shows the preview
4) Some older previews got back. Not all of them.

**Closed** 2017-01-08 21:07 UTC
Labels: bug

**Comment by Trolldemorted** [comment] 2017-01-08 22:10
4ad989cc38f6cbe2963524ae3ace455c2ee951b4 improved the situation (the quota of black previews has decreased), but this is still not fixed, some are still black. Conversation partner is on 3.24.0 (android7) and has no black previews at all, i am more or less on 4ad989cc38f6cbe2963524ae3ace455c2ee951b4 (android6) and still have black previews.

Restarting signal/the entire phone has no effect.

Log is complaining about a reconfigure call on a used bitmap:

```
01-08 22:58:39.526 15163 15163 W ThumbnailView: loading part with id content://org.thoughtcrime.securesms/part/1483877890296/32, progress 0
01-08 22:58:39.536 15163 15390 W AttachmentDatabase: getThumbnailStream((row id: 32, unique ID: 1483877890296))
01-08 22:58:39.706 15163 15163 W ThumbnailView: loading part with id content://org.thoughtcrime.securesms/part/1483877804362/31, progress 0
01-08 22:58:39.721 15163 15260 W AttachmentDatabase: getThumbnailStream((row id: 31, unique ID: 1483877804362))
01-08 22:58:39.728 15163 15260 W Bitmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
01-08 22:58:39.730 15163 15260 W Bitmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
01-08 22:58:39.988 15163 15163 W ThumbnailView: loading part with id content://org.thoughtcrime.securesms/part/1483877795352/30, progress 0
01-08 22:58:40.005 15163 15261 W AttachmentDatabase: getThumbnailStream((row id: 30, unique ID: 1483877795352))
01-08 22:58:40.007 15163 15261 W Bitmap  : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
01-08 22:58:40.008 15163 15261 W Bitmap : Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
```
