### ISSUE TITLE
Huge battery drain when on cellular data and no Google Play services

### ISSUE THREAD

**Issue by dtltf** [WhisperSystems/Signal-Android#7014] opened 2017-10-02 05:38 UTC
### Bug description
On a Google Play Services free phone and on cellular data, Signal contributes to around ~25% of battery usage during the day. This problem doesn't occur on WiFi.

### Steps to reproduce
- remove Google Play Services (or don't have them in the first place)
- turn off Wifi
- use Signal

**Actual result:** battery usage is huge.
**Expected result:** battery usage should be similar to the case with WiFi

### Platform info
**Operating System**: Android 7.0
**Signal version:** 4.10.12

I also use Telegram and Riot regullary and they do not drain as much battery.

Is there any info I can provide to help fix this issue?

### Log

Not sure if it will be helpful as it's only a recent one.

[Log](https://gist.github.com/anonymous/35ae5d8fa1a8e4e80d7e54fda46e5ba6)

Screenshots:

[Screenshot 1](https://i.imgur.com/QAvgVA5.png)

[Screenshot 1](https://i.imgur.com/0vQA8lq.png)

**Comment by moxie0** [comment] 2017-10-02 05:44
Duplicate of #6732

**Closed by moxie0** 2017-10-02 05:44 UTC
