### ISSUE TITLE
"Number not registered" when using "calling beta" in 3.30.4 - missing calls instead of ringing, too

### ISSUE THREAD

**Issue by bl-kl2** [WhisperSystems/Signal-Android#6313] opened 2017-02-28 11:06 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

### Bug description
Using "video calling beta" from an Alcatel TCL 5010D to make a call to a Blackberry Classic with no-google-play-services, on the Alcatel appears this error:
"Number not registered - The number you dialed does not support secure voice!".

Both devices are running Signal beta 3.30.4.
Alcatel has explicitly enabled "video calling beta" feature.
Blackberry has it implicitly enabled, as per moxie0's comment in #6272 ("You don't see that settings, it's on by default for you").
[btw, before beta Signal 3.30.3, the Blackberry showed "Login failed!" when trying to place a call;
now, from 3.30.3, no more "Login failed!"].

If, instead, I call from the Blackberry the Alcatel, on the Blackberry it seems all ok, ringing tone,
but the Alcatel doesnt ring, and shows a missed call just after the Blackberry stops the ringing tone,
manually or because of the timeout.

Texts and attachments work ok on both directions (A->B, B->A).
Alcatel device can place and receive audio calls correctly to/from other Signal accounts.
Blackberry device has the same behaviour as detailed here with other Signal accounts.

### Steps to reproduce
- call the Blackberry from the Alcatel, and viceversa

### Device A info

**Device:** Alcatel Pixi4 5010D
**Android version:** 6.0
**Signal version:** beta 3.30.4

### Device B info

**Device:** Blackberry Classic
**Android version:** 4.3
**Signal version:** beta 3.30.4

### Link to debug logs

- Alcatel calling Blackberry
mostly there is, it seems to me, not so much interesting data in the debug log:
http://gist.github.com/ea2bc9fb1a190aa5c6a6a4eebfd2feb7
sometimes, something appears [e.g. handleNoSuchUser, I suppose]:
http://gist.github.com/f6500cf47918bfa440fb9f665c3ac650

- Blackberry calling Alcatel [last 2 account's digits edited to 00 for privacy]
http://gist.github.com/6276fdd23691660ad81f3ea340a4f5fa

**Comment by chrihu** [comment] 2017-03-01 17:19
For some reason the non-ps-phone shows up as "video: false" in the log of the ps-phone, so when you call a non-ps-phone it tries the old redphone call which fails.

Calling the other way around works just fine on my devices.

**Comment by bl-kl2** [comment] 2017-03-01 17:44
Maybe this is related to your [now fixed] unregister bug?
Lets wait for the remaining half of 3.31.0 milestone...

**Comment by chrihu** [comment] 2017-03-03 19:09
The problem is that you don't get registered for webrtc calls automatically when you install it on a device without play services.
It works fine with my test build that has the webrtc toggle exposed on non-ps-devices.(after enabling beta calling o/c)

Anyway, this issue will fix itself as soon as redphone gets shut down :-)

**Comment by bl-kl2** [comment] 2017-03-04 03:40
Ah, damn, it is so simple then!
Thanks for pointing this out.
I was hoping in something more complicated, involving maybe some other functions etc.
The stupid hope is (was, now...) that somehow the non-ps version of Signal would magically fix #5317,
which however seems to depend on a bug in the BB Android Runtime.
So, if I want to use Signal on a BB phone with a decent physical keyboard I should use a custom build, or buy the coming K1.
Anyway I think that the non-ps version is a great step, so at the end of the day I'm happy and grateful for that.

**Comment by moxie0** [comment] 2017-03-06 20:34
Should be fixed in 3.31.0

**Closed by moxie0** 2017-03-06 20:34 UTC
Labels: bug
