### ISSUE TITLE
Settings/SMS and MMS/SMS Enabled takes to incorrect system menu on MIUI 8.5.1

### ISSUE THREAD

**Issue by belidzs** [WhisperSystems/Signal-Android#6795] opened 2017-07-06 20:34 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I click on `Settings/SMS and MMS/SMS Enabled` to set the default messaging app the system settings app opens, but wrong item gets activated

### Steps to reproduce
- Navigate to `Settings/SMS and MMS/SMS Enabled`

**Actual result:** `Settings/Network/More` opens. Here you can activate airplane mode, bluetooth tethering, etc, but no default apps can be configured
**Expected result:** `Settings/App settings/Installed apps/Defaults` should open

### Screenshots
![screenshot_2017-07-06-22-29-39-126_com android settings](https://user-images.githubusercontent.com/7085801/27931569-e61af096-629a-11e7-84f1-8bac29952e07.png)

### Device info

**Device:** Xiaomi Redmi 4A 
**Android version:** 6.0.1 (MIUI v8.5.1)
**Signal version:** 4.7.4

### Link to debug log
https://gist.github.com/anonymous/7e334dedf55f43d04fb7712b3753d196

**Comment by FeuRenard** [comment] 2017-07-06 21:18
Duplicate of #5541?

**Closed** 2017-07-06 21:33 UTC
