### ISSUE TITLE
Suggestion about how SMS should be handled with signal users

### ISSUE THREAD

**Issue by libeclipse** [WhisperSystems/Signal-Android#5571] opened 2016-07-12 12:39 UTC
I think it should be made more clear that SMS is possible with signal contacts, as it's not immediately obvious that you have to hold down the send button.

There are a few annoying edge-cases that come up when a user doesn't have an internet connection. One, is that signal doesn't "remember" that it's sending a message. If you consider another platform like WhatsApp, if there isn't an internet connection, the app keeps trying to send it until it succeeds. With signal, if a user sends a message and forgets about it, it won't be sent even when an internet connection becomes available again.

Another solution is to transition to SMS when there isn't a connection. Obviously a seamless transition brings forth security concerns, but a warning message alerting the user that a connection isn't available and then asking if they'd like to send an **insecure** SMS message instead could work. The app would display the messages differently and ask again after n minutes.

**Comment by FeuRenard** [comment] 2016-07-12 14:20
This issue seems to be duplicate of #2384.
Furthermore there was some discussion about the hold-down option in #5563.
This issue should be closed.

**Comment by 2-4601** [comment] 2016-07-12 17:37
Some previous issues about automatic resending and tuning the logic: #687, #877, #2098, #2384, #3068
SMS fallback issues: #678, #2847, #3074, #4009, #5001 
A suggestion for a more explicit switch to SMS comes up every now and then but the current long-press feature seems to be the way Moxie wants it if you read the previous replies.

**Closed by 2-4601** 2016-07-12 17:37 UTC
