### ISSUE TITLE
No SMS when no internet connection

### ISSUE THREAD

**Issue by rysiu200** [WhisperSystems/Signal-Android#5106] opened 2016-01-22 14:45 UTC
Hi, 
Text message is not sent to the Signal users, if there is no internet connection, e.g. imagine if you are abroad and have no internet data roaming plan, I would expect Signal to send ordinary smsm messages to the Signal users. Sth like it works in iMessage: no internet, then send normal sms after a while. Now, if I am in roaming and Signal is default app for messaging, I cannot send any text messages to the people that have Signal app.
How the app was designed to handle messages between people with Signal accounts when no internet connection?

**Comment by 2-4601** [comment] 2016-01-22 15:13
Closing as duplicate of #2847, #2384, #678, #877, #3074, #3068, #4009, #5001.

**Closed by 2-4601** 2016-01-22 15:13 UTC
