### ISSUE TITLE
Signal crashes when "+Add ringtone" is used to select notification sound

### ISSUE THREAD

**Issue by swedishjeff** [WhisperSystems/Signal-Android#7174] opened 2017-11-10 23:18 UTC
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when I try to set a custom notification sound using the "+Add ringtone" on Android devices

### Steps to reproduce
- Select Conversation Settings > Notification Sound > +Add ringtone
- Use the "Open From" sidebar to navigate to custom ringtones on local storage/SD card/Google Drive/OneDrive
- Select custom ringtone from one of these locations

**Actual result:** Signal crashes (Signal has stopped, must restart the app). Depending on the location of the ringtone, it may or may not add it to the list of sounds available 
**Expected result:** You should be returned to the list of available notification sounds and be able to select the newly imported sound. 

### Device info

**Device:** Essential PH-1
**Android version:** 7.1.1
**Signal version:** 4.12.3

### Link to debug log

https://gist.github.com/d08b722c5fdc6136121023c543f52ae3

**Comment by dreng** [comment] 2017-11-18 11:22
I confirm this with Android 6.0.1 on a Samsung Galaxy S5 mini (SM-G800F). Same Signal version (4.12.3). Tested ogg and mp3 with small and big files.

**Comment by lalunamel** [comment] 2017-11-22 14:26
This is reproducible, yes.

This happens in `RingtoneReferenceDialogFragmentCompat.java` in `onActivityResult` in `onPostExecute` when a new list of ringtones is returned returned from `createRingtoneList`.

This new list will replace the old list of ringtones currently onscreen.
The way we do that is pretty gross (this fragment compat touches a lot of the ui to display new data).
We also assume that we can modify the backing array for the listview on screen, and we can't (it's not an ArrayList), and the app crashes.

The quick fix to this is to make the backing array for this stuff an array list and shove that in there.
I'll look around and see if there are any patterns extant that I can couch off of to clean up this code.

**Comment by lalunamel** [comment] 2017-12-01 13:58
As it turns out, regardless of what type of array backs the adapter that displays ringtones in the `RingtoneReferenceDialogFragmentCompat`, there's no way to modify that list ad-hoc. You'd need to replace the list or adapter or fragment wholesale. 

There aren't APIs for doing the first two. The third option looks like a fairly large refactor that I doubt would get merged as I don't have many contributions to Signal Android under my belt.

Alternatively, there's the [OS's Ringtone Picker](https://developer.android.com/reference/android/media/RingtoneManager.html#ACTION_RINGTONE_PICKER) that could be launched instead. I tried it on my Android 8 phone and it looks great! Though, the appearance differs depending on what version of Android you're on.

I'm going to investigate using the built in Ringtone Picker. I don't know why Signal Android doesn't use that already (it's been available since day 1 and the `RingtoneReferenceDialogFragmentCompat` basically recreates its functionality).

**Closed** 2017-12-01 20:58 UTC
