### ISSUE TITLE
Back button inoperative when keyboard deployed.

### ISSUE THREAD

**Issue by cob16** [WhisperSystems/Signal-Android#7076] opened 2017-10-09 20:10 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Back button from chat is blocked when keyboard open

### Steps to reproduce
- Open Chat
- Tap bottom to open keyboard
- Try to go back

**Actual result:** nothing happens, keyboard sliding down
**Expected result:** Return to chat list.

- This didn't seem to exist in the current non beta 4.10.1. 
- Before discovering it's relation to the keyboard as a user this felt like the app was being unresponsive. 
- With a large phone having to close the keyboard before using the back button is frustrating
- Other actions such as the right context menu can still be accessed with the keyboard deployed.

### Device info
**Device:** Onepluss 3
**Android version:** 7.1.1
**Signal version:** 4.11.2

**Comment by p4nci** [comment] 2017-10-09 20:52
probably duplicate of  https://github.com/WhisperSystems/Signal-Android/issues/7065
Will be fixed in 4.11.3 (see https://github.com/WhisperSystems/Signal-Android/commit/a382694b1fd18569a211b7e00ecd94f7a534e4dd)

**Comment by mammuth** [comment] 2017-10-10 05:30
Well, in #7065 I assumed the behaviour only changed for the back button in the action bar (and not the device back button). I thought the behaviour has always been this way with the device back button.
But obviously I was wrong :see_no_evil:

The fix in your linked commit won't fix this issue I think.

**Comment by p4nci** [comment] 2017-10-10 18:12
@mammuth I'm pretty sure this is duplicate of #7065 (see Bug description:   `Back button from chat is blocked ` and not android back button). Further there is no back button if keyboard is open, instead back button changes to "close keyboard" (down arrow=triangle),
@cob16 could you confirm if v4.11.3 fixes your issue?
If not, could you please post a debug log?

**Comment by mammuth** [comment] 2017-10-10 20:15
You're probably right. But let's see whether @cob16 confirms it :)

**Comment by cob16** [comment] 2017-10-10 21:43
@mammuth @p4nci Yes sorry that did look like a dupe, the difference in wording threw my search off. v4.11.3 fixes this thanks all! 👍

**Comment by nrizzio** [comment] 2017-10-10 21:46
@cob16 please close the issue

**Closed** 2017-10-10 22:10 UTC
