### ISSUE TITLE
Change Emojis To Flat Emojis

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#6496] opened 2017-04-05 19:38 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
Please Change Emojis To Flat Emojis Like This And All Add All Emojis And Make Setup Like When I Send Only One Emoji It Shows Big.
Check It There: http://emojione.com/ 

### Screenshots
![screenshot 2](https://cloud.githubusercontent.com/assets/26612909/24723416/dc01a636-1a60-11e7-9214-c4edf0a52af8.png)

### Device info
**Device:** Qmobile Noir i6 Metal One
**Android version:** 6.0
**Signal version:** 4.2.4

**Comment by FaizKhan5** [comment] 2017-04-05 19:42
@moxie0 Please Update Emojis :(

**Comment by PiCob** [comment] 2017-04-05 19:58
Duplicate of #6269 and #4279 (kind of).

Discussion dealing with emoji set also came up: https://whispersystems.discoursehosting.net/t/emoji-one-in-signal/597

**Closed** 2017-04-06 02:13 UTC

**Comment by FaizKhan5** [comment] 2017-04-06 09:49
@moxie0 But Why Atleast Give Me An Answer :(
