### ISSUE TITLE
[Request] Swap Camera When In a Video Call

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6435] opened 2017-03-23 17:19 UTC
Can you please add a button that lets you swap which camera you are using when you are making a video call.
Thanks

**Comment by CFPrulez** [comment] 2017-03-23 18:49
This would be great. The user should be able to decide which camera is used during the call.

**Comment by rustybird** [comment] 2017-03-23 22:33
Duplicate of #6279

**Closed** 2017-03-23 23:44 UTC
