### ISSUE TITLE
No audio from call. Can receive but cannot transmit.

### ISSUE THREAD

**Issue by Viperized** [WhisperSystems/Signal-Android#4477] opened 2015-11-10 14:06 UTC
Person can receive calls and can hear the other person, but the other person cannot hear anything, just dead silence.

Person canl also make calls although sometimes the other end doesn't get notified of the call, and when it does, it's like 30 mins afterwards of a missed call.

Here goes the debug log right after a call that audio was received but not sent:
https://gist.github.com/anonymous/016231486a8eba60e526

I can see 2 java exceptions and termination stacks, so seems to me this person's phone model isn't well supported?

Thank you Devs!

**Comment by 2-4601** [comment] 2015-11-10 14:15
Most likely a duplicate of #4409 (or #4244). I.e. should be fixed in 3.3.x

**Comment by Viperized** [comment] 2015-11-10 14:22
Well, if it helps, the person never was able to hear audios, even when it was just the last RedPhone version before it merged with Signal. I've waited for Signal for Android to appear to test, and the problem persists.

It's a call from Android to Android. If the devs request I can put the other end debug log from the same event.

**Comment by moxie0** [comment] 2015-11-10 17:14
closing as duplicate of #4244

**Closed by moxie0** 2015-11-10 17:14 UTC

**Comment by Viperized** [comment] 2015-11-11 17:13
FYI, using the workaround on #4244, selecting loudspeaker and then back to headset, does nothing. The  other side still has no audio.

It wouldn't make much of a difference anyway, since Alice calls Bob, and Alice can hear Bob without a problem, but Bob cannot hear Alice.

Bob has recent newer phone and can call Charlie and Danny without any problem. So actually the problem lies in Alice's device hability to TRANSMIT to Bob or any other Signal user.

And the loudspeaker workaround woldn't fix it.
