### ISSUE TITLE
Reduced quality of shared images.

### ISSUE THREAD

**Issue by UNIcodeX** [WhisperSystems/Signal-Android#5736] opened 2016-09-30 19:46 UTC
### Bug description
Reduced quality of shared images.

### Steps to reproduce
- share image via one of the following: a gallery app, within Signal, or taking a picture with signal.
- save shared image to phone and view details - note resolution
- check details of original image - compare resolution to that of the sent image.
- notice that resolution is drastically impaired vs the original

**Actual result:** Resolution of sent image is much lower than that of the original image.
**Expected result:** Resolution of sent image should be the same as that of the original image.

**Other Thoughts:** Sending a full size 1080p video worked flawlessly in my test. the resolution and perceived quality are the same between original and sent video.

### Device info
**Signal version:** 3.19.1
**Device:** LG G4
**Android version:** 6.0
**Android security patch level:** 2016-06-01
**Android Kernel version:** 3.10.84
**Android Build number:** MRA58K
**Android Software Version:** LS991ZVC
**Android Security software version:** MDF v2.0 Release 1
![screenshot_2016-09-29-08-56-08](https://cloud.githubusercontent.com/assets/8235002/19004448/934a1fbe-871b-11e6-8dfa-bb00a8a3ae3f.png)
![screenshot_2016-09-29-08-56-21](https://cloud.githubusercontent.com/assets/8235002/19004452/97e416b0-871b-11e6-8612-ee6f836231b2.png)

### Link to debug log
https://gist.github.com/17d7eb79d8b8550530021665126c8648

**Comment by Trolldemorted** [comment] 2016-09-30 20:11
i think this is "working as intended", but letting the user decide would be better in my opinion.

**Comment by UNIcodeX** [comment] 2016-09-30 20:22
I hope it's not as intended. There will be a lot of people who choose not to use the app, just based on that alone. It's inconvenient to have to juggle multiple apps just to send a high quality image.

**Comment by johanw666** [comment] 2016-09-30 20:44
It is even more inconvenient to have some pictures fill up your storage. For MMS it is required as there is a (provider-dependent) limit on the picture size that will be sent at all. Most other messengers do it too, even very popular ones like WhatsApp, Viber and Facebook Messenger.

**Comment by UNIcodeX** [comment] 2016-09-30 20:51
Make it an option then. I, for one, would like to see/send the media in the absolute best content possible. A 1080p video, for instance, sends in all its glory. That would fill up a person's storage more quickly than a set of images. At least up the resolution to a respectable value, in stead of something reminiscent of 90's era internet. I think making it an option would satisfy more users. It could even default to reduced quality.

**Comment by UNIcodeX** [comment] 2016-09-30 20:52
What this issue brings to light is the fact that the Signal is reducing the quality of images to lower than that sent through MMS.

**Comment by 2-4601** [comment] 2016-09-30 20:59
Closing as duplicate of #672

**Closed by 2-4601** 2016-09-30 20:59 UTC
