### ISSUE TITLE
Groups not available in "share with" screen other than within 5 most recently contacted

### ISSUE THREAD

**Issue by eojjn** [WhisperSystems/Signal-Android#7304] opened 2017-12-28 11:22 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The "share with" screen only contains the most recently contacted contacts and groups and a complete list of contacts. The groups feature of Signal is hugely useful but this design flaw means sharing to them is a real pain and without copying and pasting, impossible. 

### Steps to reproduce
- choose to share a link, image, etc using signal

...

**Actual result:**
... 
- notice the group you sent a message to last before contacting 5 other contacts/groups is not anywhere to be found. 
- pull hair out with irritation. 
- leave the other participants of said group in ignorance of the un-shared item

**Expected result:** 

... 
- group you're looking for isn't in 5 most recently contacted contacts/groups
- scroll down to find group in list of contacts and groups. 

### Device info

**Device:** Samsung Note 3
**Android version:** 6.0.1
**Signal version:** Signal 4.14.10

### Link to debug log
N/A

### Personal message
Please excuse my sarcasm, I really love Signal. It has revolutionised my IM experience, in that I have had confidence in it's security and functionality sufficient to convince all my friends and family to start using it. None of us have looked back.

We all really appreciate the hard work you all have put into it!

**Comment by Wikinaut** [comment] 2017-12-30 02:27
duplicate of #7202

**Closed** 2017-12-30 18:08 UTC
