### ISSUE TITLE
Can't play multimedia content to the end, screen lock's itself

### ISSUE THREAD

**Issue by thrdroom** [WhisperSystems/Signal-Android#6977] opened 2017-09-20 09:14 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Playing a voice message, audio or video doesn't prevent the screen from turning black and stops playing. This does only happen on this device/android-version, this bug doesn't appear on cyanogenmod 13.

### Steps to reproduce
- Open Signal
- Open a conversation-thread
- Play a long voice-message/audio/video (with longer i mean it should be longer than the minutes of screentimeout that is set in your system-settings)

**Actual result:**
When you play a voice-message/audiofile or video which is longer than your set screentimeout limit then the screen turns black/locks itself and stops playing the multimedia-content.

**Expected result:**
Signal should avoid locking the screen, play the multimedia-content to the end and then start the system-screentimeout again.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** Stock-Rom 7.0
**Signal version:** 4.9.9

**Comment by FeuRenard** [comment] 2017-09-20 09:18
This is a duplicate of #4424.

**Comment by FeuRenard** [comment] 2017-09-20 11:11
Video issue is solved by https://github.com/WhisperSystems/Signal-Android/commit/6945ecf81d85545fc4216b6061c0f7c167bd0c5f in 4.10.1

**Comment by moxie0** [comment] 2017-09-21 01:35
closing as duplicate

**Closed by moxie0** 2017-09-21 01:35 UTC
