### ISSUE TITLE
Signal crashes upon getting a call.

### ISSUE THREAD

**Issue by p00rt** [WhisperSystems/Signal-Android#5221] opened 2016-02-13 09:11 UTC
When I get a call and try to answer it, signal stops. Here's my log: https://gist.github.com/340e90ea58ee517e2a96. Also, call notification doesn't disappear.

**Comment by cascheberg** [comment] 2016-02-13 09:56
Duplicate of #5216, will be fixed in 3.11.1

**Closed** 2016-02-13 10:18 UTC
