### ISSUE TITLE
Non-signal users are not hidden in new group dialogue

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#4970] opened 2015-12-27 00:04 UTC
When creating a new group chat, non-signal users are displayed similar to signal users and can not be differentiated (as you can see in the last picture of the gif). The dialogue after tabbing on the `+` button is much more useful as the suggestions in the textfield (which is quite superfluous).
This caused #4969.

**Device Info:** Nexus 5, Omnirom 5.5.1, Signal 3.8.1 (Btw. (again): why is this tag not present on github?)

**App state:** Push registered, SMS/MMS disabled, Privacy off

![anim](https://cloud.githubusercontent.com/assets/5571650/12008336/5cb5e012-ac35-11e5-977b-442537da2f82.gif)

**Comment by 2-4601** [comment] 2015-12-27 00:22
I understand now. Signal and non-Signal contacts are not differentiated when you **search** for contacts in the group creation view.
Otherwise they are differentiated: Signal contacts are sorted first and marked with blue capital letters.

**Comment by cascheberg** [comment] 2015-12-27 01:26
Duplicate of #4691

**Comment by McLoo** [comment] 2015-12-27 08:27
Closing as duplicate

**Closed by McLoo** 2015-12-27 08:27 UTC

**Comment by sedrubal** [comment] 2015-12-27 11:53
@2-4601 yes. Sorry for not clearly explain this...

And sorry for that dup...
