### ISSUE TITLE
Can't update Signal standalone APK

### ISSUE THREAD

**Issue by leedoyle** [WhisperSystems/Signal-Android#6740] opened 2017-06-17 20:41 UTC
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
I don't have Google Play nor google services so I use the standalone Signal apk. 
Now I can't update the google-free standalone build from https://signal.org/android/apk/ . In the contact list  there is a message saying

> Your version of Signal is outdated
>Your version of Signal will expire in 4 days
> Tap to update to the most recent version

But when I tap it says:

> no such app found

Prior to that Signal had been self-updating without any problems.

**Comment by johanw666** [comment] 2017-06-17 22:09
If the version expires you can update manually from apkmirror.com. They offer the Play Store version but it will work without gms just as the website version so you'll have to download each update yourself.

**Comment by leedoyle** [comment] 2017-06-17 22:28
@johanw666 but it's not as secure as downloading the APK directly from the WhispersSystems server and verifying the signature.
Besides, the apk I'm using does have a built-in updater, so that's clearly a bug.

**Comment by johanw666** [comment] 2017-06-17 22:58
It is not a bug, it means the apk at the website has just not been updated, and all official apk's expire after 90 days, update available or not. Apparently 90 days is too short for this project, we've had this before with 3.16.1, which was released with only change a version number bump and a new expire date.

**Comment by moxie0** [comment] 2017-06-17 23:03
The APK at the website has been updated (several times) within the last 90 days. Something must be wrong with the updater or the network, but I can't determine what is wrong without a debug log that covers the period of an update attempt.

**Comment by leedoyle** [comment] 2017-06-17 23:40
Thanks for your quick response!
Unfortunately, I can't provide such logs. However, it just occurred to me the updater might have been  tampered with by Xprivacy.
Yes, during these 90 days there have been a number of updates. I have seen them in downloading or installing ("Signal update downloading" or something of the sort) in notifications menu and was thinking the update applied successfully. 
But now I can't even initiate that update process to provide you the logs. There were no changes in Xprivacy settings during the last 90 days at all.

**Comment by moxie0** [comment] 2017-06-18 00:45
The update isn't applied "automatically." It will download, and then should prompt you to install (which requires manual approval). Very possible xprivacy interfered there.

**Comment by johanw666** [comment] 2017-06-18 01:00
As a fellow Xprivacy user, I have disabled it for some open source programs I trust. Signal is one of these. You can try that, or check the Xprivacy logfile if it mentions any blocked operation from Signal.

**Comment by leedoyle** [comment] 2017-06-18 15:07
@moxie0 I see. I've only seen it downloading, but it didn't prompt me to install. 

However, on two phones when I click on the update button, it says
>No such app found

Apparently it's trying to make use of Google Store.
And this bug doesn't let me pinpoint the earlier issue with failed updates as I can't initiate the update process.

**Comment by johanw666** [comment] 2017-06-18 16:28
Well you can always manually go to https://signal.org/android/apk/ and download the apk from there.

**Comment by nrizzio** [comment] 2017-06-18 17:30
Since this sounds more like an Xprivacy issue than a Signal issue, @leedoyle you should head on over to the [community forum](https://whispersystems.discoursehosting.net) and close out this issue.

**Comment by leedoyle** [comment] 2017-06-20 16:31
@nrizzio I have reasons to believe they are two separate issues, and the latter ("no such app found" while trying to force update) clearly has nothing to do with Xprivacy. 
It looks like an attempt to make use of Google Store that I don't have installed.  And when this happens, there's nothing relevant in Xprivacy logs.

**Comment by moxie0** [comment] 2017-06-20 17:55
@leedoyle Yes that banner assumes you have Play installed, probably just going to be how it is.

**Comment by leedoyle** [comment] 2017-06-20 22:07
@moxie0 well, that's not the behaviour one'd expect from a client that allegedly doesn't depend on Google to perform updates.

**Comment by moxie0** [comment] 2017-06-20 22:31
@leedoyle You should never be in that position to begin with. There's something wrong with the auto update mechanism on your device. It's either a bug in signal, or an xprivacy problem. My experience has been that xprivacy often causes serious problems (fuck with your phone, and fucked up things will happen to your phone), but I can't determine what is going on without a relevant debug log.

**Comment by natrius** [comment] 2017-06-30 13:56
While i understand that moxie0 does not like that approach i have to say thanks for the non-google-version and it works like a charm here, it downloads the update and shows me that there is new version available to install.
I don't use xPrivacy anymore, but i suggest you remove that one since it doesn't work anymore with android 7. anyways.

**Comment by micressor** [comment] 2017-08-25 13:14
I miss the possibility to trigger the update manually.

**Comment by moxie0** [comment] 2017-08-28 00:51
@micressor You should be able to manually update at any time, the APK is here: https://signal.org/android/apk/

I haven't gotten any more details or a debug log on the original issue, so I'm going to close this as an xprivacy problem.

**Closed by moxie0** 2017-08-28 00:51 UTC

**Comment by orblivion** [comment] 2017-11-16 01:54
I actually have the same issue and I don't have xprivacy. Maybe I have something similar? I use Cyanogenmod which has permissions controls, but everything is set to "Allowed" other than "Write SMS DB" which is "Ignored" apparently from lack of use.

**Comment by orblivion** [comment] 2017-11-16 01:55
To get a debug log I'd need to set up Android Studio, right?

**Comment by haffenloher** [comment] 2017-11-16 02:14
@orblivion In Signal's settings, tap *Advanced > Submit debug log*. Done!

**Comment by orblivion** [comment] 2017-11-16 03:21
Will it give me the option to review it before sending it?

**Comment by haffenloher** [comment] 2017-11-16 03:41
Yes.

**Comment by orblivion** [comment] 2017-11-16 03:51
Here you are: https://gist.github.com/anonymous/fcfd901fec47fe1e78ecfe67858975fb

I restarted my phone, and then tried hitting the update button a couple times. That's all the activity that this log should cover. BTW I have F-Droid, and I realized that my "No such app found." popup has the F-Droid logo, in case that's relevant.

**Comment by haffenloher** [comment] 2017-11-16 04:13
To see what's going on, Moxie would need a log of the auto update mechanism failing. The auto updater gets scheduled in your log but it doesn't seem to have been executed yet.

**Comment by orblivion** [comment] 2017-11-16 04:16
I see. I deliberately restarted my phone to wipe the log before trying the manual update. That's why it doesn't have the auto-update. And it's what, every 6 hours or something? I can try to grab the log first thing in the morning.

**Comment by moxie0** [comment] 2017-11-16 04:32
@orblivion It's scheduled to run at GMT: Thursday, November 16, 2017 5:00:18.320 AM, which is 30min from now.

**Comment by orblivion** [comment] 2017-11-16 15:40
Does this have it? It shows one exception at least right upfront.

https://gist.github.com/anonymous/81b733df9146e65ef110b63a739a2a9c

**Comment by moxie0** [comment] 2017-11-16 21:16
@orblivion There are no timestamps in your log, so it's not possible to tell, but if you waited until the morning to capture the log, then it's very unlikely. You'll have to look at when the job is scheduled for, and then capture the log ~60 after that.

**Comment by orblivion** [comment] 2017-11-19 19:08
I just connected my phone to WiFi for the first time in a good while, and now I get the Signal update popup. This happened within the last 5 minutes. I don't suppose it was even scheduled to do a check during this time?

So I guess the point is moot for now, for me. Perhaps if I have time one of these days I'll disconnect from WiFi and try to get a log for you. (Is it around 5:00 UTC every day?)

For now, for anybody else having this problem: Try a different Internet connection.

**Comment by DarthSpock** [comment] 2018-03-06 20:17
> Well you can always manually go to https://signal.org/android/apk/ and download the apk from there. Currently it offers 4.6.1

Actually it offers 4.15.5. Both the webpage and the apk file name show 4.15.5. Unless it auto-updates once installed. If that is the case, it would still be best practice to put the latest available version up every time there's an update and it makes a better user experience.

**Comment by nyxst** [comment] 2018-03-13 10:05
I have the same problem. 

A log can be found here. Hopefuylly this one is helpful:

https://gist.github.com/e07df4c0c71a5f0bfd27a292dd8ee2b7

**Comment by orblivion** [comment] 2018-03-14 15:03
Yeah, I'm having the same problem again, this time whether or not I'm connected to WiFi. I may try a different WiFi.

**Comment by micressor** [comment] 2018-03-31 19:08
@nyxst  @orblivion Confirm this. The file is located at

**file:///storage/emulated/0/Android/data/org.thoughtcrime.securesms/files/signal-update.apk**

but the popup hasn't been coming for months.

**Comment by ilf** [comment] 2018-04-17 11:49
I had the same issue, again.

@micressor Thanks, the current release APK (4.17.5) was indeed at that location and - according to the timestamp - has been there for two days. A manual upgrade by clicking on the APK worked just fine.

But I never saw a popup asking me for the update. Any idea why this might be or how I could help debug this? I'm on LineageOS 14.1, without XPrivacy.

**Comment by natrius** [comment] 2018-04-17 12:05
Now i had the same issue, OnePlus 3, LineageOS 15.1, without xPrivacy.

I got the message in Signal itself "Signal not up do date, ...." and was wondering. I downloaded the new .apk directly via the homepage. 
So, it was working before (See: https://github.com/signalapp/Signal-Android/issues/6740#issuecomment-312273783) and it did not update automatically now.
