### ISSUE TITLE
URLs in messages fail to include the trailing slash

### ISSUE THREAD

**Issue by idupree** [WhisperSystems/Signal-Android#6224] opened 2017-02-15 14:57 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
URLs in messages fail to include the trailing slash. (In contrast, Signal Desktop does include the slash.)

### Steps to reproduce
- Send someone the message `Test link: https://www.example.com/foo/bar/ Yay!`
- look at the link; click the link
- notice that Signal treated the trailing slash as not part of the link

**Actual result:** Signal treated the trailing slash as not part of the link
**Expected result:** Signal should underline the trailing slash and include it in the URL when you click it

### Screenshots

![screenshot_20170215-095051](https://cloud.githubusercontent.com/assets/947619/22979529/b735f078-f364-11e6-844c-9fc3c55747ec.png)
![screenshot_20170215-095224](https://cloud.githubusercontent.com/assets/947619/22979532/ba675796-f364-11e6-8cb5-6becd5c0e0b0.png)

### Device info

**Device:** Google Nexus 5X
**Android version:** 7.0
**Signal version:** 3.28.4

**Comment by 2-4601** [comment] 2017-02-16 12:48
Duplicate of #6019? (cc @nikwen)

**Comment by nikwen** [comment] 2017-02-16 15:19
@2-4601 Will check that when I have a few minutes.

**Comment by nikwen** [comment] 2017-02-26 12:43
Had a look at this. It does in fact look like a duplicate of #6019 to me.

It is notable that this only happens if the message contains some text after the link:

![screenshot_20170226-133612](https://cloud.githubusercontent.com/assets/3309657/23339743/d1cf76e4-fc28-11e6-8393-1cb559643809.png)

@idupree commented on how one could fix this manually [here](https://github.com/WhisperSystems/Signal-Android/issues/6019#issuecomment-280469717), but I do not think that this is a critical issue (as the link still works) and believe that this is something that should be fixed in Linkify instead of adding workaround code to every app out there using it (remember, it's part of Android).

**Comment by idupree** [comment] 2017-02-28 21:58
To be clear, I noticed this because a site had a page which was broken without the trailing slash.  (This isn't very good web practice, but it happens sometimes.)  I don't disagree about this issue being noncritical.

**Comment by 2-4601** [comment] 2017-03-02 20:29
Closing as duplicate of #6019.

**Closed by 2-4601** 2017-03-02 20:29 UTC
