### ISSUE TITLE
SMS sent from wrong sim in dual sim phone

### ISSUE THREAD

**Issue by heinhuiz** [WhisperSystems/Signal-Android#6303] opened 2017-02-26 08:05 UTC
I have:
- [v ] searched open and closed issues for duplicates
- [v ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a dual sim phone running CM13. 
Signal is set up to replace the default messaging app. The account is set up with the number of my primary sim. In the Android settings sim 2 is set as the default for SMS. 

When I send an SMS Signal defaults to sim 1 for sending; I have to longpress the send button and select sim 2 to correct that. 
Even worse, when replying to an SMS received ob sim 2, the app also defaults to sim 1 and sends the reply through that sim. 
Signal should (1) default to the sim set in the Android settings for sending SMS messages, and (2) use the number that received the original SMS when replying. 

### Device info

**Device:** Xiaomi Redmi Note 3
**Android version:** 6.0.1 (CM13) 
**Signal version:** 3.29.6

**Comment by moxie0** [comment] 2017-02-27 01:06
Hey @heinhuiz Android does not make the "default SIM" information available to apps until Android 7, so there's no way for us to intuit that on Android 6. However, the behavior you describe about using the SIM for replying has been fixed in 3.30.  Closing as a duplicate of #5266.

**Closed by moxie0** 2017-02-27 01:06 UTC
