### ISSUE TITLE
Contacts with WhatsApp appearing twice in Signal's contact list

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4428] opened 2015-11-06 23:19 UTC
I guess this is somehow related to #4029, but that one seems to be fixed - while I'm still experiencing that kind of issue.

Almost all of my contacts appear a couple of times in Signal's contact list - with all of their different phone numbers. So far, so good (expected behaviour).

But many have additional duplicate entries with the same number (it's always a **mobile** number) listed twice.

One of them has the format **+12 345 67890** (which is exactly how I format all of my phone book's entries).
The other one (the duplicate) has the very same number, but formatted as **+1234567890** (a format not to be found in my phone book).

I've noticed that - as far as I looked - each of the contacts with this kind of duplicate has an WhatsApp entry in Android's phone book (actually 2 entries - one for calls and one for messages). Interestingly, though, the WhatsApp entries in Android's phone book are also (sort of correctly) formatted as **+12 345 67890**.

I don't necessarily say that the WhatsApp entries are the culprit (i. e. they confuse Signal). But it surely looks like they are.

It has been like this for a long time, but I just took the time to inspect this more closely.

I'm using vanilla Android 6 on a Nexus 5 with Signal 3.3.0.

**Comment by agrajaghh** [comment] 2015-11-06 23:23
duplicate of #4191?

**Comment by RiseT** [comment] 2015-11-06 23:29
@agrajaghh Yes, thanks, I think so. With the difference that I've been experiencing this on Lollipop as well.

**Closed** 2015-11-06 23:31 UTC

**Comment by RiseT** [comment] 2015-11-06 23:32
@agrajaghh One would think that everyone with WA still installed (shame, shame) should have this issue...

**Comment by agrajaghh** [comment] 2015-11-06 23:40
@RiseT just checked, I got it too. see #4191

**Comment by osmand511** [comment] 2015-11-07 05:35
I've got a Nexus 4 running Android 5.1.1 and Signal 3.1.1 and a subset of the Signal contacts are also duplicated. For each duplicate contact pair, the system contact entry has only one phone number and the two corresponding Signal contact entries are exactly identical (ie. NO number syntax differences like RiseT reported). Also unlike RiseT, neither this phone nor any of the duplicated contacts have ever used or even installed Whatsapp. For this Nexus 4, each of the duplicated contacts has a populated IM field in the system contact list with custom type "CSIP" while none of the non-duplicated contacts do. However, I suspect this is not relevant. Here's why. I also have a Moto G 3rd Gen running Android 5.1.1 and Signal 3.1.1, and identically configured with all the same contacts, but sans IM/CSIP fields. This phone does NOT have the duplicated Signal contact problem. Thinking the IM/CSIP field might be relevant, I added it to one contact entry on the Moto G, but this did NOT result in a duplicated contact. I also have a Nexus 5 running Android 4.4.4 with Signal 3.1.1 and the same contacts, each of which has the IM/CSIP fields populated identical to the Nexus 4. This phone does NOT have Signal contact duplicates. All of this has me doubting this duplicated contact bug has anything to do with Whatsapp or IM/CSIP fields, but if it does I'm thinking it must have some other non-obvious sequence-based dependencies. Perhaps this bug report should be renamed to not be Whatsapp-specific?

**Comment by RiseT** [comment] 2015-11-07 17:33
Is that from CSipSimple?
https://play.google.com/store/apps/details?id=com.csipsimple

**Comment by osmand511** [comment] 2015-11-07 21:35
Yes, the IM/CSIP entries are for CSipSimple, but although that app is installed on the Nexus 4 phone suffering duplicate Signal contacts, CSipSimple is NOT enabled for integration with Android and is configured for outgoing calls ONLY. AFAIK, that means CSipSimple is not running in the background. It has also not been used since we began using TextSecure/Redphone/Signal quite some time ago. The Nexus 5 that does NOT have the duplicate contact Signal problem also has CSipSimple installed and configured identically. The Moto G3 does not have CSipSimple installed. Since my last post I have checked yet another Nexus 4, configured identically to the first one (including CSipSimple) and it does NOT have the duplicate contact problem. The presence or absence of the CSipSimple app itself is therefore not relevant, IMHO. I have not yet been able to find a noteworthy difference between the two Nexus 4 phones to explain why only one of them has the duplicate contact problem in Signal.

**Comment by MT76** [comment] 2016-09-28 09:02
Issue closed and referenced thread locked. Why is that?
Landed here looking for the same issue. Just switched to Signal, and i too see these duplicate contacts in the list. I do want to try to make my friends drop Whatsapp and switch to Signal but i know many of them will burn Signal due to these duplicates.

**Comment by RiseT** [comment] 2016-09-28 10:58
@MT76 I've closed this issue because it's a duplicate of issue https://github.com/WhisperSystems/Signal-Android/issues/4191

Please post there.

**Comment by MT76** [comment] 2016-09-28 11:29
@RiseT
Or maybe its unlocked in response to me bumping this rather old and closed issue. :)
Anyways, thanks and i will post in 4191.
