### ISSUE TITLE
Screen save protection can be bypassed

### ISSUE THREAD

**Issue by NightmareX1337** [WhisperSystems/Signal-Android#5093] opened 2016-01-19 15:39 UTC
On my Xperia Z2 running Signal 3.9.1 in Android 5.1.1 it's possible to save screen shot doing the followings:
- Start a conversation with your secret friend via Signal.
- Press sleep button at the middle of the conversation.
- Wake your phone and open it so you're back in Signal again.
- Press the square button (the button that shows open apps).
- Take a screen shot.
![screen shot](http://i51.photobucket.com/albums/f358/NightmareX1337/Mobile%20Uploads/Screenshot_2016-01-17-23-11-10_zps6axqnak6.png).

Keep in mind I'm not a native speaker...

**Comment by 2-4601** [comment] 2016-01-19 16:25
Thanks but this is a duplicate of #3712.

**Closed by 2-4601** 2016-01-19 16:25 UTC

**Comment by NightmareX1337** [comment] 2016-01-19 17:25
I'm sad to see this is an OS related bug.
I know it's not OWS team's job but should this be fixed in AOSP code or something? Seems like it's been a while and I doubt it will be fixed soon (unless it's already fixed in source code or something)...
