### ISSUE TITLE
Allow users to specify their own display name

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6395] opened 2017-03-15 15:59 UTC
When joining a large group, where most of the users are not in any user's contacts list, it's very annoying to see messages coming from phone numbers. They are difficult to recognize, remember, and associate with a name. There should be a way for users to specify a name to be shown when in a conversation with an user that doesn't have the number in his/her contacts list. When the number is in the contact list, the contact list name has to be displayed.

This has to be optional.

**Comment by FeuRenard** [comment] 2017-03-15 16:19
This is a duplicate of #4852.

**Closed** 2017-03-15 16:52 UTC
