### ISSUE TITLE
Unable to register when using SIM with transfered number.

### ISSUE THREAD

**Issue by mrorat** [WhisperSystems/Signal-Android#5155] opened 2016-01-30 16:56 UTC
Classic case of operator switch with mobile number transfer. When I'm trying to register it shows the number which was assigned to the sim card before my number was transferred. When I change it to the correct one I'm getting the verification SMS but the app shows:
Connectivity error.
Signal was unable to connect to the server.

Some possible problems include:
- No network connectivity
- Restrictive firewall.

Obviously I'm connected with both WiFi and 3G. Same happens when I'm only on WiFi and 3G.

**Comment by agrajaghh** [comment] 2016-01-30 17:01
please post a debug log

**Comment by mrorat** [comment] 2016-01-30 17:24
I would love to but there is no menu button on this screen.

**Comment by agrajaghh** [comment] 2016-01-30 17:49
if its a new install, you have to use `adb logcat`. It would be really helpful if you could do that, otherwise its impossible to debug I guess

**Comment by mrorat** [comment] 2016-01-30 20:25
I hope it recorded everything required to solve this issue.

[logs.zip](https://github.com/WhisperSystems/Signal-Android/files/110980/logs.zip)

I also took  a screenshot of my sim card details. Maybe this could help as well.

![screenshot_2016-01-30-20-19-18](https://cloud.githubusercontent.com/assets/6039858/12698239/9c172598-c78f-11e5-92e2-43795ce320b4.png)

**Comment by agrajaghh** [comment] 2016-01-30 20:37
I didn't find anything Signal related in this bug, but maybe I missed it.

But on your screenshot it says: "Mobile network state Disconnected". Are you sure you have mobile internet?

What device are you using? custom rom? root? xprivacy?

**Comment by mrorat** [comment] 2016-01-30 20:59
I'm using Elephone P6000 Pro 3GB
Android 5.1
Kernel 3.10.65
Build number ALPS.L1.MP3.V2_NB6753.65U.L1_P22
Custom built version P6000_Pro_20150914

The phone is factory rooted
No xprivacy
No firewall

I'm 100% sure I have internet from both WiFi and Mobile Network :)

**Comment by moxie0** [comment] 2016-01-30 21:02
Zero chance this has anything to do with a transferred number.  If you're getting a connectivity error, the problem is that your device doesn't have connectivity to the server.  I *highly* suspect it's a ROM issue related to whatever weird build you're running, but we'd need a log that's captured during the connectivity error to know (this log wasn't).

**Comment by agrajaghh** [comment] 2016-01-30 21:06
@mrorat to get less noise try `adb logcat -c` to clear the buffer, run `adb logcat > log.txt`, start Signal and try to register, wait fot the error and stop the logging by ctrl + c

**Comment by mrorat** [comment] 2016-01-30 21:15
[logs3.zip](https://github.com/WhisperSystems/Signal-Android/files/111000/logs3.zip)

I cleared the log as advised. Executed logcat and clicked REGISTER button in signal.

**Comment by moxie0** [comment] 2016-01-30 21:21
At no point in this log is an SMS received.

**Comment by mrorat** [comment] 2016-01-30 21:25
True, for some reason it stopped to send sms today. Yesterday I received 5 of them.
Here's one:
![screenshot_2016-01-30-21-23-20](https://cloud.githubusercontent.com/assets/6039858/12698575/0d65b89c-c798-11e5-8e80-36d8dc714fb1.png)

**Comment by moxie0** [comment] 2016-01-30 21:36
If you're not even receiving the SMS, then it's unlikely you could have generated a log that contains a network failure after you receive the SMS.  Please contact support@whispersystems.org if you would like more help

**Closed by moxie0** 2016-01-30 21:36 UTC

**Comment by mrorat** [comment] 2016-01-31 12:33
[logs5.zip](https://github.com/WhisperSystems/Signal-Android/files/111262/logs5.zip)

Hi, I deleted all app data and after that it sends the sms again. I think this time you might be able to find some useful debug.

**Comment by agrajaghh** [comment] 2016-01-31 12:45
```
W/RegistrationService(26396): java.io.IOException: PHONE_REGISTRATION_ERROR
W/RegistrationService(26396): 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
W/RegistrationService(26396): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
W/RegistrationService(26396): 	at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)
W/RegistrationService(26396): 	at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:208)
W/RegistrationService(26396): 	at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)
W/RegistrationService(26396): 	at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)
W/RegistrationService(26396): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/RegistrationService(26396): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/RegistrationService(26396): 	at java.lang.Thread.run(Thread.java:818)
```

looks like something is wrong with your gapps install

**Comment by moxie0** [comment] 2016-01-31 20:14
surprise surprise, rom issue
