### ISSUE TITLE
Group messages partially delivered on poor network conditions

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#5077] opened 2016-01-15 16:48 UTC
Hi @moxie0,

on poor network conditions I often see that Signal indicates a failed delivery while some group members have received the message. Signal does not indicate which group member have received the message and which not. Re-sending leads to some group members receiving the message with multiple copies.

In order to avoid such issues it should be possible to implement a solution based on the following principle:
- Indicate the server that a message to x group members is prepared to be sent
- Transfer all encrypted messages (for each participant) to the server
- The server waits until messages for each participant have been received
- The server delivers the messages

Found with Signal 3.9.1.

**Comment by agrajaghh** [comment] 2016-01-15 18:01
@Norbert80 have a look at the (afaik planed) optimizations mentioned in https://whispersystems.org/blog/private-groups/ 

I think the UX problems you mentioned are a duplicate of another issue, but I couldn't find it at the moment...

**Comment by x12x** [comment] 2016-01-15 18:53
I often have problems like that too -- due to poor signal (lowercase s :smile: )

**Comment by 2-4601** [comment] 2016-01-15 19:08
#2639

**Closed** 2016-01-15 19:11 UTC
