### ISSUE TITLE
Feature Request: Broadcast Msgs

### ISSUE THREAD

**Issue by tribeirom** [WhisperSystems/Signal-Android#6125] opened 2017-01-31 04:46 UTC
It would be nice to have a way to create a broadcast list to send msgs to those people who are part of this list individually. That helps to keep a number of people updated about some subject without having to put all of them together in a group.

**Comment by FeuRenard** [comment] 2017-01-31 08:00
This is a duplicate of #3301.

**Comment by Trolldemorted** [comment] 2017-01-31 08:01
in case you don't mind using signal-cli, it can send a message to multiple targets with one command.

**Comment by tribeirom** [comment] 2017-01-31 12:11
Sorry for the duplicate issue.
Is there any tutorial teaching how to use the signal-cli and how to have acess to it?

**Comment by Trolldemorted** [comment] 2017-01-31 13:42
signal-cli's [readme](https://github.com/AsamK/signal-cli/blob/master/README.md) is pretty good.

It boils down to registering: `signal-cli -u YOURNUMBER register`
verifying: `signal-cli -u YOURNUMBER verify YOURVERIFICATIONCODE`
and then you can send: `signal-cli -u YOURNUMBER send -m "hello world!" [RECIPIENT [RECIPIENT ...]] [-a [ATTACHMENT [ATTACHMENT ...]]]`

**Comment by 2-4601** [comment] 2017-01-31 13:57
Closing as dupe

**Closed by 2-4601** 2017-01-31 13:57 UTC

**Comment by saurik** [comment] 2017-08-15 12:12
@Trolldemorted Is signal-cli able to send messages to hundreds or thousands of users? I have been attempting to find documentation of how the various mentioned rate limits work (as to find out what kinds of operations are inherently rate limited), and have so far not been able to find anything terribly useful :(. (I was asked a while ago to build a service to help undocumented people receive updates on immigration raids, and we all agreed that Signal would be an interesting platform for this, but I couldn't figure out if it was actually possible to send bulk. I figure I should finally just ask ;P.)

**Comment by Trolldemorted** [comment] 2017-08-15 12:36
That is a question for the [community forum](https://whispersystems.discoursehosting.net), the [subreddit](https://www.reddit.com/r/signal) or signal-cli's issues, but not the android client's issue tracker.

If you fear the throughput of a signal client is not sufficient, you should get in contact with its developers. Be as precise as possible and estimate
- the expected amount of outgoing messages per minute (avg and max)
- the expected new established sessions per minute (avg and max)
- the maximum acceptable delay until a message is dispatched to the signal server
- the expected amount of incoming messages per minute (avg and max)

**Comment by saurik** [comment] 2017-08-15 12:54
@Trolldemorted OK, thanks for the pointers! FWIW, I had tried to search for a forum for Signal, and did not manage to find that one (and now that I have the URL, I see why: it is sufficiently unofficial that people seem to not want to list it anywhere). I definitely did not find, nor would have had any hope of finding, the subreddit: there is no mention of reddit anywhere on whispersystems.org, and now that I know to look for it directly I see that there are only three issues anywhere on these GitHub repositories for all of WhisperSystems that seems to mention it (now four; and two of the three are actually you telling people they should have already known about the subreddit ;P). Since you had recommended someone use signal-cli to do something similar to my use case, and as this question actually has nothing to do as far as I would guess with *any* of these specific software programs (as the rate limits come from the Signal servers, not from these clients), I thought it made sense to ask you (it certainly made more sense to me to ask on a closed issue than to open a new one on signal-cli). Regardless: I will go ask in the apparently-unofficial forums in the hope someone there actually knows something about the seemingly undocumented rate limits of the Signal service.
