### ISSUE TITLE
Turn off vibration during calls

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#5321] opened 2016-03-06 21:49 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

So I just sat here and talked to someone over Signal, and I sent them a message. My ears almost shattered at the sound that followed. It was pure agony. Please, for the love of all that is unholy, turn off vibration during calls!

Possibly related: https://github.com/WhisperSystems/Signal-Android/issues/4164

**Comment by haffenloher** [comment] 2016-03-07 16:55
Duplicate of #4318.
On a side note, I think #79 can be closed as well, because AFAIK the vibration only occurs during *Signal calls* now, not during normal calls.

**Comment by agrajaghh** [comment] 2016-03-07 17:00
thanks, closing as dupe

**Closed by agrajaghh** 2016-03-07 17:00 UTC
Labels: feature
