### ISSUE TITLE
Crash on Add Attachment

### ISSUE THREAD

**Issue by dcousens** [WhisperSystems/Signal-Android#7073] opened 2017-10-09 00:48 UTC
### Bug description
Using the "..." top-right "Add attachment",  only when the text field has _freshly been entered_ as un-sent text,  a crash occurs.

### Steps to reproduce
- Enter "test" into the text field,  but DO NOT SEND
- "..." -> "Add attachment"
- Crash

**Actual result:** Crash
**Expected result:** No crash

### Device info

**Device:** Google Pixel
**Android version:** 8.0.0
**Signal version:** 4.10.12

### Link to debug log
https://gist.github.com/anonymous/2b05da06aea8343d713896dbd73a2d79

**Comment by dcousens** [comment] 2017-10-09 00:51
Does not occur if I enter "test" into the text field,  go back,  re-enter the conversation,  then do "..." -> "Add attachment".

It needs to be fresh text,  from NOTHING.
If I add to the 'stale' text,  the crash does not happen.

**Comment by moxie0** [comment] 2017-10-09 01:38
Duplicate of #6894

**Closed by moxie0** 2017-10-09 01:38 UTC

**Comment by dcousens** [comment] 2017-10-09 01:52
@moxie0 I couldn't tell if that was an actual duplicate,  the steps to reproduce were different?

**Comment by moxie0** [comment] 2017-10-09 02:21
np, it's the same thing, bug is in Android 8
