### ISSUE TITLE
Signal messages/calls "enabled" after unregistering

### ISSUE THREAD

**Issue by chrihu** [WhisperSystems/Signal-Android#6358] opened 2017-03-10 15:28 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This issue has been introduced with the webrtc calling functionality. (tested with 3.30.x enabled beta calling and 3.31.x)
When you open a conversation with a signal contact after unregistering, it looks as if you are still able to send signal messages and make secure calls.
It is even possible to initiate a secure call that never successfully connects, but the other device will receive a "missed call" notification.

EDIT: found the culprit 53d590947ed7d60129fddb014550cd8490ec71c4

### Steps to reproduce
- Unregister (settings > advanced > toggle "Signal messages and calls" off > confirm dialog)
- Open a conversation with a signal contact

**Actual result:** It looks as if you are still registered (blue send button, phone icon with lock etc.)
**Expected result:** Only SMS functionality should be available. (gray send button, phone icon without lock etc.)

### Device info

**Device:** Nexus 5
**Android version:** 7.1.1
**Signal version:** 3.31.1

**Comment by johanw666** [comment] 2017-03-10 15:52
A result of https://github.com/WhisperSystems/Signal-Android/commit/b110c8a2cb39d169063832c2e1e753d1d1dd967a ?

**Comment by chrihu** [comment] 2017-03-10 17:57
Nope, it's 53d590947ed7d60129fddb014550cd8490ec71c4 fault.
Signal on the device that gets the calls from the unregistered phone even crashes sometimes:
<pre>W WebRtcCallService: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
W WebRtcCallService: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
W WebRtcCallService: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
W WebRtcCallService: 	at org.thoughtcrime.securesms.util.ListenableFutureTask.callback(ListenableFutureTask.java:103)
W WebRtcCallService: 	at org.thoughtcrime.securesms.util.ListenableFutureTask.access$100(ListenableFutureTask.java:28)
W WebRtcCallService: 	at org.thoughtcrime.securesms.util.ListenableFutureTask$2.run(ListenableFutureTask.java:91)
W WebRtcCallService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W WebRtcCallService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W WebRtcCallService: 	at java.lang.Thread.run(Thread.java:761)
W WebRtcCallService: Caused by: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
W WebRtcCallService: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:207)
W WebRtcCallService: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:404)
W WebRtcCallService: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendCallMessage(SignalServiceMessageSender.java:116)
W WebRtcCallService: 	at org.thoughtcrime.securesms.service.WebRtcCallService$8.call(WebRtcCallService.java:905)
W WebRtcCallService: 	at org.thoughtcrime.securesms.service.WebRtcCallService$8.call(WebRtcCallService.java:900)
W WebRtcCallService: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W WebRtcCallService: 	... 3 more
W WebRtcCallService: Caused by: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
W WebRtcCallService: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:550)
W WebRtcCallService: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:202)
W WebRtcCallService: 	... 8 more</pre>

**Comment by cascheberg** [comment] 2017-03-11 07:51
@moxie0 I think `ConversationActivity.initializeBetaCalling` should be removed (i.e. 53d590947ed7d60129fddb014550cd8490ec71c4 should be reverted), now that WebRTC has become the default. That will fix this bug. In case you want to keep the capability refresh for every user: the problem is that the code uses the capability of the contact, but does not check the local `isPushRegistered` pref.

The crash should be fixed separately. In `WebRtcCallService` not all `exceptions` are caught, as can be seen in the posted debug log. I also noticed that some `throws` definitions are missing.

**Comment by moxie0** [comment] 2017-03-12 01:55
it'll be removed with the redphone code in the next release

**Closed** 2017-03-12 17:50 UTC
