### ISSUE TITLE
URLs containing emojis are not clickable

### ISSUE THREAD

**Issue by Juul** [WhisperSystems/Signal-Android#6352] opened 2017-03-10 04:30 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If an URL in EmojiTextView contains an emoji then it is not clickable even if it is a completely valid URL.

### Steps to reproduce
* Send a signal message with the text: http://🍄.ga/
* Observe that neither sender nor recipient can click the link

**Actual result:** Link isn't clickable
**Expected result:** Link should be clickable

### Device info
**Device:** OnePlus One
**Android version:** 5.0.2 (but probably all)
**Signal version:** 3.30.4

**Comment by 2-4601** [comment] 2017-03-13 18:46
Seems like a duplicate of #6019. (See [comment](https://github.com/WhisperSystems/Signal-Android/issues/6019#issuecomment-271390509))

**Closed by 2-4601** 2017-03-13 18:46 UTC
