### ISSUE TITLE
[Feature Request] Check with the SMS Database to pull in new messages as an option

### ISSUE THREAD

**Issue by am385** [WhisperSystems/Signal-Android#7113] opened 2017-10-20 16:57 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
SMS Messages added through Cortana / Windows 10 link will not appear when sent from a Windows 10 client.

### Steps to reproduce
- Download and Setup Cortana on an Android device
- Setup Cortana on a Windows 10 machine with at least the Creators Update
- Link your Microsoft Account
- Use a separate device to send an SMS (not Signal) to the device with Cortana
- Wait for the message to be received and for Cortana to forward it to your Windows 10 machine
- Reply to the message through the Windows 10 interface

**Actual result:** The message is sent back through your phone but does not appear in Signal as a sent message. It will appear in the default "Messages" app though.
**Expected result:** Signal should be listening for any SMS to be added to the database that are from the current device.

### Device info
**Device:** Samsung Galaxy S6
**Android version:** 7.0
**Signal version:** 4.11.5

**Comment by Evanito** [comment] 2017-10-20 17:22
I occasionally use auto-replying apps and the messages sent do not show up in Signal, so this gets a big 👍  from me.

**Comment by moxie0** [comment] 2017-10-20 19:46
I think this is effectively a dupe of #5803.

**Closed by moxie0** 2017-10-20 19:46 UTC
