### ISSUE TITLE
SMS from new contact (non-Signal) answered with Signal message

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5027] opened 2016-01-05 11:22 UTC
I got a SMS from a new contact, which is not in my address book. Signal is my default SMS app. I attempted to answer the SMS and got an error when sending (I still did not add this contact to my address book). Tapping on the failed outgoing message I saw the lock symbol for Signal messages in the lower right corner of the message bubble. When I try to resend, it fails again as the recipient is not a Signal user. Then returning to the conversation, the default method for messaging is correctly an unsecured SMS.
Log: https://gist.github.com/anonymous/2899b36422ee4c0d769c

**Comment by cascheberg** [comment] 2016-01-05 12:27
Log shows a
> UndeliverableMessageException: Trying to send a secure SMS?

as in #4927 and #4460

**Comment by FeuRenard** [comment] 2016-01-05 14:34
I think the main issue is:
Signal offers me at first encounter by default sending a Signal-message to a number, that is not registered at the Signal server.

That this attempt to send a Signal message fails is no surprise, I think.

**Comment by 2-4601** [comment] 2016-01-05 14:51
@FeuRenard Could you try playing around with the steps laid out in https://github.com/WhisperSystems/Signal-Android/issues/4932#issuecomment-168653122
There's a bug where the transport mode does not reset properly. Perhaps it is related?

**Comment by FeuRenard** [comment] 2016-01-05 15:28
I am able to reproduce the behaviour described in https://github.com/WhisperSystems/Signal-Android/issues/4932#issuecomment-168653122. Maybe my issue is related to or even a duplicate of #4932.

**Comment by moxie0** [comment] 2016-01-05 20:38
closing as duplicate of #4932

**Closed by moxie0** 2016-01-05 20:38 UTC
