### ISSUE TITLE
Change default SMS application opens wrong settings

### ISSUE THREAD

**Issue by stumpylog** [WhisperSystems/Signal-Android#6320] opened 2017-03-01 03:26 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When in the Signal app, Settings -> SMS and MMS -> SMS Enabled opens the "Wireless and networks" settings page, instead of the expected "Default applications" page in settings.  Signal was already set as the default messaging app.  Changing to Messages, then going through the steps works as expected.  Something with the assumption that Signal is not default?

Maybe related #6235

### Steps to reproduce
- Open Signal
- Go to Settings
-  SMS and MMS
- SMS Enabled
- Touch where indicated

**Actual result:** The "Wireless and networks" page in settings is opened
**Expected result:** The "Default applications" page is opened

### Screenshots
Can add if really needed

### Device info
**Device:** Samsung S7 on Verizon (G930V)
**Android version:** 6.0.1
**Signal version:** 3.30.4

### Link to debug log
[Debug Log](https://gist.github.com/anonymous/7acdec4a3bb1a31baddb88e426801da8)

**Comment by p4nci** [comment] 2017-03-01 08:57
dupe of https://github.com/WhisperSystems/Signal-Android/issues/5541

**Closed** 2017-03-01 20:08 UTC
