### ISSUE TITLE
Invalid country code prefixed to local SMS messages

### ISSUE THREAD

**Issue by madduck** [WhisperSystems/Signal-Android#5078] opened 2016-01-16 09:21 UTC
I am registered using my German cell number, but I am currently in New
Zealand. When I receive a message from someone, it usually shows up as a local
number, e.g. 021/1234567. If I reply to this message, an SMS is sent to +49
21/1234567, that is, Signal prefixes the number with my default country code,
not the country code of the country in which I am currently logged on.

Thanks,
martin

**Comment by 2-4601** [comment] 2016-03-18 01:41
Related #5306, did @haffenloher have some suggestion for this?

**Comment by madduck** [comment] 2016-03-18 06:08
Are you sure, @moxie0 that there is no way to get the current country code? I seem to think that the other messenging apps can do this just fine…

Alternatively, if you cannot get at the country code, why not just leave it out, e.g. send the message to 021/… in the example above and let the network figure it out?

**Comment by haffenloher** [comment] 2016-03-18 11:47
@2-4601 yes, I think instead of [always using the local number's CC](https://github.com/WhisperSystems/libtextsecure-java/blob/432ffbaa3a2eeb100ca1fa6470d2243a64e6c913/java/src/main/java/org/whispersystems/textsecure/api/util/PhoneNumberFormatter.java#L93-L100), we could do something like [this](https://android.googlesource.com/platform/frameworks/base.git/+/android-4.2.2_r1/services/java/com/android/server/location/ComprehensiveCountryDetector.java#166).
E.g. use

1. [`TelephonyManager.getNetworkCountryIso()`](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkCountryIso%28%29) for non-CDMA phones
1. fall back to using the last known location
1. as a last resort, fall back to the current method of using the local number's country code

But maybe there are some problems with `getNetworkCountryIso()` that I don't know of?

**Comment by moxie0** [comment] 2016-03-18 17:24
duplicate of #5306

**Closed by moxie0** 2016-03-18 17:24 UTC

**Comment by madduck** [comment] 2016-03-18 21:42
@moxie0 frankly, I find it a bit weird to close an issue as a duplicate of one filed later, especially after a possible solution has been proposed.

**Comment by haffenloher** [comment] 2016-03-18 23:10
@moxie0 would you consider merging a PR that changes libtextsecure's PhoneNumberFormatter to use `getNetworkCountryIso()`?

**Comment by moxie0** [comment] 2016-03-19 07:04
@haffenloher Unfortunately not. It's insanely unreliable, and just inverts the problem. Our reality is that we have to e164 all numbers, and we have to do it consistently.

**Comment by codethief** [comment] 2016-06-06 07:58
I am proposing to reopen this issue. I just ran into the same situation and it is extremely annoying. It basically means that **I can't use Signal as my default text messaging app when I'm abroad** and I went back to Android's default messaging app for now. To elaborate on this, consider the following **situation** (basically my situation right now):

- Sign up for Signal using a phone number from country A with country code +X
- Go traveling in country B (country code +Y), buy a local SIM card, put it in your phone without switching numbers in Signal – [which is mess](http://support.whispersystems.org/hc/en-us/articles/212535818-What-do-I-do-if-I-get-a-new-number-What-if-I-am-switching-to-a-new-phone-) and doesn't work reliably (separate bug report will follow). (Besides why should I switch numbers in the first place if I'm staying abroad only temporarily?)
- Receive a text message from a local in country B, say Bob with phone number +Y 123456789.

**Actual result:** Provided that the phone number specified in the text message doesn't contain the country code, Signal will prepend the country code "+X" to the phone number. This leads to the following funny behavior: I text Bob (+Y 123456789), he replies and the incoming message will be filed in a new conversation with number +X 123456789. So I'll basically have a conversation for outgoing messages (+Y …) and one for incoming messages (+ X …), although the correspondent is the same. Now, consider the situation where I might not notice that and reply to the incoming message, in which case I am not only sending a text to the wrong number but I am also sending an international text **which might cause me fees I didn't expect**. (This is slightly different from the situation mentioned by OP where you don't buy a new SIM card but keep using your phone number from country A in country B. In this case you'd probably expect to pay additional fees for sending – now international – texts to Bob, anyway, though the specific fees for sending texts to numbers back in country A and for numbers in country B might differ, depending on the cellular provider.)

**Expected result:** Signal should prepend "+Y" to the number or nothing at all (the latter approach is taken by the default messaging app), so that incoming messages can be filed correctly and there is only one conversation.

**Proposed solution:** I understand that Signal must implicitly prepend country codes to phone numbers of contacts that don't carry a country code in order to find out whether those contacts are using Signal as well. However, I don't understand why this has to be done for numbers of incoming messages, too. If I receive an incoming unencrypted message from Bob, that means that Bob is not using Signal, anyway. (Otherwise his instance of Signal would have detected that I'm using Signal as well – if necessary by prepending Bob's country code to my phone number that Bob stored on his phone, see above.) So I suggest to simply omit this non-feature and follow the default messaging app's behavior (of not prepending a country code to numbers of incoming messages at all) so that Signal can finally be used abroad.

To put this into perpective, consider that, for the average Signal user, it is – as of now – far more likely (by orders of magnitude!) to experience this issue than for him to run into another Signal user Bob abroad and exchange numbers with him while not including the respective country codes in the numbers that they store of each other on their phones. (I mean, if I signed up for Signal with a foreign number, i.e. a number from country A, I wouldn't give Bob my local number to begin with but my foreign number including the correct country code, wouldn't I?)

Please let me know if I'm missing anything here.

Alternatively, if this proposal is rejected, how about introducing an option (for advanced users) to select the country code that should be prepended to local phone numbers of incoming messages? (Maybe one could also notify the user once when there's a mismatch between the country code of the number he signed up with (that is used to prepend incoming numbers) and the current country code provided by `getNetworkCountryIso()`. I mean the latter might not be reliable but if the notification is phrased correctly, it would at least put the user into power and allow him to adjust the setting if there is indeed a mismatch.)

**Comment by kiowa** [comment] 2017-01-06 22:00
I also second @codethief. Running into this problem myself when switching my main (norwegian) simcard to a mexican one (while travelling) I suddenly can't use Signal as my main sms app as it insists on adding +47 all over the place.

So for a smooth Signal experience until everybody in the world comes to their senses and starts using encrypted chats it would be nice to have support for multiple sims/phone numbers for us travellers.

**Comment by witlessbird** [comment] 2017-08-16 20:37
To expand on @codethief's report:

Let's assume that an existing simple-text conversation with some local number that is not in address book already exists. 

An attempt to continue this conversation from another country will appear to succeed, while in fact new messages will either be send to a wrong number or get silently dropped altogether (in my case I was attempting to send messages to a UK number while being in Canada). To complicate things further there's no way to check what the message was actually sent to.

 I'll second @codethief's suggestion to not assume/guess incoming texts country of origin, as it is at the very least misleading. An alternative approach might be not to use signal for simple text messaging and leave that to the default application.

**Comment by yan-** [comment] 2018-05-23 17:19
I'm having the exact same problem as described in this and various other issues. But all of them have been closed without the problem being fixed apparently. So I'd like to second the request to address this issue. If the default message app can handle the problem, why can't Signal?

**Comment by dlenski** [comment] 2018-06-30 19:35
Piling on… I signed up for Signal while abroad (using a local SIM card) and now it prepends the other country's E164 prefix to all local numbers, so I have the problem "can't use Signal for SMS when **at home**."

I quite like @codethief's proposed solutions:

1. Don't prepend a country code to incoming SMS _at all_ (upside is fixing this problem; downside is decreased ability to match unknown numbers to Signal users)
2. Allow users to configure country code for incoming SMS (perhaps with registered CC and SIM CC as the top two options?)

Another idea would be to avoid adding a CC prefix to incoming messages if the numbers are already valid E164 numbers once a `+` is prepended.

**Comment by mattkirkey** [comment] 2018-09-23 07:44
How is this closed?  This is one of the most annoying issues to exist especially when travelling abroad.  Can someone please resolve this as the current situation is unacceptable.

**Comment by kanru** [comment] 2021-04-21 08:04
The other thread is locked, so comment here. It is still the same situation in 2021.

**Comment by glith** [comment] 2021-11-18 14:56
Hello,
Signal automatically adds the country codes to the short service numbers. How do I prevent that?
For example if I live in germany and want to send an SMS to service number "123" the result is that Signal tries to send it to "+49 123" and it fails!

**Comment by danielocdh** [comment] 2021-12-23 01:41
was this ever fixed? is there a beta/alternative version of signal that can be used for this? or any other app similar to signal that can do this?

**Comment by nheinric** [comment] 2022-01-12 20:00
Piling on.
 This is still happening, and is still a problem for anyone who travels.
Great example posted above, as well as the one about short codes (eg I am never going to get an airline or bank to switch to signal, but I still need to converse with them using short codes): https://github.com/signalapp/Signal-Android/issues/5078#issuecomment-322891789

I agree with the simple solution: don't add country codes to incoming SMS _at all_.

**Comment by yan-** [comment] 2022-02-15 02:31
I can confirm that this still is a problem.

**Comment by opseasoi** [comment] 2022-06-22 05:16
Hi, same issue here. 
Signal is always adding prefix to numbers, even with special local or operator numbers like 275 or other short number. Signal is always adding +262 (my country code), so +262 275 in this example and the message is not sent. 
Please at least add a way to edit number before sending. 
Thanks,
Pascal.

**Comment by codethief** [comment] 2022-10-08 18:16
This is starting to get ridiculous. I commented on this issue 6(!) years ago – and just ran into it once again. In the meantime, there have been countless of other reports about this bug, and almost all of them have been closed:

https://github.com/signalapp/Signal-Android/issues/7321

https://github.com/signalapp/Signal-Android/issues/8838

https://github.com/signalapp/Signal-Android/issues/9602

https://github.com/signalapp/Signal-Android/issues/11274

**Comment by codethief** [comment] 2022-10-12 19:53
Looks like my hope that this will be fixed eventually was misplaced: Instead, [SMS support will be removed entirely](https://signal.org/blog/sms-removal-android/).

I can't put into words just *how* angry this decision makes me. It's not just that SMS support will be gone for future messages, no. Existing SMS messages will also be erased from the message history. Given how many of my contacts over the years switched between using Signal, not using it and using it once again, my conversation history will also suddenly be inconsistent. What the actual fuck. 

@#$!&?%

**Comment by haffenloher** [comment] 2022-10-13 14:48
Fyi: existing SMS messages [will *not* automatically be erased](https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954/18) from the database.

**Comment by codethief** [comment] 2022-10-13 17:27
Thanks, @haffenloher ! I came back here to correct my comment as someone else on the community forums had pointed me to that post but I see you were faster. :)

That's at least somewhat of a relief.
