### ISSUE TITLE
Some (minor) group UI issues

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#1347] opened 2014-04-12 13:47 UTC
1) wrong ActionBar title:
- open an existing group
- select update group
- ActionBar correct title: "Update Group: *some groupname*"
- leave the activity by locking the screen, adding a member or adding an avatar
- when you return to the group settings the action bar title now is: "New Group"

2) The default group avatar is not circle cropped, in the settings activity.
Edit: fixed many commits ago
Edit 2: unfixed lately

3) Leaving the group settings with the check mark - without effectively changing something (name, members, avatar) - leads to a group update broadcast. This is distracting for the receivers when nothing has changed.

4) ~~Group conversation recipients dialog allows tapping a contact to highlight it shortly. is there any reason for that? Planned features maybe?~~ fixed

5) An avatar can not be changed back to default

**Comment by 2-4601** [comment] 2015-11-12 21:40
2) has not been an issue for a while?

1) probably will be solved by pr #4502?

**Comment by mcginty** [comment] 2015-11-12 22:23
3) is a necessary evil until groups are less broken (it's the only way to send new group contexts to users missing them without needing to change the group info)

5) I had put a PR out to fix a while back that didn't get accepted, so I guess we can call that "won't fix"

closing this as dupe of #4502

**Closed by mcginty** 2015-11-12 22:23 UTC
Labels: bug, ux

**Comment by agrajaghh** [comment] 2015-11-12 22:33
> 3) is a necessary evil until groups are less broken (it's the only way to send new group contexts to users missing them without needing to change the group info)

but we don't have to show this on the client side if nothing changes, no? but to be honest, it shouldn't happen often...

**Comment by mcginty** [comment] 2015-11-12 22:46
@agrajaghh for a user without the context, the group *is* updated. seems complicated to do right and rare enough to not put a high priority on it, imo.

**Comment by agrajaghh** [comment] 2015-11-12 22:52
I meant the other users who are already up to date, but I guess you're right. Its too much work for that atm...

**Comment by mcginty** [comment] 2015-11-12 22:56
@agrajaghh right, but that logic of determining whether the diff is zero for a group context update would have to be moved to before a notification is given, if I'm guessing correctly, which seems rough.
