### ISSUE TITLE
Missing space after comma in group members list; sort alphabetically

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#7079] opened 2017-10-09 22:43 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

- In a group conversation, the group members are listed below the group name. The names are comma-separated, but after the commas there should be a space, as recommended by any manual of style. WhatsApp puts a space there indeed.
- The list should be sorted alphabetically.
- The list that appears when tapping on the "group members" button should also be sorted alphabetically.

### Device info

**Android version:** 7.1
**Signal version:** 4.11

**Comment by moxie0** [comment] 2017-10-10 16:06
Duplicate of #7060

**Closed by moxie0** 2017-10-10 16:06 UTC
