### ISSUE TITLE
Sometimes attachments are saved with the suffix ".attach"

### ISSUE THREAD

**Issue by AndrewPy** [WhisperSystems/Signal-Android#6507] opened 2017-04-08 12:09 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes attachments are saved with the suffix ".attach" (instead of the correct suffix).
The problem only occurs briefly but it occurred several times in the last few days.

### Steps to reproduce
- Receive a message with attachment (video or sound).
- Save the attachment.

**Actual result:** The message is saved with the suffix ".attach".
**Expected result:** The message should be saved with the correct suffix (".mp3", ".mp4", ".3gp" or ".amr").

### Device info
**Device:** Wiko Pulp 4G
**Android version:** 5.1.1
**Signal version:** 4.2.4

### Link to debug log
https://gist.github.com/ebe7f29ce22a4ce637ccdf63f49d9802

**Comment by FeuRenard** [comment] 2017-04-12 11:28
This is not exactly a duplicate of #5899, but one of these issues in "open" state should be sufficient.

**Comment by 2-4601** [comment] 2017-04-29 14:08
Let's use #5899.

**Closed by 2-4601** 2017-04-29 14:08 UTC
