### ISSUE TITLE
multiple devices support (non Desktop)

### ISSUE THREAD

**Issue by altring** [WhisperSystems/Signal-Android#5735] opened 2016-09-30 14:50 UTC
Hello.
It would be great for Signal to support multiple android devices so people will be able to use it on smartphone and  tablet simultaneously like in case of WhatsApp or Viber.
For many people this is a stopper to start using Signal.
Thanks in advance!

**Comment by 2-4601** [comment] 2016-09-30 18:05
Closing as duplicate of #5102

**Closed by 2-4601** 2016-09-30 18:05 UTC

**Comment by Trolldemorted** [comment] 2016-09-30 20:09
If you don't mind compiling Signal yourself, you could test my [multidevice fork](https://github.com/Trolldemorted/Signal-Android/tree/multidevice) and report all bugs you encounter. I am using it myself and so far it is looking good.


Why is #5102 locked by the way?

**Comment by claell** [comment] 2022-01-07 10:34
It seems, we need to create just another issue for this.
