### ISSUE TITLE
Can't send SMS: org.thoughtcrime.securesms.transport.UndeliverableMessageException: Trying to send a secure SMS?

### ISSUE THREAD

**Issue by lpar** [WhisperSystems/Signal-Android#5127] opened 2016-01-25 20:25 UTC
Can't send SMS to a non-Signal user.

https://gist.github.com/anonymous/47fd3b31c06f7958cd4b

Error seems to be at lines 61 and 181 (I tried twice in quick succession).

Confused about the error, because I didn't think Signal supported encrypted SMS any more.

**Comment by 2-4601** [comment] 2016-01-25 21:24
Looks like a dupe of #4765. If you can reproduce this could you please add the steps there?

**Closed by 2-4601** 2016-01-25 21:24 UTC

**Comment by jmayday** [comment] 2019-05-17 12:37
#4765 has been closed despite issue is still present (Signal 4.39.4)

**Comment by alan-signal** [comment] 2019-05-17 13:17
@jmayday This issue is also closed. Please open a new issue.

**Comment by alan-signal** [comment] 2019-05-17 13:18
OK, I see you did, https://github.com/signalapp/Signal-Android/issues/8816
