### ISSUE TITLE
Mms download failed occurs when receiving mms

### ISSUE THREAD

**Issue by moltenz** [WhisperSystems/Signal-Android#5681] opened 2016-09-13 10:59 UTC
**Device:** Samsung s7
**Android version:** 6.0.1
**Signal version:** 3.18.3

### Link to debug log

https://gist.github.com/anonymous/b43a28f44f68d4e142ca602915884893

**Comment by FeuRenard** [comment] 2016-09-13 11:17
Your debug log shows the same exceptions like the one in [this post](https://github.com/WhisperSystems/Signal-Android/issues/4878#issuecomment-187919501).
Could you please check, whether this issue is a duplicate of #4878? Maybe in the discussion are even some hints at a solution that works for you.

**Comment by moltenz** [comment] 2016-09-13 11:29
Hi thanks for the reply.

Unfortunately can't do what is listed as the solution in this thread (set
apn settings within signal, SMS and MMS section doesn't have that option)

Was it removed?

What exceptions are being shown?

**Comment by FeuRenard** [comment] 2016-09-13 11:47
Ok, but from your point of view, you agree, that the issues seem to be same? Especially looking at the screenshot in #4878?
From my point of view (roughly comparing the logs) this is a duplicate of #4878.

I have no experience with MMS with or without Signal. But in both logs there are the following exceptions concerning MMS download. Maybe the lines before are relevant, too. But those slightly differ.
> W/IncomingLollipopMmsConnection(11202): java.io.**FileNotFoundException**: No such file or directory
W/IncomingLollipopMmsConnection(11202): 	at android.os.Parcel.openFileDescriptor(Native Method)
W/IncomingLollipopMmsConnection(11202): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
W/IncomingLollipopMmsConnection(11202): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.providers.MmsBodyProvider.openFile(MmsBodyProvider.java:77)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1356)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1536)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1602)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:400)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
W/IncomingLollipopMmsConnection(11202): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.providers.MmsBodyProvider$Pointer.getInputStream(MmsBodyProvider.java:133)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:89)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:67)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:97)
W/IncomingLollipopMmsConnection(11202): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/IncomingLollipopMmsConnection(11202): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/IncomingLollipopMmsConnection(11202): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/MmsDownloadJob(11202): ws.com.google.android.mms.MmsException: java.io.**FileNotFoundException**: No such file or directory
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:97)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:67)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:97)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/MmsDownloadJob(11202): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/MmsDownloadJob(11202): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/MmsDownloadJob(11202): Caused by: java.io.**FileNotFoundException**: No such file or directory
W/MmsDownloadJob(11202): 	at android.os.Parcel.openFileDescriptor(Native Method)
W/MmsDownloadJob(11202): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
W/MmsDownloadJob(11202): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.providers.MmsBodyProvider.openFile(MmsBodyProvider.java:77)
W/MmsDownloadJob(11202): 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1356)
W/MmsDownloadJob(11202): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1536)
W/MmsDownloadJob(11202): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1602)
W/MmsDownloadJob(11202): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:400)
W/MmsDownloadJob(11202): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
W/MmsDownloadJob(11202): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
W/MmsDownloadJob(11202): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.providers.MmsBodyProvider$Pointer.getInputStream(MmsBodyProvider.java:133)
W/MmsDownloadJob(11202): 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:89)
W/MmsDownloadJob(11202): ... 5 more

**Comment by moltenz** [comment] 2016-09-13 12:23
As far as the issue is concerned ( can't download mms) it is a duplicate
yes.

But as for it being the same cause as this other issue, I'm unsure.

**Comment by moltenz** [comment] 2016-09-14 10:37
Anyone else have anything to add? 

I've tried a reinstall of the app too, same deal unfortunately :(.

**Comment by moltenz** [comment] 2016-09-14 10:58
Found the issue. Com.android.mms.service is tagged as bloatware by package disabler Pro (a program I use to turn off manufacturer bloat that is typically not needed for a phone to function correctly)

It appears that signal uses this service for mms send/recieve. Apparently stock Android app does not use this service as it still functions fine with it disabled.

If anyone has this issue in the future and debug looks similar to mine, I recommend this as one of the troubleshooting steps if use a program like I mentioned above.

Thanks for your help Renard.

**Closed** 2016-09-15 08:44 UTC
