### ISSUE TITLE
Enhance Signal to allow transfer of arbitrary file types

### ISSUE THREAD

**Issue by darmbrust** [WhisperSystems/Signal-Android#5837] opened 2016-11-03 19:38 UTC
One of the requests that came out of the work to improve photo quality (https://github.com/WhisperSystems/Signal-Android/issues/672) was the ability to simply send photos exactly as they are, without reprocessing them.

In the other thread, there are many good reasons why there isn't an option to handle photos that way, dealing with the previews, display, memory limitations, etc.

It occurs to me that the way to allow this option to those that need it - and also provide more utility overall - is to provide an option to send arbitrary file types - including photos - without processing them.

There are currently choices for Images, Audio, Video when sending a message. Just give us an option for "Files". Add an option to the attachment area for "File". If we pick a picture via the file option, instead of the image option, we just send the image exactly as is with no processing / preview / etc. The bonus is it now works for any file type.... and I can finally send full resolution images without having to revert to e-mail or something like that.  Giving us the ability to push them through as files, however, bypasses a all of the issues related to device memory, preview, etc.  Following the existing UI design / pattern gives the user customizability over what is downloaded (and when - only wifi, etc).

It also now lets us send any other document securely, which would be a great bonus.

Not sure what the upper limit needs to be on the file size... but even if it was as low as 10 MBs, we could send full resolution photos.

**Comment by FeuRenard** [comment] 2016-11-03 19:52
This is a duplicate of #993.

**Closed** 2016-11-03 19:54 UTC
