### ISSUE TITLE
[REQUEST] Pop Out Bubble Chats like FB Messenger

### ISSUE THREAD

**Issue by JustPassingByHere** [WhisperSystems/Signal-Android#7057] opened 2017-10-06 14:25 UTC
This is not an issue but could not find the best place to post this. 

Are there any plans to implement a feature like the Facebook Messenger where the conversations are easily accessible from any screen? I find it really useful to be able to have the bubbles on the side while I have another app open without the need to constantly switch between them to keep the conversation going.

**Comment by FeuRenard** [comment] 2017-10-06 14:37
Duplicate of #3039

**Comment by JustPassingByHere** [comment] 2017-10-06 15:15
Ah sorry for my duplicate post! I tried searching for Messenger and Facebook but nothing came up for me.

**Comment by JustPassingByHere** [comment] 2017-10-06 15:23
I read the other post and realized it has not reached a decision. Reopened.

**Comment by FeuRenard** [comment] 2017-10-06 15:29
We don't need two issues tracking the same feature request. #3039 is still open and thereby considered a valid request. Please close this one.

**Closed** 2017-10-06 19:09 UTC

**Comment by JustPassingByHere** [comment] 2017-10-06 20:16
Closed as requested. 

There should be a separate area (Wiki perhaps?) to house improvements and suggestions such as this. The original thread you linked is buried behind so many pages. It is difficult to find it unless you know what to look for.

**Comment by FeuRenard** [comment] 2017-10-07 07:11
Thanks! You're welcome to join the community forum for any discussions:
https://whispersystems.discoursehosting.net/
