### ISSUE TITLE
Attachment drawer not correctly positioned on some screens

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#4973] opened 2015-12-27 11:35 UTC
It wasn't until I saw https://github.com/WhisperSystems/Signal-Android/commit/759ecbc7b82be80261164d392875bb237764ed6f that I realized this was wrong: this happens on a Sony XPeria Z1 Compact, Android 4.4.4 and a 4.3" screen with a resolution of 1280x720. Signal 3.8.1.
![signal-3 8 1-attachmentdrawer](https://cloud.githubusercontent.com/assets/8427572/12010067/473646ee-ac96-11e5-8033-8557a68978bd.png)

**Comment by agrajaghh** [comment] 2015-12-27 12:58
closing as duplicate of #4405

**Closed by agrajaghh** 2015-12-27 12:58 UTC

**Comment by johanw666** [comment] 2015-12-27 13:42
Sorry, I didn't see that issue. At least it seems not a Motorola only issue.

**Comment by agrajaghh** [comment] 2015-12-27 15:56
@johanw666 maybe post your device info there as well, might be helpfull

**Comment by johanw666** [comment] 2015-12-28 08:46
I did (above the screenshot), what more do you want to know?

**Comment by agrajaghh** [comment] 2015-12-28 12:51
@johanw666, no I meant in the original issue :wink: 
#4405
