### ISSUE TITLE
Dark Theme suggestions

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#2446] opened 2015-02-11 00:23 UTC
I am a big fan of the dark theme so in using it I had a few thoughts about things I think would improve it.  I'm not savvy on all the material design guidelines from google so if I have ideas that break that you know why. :) Here goes:
1. The light theme has a blue bar on the top.  The dark theme is black.  I don't know which is more palatable but it might look pretty slick if the textsecure icon or the top bar was also blue in the dark theme.
2. When there is an unread message it shows the time in blue.  I like the color idea but should the color match the security level, i.e. green for SMS, blue for TS messages?
3. The "TextSecure" text at the top doesn't look bold like the same text in the light theme.  Don't know which is right but they should probably match.
4. In the "Settings" area, the checkbox for push has a sea green or aqua background which looks kinda pukey to me.  I'd like to see it blue like in the light theme or maybe have it be black and the checkmark be blue.  This is in the "Advanced" area of "Settings" too.
5. This one is actually in both dark and light: The lock, phone and option menu dots in the top right take up enough space that most if not all my contacts names are partially truncated with the ellipses.  Not a huge deal but is there a way to re-arrange that area to show the whole name?

Thanks again for the effort put behind TextSecure and all the other apps you guys work on.  Really truly great stuff; you guys are like coding gymnasts.  I hope these are helpful and not a waste of time.

**Comment by jeremymasters** [comment] 2015-02-12 00:33
I thought of another one.  When I choose to add an attachment to a conversation, the window that pops up is light themed instead of dark.  Same for choosing the actual piece of media I'm sharing.  That's also in light theme.

**Comment by riyapenn** [comment] 2015-09-24 00:33
Looks like only points 1 & 4 still exist and are dupes of #3560 and #3281

**Comment by jeremymasters** [comment] 2015-09-24 02:05
Wouldn't those be dupes of this one then if they are the same and this came first? Not that it really matters. I'm being pedantic.

**Comment by FeuRenard** [comment] 2016-04-14 23:01
1. is duplicate of #2397
2. is outdated as color and security level don't correlate anymore.
3. is outdated as the title text appearance now matches between themes
4. is outdated as checkboxes and switches in the settings are now blue (dark or light depending on theme)
5. is outdated as there are only two symbols left now in the top bar of the a conversation.

This issue should be closed.

**Comment by agrajaghh** [comment] 2016-04-14 23:13
ty @FeuRenard

**Closed by agrajaghh** 2016-04-14 23:13 UTC
Labels: ux
