### ISSUE TITLE
Deletion of contact keys

### ISSUE THREAD

**Issue by Waboru** [WhisperSystems/Signal-Android#1133] opened 2014-03-12 15:52 UTC
Hello moxie,

could you please let us delete the contact keys?

Several of my friends changed their number or uninstalled TextSecure, I'm not liking to scroll threw their contact keys whenever I check them.
Let us long press them for deleting, add a warning and everything would be fine.

**Comment by 2-4601** [comment] 2015-12-19 01:54
Closing as duplicate of #682 (plus obsolete features)

**Closed by 2-4601** 2015-12-19 01:54 UTC
Labels: defer, feature
