### ISSUE TITLE
SMS counter

### ISSUE THREAD

**Issue by beatstick** [WhisperSystems/Signal-Android#5255] opened 2016-02-17 23:07 UTC
I am using signal on Android as sms app. As the database for the sms gets encrypted I can't seem to find a way to count my monthly used sms. Would it be possible to implement an sms counter into signal or somehow let another app to count the number of outgoing sms? This would be helpful for users with a monthly amount of prepaid sms.

**Comment by moxie0** [comment] 2016-02-17 23:28
Duplicate of #442, please check existing issues before opening new ones.

**Closed by moxie0** 2016-02-17 23:28 UTC
