### ISSUE TITLE
[Feature Request] Custom In Chat Background Theme / Image 

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#7245] opened 2017-12-04 13:12 UTC
Can you please give users the option to set an image or theme for the background of a chat, that everyone in the chat can see.
Thanks

**Comment by p4nci** [comment] 2017-12-04 14:35
duplicate of https://github.com/WhisperSystems/Signal-Android/issues/809

**Closed** 2017-12-04 19:32 UTC
