### ISSUE TITLE
images being compressed beyoned being usable

### ISSUE THREAD

**Issue by NeoFromMatrix** [WhisperSystems/Signal-Android#6262] opened 2017-02-20 22:07 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Image compression is so high that images become unusable. 

### Steps to reproduce
- send an image, taken with the standard camera from one device to another, no other steps involved

**Actual result:** Image is compressed from 3264x2448px, 1.5MB to 408x306 px, 36.4KB. Image is not even close to being usable (in this case it is a foto of an time schedule). There is no option available to send the image in a way where it can be used on the recipient side. 
Seems to be related to #672 (didn't read though it as it is closed and I would expect that to mean resolved)
**Expected result:** Images are received only with mild compression, not affecting the image visibly. 

**Suggestion:** Lower the compression rate and allow for the option to send uncompressed images (either via the image send dialogue or introduce an option to send all file types. Last would be fulfilled by #993, which is unfortunately locked for comment. Also I don't like to idea of my data being modified without the possibility to change this. 

**Note:** I did not add any further information as I expect this to be device independent. Further information can be provided if needed.

**Comment by 2-4601** [comment] 2017-02-20 22:43
depends on the memory class of the device, duplicate of #672

**Closed by 2-4601** 2017-02-20 22:43 UTC
