### ISSUE TITLE
Plaintexts backup and group chats

### ISSUE THREAD

**Issue by cgogolin** [WhisperSystems/Signal-Android#6536] opened 2017-04-17 10:25 UTC
I have seen various groups chat bugs here, but this one I couldn't find so far:

After exporting all messages and then importing them on a new device, messages from group charts appear under the account who sent them instead of in the group.

Without the context of the conversation many such messages however are completely useless and, worse, even mess up the chats with the individual contracts.

Is there some way to preserve group chats when moving device? If not this seems to be a serious bug that drastically limits the usefulness of group chats.

**Comment by johanw666** [comment] 2017-04-17 12:31
Yes, use a root backup tool like Titanium or mess with adb (downgrade first to 2.28 to allow adb backups to be made).

**Comment by cgogolin** [comment] 2017-04-18 09:03
Thanks. Out of curiosity: Would it be difficult to implement a simple "move to another device" function that would simply dump the whole internal Signal database including private keys, chats, images, and so on to a file that could be imported by another instance of Signal (at least if they have the same version)? I am really trying hard to convince all my friends to mode to Signal, but things like the bug reported above make this very difficult, unfortunately.

**Comment by johanw666** [comment] 2017-04-18 10:07
@cgogolin : that would be dead easy, sush functionality was already implemented but was removed due to unspecified issues.

**Comment by cgogolin** [comment] 2017-04-18 10:31
I don't mean to complain (you are all doing a great job with Signal!), but for a Signal user it looks like a strange development decision to lock all people without extensive technical skills (root, adb, ...) into there devices or break their group chats because of "unspecified issues".

**Comment by 2-4601** [comment] 2017-04-29 16:06
Duplicate of #3024

**Closed by 2-4601** 2017-04-29 16:06 UTC
