### ISSUE TITLE
Low sound in call ( Signal 3.5.2+)

### ISSUE THREAD

**Issue by jocelynthode** [WhisperSystems/Signal-Android#4733] opened 2015-11-27 09:36 UTC
Hey,

I still have the problem of the closed issue #4244. The workaround of enabling/disabling speakers still does the trick.

Device info: Samsung I9300 , CM Lolipop 5.1.1, Signal 3.5.2

Debug log : https://gist.github.com/anonymous/b09ff201c845cddd5da1

In the log, I phoned a friend, confirmed that I could barely hear him, then did the workaround. Then I confirmed I could hear him well and stopped the call.

**Comment by mcginty** [comment] 2015-11-28 00:09
tentatively fixed by https://github.com/WhisperSystems/Signal-Android/pull/4737

**Comment by 2-4601** [comment] 2015-11-28 04:35
Do you still experience this in 3.6.0?

**Comment by peterpanondrugs** [comment] 2015-11-28 14:12
i do. https://gist.github.com/7baf7dd095bb9076650a
Same is for just the "ringing"
If it starts ringing (#1) then use the speaker on -> off trick, afterwards ringing volume (#2) is louder then #1.

**Comment by jocelynthode** [comment] 2015-11-28 18:53
I can't tell you yet if the problem is fixed in 3.6.0 as this version isn't yet available for me on the play store.

**Comment by AlfonsoMuskedunder** [comment] 2015-11-30 11:31
@2-4601 I do, too.
In case a log provides useful information: https://gist.github.com/616e3dab2632d1b5c8da
(I just made a call where this happened - including the workaround - on a Moto G, Android 5.1, Signal 3.6.0; other end on a Samsung SIII Mini, Android 4.1.2, Signal 3.6.0.)

**Comment by 7adietri** [comment] 2015-12-04 13:46
Also encountering this on a Fairphone 1 (Android 4.2.2, Signal 3.6.1). The speaker workaround fixes this for me too.

**Comment by jocelynthode** [comment] 2015-12-06 15:52
Problem still present for me on Signal 3.6.1

@moxie0  any idea why ?

**Comment by 2-4601** [comment] 2015-12-14 23:25
Everyone experiencing this please test pr #4885.

**Comment by jocelynthode** [comment] 2015-12-16 09:22
@2-4601 Sorry I don't have an environment to test with a dev build.

**Comment by 2-4601** [comment] 2015-12-24 18:06
0caad7f348ae51fb4fec36ebc934065302c7303e should fix this

**Closed by 2-4601** 2015-12-24 18:06 UTC
Labels: redphone

**Comment by cascheberg** [comment] 2015-12-28 14:16
Please check if the issue is fixed in 3.9.0 if you can. It is available on the Google Play Store as a beta release.

**Comment by AlfonsoMuskedunder** [comment] 2015-12-29 18:31
@cascheberg My tentative answer is yes, it seems fixed. I've just placed a successful call to the same contact I mentioned above; the volume was normal; and adjusting it worked. (I have found issues regarding calls hard to reproduce sometimes in the past, however...) Thanks for the great work!

**Comment by drizzd** [comment] 2015-12-31 22:53
I am in the test program, I installed 3.8.1 a week ago, which still had the issue. It says up to date. Do I have to uninstall and re-register to upgrade? I do not have my SIM card on hand.

Compiling from source does not help either. I get an error during install, probably because Signal is already installed.

Is there any way to upgrade from 3.8.1 to 3.9.0 without having to re-register?

**Comment by x12x** [comment] 2016-01-04 20:59
I still think the audio is too low even in 3.9.0.

**Comment by infinite-Joy** [comment] 2016-01-05 02:50
I think in my case the volume button doesn't seem to work.

**Comment by drizzd** [comment] 2016-01-05 17:41
How about setting up an automatic answering service as provided by Skype to help test issues with sound volume? I think this would make debugging easier.

**Comment by jocelynthode** [comment] 2016-01-08 21:42
Everything fixed for me ! Thanks guys !
