### ISSUE TITLE
Signal uses half a gigabyte of storage for seemingly no reason

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6774] opened 2017-06-28 13:56 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal uses over half a gigabyte of "data" for seemingly no reason. See the picture.

### Steps to reproduce
Honestly I wish I knew. I've had my phone for about 7 months now (Since last Christmas) and I've been using the same install of Signal all this time. This morning I look at Signal's storage usage and I discover it's using waaaaaaay more than it should.

I have the SD timer set to 12 hours on 2 chats and 24 hours on 1 chat.
**I've tried deleting my 3 chats to see if that would help. It didn't.**

**Actual result:** It seems Signal isn't properly deleting attachments or something.
**Expected result:** Signal shouldn't use half a gigabyte of my phone's memory unless I got half a gigabyte of attachments in my conversations. I don't.

### Screenshots
![screenshot_20170628-154942](https://user-images.githubusercontent.com/12563436/27640592-03685ab2-5c1a-11e7-9144-39bebc034378.png)

### Device info
Device  : motorola Moto G (4) (athene)
Android : 7.0 (4, NPJS25.93-14-4)
Memory  : 34M (15.22% free, 384M max)
Memclass: 192
OS Host : ilclbld31
App     : Signal 4.7.4

### Link to debug log
https://gist.github.com/anonymous/e897db97fadd015e7e207306b7835b82

**Comment by cascheberg** [comment] 2017-06-28 15:12
Duplicate of #5515. There is some recent activity there from people trying to provide more info.

**Closed** 2017-06-28 17:11 UTC

**Comment by domenukk** [comment] 2019-08-24 14:58
The original bug has since been closed automatically, is there any way to reopen this one instead?
I'm at over 4 GB even though I cut messages at 500  entries per thread...
