### ISSUE TITLE
Signal-Android for tablets

### ISSUE THREAD

**Issue by oliof** [WhisperSystems/Signal-Android#5159] opened 2016-01-31 08:17 UTC
I cannot use Signal-Android on tablets, I.e.the Pixel C. Assume that this is because of lack of cellular/SMS capabilities, but with the introduction of the desktop client it seems there is a way to do multi device setups supporting devices without a cellular modem/SMS capabilities.

**Comment by moxie0** [comment] 2016-01-31 09:24
Duplicate of #614. Please check existing issues before opening new ones.

**Closed by moxie0** 2016-01-31 09:24 UTC

**Comment by oliof** [comment] 2016-01-31 12:05
I did but failed to see that one -- will try to do better next time.

Moxie Marlinspike <notifications@github.com> schrieb am So., 31. Jan. 2016,
10:24:

> Duplicate of #614
> <https://github.com/WhisperSystems/Signal-Android/issues/614>. Please
> check existing issues before opening new ones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/5159#issuecomment-177447350>
> .
>
-- 
-- 
Harald Wagener
wagener@gmail.com
https://profiles.google.com/+HaraldWagener
