### ISSUE TITLE
Sending an SMS to short code like 18100 changes it to +${COUNTRY_CODE}18100

### ISSUE THREAD

**Issue by bleadof** [WhisperSystems/Signal-Android#4853] opened 2015-12-10 11:15 UTC
I was trying to send an SMS to the number **18100** and it got changed to **+35818100** and the SMS didn't reach the correct number.

Some of these [SMS short codes](https://en.wikipedia.org/wiki/Short_code) and service numbers are national or even per network, so adding country code to it changes the number. For someone who relies heavily on service numbers this might the biggest reason not to use Signal as main messaging app.

Here's the only quote I found on the topic declaring them national...
> Short codes only work within one country, they are not international.
>- [Premium rated short messages, Short Message Service, Wikipedia](https://en.wikipedia.org/wiki/Short_message_service#Premium-rated_short_messages)

**Comment by moxie0** [comment] 2015-12-10 11:36
looks like libphonenumber has incorrect data for finland, will be fixed in 3.8.0

**Closed by moxie0** 2015-12-10 11:36 UTC

**Comment by bleadof** [comment] 2015-12-10 11:43
:tada: Awesome response time! :+1: :bow:

**Comment by krasron** [comment] 2016-02-24 21:31
I was told to submit my debug log here as I have a similar issue. I get +38650001 when I want to send an SMS to 50001. I don't live in Slovenia though, I live in Kosovo where we don't have a country code assigned yet. My provider is uses the Slovenian prefix for its numbers. Here's the log: https://gist.github.com/anonymous/88ae7acfc839e8b48818

**Comment by Kadazo** [comment] 2016-03-23 00:58
I'm facing the same SMS short code's problem in Malaysia. I was intended to send SMS to 28882 but with the latest Signal v3.14.2 it still keeps adding the country code +60 in front of the short code automatically and it becomes +6028882. I've attached the log here: 
https://gist.github.com/anonymous/ecc382e5c493ed8b29ea

Thank you!

**Comment by flansch** [comment] 2016-08-20 09:04
Why has this issue been closed? I'm running Signal 3.16.1 and facing the exact same problem. When I'm creating a new message to the service number 31312 of my network operator "3" Austria, it is automatically changed to +4331312 and, after sending, the message is not recognized by "3".

**Comment by manwithnoname** [comment] 2016-10-16 20:30
Same thing happens with me in Portugal.

Signal adds the +351 to the short (network) number and the sms fails. Sending through the system messenger works perfectly.

**Comment by blackyellowred** [comment] 2016-12-14 17:45
I have same issue where signal would add +1 to the number. Please fix it.

**Comment by riyapenn** [comment] 2016-12-14 17:50
On some phones there is a setting to enable sending messages to Short codes or short numbers.
You will need to allow sending "Premium SMS".
Go to Settings > Apps > Signal > scroll to the permissions section > tap on the down arrow for the section "Send premium SMS" and choose 'Ask' or 'Always allow'

**Comment by blackyellowred** [comment] 2016-12-15 03:37
I don't see the setting riyapenn is referring to. I am on 6.0.0.

**Comment by simoncpu** [comment] 2017-04-03 08:26
I'm having the same issue. There's no "send premium setting".

**Comment by skryzhny** [comment] 2017-05-10 11:12
Same issue for me, can't use short numbers in Ukraine.

**Comment by pwlbc** [comment] 2017-09-29 20:35
I am not able to send a SMS to 19872 in Poland.
Signal automatically changes the number to +4819872 which result in failure to send SMS.
The number has to be 19872 without country code.
Please fix this.

**Comment by moxie0** [comment] 2017-10-02 17:50
@pwlbc Please do not post the same thing over and over again to multiple issues. It only means I have less time to fix things like this.

**Comment by pwlbc** [comment] 2017-10-02 19:19
Ok, sorry.

**Comment by drphr4ud** [comment] 2017-11-12 06:41
I have the same issue on all my devices and I do not see a duplicate bug on this issue, yet it has been marked as closed. What gives ?

**Comment by atenrok** [comment] 2017-11-28 01:15
today is Nov 27, 2017. Every time when I need to reply a text from my bank I deactivate signal and switch to a default texting app in order send a one word text to a short number. Why the hell is this bug closed???

**Comment by atenrok** [comment] 2018-02-17 03:47
Still the same issue. 5-digit number in US. Never sends a text

**Comment by Lundeful** [comment] 2019-02-26 18:52
It's February 2019 and it still isn't fixed

**Comment by bleadof** [comment] 2019-02-27 09:58
I'm going to say something that is obvious, but something that is easy to forget. We're not paying for this service. This is open source. Respectful conduct in comments usually gets more similar kind of feedback. I'm sad that I'm too busy that I can't actually fix it myself.

**Comment by Lundeful** [comment] 2019-02-27 10:11
Yes, you are right. I did not mean to sound rude or demanding. It was more to inform people coming here searching for answers that it is still an issue.

**Comment by ravinperumal** [comment] 2019-05-12 03:20
On version 4.39.4 and still having the same issue.
Malaysian phone number global roaming in Australia.
All my local Australian numbers get automatically prefixed with a +61(Australian country code) although they are stored in Google Contacts without the country code when I try and chat using Signal to Australian numbers. No matter how I save my numbers in my Contact list they all get automatically pre fixed with the +61 in Signal. 
From my local Australian number/sim(different physical phone) the same number(stored on both phones) does not get automatically pre-fixed. So it is only happening on my phone that is roaming. Both using the same version of Signal.

**Comment by abdulrehmanis** [comment] 2019-06-19 05:19
Thanks. We have also same problem about [shortcode sms](https://its.com.pk/shortcode-services/)

**Comment by NeoFromMatrix** [comment] 2019-12-29 21:55
I'm currently on the 36C3 congress, they set up a own phone network where anyone can get sim cards and register a 4-5 digit number (as long as it's unique in the system)

This issue makes communication hard here. No matter if a contact is added or the phone number is typed, Signal adds a country code in front.

Receiving SMS works properly, the correct number is displayed.

**Comment by NeoFromMatrix** [comment] 2019-12-29 21:59
I don't understand why this issue is closed, the problem is not resolved.

**Comment by bluelayer** [comment] 2020-04-07 03:36
hey guys any solution to this? I can't send sms to "12345"
