### ISSUE TITLE
Groupmessage delivery failed false postive

### ISSUE THREAD

**Issue by m0jo** [WhisperSystems/Signal-Android#4909] opened 2015-12-17 15:14 UTC
Whenever i send a groupmessage in this specific group, i receive a failed deilvery notification although the message is successfully delivered to all contacts.

![screenshot_2015-12-17-16-02-31](https://cloud.githubusercontent.com/assets/322587/11873072/05af4820-a4d9-11e5-97c7-7a0cfc1f69fe.png)
![screenshot_2015-12-17-16-02-38](https://cloud.githubusercontent.com/assets/322587/11873071/05a8b884-a4d9-11e5-8ad0-9f2c1591e2d9.png)

Log:
https://gist.github.com/anonymous/568c9b3aca9d68a045c6

**Comment by 2-4601** [comment] 2015-12-17 15:36
Has someone in the group unregistered from Signal?
```
W/TextSecureMessageSender( 8300): org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:289)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:386)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:368)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:300)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:275)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:153)
W/TextSecureMessageSender( 8300): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:151)
W/TextSecureMessageSender( 8300): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:82)
W/TextSecureMessageSender( 8300): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
W/TextSecureMessageSender( 8300): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/TextSecureMessageSender( 8300): Caused by: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:513)
W/TextSecureMessageSender( 8300): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:260)
W/TextSecureMessageSender( 8300): 	... 11 more
W/PushGroupSendJob( 8300): org.whispersystems.textsecure.api.push.exceptions.EncapsulatedExceptions
W/PushGroupSendJob( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:289)
W/PushGroupSendJob( 8300): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:153)
W/PushGroupSendJob( 8300): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:151)
W/PushGroupSendJob( 8300): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:82)
W/PushGroupSendJob( 8300): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
W/PushGroupSendJob( 8300): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushGroupSendJob( 8300): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/PushGroupSendJob( 8300): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Possibly duplicate of #2408

**Comment by peterpanondrugs** [comment] 2015-12-29 23:10
How do you know that all recepients got your message? Did you ask them? Are you 100% sure?
I had the same issue, but problem was 1 (ios) contact. After he disconnected his number from the account, all was went better. 
I had severe problems with crashing signal while sending (single or group message with that person)

**Comment by m0jo** [comment] 2016-01-17 22:45
All remaining groupmembers received the message, yes i asked them. Their are no IOS users in that group. However, seems like someone unregistered and reregistered.
Possible duplicate of https://github.com/WhisperSystems/Signal-Android/issues/4550

**Comment by 2-4601** [comment] 2016-01-17 22:56
Thanks for reporting back @m0jo, closing as duplicate :)

**Closed by 2-4601** 2016-01-17 22:56 UTC
Labels: pending information
