### ISSUE TITLE
Manual SMS validation

### ISSUE THREAD

**Issue by alexandrujuncu** [WhisperSystems/Signal-Android#4956] opened 2015-12-24 09:50 UTC
Hi!

I tried to validate my Google Voice number, which I know you have as a known issue as not working.
But my issue is why you don't allow manual validation. I to receive the SMS over Google Voice and it's just not caught by the app.
The next step is to be called and manually enter what I hear in a text box.
My question is: why don't you allow the validation text box to be used for SMS too.

It's great that you have the automatic SMS validation (it's user friendly) but after the timeout, you could just leave the option to have the SMS code manually entered. It would offer more flexibility and I don't see what would be the downside (if I am wrong, do tell).

Thanks!

**Comment by 2-4601** [comment] 2015-12-24 10:12
Closing as duplicate of #2410. (Also see https://github.com/WhisperSystems/Signal-Android/issues/4354#issuecomment-153441706)

**Closed by 2-4601** 2015-12-24 10:12 UTC

**Comment by alexandrujuncu** [comment] 2015-12-24 14:43
@moxie0 Hi! You closed #2410 and chat is disabled so I am posting here.
I am really curious regarding why you don't want to do this. Is there some technical or security reason?

Thank you!

**Comment by nrizzio** [comment] 2015-12-24 15:11
https://github.com/WhisperSystems/Signal-Android/issues/4354#issuecomment-153441706

> If you're using GV, there's no way for Signal to "see" the incoming SMS and process the verification code, so you have to use the voice verification feature. I understand this is not ideal since you have to wait, but it's also not the common case we're optimizing for.

**Comment by alexandrujuncu** [comment] 2015-12-24 15:15
But that is NOT what I was proposing. I understand that part and it's ok.
I was just saying to do the same thing you do for voice: let people manually input it into a text field.
The text message gets sent just like the voice call is made and you input what you see/hear.

Thanks!

**Comment by danopia** [comment] 2016-04-06 07:48
It's really silly that I get my code perfectly fine but have to sit there waiting for Signal to give up on auto detecting the code, and resort to a phone call. If you can accept a manual code from a phone call, it would make sense to accept one before that, too.

I managed to search for, pull up this issue, and read the rejection before I was able to hit "Call me".
