### ISSUE TITLE
Signal closes when switching app

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#4938] opened 2015-12-21 02:52 UTC
Whenever I enter the app switcher, Signal closes or disappears. (I think this is since the last update).

Device info: Nexus 5, omnirom 5.1.1, Signal 3.7.2

App state: Push registered, SMS & MMS disabled, Privacy & Sreen security off

![anim](https://cloud.githubusercontent.com/assets/5571650/11922345/77eed558-a796-11e5-8662-5ad7492ed68e.gif)

Debug logs if useful...: https://gist.github.com/anonymous/7baf067990821b372af1

**Comment by 2-4601** [comment] 2015-12-21 20:00
This seems to be a dupe of #3038.

**Closed by 2-4601** 2015-12-21 20:00 UTC

**Comment by sedrubal** [comment] 2015-12-21 20:08
Thanks, yes it is exactly the same and rebooting fixed it, too... - strange...
