### ISSUE TITLE
[Feature Request] Automatic backups/exports (as an option)

### ISSUE THREAD

**Issue by BloodyIron** [WhisperSystems/Signal-Android#5718] opened 2016-09-25 17:32 UTC
I want to see Signal to have a setting where it can automatically create a backup on the phone of it's messages (SMS/MMS/etc) and the key set, in a bundle that I can backup to my servers (for example, to ownCloud).

There's already a way to export to clear text, but this doesn't backup the keys. And, this is manual.

I need this, otherwise wiping my device, or switching to a new one, is going to be painful. Or, to put it another way, if my phone is lost, so is all my messaging. Who isn't an advocate for backups?

Please?

**Comment by sweeper3000** [comment] 2016-09-25 19:10
Looks to be a dupe of  #1529, #339

**Comment by BloodyIron** [comment] 2016-09-25 19:23
#1529 is closed, so irrelevant

#339 hasn't been touched **for over a year**, so how about we get some traction here?

Backups are important (even if not for everyone).

**Comment by sweeper3000** [comment] 2016-09-25 19:32
I think the devs don't want duplicate issues, even if closed. There are many little features that never really gain any traction if you dig into the issues going back a few years. I can't blame Moxie, because he's been running the Android repo all by himself and he's only one guy.

**Comment by 2-4601** [comment] 2016-09-25 19:43
So many issues, so little time.
If this is a feature you really want, best way to get things moving is to contribute to the project yourself.

**Closed by 2-4601** 2016-09-25 19:43 UTC

**Comment by BloodyIron** [comment] 2016-09-26 01:22
lol, I see how seriously (as in not) this project takes backups... what a joke. I know that there are limited human resources here, but I'm demonstrating demand for this feature, and you're just shutting down my request by closing the ticket. What a horrible response.

**Comment by 2-4601** [comment] 2016-09-26 01:43
> Why exactly have the ability for users to submit feature requests if they're just gonna get closed?

Opening duplicate feature requests does not help resolving issues.
If you have something relevant to add to the issue, you can do so at the original issue.
