### ISSUE TITLE
Reproducible crash when entering conversation.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-Android#6661] opened 2017-05-19 14:49 UTC
I've got a very reproducible crash when navigating to conversation view for a certain conversation.

Latest Android beta.  I updated, still repros.

I've attached video demonstrating the crash...

Here's the debug logs that include the two crashes in that video.

https://gist.github.com/anonymous/968acde47c5b90403e8b0ebe15c2e890

Video: https://cl.ly/042n3H2m1N45

**Comment by haffenloher** [comment] 2017-05-19 15:48
Duplicate of #6660?
not sure if that matters, but in both reports, the crashes occured when entering a group conversation.

**Closed** 2017-05-31 21:52 UTC
Labels: bug, crash
