### ISSUE TITLE
Send Message to a Service Number

### ISSUE THREAD

**Issue by bgpink** [WhisperSystems/Signal-Android#4537] opened 2015-11-14 20:10 UTC
I try to send a message to a German service number 44644. But signal puts automatically the German area code before the service number (+4944644). Therefore I always get a send error. How can I turn that automatism off?

**Comment by moxie0** [comment] 2015-11-14 20:28
duplicate of #4478, please check existing issues before opening new ones

**Closed by moxie0** 2015-11-14 20:28 UTC
