### ISSUE TITLE
distinguish unread messages

### ISSUE THREAD

**Issue by an64** [WhisperSystems/Signal-Android#5163] opened 2016-01-31 20:04 UTC
Sometimes it hard to finda place , where i stop read conversation last time, especially in group chat
It will be nice to show some border (some thin line or so) under the last readed message

**Comment by agrajaghh** [comment] 2016-01-31 20:28
duplicate of #1211 ?

**Comment by x12x** [comment] 2016-01-31 20:33
No, I think it's a duplicate of #965

**Comment by agrajaghh** [comment] 2016-01-31 20:34
@x12x true :blush:

**Closed by agrajaghh** 2016-01-31 20:34 UTC

**Comment by an64** [comment] 2016-02-02 02:29
Yes, this is duplicate, sorry!
