### ISSUE TITLE
Signal crashes after entering password when sharing from Google Photos

### ISSUE THREAD

**Issue by RichJeanes** [WhisperSystems/Signal-Android#5726] opened 2016-09-28 17:37 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This seems to be related to #3989, #4374, #4339, which is marked as fixed in 3.3.0.
I think what is different in this case is that Signal only crashes if the app is locked when I share to it, not when it is unlocked.

### Steps to reproduce
- Make sure Signal is locked with a passphrase
- Share an image from Google Photos to Signal
- Enter Signal Password

**Actual result:** Signal crashes
**Expected result:** Presented with recipient list to send image to

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.0
**Signal version:** Tested on 3.18.3 and 3.19.1 (Built from source)

### Link to debug log
**(3.18.3)** https://gist.github.com/99b00f670f72768e438cb01a21307b39
**(3.19.1)** https://gist.github.com/1714e592a4cad1d08fe7f0d68c16e49a

**Comment by 2-4601** [comment] 2016-09-29 13:49
Closing as duplicate of #3990.

**Closed by 2-4601** 2016-09-29 13:49 UTC

**Comment by RichJeanes** [comment] 2016-09-29 15:31
Sorry. Didn't come across that one when I was searching issues.
