### ISSUE TITLE
Group chats are broken after switching to a new phone.

### ISSUE THREAD

**Issue by DooMMasteR** [WhisperSystems/Signal-Android#5636] opened 2016-08-25 06:26 UTC
I have:
- [x] searched open and closed issues for duplicates, which is getting more and more complicated, due to all the open issues.
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I was member of a Group when I switched phones and wiped the old one.
Upon registering on the new phone the Group did not appear.
When someone wrote tot he group again it appeared as Unnamed group, which I cannot rename, and in the group details view has a cryptic name.
I can not write messages to the group from my phone (the text input area seems locked).
I can however send messages to it from a linked web client, which works just fine and all members receive the messages I sent.
I can however not remove myself from this group, nor can anybody else remove me.
This behavior is utterly broken.
### Steps to reproduce

Be member of a group, switch to new phone, receive message from group.
### Device info

**Device:** Oneplus 3 and Oneplus One
**Android version:** 6.0.1
**Signal version:** 3.17.0

**Comment by FeuRenard** [comment] 2016-08-25 08:06
Sounds like a duplicate of #1048

**Comment by McLoo** [comment] 2016-08-26 05:26
Yep. Dupe of #1048 and #1029 
The latter should have the [solution](https://github.com/WhisperSystems/Signal-Android/issues/1029#issuecomment-36721702) for you:
"Updating the group (setting a new title)" or avatar

**Comment by DooMMasteR** [comment] 2016-08-26 06:53
not really, at least not if editiong should work.
I cannot edit the group name or anything at all, but whenever someone just edits the group they endup in the same loop as I did, even without switching phones.

**Comment by McLoo** [comment] 2016-08-26 07:32
This worked perfectly fine in all my cases

**Comment by DooMMasteR** [comment] 2016-08-26 07:35
It did not in my case :-1: and now others are affected too.
The issue exists since 2014 and has not been fixed yet.... and in this case seems to have gotten worse.

What is even the reason for the Android client denying to send messages to the group when the webclient, that uses the phone as middleman, has no problems at all.

**Comment by brinerustle** [comment] 2016-08-26 11:36
Perhaps we can set up a signal group for testing purposes, if there isn't one already.

If there's interest, i'd be willing to publish my phone number here on github and start the group for whoever wants to do testing.

**Comment by Norbert80** [comment] 2016-09-03 10:24
I can confirm that these bugs (unnamed groups) are still occurring today.

**Comment by AlfonsoMuskedunder** [comment] 2016-09-06 12:52
@McLoo Maybe @DooMMasteR's group got broken because the update procedure itself failed? See https://github.com/WhisperSystems/Signal-Android/issues/4974.

**Comment by 2-4601** [comment] 2016-12-01 20:54
Fix in 3.24.0 (cf01959e16acc1ff31cd007d68b3ba43810b6c3a)

**Closed by 2-4601** 2016-12-01 20:54 UTC

**Comment by andrejpodzimek** [comment] 2017-07-05 00:34
This is still happening. Group chats are completely broken after switching to a new phone. (Happened today.) Names of the group chats got changed into generic *unnamed* ones on the phone. Chat names stay consistent on computers though. The problem is also that there is no way to delete a group chat, neither from the mobile app, nor from the Chrome extension.

**Comment by ktpx** [comment] 2019-02-19 20:28
Still happening...
