### ISSUE TITLE
MMS picture messages go to a "group" with just me and the sender

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-Android#6951] opened 2017-09-10 20:17 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### STR

- Have a friend who isn't on Signal send you an image over MMS
- Notice how instead of the image being displayed inline in the conversation, a new "group" is created whose members are only you and your friend

### Device info

**Device:** Nexus 6P
**Android version:** CyanogenMod 13.0-20161220-SNAPSHOT-ZNH5YAO3XH-angler based on Android 6.0.1
**Signal version:** 4.10.6

### Link to debug log

https://gist.github.com/anonymous/83ea2b92456d43163cc6749f75e7b5fc

(Might be some unrelated chatter since I was receiving some Signal group messages at the same time as my friend was helping me reproduce this - sorry!)

**Comment by nrizzio** [comment] 2017-09-10 20:18
Duplicate of #6947?

**Closed** 2017-09-10 20:25 UTC

**Comment by crepehat** [comment] 2019-09-27 17:37
This issue still exists, it's happened on every phone i've installed signal on. I get a separate thread with 'me', my number as a separate contact, and the sender of the sms.

**Comment by strugee** [comment] 2019-09-28 17:45
@crepehat please search for duplicates and if you can't find any _open_ issues, create a new one. Make sure to include your carrier and the other person's carrier, as well as a debug log. Thanks!
