### ISSUE TITLE
[Feature] Responsive theme according to daylight and wallpapers

### ISSUE THREAD

**Issue by gabrielfranco89** [WhisperSystems/Signal-Android#6626] opened 2017-05-10 21:30 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
Hello!

It would be nice if we have a custom wallpaper feature in Signal App, like WhatsApp.

Also, the dark and light theme could have an option to be responsive to daylight. Light theme during daylight and dark theme during night.

**Comment by 2-4601** [comment] 2017-05-23 11:03
Daylight responsivity is a duplicate of #751

Let's track custom wallpaper feature with the custom theme issue #1283

**Closed by 2-4601** 2017-05-23 11:03 UTC
