### ISSUE TITLE
Feature Request: Multi-Device support

### ISSUE THREAD

**Issue by pigsflew** [WhisperSystems/Signal-Android#6442] opened 2017-03-25 17:31 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Related closed issue: https://github.com/WhisperSystems/Signal-Android/issues/5102 which I feel the point of which was missed for the user's misunderstanding of the implementation.

### Bug description
I cannot have two android devices or two mobile phones logged in to the same identity at the same time.

### Steps to reproduce
- Open up the app
- Attempt to identify yourself without a SIM present.

**Actual result:** No options to use this app
**Expected result:** Identify via *((mms)), ((email)) ((SIP/VOIP Provider)) ((Google Voice)) ((OAuth Provider)) ((scan QR code from existing device))*. You should also be able to link identities accross different ID providers (multiple phone numbers + email address, for example) once signed in by using a device scan.

### Device info
**Device:** ZTE Axon Mini 7 / Affects all Android + iOS
**Android version:** 6.0.1 / Affects all supported versions
**Signal version:** 4.0.0

**Comment by Trolldemorted** [comment] 2017-03-25 19:25
I am semi-actively working on this, if you want to test it, compile and deploy [this ](https://github.com/Trolldemorted/Signal-Android/commits/multidevice)on your slave device and click "cancel" when it promts you to enter a phone number.

**Comment by Cormak** [comment] 2017-03-26 00:07
Everybody who is interested in multi-device support should also be looking at the XMPP extension OMEMO for inspiration as that secure protocol seems to be derived from the double ratchet (Signal) protocol and has multi-device support. 

https://github.com/omemo
https://en.wikipedia.org/wiki/OMEMO

**Comment by moxie0** [comment] 2017-03-26 16:53
Closing as duplicate of #5102

**Closed by moxie0** 2017-03-26 16:53 UTC
