### ISSUE TITLE
end secure session + transport options = confusing

### ISSUE THREAD

**Issue by arafey** [WhisperSystems/Signal-Android#3639] opened 2015-07-12 20:41 UTC
When in a secure session with SMS/MMS support enabled, the End secure session button doesn't work to end the session. This may be by design, I'm not sure, but it doesn't work well if I'm sending a regular message to a contact who uses a separate app for regular texts (but who is also registered for TextSecure)  and doesn't want to sign in to read any message I send them. If both parties are solely using TextSecure then it doesn't matter, but it should probably be up to the user to decide on the communication protocol.

**Comment by jeremymasters** [comment] 2015-07-12 22:49
Long-press the send icon to choose protocol. Then end session button is a little more complicated.

**Comment by rhodey** [comment] 2015-07-13 23:49
our issues tracker is riddled with closed issues caused by confusion with 'end secure session', I couldn't find any currently open though. I think this should be labeled a UX thing or closed and open a new issue specifically.

**Comment by JasonLocklin** [comment] 2015-09-27 15:04
If I understand correctly, the "end secure session" triggers a re-negotiation of the encrypted session and is intended to be used if there is a problem with messages not being exchanged properly? 

If so, simply re-naming it to "~~end~~ **reset** secure session" may make it far less confusing, as the notion to "reset" a technology when it is mis-behaving is more intuitive to less technical people.

**Comment by dcherian** [comment] 2015-11-19 03:49
Can be closed

**Comment by 2-4601** [comment] 2015-12-19 02:23
:+1: 
Closing because "end secure session" has been changed to "reset secure session" which fixed this.

**Closed by 2-4601** 2015-12-19 02:23 UTC
Labels: ux
