### ISSUE TITLE
Feature: Mention users in group chat

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#5707] opened 2016-09-20 20:18 UTC
### Feature description
After typing `@` in the compose text box in a group chat, a popup should pop up and list group members. When selecting one of them or when you type one name he should be highlighted as link. After sending the message you should be able to open the chat whit this user. The mentioned user should become a special notification like `xy has mentioned you in chat $chat name`.

### Screenshots

![mention](https://cloud.githubusercontent.com/assets/5571650/18687361/07838620-7f80-11e6-95a3-db24481a6824.png)

**Comment by FeuRenard** [comment] 2016-09-21 08:55
This is a duplicate of #5401.

**Closed** 2016-09-21 09:18 UTC
