### ISSUE TITLE
Call drops after no more than 3 minutes of conversation

### ISSUE THREAD

**Issue by benefaktorix** [WhisperSystems/Signal-Android#5836] opened 2016-11-03 19:37 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
Every time I call someone, the call drops after 2-3 minutes, i am not aware if this a new update issue, yet it wasn't an issue a some time before (2-3 weeks).

### Steps to reproduce
- Call using signal 3.21.3 build
- Have a conversation for 2-3 minutes
- Call unexpectedly drops

**Actual result:** call drops
**Expected result:** call doesn't drop until I press End Call button (big red)

**Device**: Blackberry STV100-4 (veniceemea)
**Android version:** 6.0.1 (AAG853)
**Signal version:** 3.21.3

### Link to debug log
https://gist.github.com/anonymous/a669e2323b79af2885956248f96f720e

**Comment by knusprjg** [comment] 2016-11-05 21:05
Same issue here. Calls are constantly dropped for some days now, maybe an issue with the latest Signal update?

Device: Motorola X Play
Android version: 6.0.1
Signal version: 3.21.3

**Comment by catcattencattis** [comment] 2016-11-06 19:27
I have also this problem before and after the update. Is there still no fix for this??

**Device:** Samsung S5 Mini (SM-G800F)
**Android Version:** 5.1.1 
**Signal version:** 3.21.3

And it also use to do this with the older version of signal: 3.20.4

**Comment by JasMan78** [comment] 2016-11-08 20:22
Same issue with...

**Device:** Moto X 2014
**Android Version:** 6.0.0
**Signal Version:** 3.21.3

## Link to debug log
https://gist.github.com/8fcdc319e6b9199dafa7e935c54feb85

**Comment by sneakyfox1964** [comment] 2016-11-09 12:22
I have had the same problem for a few weeks now. Before that, everything worked well. I have been a daily user for about two months. 

Device: Huawei P8 Lite
Android Version: 6.0 (updated from v5 recently, same problem before)
Signal Version: 3.21.3

**Comment by andonevris** [comment] 2016-11-09 15:10
+1 for this, can't make any long calls on signal for weeks now, always disconnects after a few minutes.
Galaxy S7 Edge
Android 6.0.1
Signal 3.21.3

**Comment by MatejKovacic** [comment] 2016-11-09 16:12
I have noticed that Signal drops connection after about a minute or a little bit more - regardless I am on wifi or on mobile network. After that, there is no sound and usually connection drops.

I have also noticed that when on a mobile network, connection usually drops when base station is changed. A few moments after that, I have a perfect 4G signal, but SignalApp cannot call - it says network error. It seems that when base station is changed, 4G signal is good, but there is no network connection. It also seems to me that the problem is when there is a handover between base stations...

But as I said, there is also a problem when I am on a wifi network.

I have Nexus 5 with CyanogenMod. However some of my friends are experiencing the same problem. We are located in Slovenia, Europe if that matters.

Any idea what could be wrong?

**Comment by moxie0** [comment] 2016-11-10 03:53
What version of Signal are the people everyone here is calling running? Android? iOS?

**Comment by knusprjg** [comment] 2016-11-10 07:14
In my case they are all Android users too, for at least one I can also testify that he's also running the latest version (3.21.3).

**Comment by moxie0** [comment] 2016-11-10 07:21
Can anyone who can reproduce this check and see if this happens consistently on 3.20.x?

**Comment by 2-4601** [comment] 2016-11-10 15:12
For me this happens consistently both on 3.21.3 and 3.20.4.

### Steps to reproduce:
- Call another Signal Android
- Call connects succesfully
- Both clients can hear each other
- After one minute or so neither party can hear each other - yet the call still appears to be established in the UI
- After ten seconds or so of this silence you can hear again part of the previous conversation briefly (<1 sec, maybe one word) and then the call drops and Signal returns to the conversation screen

### Logs
- 3.21.3
    * Call 1
        + Caller: https://gist.github.com/fb9488c6982489075b6d21a157c5916d
        + Recipient: https://gist.github.com/4e225d2708d657fc7e79bd7ba0a9ab42
    * Call 2
        + Caller: https://gist.github.com/e415b601618bb3030e3ed8acd6383a94
        + Recipient: https://gist.github.com/9e6b0a80f944eff9cddf69c9149d0d88

- 3.20.4
    * Call 1
        + Caller: https://gist.github.com/cde8564c882d4b6b7db0191e7e066725
        + Recipient: https://gist.github.com/88bb91ab7baae7c6448675ce5099813a
    * Call 2
        + Caller: https://gist.github.com/ecec2a1e9fd30377a53faae7da2d4ab6
        + Recipient: https://gist.github.com/66185bbb9b1ad3c2466e2ec3c6a4ce68

**Comment by MatejKovacic** [comment] 2016-11-11 14:39
moxie0: this is my log - https://gist.github.com/anonymous/8d9bb74c94cc6ef32681134af7defaae
I have 3.21.3

A have talked to several people in Slovenia, almost everybody has the same issue.

**Comment by moxie0** [comment] 2016-11-12 01:49
I think this should be fixed now. I couldn't reproduce it, but I think it was a region-specific server-side issue. Can anyone consistently affected verify?

**Comment by JasMan78** [comment] 2016-11-12 12:59
I've just made a call about 20 minutes without any problem / disconnect. 
Hopefully this was not an exception. 👍

**Comment by MatejKovacic** [comment] 2016-11-12 14:10
I can also confirm it is working much better now. Call quality was great (clear sound, etc.). My call lasted several minutes, after that it dropped, but I was able to call back immediately and second call also lasted for several minutes.

**Comment by 2-4601** [comment] 2016-11-12 17:59
Seems to be working now for me too. Tested with two 3.20.4.

**Comment by moxie0** [comment] 2016-11-13 00:12
thanks everyone! and sorry!

**Closed by moxie0** 2016-11-13 00:12 UTC
Labels: redphone
