### ISSUE TITLE
Earphone microphone not working

### ISSUE THREAD

**Issue by johnrezzo** [WhisperSystems/Signal-Android#4630] opened 2015-11-20 16:06 UTC
Hello. I'm using Signal v3.4.2 on a LG G4 H815 (running Android v5.1) with a wired earphone that has its own microphone.

No problem at hearing the caller from the earphone, but Signal seems to use only the phone mic instead of the earphones' one, hence the caller hear my voice low, like 'from far away'.

**Comment by haffenloher** [comment] 2015-12-30 19:26
Can't reproduce with 3.9.0, I think this has been fixed in the meantime. Do you still encounter this issue?

**Comment by 2-4601** [comment] 2017-03-13 21:50
Closing as RedPhone issue.

**Closed by 2-4601** 2017-03-13 21:50 UTC
Labels: redphone
