### ISSUE TITLE
Stopped using signal, new signal user's message to me didn't get delivered

### ISSUE THREAD

**Issue by howdystranger** [WhisperSystems/Signal-Android#5564] opened 2016-07-06 08:45 UTC
### Bug description
I used to have Signal for Android which I loved. However I got an ubuntu phone which doesn't have signal. My friend got a new phone and I recommended that they get signal. They sent me a message (which was an encrypted one as it detected my cell number) which I never received. I presume this is because Signal is trying to deliver an encrypted message to me which I can't receive.

Ideally Signal would detect that I no longer use the app and can't receive encrypted messages, and should deliver a normal SMS instead. 

### Steps to reproduce
- use signal
- stop using signal
- someone who still uses signal sends you a message

**Actual result:** you never receive the sent message.
**Expected result:** signal defaults to SMS (or asks sender if they're okay downgrading to SMS) once it realises you're no longer using the app and can't receive encrypted messages.

### Device info
Sending device
**Device:** Huawei P9
**Android version:** 6.0
**Signal version:** 3.16.0

**Comment by ferranti** [comment] 2016-07-06 08:48
You have to unregister your phone number with signal here: https://whispersystems.org/textsecure/unregister/ 
Then unsecure sms will work.

Chris

On July 6, 2016 2:45:29 AM MDT, Harry Chapman <notifications@github.com> wrote:
>### Bug description
>I used to have Signal for Android which I loved. However I got an
>ubuntu phone which doesn't have signal. My friend got a new phone and I
>recommended that they get signal. They sent me a message (which was an
>encrypted one as it detected my cell number) which I never received. I
>presume this is because Signal is trying to deliver an encrypted
>message to me which I can't receive.
>
>Ideally Signal would detect that I no longer use the app and can't
>receive encrypted messages, and should deliver a normal SMS instead. 
>
>### Steps to reproduce
>- use signal
>- stop using signal
>- someone who still uses signal sends you a message
>
>**Actual result:** you never receive the sent message.
>**Expected result:** signal defaults to SMS (or asks sender if they're
>okay downgrading to SMS) once it realises you're no longer using the
>app and can't receive encrypted messages.
>
>### Device info
>Sending device
>**Device:** Huawei P9
>**Android version:** 6.0
>**Signal version:** 3.16.0
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5564

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by howdystranger** [comment] 2016-07-06 08:52
Thanks for the very quick response. I feel like there might be a wider issue here though. How are people who have stopped using signal going to know that they have to deregister? Could the process be automated?

**Comment by 2-4601** [comment] 2016-07-06 09:18
> How are people who have stopped using signal going to know that they have to deregister? Could the process be automated?

Unfortunately it's not trivial to distinguish people who have uninstalled the app from people who are just unavailable (e.g. on a holiday). There have been many issues about this and the developers are aware of the issue.

Closing as duplicate of #1026.

**Closed by 2-4601** 2016-07-06 09:18 UTC

**Comment by jmayday** [comment] 2016-09-08 12:49
Seems like all referenced tickets are closed, but **issue is still present**. 

1. I've added my friend's number (who was using Signal but uninstalled it some time ago).
2. On my side there was notification to say hello to my friend.
3. I've sent him a message
4. Message was not delivered which means communication is down

This is serious problem of Signal and should be solved somehow. I doubt that anyone who uninstalls the app is aware that it's mandatory to unregister.

**Comment by androclus** [comment] 2017-01-24 15:29
i agree with jmayday.  shouldn't uninstalling the app automatically unregister / deregister me? that would seem to be the way to go.  i will look into issue #1026.

**Comment by SethArchambault** [comment] 2018-02-06 16:54
Plus 1 here - this is a very serious issue, which is preventing me from recommending signal to more people at this point. I've had at least 2 people stop receiving messages from me after they installed and then unstalled the app.

I use Signal as my default text messager, which provides the great benefit of automatically using encryption when my friends join Signal, but if they don't go all in on it and someday decide to uninstall, I have no way of knowing, and they can text me, but not see my messages in return, making me look like I'm ignoring them. 

I definitely see the technical issue here, so the solution may be to educate all new users, letting them know they must unregister, otherwise they will not be able to receive messages from their friends. 

I've just started using Wire, and I see this as a comparative advantage - users are either communicating via Wire, or they're not, there's no chance of an inbetween state..

**Comment by NetScr1be** [comment] 2018-06-09 17:47
Same here. Messages with a close contact switched to saying "Tap for unsecured fallback".

If unsecured fallback is the only way to get there message through them there should be the option of making it permanent/default.

This isn't that complicated.

If the user cares enough about service comms they will straighten it out with the correspondent.

We shouldn't have to select unsecured fallback every

time

we

send

a

message

**Comment by igor47** [comment] 2018-08-20 22:08
strongly agree. i friend stopped using signal because she often wouldn't get notified about a new message. now, i have to "tap for unsecured fallback" every time i message her. i've tried resetting the secure session, which does nothing. ideally, in 'conversation settings' there should be an option to default to unsecured messages, but there's no such option :(

**Comment by martinb3** [comment] 2020-09-25 21:16
The link in this issue, to unregister, seems broken. I'm stuck with people unable to reach me as well...
