### ISSUE TITLE
Should import MMS

### ISSUE THREAD

**Issue by jacksenechal** [WhisperSystems/Signal-Android#4915] opened 2015-12-18 09:17 UTC
When I first open the app after installation I'm able to import my SMSes from the system to the Signal database. It does not import MMS successfully though, so I can't switch to Signal as my primary SMS app without losing many important messages in my history.

**Comment by 2-4601** [comment] 2015-12-18 15:38
Closing as duplicate of #4095.

**Closed by 2-4601** 2015-12-18 15:38 UTC
