### ISSUE TITLE
Registration text message states "TextSecure" not "Signal"

### ISSUE THREAD

**Issue by funkydude** [WhisperSystems/Signal-Android#5332] opened 2016-03-13 15:34 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Android registration text message states "TextSecure" not "Signal".
Exact message contents: `Your TextSecure verification code: ...`

### Steps to reproduce
- Install Signal
- Register your phone number
- Receive text message

**Comment by 2-4601** [comment] 2016-03-13 15:41
Thanks for the report, this is a known issue. Closing as duplicate of #5162

**Closed by 2-4601** 2016-03-13 15:41 UTC
