### ISSUE TITLE
Swiping Signal out from the recent apps list closes the list, other apps don't have this behaviour

### ISSUE THREAD

**Issue by olbrew** [WhisperSystems/Signal-Android#5026] opened 2016-01-05 10:10 UTC
Someone recently notified me of this quirky behaviour, apparently it has been the case for a long time already as they had the same problem on their former phones as well.

Steps to reproduce:

1. Open recent app list
2. Swipe away Signal
3. Recent apps list closes, for other apps it stays.

Tested on a OnePlus One and Oneplus X fully updated. (ROMs based on Android 5.1)

**Comment by 2-4601** [comment] 2016-01-05 11:48
Closing as duplicate of #1037.

**Closed by 2-4601** 2016-01-05 11:48 UTC

**Comment by olbrew** [comment] 2016-01-05 12:58
D'oh, didn't found that one when searching through the issues.

**Comment by groveld** [comment] 2016-11-30 16:39
I don't know if it's addressed somewhere else but i still have this problem on my Nexus 6P running Android 7.1.1. is there more information about this problem?
Thanks in advance!
