### ISSUE TITLE
German Umlaut ß is missing on Finish button on **Your profile info** screen 

### ISSUE THREAD

**Issue by mlsxlist** [WhisperSystems/Signal-Android#6953] opened 2017-09-11 05:14 UTC
I have:
- [X] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The **Finish** button on the Profile information screen **Your profile info** screen is missing the German umlaut ß when language is set to German

### Steps to reproduce
- Switch to German language
- select **Einstellungen** and tap the profile at the top

**Actual result:** The button at the bottom on the screen contains the text **ABSCHLIE EN**.
**Expected result:** The text should be **ABSCHLIEßEN**

### Screenshots
![screenshot_2017-09-10-10-26-53](https://user-images.githubusercontent.com/6071818/30259202-2fe18364-96af-11e7-8ac1-f3e304938369.png)

### Device info
**Device:** samsung GT-I9100 (GT-9100)
**Android version:** 4.4.4 cm_i9100
**Signal version:** 4.10.7

**Comment by Trolldemorted** [comment] 2017-09-11 07:00
Side note: Before the 29th of june 2017, the letter ß had no official capital letter. ẞ is now official, and the letter is in the unicode standard since 2008 (unicode 5.1).

https://en.wikipedia.org/wiki/Capital_%E1%BA%9E

Java 8's toUpperCase most likely will not know that and convert it to SS instead, though.

**Comment by rainerzufall** [comment] 2017-09-11 09:43
can not reproduce on Android 6.0.1 and Signal 4.10.7:

![signal_abschliessen](https://user-images.githubusercontent.com/12666598/30268481-22ba5e9a-96e6-11e7-9799-5f66699de41e.png)

**Comment by FeuRenard** [comment] 2017-09-11 11:58
I can confirm the missing ß for 4.4.4.

**Comment by minnmann** [comment] 2017-09-11 12:39
I can also confirm the ß beeing visible for Android 6.0 and Signal 4.10.7.

**Comment by Trolldemorted** [comment] 2017-09-11 12:51
Could it be that signal uses the default font and some roms have a default font which is missing the capital ẞ?

**Comment by johanw666** [comment] 2017-09-11 14:01
Workaround: switch to Greek and use a Greek Beta?

**Comment by vvug** [comment] 2017-09-11 14:30
@jocelynthode insane idea. The typical workaround here is to use the small caps ß. It's a pity that KitKat is still so widely used.

**Comment by jocelynthode** [comment] 2017-09-11 14:38
I think you didn't link the right user. 

Le 11 septembre 2017 16:31:22 GMT+02:00, vvug <notifications@github.com> a écrit :
>@jocelynthode insane idea. The typical workaround here is to use the
>small caps ß. It's a pity that KitKat is still so widely used.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/6953#issuecomment-328547535

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by RiseT** [comment] 2017-09-11 20:50
I'm the one who did this string's translation shown above with the new capital "ß" (hey, I just wanted to use the latest & greatest...)

Note that per offical rules, one **doesn't have to** replace the old "SS" with the new capital "ß". It's just an alternative that is now official (although it has been a strange situation to have a letter with no upper case equivalent).

So if there are technical problems, thete's not problem changing this into "ABSCHLIESSEN".

**Comment by mlsxlist** [comment] 2017-09-12 04:57
Thanks all. If nobody consists on the capital "ß" @RiseT can you please change translation to **ABSCHLIESSEN**.

**Comment by Trolldemorted** [comment] 2017-09-12 07:14
We might want to track down the underlying issue - if ẞ is not working in textbox labels, i assume maybe it won't work in conversations either?

**Comment by RiseT** [comment] 2017-09-12 14:33
Another viable alternative would "Abschließen" (i. e. lower case). The button doesn't look worse than with upper case.

**Comment by moxie0** [comment] 2017-09-14 00:22
I think this has to be fixed on transifex, so I'm closing this here

**Closed by moxie0** 2017-09-14 00:22 UTC
