### ISSUE TITLE
opening hyperlink with no browser installed crashes TS

### ISSUE THREAD

**Issue by yawnbox** [WhisperSystems/Signal-Android#3726] opened 2015-07-19 22:07 UTC
https://gist.github.com/40e0ca458f712207dee7

If I send or receive an HTTP/HTTPS link and try to open said link on a device that has no web browser installed, TextSecure will crash.

**Comment by jeremymasters** [comment] 2015-07-20 00:12
No Web browser?

**Comment by yawnbox** [comment] 2015-07-20 05:46
Yes, no browser.

"I don’t have a browser like Chrome or Firefox because the web isn’t safe."
https://yawnbox.com/?p=2561

Because my goal is to protect my messages and my contacts. But this is beside the point, TS shouldn't crash because of a lack of third party software that has nothing to do with TS.

**Comment by junitas** [comment] 2015-08-01 21:35
This behavior happens with the native SMS app on Android as well. Is this something that can be fixed in the TS code or is it a problem with how Android deals with clickables that are formatted as HTTP/S links? I'm not seeing anywhere where the proper Intent is built for the web browser activity in ConversationItem or anywhere else.

**Comment by RalfKeller** [comment] 2015-08-16 20:55
I can't reproduce this issue, on my phone (UMI ZERO with Android 4.4.2) it just says "No App found for this Action" (or something like this, it actually says "Diese Aktion kann von keiner App ausgeführt werden.")

**Comment by SergejKern** [comment] 2015-09-16 08:51
If I understand correctly, for massage display the android class TextView is used. So this class delegates the click on a link to according app.
Does it make sense to set linksClickable to False if no browser is detected?

**Comment by FeuRenard** [comment] 2016-08-05 21:27
This issue also affects the help button in the conversation list's menu.

**Comment by FeuRenard** [comment] 2016-08-05 22:53
Those crashes will happen every time you click one of these items:

- URL but no browser installed
- phone number but no dialer or contacts app installed
- email address but no email app installed
- map address but no map app installed (not tested)

[Here](https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/AppDetails.java#L793) is what F-Droid does to check for an installed activity. But its links aren't in a TextView. So no simple copy and paste :disappointed:. Anyway it could be used for the help button.

**Closed** 2016-09-01 19:31 UTC
Labels: bug, easy
