### ISSUE TITLE
Cannot forward to group if group does not appear under recent conversations

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#7281] opened 2017-12-16 16:08 UTC
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In forwarding a message, groups appear only under recent conversation. This makes it hard to share a message with a group, especially if it has an attachment.

### Steps to reproduce
- Make sure some conversations and groups exist
- Select a message and try to forward it to a group.

**Actual result:**
Groups only appear in the following lists under "recent conversations". This means, if the group does has no recent messages, it cannot be selected here. Also, the search functionality does not find groups in this activity.

**Expected result:**
I'd expect groups to appear in the contacts list as well and that they can be found by the search feature. Alternatively, an extra category "groups" could be introduced alongside "recent conversations" and "contacts".

**Comment by Wikinaut** [comment] 2017-12-16 16:31
Yes, I also wanted to report this problem, thanks!

**Comment by Wikinaut** [comment] 2017-12-16 16:32
I think, "groups" should be simply sorted-into the alphabetically list of contacts.

**Comment by rainerzufall** [comment] 2017-12-16 16:48
Conpletely agree, but unfortunately it is a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/7202 Moxie already commented, but then did not resolve it. Still, please close this issue and show your support via the built in emojis there...

**Closed** 2017-12-16 18:27 UTC
