### ISSUE TITLE
Signal doesn't resync known contacts

### ISSUE THREAD

**Issue by sashw** [WhisperSystems/Signal-Android#5094] opened 2016-01-19 16:33 UTC
This is a duplicate of #4338 as this issue was already closed. See also maybe related issues I pointed out there.

In short: If Signal already "knows" phone numbers of contacts, it doesn't resync with the phone contacts in case they're deleted or changed.

I had for some reason multiple local phone contacts. To get rid of them, I deleted all my contacts from my phone and resynced them with DavDroid from my server. Since then Signal hasn't changed any of my contacts to add them as a Signal user. I'm running Signal 3.9.1 on Android 5.1.1 (CM 12.1) on a rooted device. It seems that Signal doesn't check the contacts anymore for already known numbers. 

Things I tried: Sync Signal via Settings -> Accounts; refresh contacts in Signal itself. When I display only Signal contacts, none of the former Signal contacts are shown. In fact only my own contact shows up.

I can also confirm that this happened on a non-rooted Samsung Galaxy S4 mini running Android 4.4 and Signal 3.9.1. There the contacts had been deleted and resynced with Google. The only "solution" which helped to add Signal users in contacts again was to reinstall the app.

**Comment by 2-4601** [comment] 2016-01-19 18:42
Closing as duplicate of #4338 :)

**Closed by 2-4601** 2016-01-19 18:42 UTC
