### ISSUE TITLE
Show confirmation time in sent message details

### ISSUE THREAD

**Issue by GfEW** [WhisperSystems/Signal-Android#4862] opened 2015-12-11 07:39 UTC
It would be helpful at times to see in sent message details not only the time a message was sent (first checkmark) but also the time the second checkmark appeared.

**Comment by FeuRenard** [comment] 2015-12-11 09:44
This is a duplicate of #2055 (Signal messages) and #1692 (SMS).

**Closed** 2015-12-12 06:36 UTC
