### ISSUE TITLE
Signal crashes on activating attachment menu on Android N

### ISSUE THREAD

**Issue by daijizai** [WhisperSystems/Signal-Android#5630] opened 2016-08-23 03:18 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Attempting to activate the attachment menu causes Signal to hang on SMS/MMS threads and Signal protocol threads. Function is the same for single and group messages.

### Steps to reproduce
- activate a new or existing thread while using Android 7
- click paperclip icon to engage the attachment menu
- signal hangs
- signal does not resume
- click home and signal crashes within approximately 5 seconds

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Application hangs and triggers Android's crash notification.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Application should display the attachment dialog

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.0
**Signal version:** 3.16.1

### Link to debug log

https://gist.github.com/02cbbfce0581760c2747ad62a8f4b661

**Comment by 2-4601** [comment] 2016-08-23 08:52
Closing as duplicate of #5583.

**Closed by 2-4601** 2016-08-23 08:52 UTC
