### ISSUE TITLE
Ringer Volume Too Low When Recieving Signal Calls with Beta, Video Calls Enabled on both devices

### ISSUE THREAD

**Issue by KyleRConway** [WhisperSystems/Signal-Android#6216] opened 2017-02-12 19:12 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On the Android Beta for signal (with video calls enabled), making a voice call to another signal user produces a low-volume (in-ear only; not speaker) ring sound that is inaudible. This happens  for the call reciever. If the call reciever, prior to picking up the phone, hits the "speaker" button, the volume of the ringer reaches the expected volume.

### Steps to reproduce
0. Enable video calls on beta on both recieving and calling device
1. Recieve signal call on either phone.
2. *ACTUAL RESULT* Volume doesn't come through speaker (only ear speaker). (*EXPECTED RESULT* load volume through speaker).
3. Disable video calls on beta (on either or both devices)
4. Recieve signal call.
5. Note that volume comes through speaker (and is loud).

### Device info
**Device:** Moto G 3rd Gen XT1540
**Android version:** 6.0
**Signal version:** 3.29.3

### Link to debug log
https://gist.github.com/3da3b235d3e137b4b4e70e9c2a9ae480

**Comment by moxie0** [comment] 2017-02-12 19:30
Thanks @KyleRConway, I think this is a dupe of #6169. Can you confirm?

I can't reproduce this behavior on any of my test devices, I'll have to try to find a device where it occurs.

**Comment by KyleRConway** [comment] 2017-02-12 19:44
@moxie0 -- can confirm. It does appear to be a dupe of #6169 (apologies for not seeing it before submitting). Do let us know if we can assist in some way. Really appreciate your work on this.

**Comment by 2-4601** [comment] 2017-02-13 00:11
Closing as duplicate of #6169

**Closed by 2-4601** 2017-02-13 00:11 UTC
