### ISSUE TITLE
Reinstall no contacts, groups broken

### ISSUE THREAD

**Issue by frederik-b** [WhisperSystems/Signal-Android#5138] opened 2016-01-27 19:28 UTC
Hi, I factory reset my phone and installed Signal...
and I reinstalled Signal multiple times now.

The registration process is without problem...

If I don't set Signal as the default SMS app, it shows no contacts whatsoever,
allthough I resynced every possible account on the phone multiple times.

If I set Signal as the default SMS app, it shows every contact twice (once from the google account and once from the whatsapp account, I think), allthough the rest of the phone handles identical entries without a problem. Also Contacts who write me still appear as phone numbers only and not in any way with a name, neither in groups nor in the chat overview nor in single chats.

In either case:
Groups where I am part of pop up when someone writes something in them, but they have cryptic names in popups (__textsecure_group__!1c20d...) and are named Unnamed Group inside the App.
I can't reply in these groups, the keyboard dosn't even open.
Also showing Group Members gives an empty Popup.

This is by far not the first time I have Killer Issues with Textsecure/Signal (broken chats that can't be resolved, Contacts Syncing, allways broken Groups after reinstall (yes this is by far not the first time I'm having that issue, just the completely broken contacts are my main Issue right now)),
Which saddens me because this is otherwise just an awesome Product and with Desktop support would replace 2 other messaging apps at once for me (of which I have about 5 at the moment).

I seriously believe there are enough people that sent you debug logs and everything on similiar or the same issues, but if you need some I can provide them... with or without SMS enabled.

Debug Log: https://gist.github.com/301d3f67764d531ced2e

**Comment by agrajaghh** [comment] 2016-01-27 20:19
regarding groups its a duplicate of #2581 
the contact issue looks like #5079, could you please give a description of your problem (+ the log) there? Thanks!

**Closed by agrajaghh** 2016-01-27 20:19 UTC
