### ISSUE TITLE
Publicly available APK

### ISSUE THREAD

**Issue by hiredgunhouse** [WhisperSystems/Signal-Android#5379] opened 2016-03-25 16:12 UTC
Please make APK publicly available for those who do not want to sign-up to Google services like Play store.
I suppose GitHub releases feature would be perfectly fine, ideally you could put the APK on F-Droid.

**Comment by 2-4601** [comment] 2016-03-25 16:23
Please read the guidelines for contributing article that's visible when you open a new issue. Also please read the issue template and search for existing issues before opening new ones.
Closing as duplicate of #127.

**Closed by 2-4601** 2016-03-25 16:23 UTC

**Comment by hiredgunhouse** [comment] 2016-03-25 21:21
@2-4601 I did search for existing issues but missed the one at the bottom of the page, my bad. As for the template I did not bother to read it cause I figured it is for bugs not requests and turns out I was right.

**Comment by Nhorning** [comment] 2016-11-08 10:55
Just to point out on this -  Signal is now recommended by Security in a Box, so we are doing trainings on it for Human Rights defenders.  Having 25 people download the app from the play store using the wifi of a venue in a less developed country is a bit out of the question.

**Comment by hiredgunhouse** [comment] 2016-11-08 12:28
@Nhorning I gave up on Signal because of the issue discussed here. I can't understand an OSS project enforcing a restricted distribution policy. It's like saying we're OSS, you can read the code, take it and... keep it to yourself - WTF?

**Comment by zoff99** [comment] 2016-11-08 14:52
download libresignal (only if you trust it):
https://fdroid.eutopia.cz/
https://eutopia.cz/fdroid/repo/
