### ISSUE TITLE
Incoming sound ringing from talking speaker

### ISSUE THREAD

**Issue by Exlatus** [WhisperSystems/Signal-Android#6504] opened 2017-04-08 00:43 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Problem with incoming call sound. At LockScreen sound very quiet.

### Steps to reproduce
1. Unlock the phone and start the application
2. Call this phone in the signal
3. Hear that the call is loud and clear
4. Lock the phone
5. Call this phone again in the signal
6. Detect that the call can not be heard.

It sounds like a talking speaker, not the main speakers.

### Device info

**Device:** Sony E5823  (Xperia Z5)
**Android version:** 7.0
**Signal version:** 4.2.4
and
**Device:** Xiaomi Redmi Note 3 Pro
**Android version:** 6.0.1
**Signal version:** 4.2.4

**Comment by chrihu** [comment] 2017-04-08 07:19
Duplicate of #6356

**Closed** 2017-04-29 14:07 UTC
