### ISSUE TITLE
Androidtaskmanager closes when closing singnal task in it

### ISSUE THREAD

**Issue by Commtiy** [WhisperSystems/Signal-Android#6633] opened 2017-05-12 23:21 UTC
I have:
- [X] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I opened the Native Taskmanager of Android and I kill the task of Signal the Taskmanager also closes.

### Steps to reproduce
- open Signal
- press home button (close Signal and go to the HomeScreen of Android)
- open native Android Taskmanager
- kill Signal Process (by swyping it to the side)

**Actual result:** The native android taskmanager also closes
**Expected result:** The native android taskmanager should not close

### Device info
**Device:** Samsung Galaxy Note 4; Sony Xperia M5;
**Android version:** 6.0.1
**Signal version:** 4.5.3

**Comment by nrizzio** [comment] 2017-05-12 23:46
This is a duplicate of #1037.

**Closed** 2017-05-13 03:08 UTC
