### ISSUE TITLE
Time/date not translated in image view

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#3449] opened 2015-06-21 17:18 UTC
2.19.0
_Edit: see third comment for a proper bug report._
![phil thomas katt enterprise room](https://cloud.githubusercontent.com/assets/174176/8272598/879f4cfe-1852-11e5-9218-54a47715bf88.png)

**Comment by McLoo** [comment] 2015-06-21 19:49
Disagree 

![screenshot_2015-06-21-21-47-56](https://cloud.githubusercontent.com/assets/5326916/8273114/5ed39cbe-185f-11e5-9e55-b552e7a0e5ba.png)

**Comment by 2-4601** [comment] 2015-06-21 20:15
@McLoo Do you have system language set to Deutsch?

I can only reproduce this if system language is different than TS language. E.g. system: English; TS: Deutsch.

Tested on:
- Nexus 4, stock Android 5.1
- Huawei U880, Android 4.0.4

**Comment by McLoo** [comment] 2015-06-22 11:03
confirmed.
seems to be #2815

**Comment by 2-4601** [comment] 2015-06-22 12:48
Hmm... wasn't #2815 caused by rotation changes? This happens if system language and TS language are different.

**Comment by rhodey** [comment] 2015-06-22 18:04
yeah #2815 is a pain cause by screen rotation and can only be resolved by moving all our dynamic language stuff into the base activity classes from which all other activities extend.

**Comment by FeuRenard** [comment] 2016-08-04 22:17
I found the root cause of this problem:
To get formatted timespan strings usually the class `DateUtils` inside the Signal project is used. This class' methods consider the language set within Signal. Such methods are used for the message bubble timestamps and the timestamps in the conversation list.
For the media preview's timestamp currently a method of Android's `DateUtils` is used, which considers the system language.

I am going to work on this.

**Closed** 2016-11-30 03:29 UTC
Labels: bug
