### ISSUE TITLE
Signal crashed on MMS receive

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#7096] opened 2017-10-15 02:16 UTC
Was using another app when Android told me that Signal had crashed.

An mms was delivered when it happened.

On mobile devices it's hard to check for duplicates

Debug log: https://gist.github.com/anonymous/7fea46d9e5ee648f92f1ef97bbc7e4a8

**Comment by moxie0** [comment] 2017-10-15 17:09
Duplicate of #7094

**Closed by moxie0** 2017-10-15 17:09 UTC
