### ISSUE TITLE
MMS download not working on android 4.1.2

### ISSUE THREAD

**Issue by rgrannemann** [WhisperSystems/Signal-Android#5458] opened 2016-04-24 09:02 UTC
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by rgrannemann** [comment] 2016-04-24 09:02
04-24 10:34:57.360 W/MmsDownloadJob(16839): java.io.IOException: Not able to use Lollipop APIs, giving up...

**Comment by rgrannemann** [comment] 2016-04-24 09:08
04-24 10:34:57.360 W/MmsDownloadJob(16839): java.io.IOException: Not able to use Lollipop APIs, giving up...

**Comment by rgrannemann** [comment] 2016-04-24 09:08
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=JZO54K
ro.build.display.id=Rainbox Rom V8.3 Final JB XXLSJ
ro.build.version.incremental=I9100XXLSJ
ro.build.version.sdk=16
ro.build.version.codename=REL
ro.build.version.release=4.1.2
ro.build.date=Dec  18 12  2012
ro.build.date.utc=1352135821
ro.build.type=user
ro.build.user=se.infra
ro.build.host=SEP-111
ro.build.tags=release-keys
ro.product.model=GT-I9100
ro.product.brand=samsung
ro.product.name=GT-I9100
ro.product.device=GT-I9100
ro.product.board=smdk4210
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product_ship=true
ro.product.manufacturer=samsung
ro.product.locale.language=en
ro.product.locale.region=GB
ro.wifi.channels=
ro.board.platform=exynos4
# ro.build.product is obsolete; use ro.product.device
ro.build.product=GT-I9100
# Do not try to parse ro.build.description or .fingerprint
ro.build.description=GT-I9100-user 4.1.2 JZO54K I9100XXLSJ release-keys
ro.build.fingerprint=samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XXLSJ:user/release-keys
ro.build.characteristics=default
# Samsung Specific Properties
ro.build.PDA=I9100XXLSJ
ro.build.hidden_ver=I9100XXLSJ
ro.build.changelist=462349
# Call Tweaks
ro.telephony.call_ring.delay=0
ro.lge.proximity.delay=25
mot.proximity.delay=25
# end build properties
#
# system.prop for smdk4210
#
rild.libpath=/system/lib/libsec-ril.so
rild.libargs=-d /dev/ttyS0
ro.sf.lcd_density=240
ro.lcd_min_brightness=30

**Comment by 2-4601** [comment] 2016-04-24 13:44
Try to make your issue report look like this [example issue](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#tldr-example-issue). In this current form it's hard to find the cause of the bug.
And this is probably a duplicate of one of the many MMS download issues.

**Closed by 2-4601** 2016-04-24 13:44 UTC

**Comment by rgrannemann** [comment] 2016-04-24 20:24
Now it works. After doing manual mms settings (from provider page) i am able to download mms.
