### ISSUE TITLE
Long messages

### ISSUE THREAD

**Issue by leonardoporpora** [WhisperSystems/Signal-Android#7347] opened 2018-01-18 22:33 UTC
I’m not able to receive messages much long. On iPhone I simply click on the message tap for more and then I can see al the message whereas in android the message I cut, I can’t see all it.

**Comment by jeremymasters** [comment] 2018-01-18 22:58
@leonardoporpora again, you need to fill out the template.  At the very least, you need to include a log file.

**Comment by FeuRenard** [comment] 2018-01-19 02:32
This is probably a duplicate of #5146

**Closed** 2018-01-19 18:39 UTC
