### ISSUE TITLE
Crash after closing video call

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6138] opened 2017-02-02 01:53 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I place a video call between 2 devices: an Acer Z205 running 4.4.2 and a Sony XPeria Z3 compact running 6.0.1. After hanging up, on the Acer device Signal crashes. Both run Signal 3.29.0.

**Actual result:** Crash.
**Expected result:** Normal closure,

### Device info

**Device:** Acer Z205
**Android version:** 4.4.2
**Signal version:** 3.29.0

Note: this device does not have a front camera, Signal shows automatically the image of the back camera.

### Link to debug log

https://gist.github.com/anonymous/1b659729fb19152b9deafe1ca43947d5

(There is a NPE at line 4472, maybe that's the problem?)

**Comment by p4nci** [comment] 2017-02-02 06:00
@johanw666 please update to v3.29.1 and retry. see also https://github.com/WhisperSystems/Signal-Android/issues/6137

**Comment by moxie0** [comment] 2017-02-02 06:56
looks like you compile from source, can you check that change if this is reproducible?

**Comment by johanw666** [comment] 2017-02-02 11:54
I could not reproduce the crash with 3.29.0 today (it was late yesterday, I didn't check thouroughly). However, I built https://github.com/WhisperSystems/Signal-Android/commit/8dc6f2b15b82505ddcf719977251978d1618e472 and it does work OK. I'll close this issue unless I might encounter something similar again.

**Comment by RiseT** [comment] 2017-02-02 15:28
I have another log with 2 fatal exceptions here:
https://gist.github.com/anonymous/d4fd30b33e04a724ae564840454c38e2

**Comment by haffenloher** [comment] 2017-02-02 15:33
@RiseT that was without 8dc6f2b1, right? Or did you build from source?

**Comment by RiseT** [comment] 2017-02-02 15:35
Yes, only the other side of the call (i. e. my personal phone) had https://github.com/WhisperSystems/Signal-Android/commit/8dc6f2b15b82505ddcf719977251978d1618e472 installed. Not the Nexus 4 the log comes from.

**Comment by RiseT** [comment] 2017-02-02 15:47
I should add that the crashes in the log occured at the very beginning of the (at that point in time non-video) call, not after closing it.

**Comment by p4nci** [comment] 2017-02-02 20:39
experienced the same crash as @johanw666 after hanging up and without https://github.com/WhisperSystems/Signal-Android/commit/8dc6f2b15b82505ddcf719977251978d1618e472
Signal v3.29.1 and CM13 (Android v6.0.1):
```
--------- beginning of crash
02-02 21:02:11.558  5348  8864 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
02-02 21:02:11.558  5348  8864 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5348
02-02 21:02:11.558  5348  8864 E AndroidRuntime: Theme: themes:{}
02-02 21:02:11.558  5348  8864 E AndroidRuntime: java.lang.RuntimeException: This object has been released
02-02 21:02:11.558  5348  8864 E AndroidRuntime: 	at org.webrtc.EglBase14.checkIsNotReleased(EglBase14.java:144)
02-02 21:02:11.558  5348  8864 E AndroidRuntime: 	at org.webrtc.EglBase14.release(EglBase14.java:150)

```

**Closed** 2017-02-02 21:55 UTC
Labels: bug, crash, webrtc
