### ISSUE TITLE
Texts not delivered to users who get new phones and don't reinstall Signal

### ISSUE THREAD

**Issue by zacharycohn** [WhisperSystems/Signal-Android#6905] opened 2017-08-28 18:20 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Scenario: Someone is using Signal, then switches to a new phone but doesn’t reinstall/re-set up Signal. 
Issue: I send them a text message through Signal. The lock symbol appears (so the message is being routed through Signal), the first checkmark (the message was sent) appears, but I never get the second checkmark (the message was delivered).

I've run into this issue with at least 3 people in the last week. In addition to the problem itself, it is additionally problematic that there is no notification the message was never delivered. I only discover it when I go to text that person again days, or weeks later - and even then it often takes me a few more instances before I notice what's going on. 

### Steps to reproduce
- Set up Signal on a phone.
- Drop phone in toilet.
- Get a new phone, don't set up Signal.
- Have someone else send you a text message. 

**Actual result:** 
- The recipient does not receive any message.
- The sender does not receive a notification their message failed to deliver.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- The text message would be routed to the recipient's normal text message app, OR...
- The sender would be notified the text message could not be delivered.

### Platform info

**Operating System**: LG G6, Android 7.0.
**Signal version:** 4.9.9

**Comment by johanw666** [comment] 2017-08-28 22:33
You didn't send an sms message (Text in American) but a Signal message because the server thinks the user is a Signal user.

**Comment by riyapenn** [comment] 2017-08-29 05:22
@zacharycohn Closing this issue as a duplicate of a few closed issues, most notably https://github.com/WhisperSystems/Signal-Android/issues/6377#issuecomment-286608149

You can [long-press the send button on Android to switch to insecure SMS](https://support.whispersystems.org/hc/en-us/articles/212535548). Until your contact [unregisters](https://support.whispersystems.org/hc/en-us/articles/213190627), you will have to long-press to send an SMS. Your contact can unregister on the webpage https://signal.org/signal/unregister/

**Closed by riyapenn** 2017-08-29 05:22 UTC

**Comment by zacharycohn** [comment] 2017-08-30 18:16
@riyapenn That's not really the issue. The problem is the remote user doesn't know they have to de-register, the sending user doesn't know the remote user didn't reinstall Signal (so how would I know to send SMS instead of Signal?), and there's no notification to the sending user their message wasn't delivered. 

It's a very poor user experience to leave it up to the user to double check to make sure their message was delivered. Especially when many people who haven't used Whatsapp aren't aware what the double check marks mean.

[Lenbok's suggestion](https://github.com/WhisperSystems/Signal-Android/issues/6377#issuecomment-286608149) would essentially solve the problem. A notification after N minutes that the message wasn't delivered is really all you'd really need. 

I'd strongly encourage you to re-open this issue and consider Lenbok's suggestion.

**Comment by zacharycohn** [comment] 2017-09-04 18:22
@riyapenn Since posting this issue a week ago, I have run into this problem with 3 more people. There was also a [new, identical issue](https://github.com/WhisperSystems/Signal-Android/issues/6912) opened, then closed. I think this _is_ a widespread problem, and the user experience needs to be improved

I would implore you to re-open this issue (with the feature suggestion being "a notification after _x minutes_ when a message is not delivered").

**Comment by lordgnarington** [comment] 2018-06-26 03:05
Would be great to be able to toggle between secured and unsecured messages with particular contacts. It's awkward to have to explain to people that you aren't snubbing them. I will have to uninstall signal if this issue continues with no integrated solution.

**Comment by Coehill** [comment] 2019-03-05 00:16
This issue still exists for me.
