### ISSUE TITLE
Track verified safety numbers

### ISSUE THREAD

**Issue by mach-o** [WhisperSystems/Signal-Android#6606] opened 2017-04-30 21:56 UTC
Signal should remember that you've verified safety numbers with a contact.

When you run into a friend, it's easy to forget whether you've done this or not, and anything to make it more convenient increases security. Some users add a check mark to the contact's name, but this is a terrible solution. This change shouldn't require any new options or settings.

It would be nice:
- for both users to see a "Your safety number with XXX was verified [/ not verified]" message in the conversation in the style that you already see e.g. "Your safety number with XXX has changed"
- to see an indication of whether the safety number for any given contact has been verified in "Conversation settings > verify safety number", and perhaps also additional info about it e.g. when verification occurred, how ...
- to have some ongoing visual indication of the verification status within each conversation (maybe the lock and checkmarks could become green instead of grey? or there could be a different color in the title bar or background color?)
- I'm guessing it's unwise, though, to prevent someone from re-verifying a safety number with a contact in case, e.g., their threat model includes physical tampering

Thanks for considering this!

**Comment by FeuRenard** [comment] 2017-04-30 22:21
Duplicate of #6416

**Comment by 2-4601** [comment] 2017-05-23 08:46
Closing as duplicate

**Closed by 2-4601** 2017-05-23 08:46 UTC
