### ISSUE TITLE
Writes phone numbers to log

### ISSUE THREAD

**Issue by Safari77** [WhisperSystems/Signal-Android#4930] opened 2015-12-20 13:47 UTC
```
12-20 15:41:23.798 W/PushServiceSocket( 7547): Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+3585xxxxyyyy
12-20 15:41:25.809 W/MessageRetrievalService( 7547): Retrieved envelope! +3585xxxxyyyy
```

If you must, consider doing this as a debug feature.
Version 3.7.2.

**Comment by haffenloher** [comment] 2015-12-20 17:09
Duplicate of #4832 and #2065:
> We filter these out in the debug logs we generate, but we have to emit them for debugging.

**Comment by Safari77** [comment] 2015-12-20 21:03
Well this is not a duplicate if the bug still exists.

I meant "a debug feature user enables when he/she NEEDS to", not "a debug feature enabled for all because moxie wants to".

**Comment by agrajaghh** [comment] 2015-12-20 21:09
are the numbers in the debug log generated by signal (settings -> advanced -> submit debug log) or in a log obtained by `adb logcat`?

**Comment by Safari77** [comment] 2015-12-20 21:23
```adb logcat```.

**Comment by agrajaghh** [comment] 2015-12-20 21:24
What is the problem then? No other app can access this data, no?

**Closed** 2015-12-20 21:27 UTC
