### ISSUE TITLE
Failure to send picture messages (secure) via 4G or WiFi

### ISSUE THREAD

**Issue by SamClarke2012** [WhisperSystems/Signal-Android#6318] opened 2017-02-28 21:33 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal (secure) fails to send pictures on both 4G and WiFi.  Log reports:
`JobConsumer: Caused by: java.io.IOException: Bad response: 500 Internal Server Error`

Persistent after reboot, emerged overnight. 

### Steps to reproduce
- Attempt to send a picture either via attachment or directly using the camera within Signal

**Actual result:** 

Progress bar completes, flickers, then the message fails to send.

**Expected result:** 

Message should send.

### Device info

Device  : LGE Nexus 5 (hammerhead)
Android : 6.0.1 (3437181, M4B30Z)
App     : Signal 3.29.6

### Link to debug log
https://gist.github.com/anonymous/203ca9699b28f8f874b0580ffe7e01e4

**Comment by haffenloher** [comment] 2017-02-28 21:35
Duplicate of #6316.

**Comment by nrizzio** [comment] 2017-02-28 21:35
Amazon S3 (which Signal uses for encrypted attachment storage) is having a massive outage currently. It's not just Signal that's affected either. There's nothing OWS can do but wait until Amazon fixes everything on their end.

**Comment by moxie0** [comment] 2017-02-28 22:47
should be resolved now

**Closed by moxie0** 2017-02-28 22:47 UTC
