### ISSUE TITLE
"Verify identity" doesn't use contact color

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#3630] opened 2015-07-12 12:39 UTC
Opening "verify identity" switches back to blue instead of using the contact color like "conversation settings". Would also be nice to have a smooth animation like when showing "conversation settings".

**Comment by wp9015362** [comment] 2015-07-12 13:12
More or less a duplicate of:

https://github.com/WhisperSystems/TextSecure/issues/3521

Regards

**Comment by agrajaghh** [comment] 2015-07-12 14:06
doesn't look like #3521 

but I got a PR open to fix it: #3580

**Closed** 2016-10-05 17:28 UTC
Labels: ux
