### ISSUE TITLE
Recording a voice message doesn't prevent the screen from turning black

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6128] opened 2017-01-31 14:55 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I was recording myself singing a song so that I could send it to my friend, but the screen decided to turn itself off after 45 seconds or so.
### Steps to reproduce
1. Open a chat
2. Hold your finger on the voice message button
3. Wait
4. Profit!

**Actual result:** The screen turns itself off
**Expected result:** The screen should not turn itself off if you take too long

### Device info
Moto G4
Latest Signal
Android 6.0.1

**Comment by FeuRenard** [comment] 2017-02-19 11:07
I just noticed that this issue is a duplicate of #4646.

**Closed** 2017-02-19 11:39 UTC
Labels: ux
