### ISSUE TITLE
Remote Deletion of my sent messages on other chat partners devices AKA kill switch for messages

### ISSUE THREAD

**Issue by ND4SPEED** [WhisperSystems/Signal-Android#5547] opened 2016-06-21 22:48 UTC
Feature suggestion:
Remote Deletion of my sent messages on other chat partners devices AKA kill switch for messages, that I wrote.

Current Situation: Android: can limit to e.g. 50 messages, older messages get deleted automatically. (need to define this for all chat partners individually)

Feature Suggestion
Variant A) I can set the "Remote limit of my messages" to automatically cut off after 50 messages in MY chat with the other chat partner on THEIR devices. (kill older messages, than 50)
Variant B) Remote Delete my sent messages on other chat partners devices (kill my messages)

Reason: 
I want to keep control of my messages, of my lines that I sent, after I sent them.

**Comment by nrizzio** [comment] 2016-06-21 23:28
http://support.whispersystems.org/hc/en-us/articles/213134237
If that functionality is implemented, I could just remove it and install the patched app on my phone.

**Comment by 2-4601** [comment] 2016-06-22 00:22
plus duplicate of #1764, #4517

Next time please read and use the issue template.

**Closed by 2-4601** 2016-06-22 00:22 UTC
