### ISSUE TITLE
[feature] Add the ability to retract messages

### ISSUE THREAD

**Issue by barhom** [WhisperSystems/Signal-Android#5451] opened 2016-04-19 08:08 UTC
Hi,

I'd like to start a discussion regarding adding the ability for Signal to retract messages sent.

I propose that a user who sends messages retains the ability to delete a message that will also be deleted on the message recipients devices.

Both parties should see that the message was retracted but not the content anymore.

**Comment by 2-4601** [comment] 2016-04-19 09:21
Duplicate of #1764.
Please use the issue template when opening new issues.

> I'd like to start a discussion

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum

**Closed by 2-4601** 2016-04-19 09:21 UTC
