### ISSUE TITLE
Messages to some non-signal iPhone users say message was not delivered

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5895] opened 2016-11-28 04:07 UTC
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send some of my non-signal contacts messages, they are reported as "not delivered" with the "tap for details" message shows for each message, which when tapped, allows me to resend. Since these people respond to all of my messages, I know they are actually being delivered, and hitting the "resend" button gives them a duplicate message.  Happening since at least September 8th.

**Update: It's for _every_ message to the contacts that have issues.

### Device info

**Device:** Samsung Galaxy S7,  Note 5
**Android version:** 6.0.1, November security release, stock Verizon rom
**Signal version:** 3.23. 0

### Link to debug log

https://gist.github.com/c33552ae025923698f0ae1039840933e

**Comment by jeremymasters** [comment] 2016-12-04 03:47
https://gist.github.com/3375b5ac4377267f561d0304fee1c510

**Comment by Trolldemorted** [comment] 2016-12-04 09:11
so basically, every sms sent to an iphone user is reported as "failed to send"? Is this happening in groups or with direct messages goo?

**Comment by jeremymasters** [comment] 2016-12-04 15:02
Just both group and direct. It's making me crazy.

**Comment by jeremymasters** [comment] 2016-12-05 17:43
BTW, I'm happy to run test/debug builds as long as I can just upgrade to the next version when it comes out, etc.

**Comment by Trolldemorted** [comment] 2016-12-05 19:34
is the standard sms app working?

**Comment by jeremymasters** [comment] 2016-12-05 19:38
@Trolldemorted Signal is my default.  I have disabled the stock SMS app.

**Comment by Trolldemorted** [comment] 2016-12-05 19:42
well, could you try to use it at least one more time, and tell us if it works?

**Comment by jeremymasters** [comment] 2016-12-05 20:03
Just tried the default app and it receives a delivery report fine.

**Comment by jeremymasters** [comment] 2016-12-05 20:12
Switched back to signal and errors still https://gist.github.com/a34e4152bdef060508b4f5b5d0101833

**Comment by riyapenn** [comment] 2016-12-06 07:31
Closing as dupe of https://github.com/WhisperSystems/Signal-Android/issues/3728

Also related to: https://github.com/WhisperSystems/Signal-Android/issues/4020,  https://github.com/WhisperSystems/Signal-Android/issues/3014, https://github.com/WhisperSystems/Signal-Android/issues/3297

Are these iPhone users on Verizon?

Relevant: 
```
12-03 20:27:16.641 12499 12536 W SmsSentJob: Got SMS callback: org.thoughtcrime.securesms.SendReceiveService.DELIVERED_SMS_ACTION , 131072
12-03 20:27:16.641 12499 12536 W MessageDatabase: Updating ID: 24135 to status: 131072
```

Current work around is to disable delivery receipts of your messages: Go to Signal > Menu > Settings > SMS and MMS > and Disable SMS delivery receipts

**Closed by riyapenn** 2016-12-06 07:31 UTC
Labels: bug

**Comment by jeremymasters** [comment] 2016-12-06 16:17
@riyapenn I never had the issue with one contact with an iPhone on Verizon.  I suppose just on those off of Verizon?
