### ISSUE TITLE
Constantly crashing when trying to answer unknown group recovery request

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#5919] opened 2016-12-03 09:06 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
@moxie0 I was testing #5876. The device that is trying to answer the request for unknown group details is constantly crashing on startup.

### Steps to reproduce
- Devices A and B in a group
- A running current beta 3.24.0, B still on 3.23.0
- Re-install on device B
- sent group message from device A to B
- B receives message in unknown group
- update device B to Signal 3.24.0
- sent another message from A to B

**Actual result:** Device A is crashing on startup since then
**Expected result:** Device A should answer B's request and not crash

### Device info
**Device A:** Nexus 5
**Android version:** Stock Android 5.1.1
**Signal version:** see above

### Link to debug log
I can only send a Google Feedback report after the crash.
I get this in Android Studio:
```
W/JobConsumer: java.lang.NullPointerException: Attempt to get length of null array
  at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
  at org.thoughtcrime.securesms.jobs.PushGroupUpdateJob.onRun(PushGroupUpdateJob.java:68)
  at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
  at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Apparently `PushGroupUpdateJob` is trying to attach a group avatar. The group did not have a custom avatar set.

_I'm really hoping for a quick fix in the beta channel. Thanks!_

**Comment by Trolldemorted** [comment] 2016-12-03 20:58
can confirm and reproduce.

If a group info request for a group without avatar is received, signal crashes and keeps crashing on startup.

**Comment by Trolldemorted** [comment] 2016-12-03 21:41
fixed by #5921.

**Comment by neurotensin** [comment] 2016-12-04 19:26
Hi,

Here is my crash log, though I'm not sure if it is related. It has been constantly crashing since nougat update. There's a new nougat update coming in a few days so maybe it will change again...

https://gist.github.com/anonymous/2c4e04d9583b6f8f1721c2adf93d7c24

**Comment by Trolldemorted** [comment] 2016-12-04 21:55
Defenitely not related to this issue.

If this is happening exactly since the nougat update, i guess it messed up some of signal's files. Nevertheless you should open a seperate issue for that.

**Closed** 2016-12-05 02:07 UTC
Labels: bug, crash
