### ISSUE TITLE
Missing possibility to manually insert the SMS registration code 

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6490] opened 2017-04-04 12:04 UTC
There are situations where the device where Signal is installed can't directly receive SMS messages, but the users can receive the message on another device/service. Some devices do not have a sim card slot but the users owns another phone that can receive messages. Other users want to register with a phone number bought from a service like Twilio. In these cases it is difficult to register with the current procedure.

I propose this kind of solution:
- After the 2 minutes SMS timeout, a screen is shown to the user, asking to manually enter the code receives via SMS. The screen also have a clear button that says "I didn't receive any sms", or something like that.
- If the user taps on "I didn't receive the SMS", the current voice verification screen is shown.

The vast majority of the users will never see this screen. I think there are more users which can receive messages on a different device than users that try to register, expect to receive the message, but then something does not work.

**Comment by FeuRenard** [comment] 2017-04-04 12:50
This is a duplicate of #6029.

**Comment by McLoo** [comment] 2017-04-05 07:10
@vvug thanks for the input, but this is indeed a duplicate. closing.

**Closed by McLoo** 2017-04-05 07:10 UTC

**Comment by fortran77** [comment] 2017-04-05 11:15
I don't think this is strictly a duplicate of #6029.

#6029, which I filed, asks for an opportunity to manually enter the SMS code received on device A if it is not autodetected on device A, instead of proceeding with voice verification on the same device A.

#6490 (this one), if I understand it correctly, asks for an opportunity to receive an SMS code on device B, then enter that code into device A to register Signal on device A.

To make this more clear:

- Suppose device A can run Signal but can't receive PSTN calls or SMS messages.
- Suppose device B can't run Signal but can receive SMS messages.
- User installs Signal on A, specifies the number for device B.
- Incoming SMS code arrives on device B.
- User enters that code into device A to register Signal.
- Device A is now running Signal.

I do see partial duplication with #614, #1153, #5041, and numerous others, where people are asking for SIM-less devices to be supported, but I also see multi-device support mentioned there, which is not what is being requested here.
