### ISSUE TITLE
Add delivery date/time for outgoing SMS/Signal messages info

### ISSUE THREAD

**Issue by scienmind** [WhisperSystems/Signal-Android#4814] opened 2015-12-05 16:39 UTC
Feature proposal:
Add delivery date/time for outgoing SMS/Signal messages in "message details".

In a similar way that we can see when the incoming message was both sent and delivered in the "message details" dialog, add this functionality to the outgoing messages. Right now, only "sent" date/time is shown there.

Regarding privacy implications - this will not change anything there, no extra info is required from the recipient to provide. Just present the already non-secret "second checkmark's timestamp" in a more convenient way to the user (via "message details" dialog).

Just as the "second checkmark" itself, the usability of this if obvious, especially if a contact in a bad reception area and you don't get the "second checkmark" right away.

For SMS, this functionality is provided by most SMS apps if "delivery receipts" are enabled. So in a way, using Signal as SMS client in current form reduces this sms functionality (so for SMS case it might as well be considered as a bug).

**Comment by FeuRenard** [comment] 2015-12-05 16:47
This is a duplicate of #1692 and #2055 .

**Comment by scienmind** [comment] 2015-12-05 16:49
Thanks, somehow i didn't find those. I think I'll close this one then.

**Closed** 2015-12-05 16:50 UTC
