### ISSUE TITLE
Seemingly random crashes since last update

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6057] opened 2017-01-16 15:09 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal sometimes crashes when I open the app itself, or when I open a conversation.

It started when I sat in school, about to die from boredom. A Signal contact sent me a picture of a bird with a message like "Wow this bird is fat". I originally saw this in the preview on the Signal "homepage", so I clicked the chat to show the picture and... Crash!

After this I've had 1 more crash after opening Signal, so I think it's something with the picture.

### Steps to reproduce
I have no clue really, but if I had to guess I would guess something like
1. Receive a picture
2. Open Signal
3. Click the conversation before the picture has fully loaded
4. Crash Bandicoot makes his entrance!

**Actual result:** It crashes
**Expected result:** It shouldn't crash

### Device info
Device  : motorola Moto G (4) (athene)
Android : 6.0.1 (64, MPJ24.139-63)
Memory  : 43M (32.03% free, 192M max)
Memclass: 192
OS Host : ilclbld87
App     : Signal 3.27.0

### Link to debug log
https://gist.github.com/anonymous/0e05640f6a27c58c11e53cfaa734c4b2
https://gist.github.com/anonymous/10bc16289a8bd8fc12905233ed7828ac

**Comment by 2-4601** [comment] 2017-01-16 15:57
```
E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8464
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
E AndroidRuntime: 	at android.app.NotificationManager.getActiveNotifications(NotificationManager.java:683)
E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.cancelOrphanedNotifications(MessageNotifier.java:146)
E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:271)
E AndroidRuntime: 	at org.thoughtcrime.securesms.notifications.MessageNotifier.updateNotification(MessageNotifier.java:172)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$25.doInBackground(ConversationActivity.java:1356)
E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationActivity$25.doInBackground(ConversationActivity.java:1350)
E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E AndroidRuntime: 	... 4 more
```

**Comment by moxie0** [comment] 2017-01-16 19:22
Hmm, this is the same as #6043. Looks like it's not as easy as disabling this behavior on old devices. I have no idea what's going on here, the crash is in the Android code.

**Comment by 2-4601** [comment] 2017-01-16 21:11
Closing as duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6043#issuecomment-272277308

**Closed by 2-4601** 2017-01-16 21:11 UTC
Labels: bug, crash
