### ISSUE TITLE
Google Play Store Romanian translation

### ISSUE THREAD

**Issue by 0xFFRO** [WhisperSystems/Signal-Android#5967] opened 2016-12-17 13:54 UTC
@moxie0 Could you update the play store description for Romanian language? Here is the text: https://gist.github.com/0xFFRO/10097b9b7437eaa5f1168b1c5cd214ae

**Comment by 2-4601** [comment] 2016-12-18 00:39
Thanks for the effort, this is basically a duplicate of #4754

**Closed by 2-4601** 2016-12-18 00:39 UTC
