### ISSUE TITLE
Not able to select group when forwarding picture

### ISSUE THREAD

**Issue by hennjo** [WhisperSystems/Signal-Android#7309] opened 2017-12-31 15:35 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Im trying to forward a picture fom a signal chat to a specific signal group. In the list where i choose the recipient there're no groups in the contacts. If I'm lucky and the group is in the recent list, i can forward it but otherwise i can only go into that group and insert a saved picture.

### Steps to reproduce
- long press picture in chat
- tap 3 dots in top right corner and tap forward
- take a look at the list shown and search for groups

**Actual result:** No groups are shown in the list of Persons (what makes sense, cause groups aren't persons) but the ones in the recent list at the top.
**Expected result:** Have a part of the list contain all signal groups or insert them into the persons list.

### Device info

**Device:** Oneplus 5
**Android version:** 7.1.2
**Signal version:** 4.14.10

**Comment by nrizzio** [comment] 2017-12-31 15:51
Duplicate of #7202.
Please check for duplicate issues before opening a new one.

**Comment by hennjo** [comment] 2017-12-31 16:41
I tried, but it didn't show up. thanks for the comment. I'll delete this post.

**Closed** 2017-12-31 16:42 UTC
