### ISSUE TITLE
Voice call volume very low

### ISSUE THREAD

**Issue by 7adietri** [WhisperSystems/Signal-Android#4801] opened 2015-12-04 11:03 UTC
On the Fairphone 1 (Signal 3.6.1) the voice call volume is very low, compared to the regular phone app. Even with the volume cranked all the way up, I need to be in a quiet environment to clearly hear the other party.

**Comment by mawed** [comment] 2015-12-04 11:43
duplicate of  #4733.

Please close this ticket here and provide your information there.

Thanks

**Closed** 2015-12-04 13:44 UTC
