### ISSUE TITLE
The Android share signal link links to only an ios download and isn't smarter. [ easy ish fix ]

### ISSUE THREAD

**Issue by chamunks** [WhisperSystems/Signal-Android#5050] opened 2016-01-10 03:24 UTC
I have convinced a shocking number of people in friends with to download and prefer signal. But the invite to use signal link doesn't detect the mobile os in use and auto magically redirect to the correct os download.

**Comment by neikei** [comment] 2016-01-11 10:23
Can't reproduce your issue. I use a Moto G with Android 5.1 and the link for the invitation does a redirect over whispersystems.org to the Signal app in the playstore.

**Comment by agrajaghh** [comment] 2016-01-11 11:54
@chamunks pls give some more info. On which device/OS/Version are you experiencing this problem?

**Comment by scienmind** [comment] 2016-01-11 13:07
I think what hement, is that the build in "invite" SMS message creates link to the Signal *on Android* application (which is, seemingly by design), no issue here.

The issue is that some non-signal friends may have iOS devices, and sending link to an android application for those is pointless.

So my guess is that @chamunks suggesting an option to select (or detect somehow) the OS version of the non signal contact and send the "invite" link with the appropriate platform link.

**Comment by chamunks** [comment] 2016-01-11 14:25
@scienmind +1

**Comment by agrajaghh** [comment] 2016-01-11 14:39
did you actually test this on a iOS device? afaik the link redirects to the iOS app on iOS and OS X...

**Comment by chamunks** [comment] 2016-01-11 16:05
That's fair I only had it reported by one friend. I've referred about 15 people to this app this last week and I haven't bothered to ask what devices they have. So only ones complained.  Maybe they were using a non standard device browser like Firefox

**Comment by agrajaghh** [comment] 2016-01-11 16:26
okay, I'll close this for now. If you find someone using iOS where the link redirects to the play store, please comment with browser + version (or preferably user agent string) and I'll reopen it :blush:

**Closed by agrajaghh** 2016-01-11 16:26 UTC
