### ISSUE TITLE
android crashing when attached audio file

### ISSUE THREAD

**Issue by grcninja** [WhisperSystems/Signal-Android#4396] opened 2015-11-05 18:54 UTC
Device  : Sony D6616 (D6616)
Android : 5.0.2 (4078982578, 23.1.C.0.399)
Memory  : 20M (0.14% used, 192M max)
Memclass: 178
OS Host : BuildHost
App     : Signal 3.1.1

--------- beginning of crash
E/AndroidRuntime( 7856): FATAL EXCEPTION: JobConsumer-4
E/AndroidRuntime( 7856): Process: org.thoughtcrime.securesms, PID: 7856
E/AndroidRuntime( 7856): java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.util.CharArrayBuffer org.apache.http.message.LineFormatter.formatRequestLine(org.apache.http.util.CharArrayBuffer, org.apache.http.RequestLine)' on a null object reference
E/AndroidRuntime( 7856): 	at org.apache.http.impl.io.DefaultHttpRequestWriter.writeHeadLine(DefaultHttpRequestWriter.java:66)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.io.AbstractMessageWriterHC4.write(AbstractMessageWriterHC4.java:109)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestHeader(DefaultBHttpClientConnection.java:141)
E/AndroidRuntime( 7856): 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:201)
E/AndroidRuntime( 7856): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:260)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
E/AndroidRuntime( 7856): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:185)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:93)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:86)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime( 7856): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 7856): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 7856): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
E/AndroidRuntime(13025): FATAL EXCEPTION: JobConsumer-1
E/AndroidRuntime(13025): Process: org.thoughtcrime.securesms, PID: 13025
E/AndroidRuntime(13025): java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.util.CharArrayBuffer org.apache.http.message.LineFormatter.formatRequestLine(org.apache.http.util.CharArrayBuffer, org.apache.http.RequestLine)' on a null object reference
E/AndroidRuntime(13025): 	at org.apache.http.impl.io.DefaultHttpRequestWriter.writeHeadLine(DefaultHttpRequestWriter.java:66)
E/AndroidRuntime(13025): 	at org.apache.http.impl.io.AbstractMessageWriterHC4.write(AbstractMessageWriterHC4.java:109)
E/AndroidRuntime(13025): 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestHeader(DefaultBHttpClientConnection.java:141)
E/AndroidRuntime(13025): 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:201)
E/AndroidRuntime(13025): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
E/AndroidRuntime(13025): 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:260)
E/AndroidRuntime(13025): 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
E/AndroidRuntime(13025): 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
E/AndroidRuntime(13025): 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
E/AndroidRuntime(13025): 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
E/AndroidRuntime(13025): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
E/AndroidRuntime(13025): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:185)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:93)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:86)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime(13025): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime(13025): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime(13025): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
E/AndroidRuntime(21384): FATAL EXCEPTION: JobConsumer-2
E/AndroidRuntime(21384): Process: org.thoughtcrime.securesms, PID: 21384
E/AndroidRuntime(21384): java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.util.CharArrayBuffer org.apache.http.message.LineFormatter.formatRequestLine(org.apache.http.util.CharArrayBuffer, org.apache.http.RequestLine)' on a null object reference
E/AndroidRuntime(21384): 	at org.apache.http.impl.io.DefaultHttpRequestWriter.writeHeadLine(DefaultHttpRequestWriter.java:66)
E/AndroidRuntime(21384): 	at org.apache.http.impl.io.AbstractMessageWriterHC4.write(AbstractMessageWriterHC4.java:109)
E/AndroidRuntime(21384): 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestHeader(DefaultBHttpClientConnection.java:141)
E/AndroidRuntime(21384): 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:201)
E/AndroidRuntime(21384): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
E/AndroidRuntime(21384): 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:260)
E/AndroidRuntime(21384): 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
E/AndroidRuntime(21384): 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
E/AndroidRuntime(21384): 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
E/AndroidRuntime(21384): 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
E/AndroidRuntime(21384): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
E/AndroidRuntime(21384): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:185)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:93)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:86)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime(21384): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime(21384): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime(21384): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
--------- beginning of system
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.sonymobile.settings.illumination.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.sonymobile.settings.illumination.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
E/AndroidRuntime(23018): FATAL EXCEPTION: JobConsumer-2
E/AndroidRuntime(23018): Process: org.thoughtcrime.securesms, PID: 23018
E/AndroidRuntime(23018): java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.util.CharArrayBuffer org.apache.http.message.LineFormatter.formatRequestLine(org.apache.http.util.CharArrayBuffer, org.apache.http.RequestLine)' on a null object reference
E/AndroidRuntime(23018): 	at org.apache.http.impl.io.DefaultHttpRequestWriter.writeHeadLine(DefaultHttpRequestWriter.java:66)
E/AndroidRuntime(23018): 	at org.apache.http.impl.io.AbstractMessageWriterHC4.write(AbstractMessageWriterHC4.java:109)
E/AndroidRuntime(23018): 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestHeader(DefaultBHttpClientConnection.java:141)
E/AndroidRuntime(23018): 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:201)
E/AndroidRuntime(23018): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
E/AndroidRuntime(23018): 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:260)
E/AndroidRuntime(23018): 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
E/AndroidRuntime(23018): 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
E/AndroidRuntime(23018): 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
E/AndroidRuntime(23018): 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
E/AndroidRuntime(23018): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
E/AndroidRuntime(23018): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:185)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:93)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:86)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime(23018): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime(23018): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime(23018): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.sonymobile.settings.illumination.jar' does not exist or contains no resources.
W/ResourcesManager(23018): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/ResourcesManager( 5581): Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
W/ResourcesManager( 5581): Asset path '/system/framework/com.sonymobile.settings.illumination.jar' does not exist or contains no resources.
W/ResourcesManager( 5581): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
E/AndroidRuntime( 5581): FATAL EXCEPTION: JobConsumer-1
E/AndroidRuntime( 5581): Process: org.thoughtcrime.securesms, PID: 5581
E/AndroidRuntime( 5581): java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.util.CharArrayBuffer org.apache.http.message.LineFormatter.formatRequestLine(org.apache.http.util.CharArrayBuffer, org.apache.http.RequestLine)' on a null object reference
E/AndroidRuntime( 5581): 	at org.apache.http.impl.io.DefaultHttpRequestWriter.writeHeadLine(DefaultHttpRequestWriter.java:66)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.io.AbstractMessageWriterHC4.write(AbstractMessageWriterHC4.java:109)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestHeader(DefaultBHttpClientConnection.java:141)
E/AndroidRuntime( 5581): 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:201)
E/AndroidRuntime( 5581): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:260)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
E/AndroidRuntime( 5581): 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:185)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.sendBytes(OutgoingLegacyMmsConnection.java:135)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:118)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:93)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:86)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
E/AndroidRuntime( 5581): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 5581): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 5581): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
--------- beginning of main
W/ExperienceUpgradeActivity( 6010): getExperienceUpgrade(157)
W/PassphraseRequiredActionBarActivity( 6010): routeApplicationState(), state: 2
I/Timeline( 6010): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:30948472
D/OpenGLRenderer( 6010): Render dirty regions requested: true
D/Atlas   ( 6010): Validating map...
I/Adreno-EGL( 6010): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL( 6010): OpenGL ES Shader Compiler Version: E031.25.03.00
I/Adreno-EGL( 6010): Build Date: 03/10/15 Tue
I/Adreno-EGL( 6010): Local Branch: au018
I/Adreno-EGL( 6010): Remote Branch: 
I/Adreno-EGL( 6010): Local Patches: 
I/Adreno-EGL( 6010): Reconstruct Branch: 
I/OpenGLRenderer( 6010): Initialized EGL, version 1.4
D/OpenGLRenderer( 6010): Enabling debug mode 0
I/Timeline( 6010): Timeline: Activity_idle id: android.os.BinderProxy@3b6249a5 time:30948962
W/art     ( 6010): Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
I/Timeline( 6010): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:30953527

**Comment by moxie0** [comment] 2015-11-05 19:15
Thanks this is a duplicate of #4379.  Same issue, there's something weird with the Apache HTTP implementation on your ROM.

**Closed by moxie0** 2015-11-05 19:15 UTC
