### ISSUE TITLE
MMS messages are recieved multiple times

### ISSUE THREAD

**Issue by codeofcarson** [WhisperSystems/Signal-Android#7272] opened 2017-12-13 17:06 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I often receive MMS messages multiple times. It is not clear why I receive multiple copies of the message but the most recent occurrence was when I went out of country and was roaming. The messages themselves are identical with no problems in transmission, download or display. This has happened with multiple messages which are re-received n+1 times. These re-receptions do not seem to occur in a regular manner with some of them coming in days or even weeks later.

May be related to #1436

### Steps to reproduce
- Have someone send you an MMS message (preferably while roaming or experiencing network problems)
- Wait

**Actual result:** Receive multiple copies of the MMS message
**Expected result:** Receive only one copy of the MMS message

### Screenshots
https://drive.google.com/open?id=1xYLEvyCUwSgbtNh_sUT3gbELEwWjfg7S
https://drive.google.com/open?id=12ZDQnsTawsEV1SA8WQaVMapWTZlsA--J

### Device info

**Device:** Google Pixel 2 (Bell Canada version)
**Android version:** 8.0.0
**Signal version:** 4.13.6

### Link to debug log
https://gist.github.com/ea8351730a42f9d19c8bbc4f0bdf04d1

**Comment by riyapenn** [comment] 2017-12-14 23:50
This issue looks like a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/5396#issuecomment-328136082

**Comment by codeofcarson** [comment] 2017-12-15 05:34
Sorry about that, should I close it then? I did try looking but that issue is not tagged with MMS

**Comment by Dyras** [comment] 2017-12-19 14:01
@codeofcarson Yup you should close it and post your debug log in the issue riyapenn linked instead

**Closed** 2017-12-19 15:46 UTC
