### ISSUE TITLE
Disappearing & Reappearing draft

### ISSUE THREAD

**Issue by osteoboon** [WhisperSystems/Signal-Android#6333] opened 2017-03-06 22:35 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This issue is not about the feature called "Disappearing Messages". It's about a draft that I composed, left in the draft compose box and that, when I made a Signal voice call, disappeared from the draft compose box. Strangely, when I left the app and then re-entered the app, the missing draft re-appeared.

### Steps to reproduce
- compose a draft
- make a Signal voice call to the message draft recipient
- check that the draft disappeared
- leave Signal, returning execution to the Android OS
- re-enter Signal, see that the draft returned.

**Actual result:** described above

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- compose a draft
- make a Signal voice call to the message draft recipient
- check that the draft did not disappear from the draft compose box

### Device info

**Device:**OnePlus A0001 (bacon)
**Android version:** 6.0.1
**Signal version:** 3.30.4

### Link to debug log
App did not crash, so no debug log included

**Comment by p4nci** [comment] 2017-03-07 09:12
imo: duplicate of https://github.com/WhisperSystems/Signal-Android/issues/4729

**Closed** 2017-03-13 18:16 UTC
