### ISSUE TITLE
Checkmark With Number Not Showing Sometimes

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7259] opened 2017-12-09 13:41 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes when i open conversation checkmark show with number but when i go back and again open conversation it doesn't show checkmark. Sometimes show and sometimes not.

### Steps to reproduce
- In conversation list
- when open conversation
- sometimes it doesn't show checkmark

**Actual result:** Check show sometimes but when i go back to conversation list and again open conversation it doesn't show checkmark
**Expected result:** Always show checkmark with number when verified option is on.

### Device info
**Device:** Huawei Mate 10 lite
**Android version:** 7.0
**Signal version:** 4.14.4

### Link to debug log
Also i can't get debug info i don't know why but it only shows device info like model signal version etc.

**Comment by FeuRenard** [comment] 2017-12-09 15:09
This is a duplicate of #7165.

**Comment by FaizKhan5** [comment] 2017-12-09 23:36
But its a serious issue and i think fix it ASAP.

**Comment by moxie0** [comment] 2017-12-10 00:20
@FaizKhan5 Please read the contributing guidelines before posting here again. You've intentionally opened many duplicate issues in the past, which only makes development go more slowly. Please be respectful of everyone here's time.

**Closed by moxie0** 2017-12-10 00:20 UTC
