### ISSUE TITLE
Swiping between media items in conversation

### ISSUE THREAD

**Issue by s0riak** [WhisperSystems/Signal-Android#6330] opened 2017-03-04 08:42 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
When opening a media item (image, video) in "full" screen from a conversation or the media overview it is currently not possible to swipe to the previous or next media item. It would speed up opening several images in sequence if swiping to the previous and next media item would be supported.

### Steps to reproduce
- Open a media item in "full"-screen from a conversation or media overview
- Swipe from right to left/left to right

**Actual result:** Nothing happens
**Expected result:** If swiped from right to left, the next media item in the conversation is displayed. If swiped from left to right, the previous media item is displayed

### Screenshots
n.a.

### Device info
**Device:** BQ Aquaris M5
**Android version:** 6.0.1
**Signal version:** 3.30.4

### Link to debug log
n.a.

**Comment by FeuRenard** [comment] 2017-03-04 10:42
Duplicate of #2355

**Closed** 2017-03-04 18:38 UTC
