### ISSUE TITLE
Have a username in order not to disclose phone number

### ISSUE THREAD

**Issue by nammamir** [WhisperSystems/Signal-Android#5315] opened 2016-03-04 21:23 UTC
Today, I wanted to put in touch two people who didn't want to disclose their names. Both have WhatsApp, Telegram and Viber accounts, therefore, it was impossible to share their phone numbers because as soon as they saved phone numbers they could find some data about the other one.

So, How can I set a username for account? I think there is no option for it. if I'm right, is there any plan for it?

I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Steps to reproduce
- add your steps here
- as a list
- using hyphens

### Device info

 **Model:** Manufacturer Model XVI

 **Android version:** 0.0.0

 **Signal version:** 0.0.0

**Comment by nrizzio** [comment] 2016-03-04 21:27
Duplicate of #1085. Please use the search function and complete the checklist before opening issues.

**Closed** 2016-03-04 21:28 UTC
