### ISSUE TITLE
Show active conversation

### ISSUE THREAD

**Issue by luddhelm** [WhisperSystems/Signal-Android#7083] opened 2017-10-11 20:16 UTC
I have:
- [x] searched open and closed issues for duplicates (though I'm not really sure on what to search for)
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When starting the app (touching the Signal icon on the home screen) I get to list of all conversations. In all other messaging applications I get to the last conversation I was active in. 

### Steps to reproduce
- Send a message to a contact and keep the conversation open
- Go back to home screen
- Press the Signal app icon on the home screen

**Actual result:** Get to the main list of conversations in Signal
**Expected result:** Get back to the conversation I had open. 

### Device info
**Device:** Sony XZ1 Compact
**Android version:** 8.0.0
**Signal version:** 4.10.12

**Comment by FeuRenard** [comment] 2017-10-11 20:54
This is a duplicate of #1311.

**Closed** 2017-10-11 23:06 UTC
