### ISSUE TITLE
Android 6.0.1 Nexus 6P - can't make voice calls

### ISSUE THREAD

**Issue by wwwiretap** [WhisperSystems/Signal-Android#4921] opened 2015-12-19 01:12 UTC
Just installed Signal from the Google Play Store on a brand new Nexus 6P, running Android 6.0.1 and when I try to make a call from inside the app, by clicking the Phone Icon, i am taken to the phone's own dial prompt and a GSM call gets initiated.

I am able to receive calls but can't make outgoing calls in Signal.

**Comment by 2-4601** [comment] 2015-12-19 01:20
Hi,
Your Signal contact list is not up to date, see how to update it:
http://support.whispersystems.org/hc/en-us/articles/213132447-Who-can-I-call-
Closing as duplicate of #4355

**Closed by 2-4601** 2015-12-19 01:20 UTC
