### ISSUE TITLE
Feature Request: Ability to search conversation history

### ISSUE THREAD

**Issue by deper29** [WhisperSystems/Signal-Android#6287] opened 2017-02-22 18:22 UTC
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Description
Add search functionality to be able to search for keywords in a conversation . Telegram and Slack both have this and it is much easier than scrolling back through months worth of a conversation.

**Comment by FeuRenard** [comment] 2017-02-22 18:40
This is a duplicate of #1232.

**Closed** 2017-02-22 19:42 UTC
