### ISSUE TITLE
Prevent the screen from going dark while recording a voice note

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-Android#4646] opened 2015-11-21 12:13 UTC
My screen turns off after a very short time of inactivity (a few seconds). This causes the screen to turn off while I'm recording voice notes -- assuming I keep the finger very still, which I do to avoid cancelling the note by accident.

**Comment by mcginty** [comment] 2015-11-21 23:54
almost a dupe of #4424 but this is for recording instead of playback

**Closed** 2017-03-06 22:11 UTC
Labels: ux
