### ISSUE TITLE
Invalid contact "-1" in contact list when forwarding message

### ISSUE THREAD

**Issue by Lesik** [WhisperSystems/Signal-Android#7108] opened 2017-10-17 12:39 UTC
When forwarding a message to another contract, the contract choser shows a "-1" at the bottom of the contract list, even though I have no such telephone number saved in my contracts.

When clicking on that entry and thus forwarding a message to that contact, sending fails. Also, the next time trying to forward a message, the "-1" is present __twice__ in the list, once because it is now part of the chat list (due to that unsent forwarded message), and once again at the very bottom of the list.

**Comment by FeuRenard** [comment] 2017-10-17 15:18
This is a duplicate of #6304.

**Comment by Lesik** [comment] 2017-10-18 11:37
Related, but since my entry says "-1", no "Anonymous", I'd keep this open.

Also, according to my bug report, the "-1" is present twice. None of the other bug reports mention this.

**Comment by FeuRenard** [comment] 2017-10-18 12:00
The last two comments in #6304 describe the "-1" issue. Seems very similar to your issue. So until we know more details, e.g. how to reproduce, one issue should be sufficient.

**Comment by Lesik** [comment] 2017-10-18 12:13
@FeuRenard That simply means that the comments on #6304 are just as unrelated to the #6304 OP, as my issue is.

**Comment by FeuRenard** [comment] 2017-10-18 12:56
https://github.com/WhisperSystems/Signal-Android/issues/6304#issuecomment-321681584 says that after a Signal version update he sees the "-1" contact instead of "Anonymous". So the "Anonymous" issue apparently became the "-1" issue. The title doesn't reflect this development but the comment thread does.

Personally I also saw "Anonymous" in the past and now there is "-1" at the bottom of the share list.

I still recommend to close this issue in favor of #6304. But you could add there that you were able to produce a second "-1" entry. This could be very helpful information for investigating this issue.

**Closed** 2017-10-18 17:11 UTC

**Comment by Lesik** [comment] 2017-10-18 17:17
@FeuRenard Ah, I was confused by what "canonical address database" was supposed to mean. You are right, thanks for clarifying.
