### ISSUE TITLE
Compatibility with Nougat

### ISSUE THREAD

**Issue by themightyoarfish** [WhisperSystems/Signal-Android#5758] opened 2016-10-08 09:42 UTC
The app cannot be installed on a Pixel C tablet with Android 7.0.

**Comment by 2-4601** [comment] 2016-10-08 09:54
The Play Store release does not install on tablets.

Duplicate of #614

> At this time [Signal] still uses a phone number for ID so it is required that the target Android device have telephony capabilities.

**Closed by 2-4601** 2016-10-08 09:54 UTC
