### ISSUE TITLE
Message reports Failed to send for all group members, but is received by all group members

### ISSUE THREAD

**Issue by lazlolazlolazlo** [WhisperSystems/Signal-Android#5891] opened 2016-11-26 12:49 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When sending messages in a group chat sometimes the messages reports Failed to send for all the group members. But they are received correctly by everyone. Other users in the group are experiencing the same issue sometimes and then start hitting the resend button. And then #2639 will spam the group with the same messages.

### Steps to reproduce
- send message in group chat

**Actual result:** message reports Failed to send for all group members
**Expected result:** message should report received by all group members

### Device info

**Device:** motorola XT1021
**Android version:** 4.4.4
**Signal version:** 3.23.0

### Link to debug log
https://gist.github.com/71d04edaca4110cbf470c53fbfb12fd4

**Comment by moxie0** [comment] 2016-11-26 22:33
Looks like you're getting rate limited on requesting a prekey for whoever's number ends in 71. That shouldn't happen in normal circumstances, did that person uninstall and reinstall a bunch of times in a row?

**Comment by lazlolazlolazlo** [comment] 2016-11-27 16:46
I just noticed that this person switched phone numbers and the old phone number did not leave the group. Signal Desktop throws a Number not registered error on every message.

**Comment by moxie0** [comment] 2016-11-28 01:19
ah makes sense. i think there's an issue for that somewhere? i think the best we can do is reporting "so and so left the group" when a client gets that... even though that means clients are out of sync regarding membership until they all try sending

**Comment by 2-4601** [comment] 2016-11-28 01:30
At least the error got handled in Signal Android in a more user friendly way in #5318.

**Comment by JohnnyMT** [comment] 2016-12-08 06:06
Same Issue over here, except that it also happens with a good network connection and that resending will start an endless amount of messages to all group members. It will send the message over and over by itself until I switch to flight mode. 
There is also a obsolete number in the group which can't be unregistered, because the person got a new number.

**Comment by jessebett** [comment] 2016-12-14 03:26
I think this issue just happened in my group chat. Another user got a 'message did not send' error for 2 messages, she tried to resend, and both messages each appeared 4 times in the chat. I don't know if this is a coincidence but there are also 4 other members in the chat. Could the resend message be trying to send the message once for every member?

**Comment by mathewcrane** [comment] 2016-12-15 20:35
@jessebett this has happened to two members of one of my group chats. Both happened when they had weak signal, received a failed message error, and hit resend. It sent the message n*(number of members in group chat) for each failed message.

**Comment by 2-4601** [comment] 2016-12-15 20:58
@jessebett @mathewcrane What you are describing is #2639. This is about an unregistered group member causing issues which in the end resulted the same scenario as in #2639.

**Comment by lazlolazlolazlo** [comment] 2017-01-02 08:57
Reporting "so and so left the group" should be a good solution! But how to get rid of someone in the group who is not registered to Signal any more? I now have a very large group which becomes unusable after a couple of messages because of this bug. Only solution I can think of is creating a completely new group?

**Comment by JohnnyMT** [comment] 2017-01-02 11:44
I've had the issue several times last night and this morning, so I can provide a fresh debug log:
https://gist.github.com/cbd9a9cde51fac8609e4aee0d081918e

I took a quik look over it but found only two errors: 
 - PhoneNumberFormatter: Error type: TOO_LONG. The string supplied is too long to be a phone number.
 - Read error: ssl=0xd3329840: I/O error during system call, Connection timed out

Hope this helps somehow

**Comment by Trolldemorted** [comment] 2017-01-28 22:30
can we close this as a duplicate of #6003?

**Comment by JohnnyMT** [comment] 2017-01-29 17:35
If I got #6003 correctly, it will happen only with a bad connection. This error also appears with a good connection.

**Comment by Trolldemorted** [comment] 2017-01-29 20:21
Well, the solution to this issue is discussed there, and the PR fixing this is referencing #6003, and not this ¯\\_(ツ)_/¯

If 6003 is about bad connections, it is a duplicate of #2639.

**Comment by 2-4601** [comment] 2017-01-30 01:11
Closing in favor of #6003.

**Closed by 2-4601** 2017-01-30 01:11 UTC
Labels: bug
