### ISSUE TITLE
[Minor UX] Dark theme improvements

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#3281] opened 2015-05-29 22:04 UTC
Two dark theme items:
1. The TS message send arrow/airplane is lighter color blue than the the text bubbles.  I noted there are other dark theme blue icons so this might be nice to have here.
2. The background of the top bar where the "TextSecure" and the search magnifying glass and options dots are in the list of conversations has no color at all.  I think it'd be a nice touch to have a blue background for that bar like the light theme does but using the darker blue.

**Comment by agrajaghh** [comment] 2015-05-30 14:51
have a look at the mailing list for the second point

**Comment by jeremymasters** [comment] 2015-05-31 05:53
@agrajaghh looks like we were thinking similarly! I like the dark blues best, fwiw

**Comment by voidzero** [comment] 2015-06-12 10:13
Can I add to this? The smiley menu, or emotes w/e had a black background that turned white all of a sudden. With the black theme!

Also it seems like some emotes were changed but I suppose this is a different subject. We need more preferences! 🙋

**Comment by agrajaghh** [comment] 2015-06-12 10:15
@voidzero background will be dark again (for the dark theme) in the next release. see https://github.com/WhisperSystems/TextSecure/commit/ae4f6b1dd4af6b8dce07d6dfe4024ed95f738511

we don't need more preferences...

**Comment by voidzero** [comment] 2015-06-12 11:08
@agrajaghh hehe alright, the comment about prefs was to say that some users prefer one, others the other. But I meant it jokingly; I was listening to Rage Against the Machine and guess that their sentiment seeped through, hence the emote. Glad to hear the background will be dark again, that's what I prefer! And thank you for pointing me to the relevant commit. :smile:

**Comment by FeuRenard** [comment] 2016-04-14 22:51
1. is outdated as the text bubble color can now be customized and the color inconsistency is barely noticable (is it even there?). If this is still a thing, the issue title should be more precise.
2. is duplicate of #2397

**Closed** 2016-04-14 23:14 UTC
Labels: ux
