### ISSUE TITLE
OOM - Crash while sending picture

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#3094] opened 2015-05-01 10:24 UTC
I was sending a picture when textsecure crashed. The sending also failed by the way.
Log https://gist.github.com/anonymous/74de533cc8d30b66e7d4

**Comment by moxie0** [comment] 2015-05-01 14:40
This looks like a duplicate of #3092

**Comment by peterpanondrugs** [comment] 2015-05-06 21:12
still the same ... 
https://gist.githubusercontent.com/anonymous/6723cd79ded93c219999/raw/cat.log

**Comment by mcginty** [comment] 2015-11-16 21:34
closing since this is old and Glide helped resolve most of these

**Closed by mcginty** 2015-11-16 21:34 UTC
Labels: bug, memory
