### ISSUE TITLE
Add longer muting periods

### ISSUE THREAD

**Issue by blinry** [WhisperSystems/Signal-Android#4448] opened 2015-11-08 11:06 UTC
I have friends who always want to mute certain groups. Currently, it's only possible to mute groups one week at a time, which can get really cumbersome. I'd be convenient for them to have the option to mute these groups for a really long time.

Is there any rationale not to extend the muting options with longer periods, like "1 year" or "forever" (9999 years)?

**Comment by Dyras** [comment] 2015-11-08 12:18
+99999999999999
Was just about to suggest this. I like to mute most of my conversations so that I don't have to listnen to the damn PING PING PING PING every five minutes. I suggest we add a century as an option. Will be fun and somewhat original.

**Comment by grandchild** [comment] 2015-11-08 12:51
@Dyras if you want to silence _most_ of your conversations forever, take the reverse approach: just silence Signal in the settings. You can then set the important conversations to vibrate, ring and so on.

That being said, I would also like "forever" as a mute option.

**Comment by Dyras** [comment] 2015-11-08 14:51
@grandchild Thanks for the tip, but I get a lot of "random" text messages, invitations and stuff, so I would very much prefer being able to permanently mute the trolls.

**Comment by blinry** [comment] 2015-11-08 16:39
Yep. And I cannot see how it could possibly hurt anyone to add an additional "century" option to the existing list. I could even whip up a PR for this if someone gives me an OK.

**Comment by 2-4601** [comment] 2015-11-08 17:58
Duplicate of #3407, #4414 (but don't know if the position has changed)

**Comment by Dyras** [comment] 2015-11-08 18:02
Personally I don't see the problem. I guess some people will be stupid enough to mute a chat without knowing how to unmute it, but can't you just show a message on top saying "This conversation is muted, click here to unmute" and that problem is out of the way.

**Comment by blinry** [comment] 2015-11-08 18:04
Thanks, @2-4601. Maybe @moxie0 can comment on this?

**Comment by moxie0** [comment] 2015-11-08 18:09
i'd be ok with 1 year now

On 11/08/2015 10:04 AM, Sebastian Morr wrote:
> Thanks, @2-4601 <https://github.com/2-4601>. Maybe @moxie0
> <https://github.com/moxie0> can comment on this?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/4448#issuecomment-154854234>.
> 

-- 
http://www.thoughtcrime.org

**Comment by blinry** [comment] 2015-11-10 18:26
Just for cross-reference: I created a PR which adds the "one year" option: https://github.com/WhisperSystems/Signal-Android/pull/4454

**Comment by 2-4601** [comment] 2015-11-11 01:13
Can be closed now.

**Closed** 2015-11-11 01:14 UTC
