### ISSUE TITLE
checkbox when adding contacts overlapped by scrolling click zone

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/Signal-Android#3333] opened 2015-06-03 22:33 UTC
tested on 82d7300fc0cfb0303c19a574b0e22f7003f8e9f3

1) create a TS group with person A
2) tap update group
3) tap the weird plus icon next to the add member edit text
4) try to check the box next to TS user person B
5) notice it ripples in a really cool way but also it's really difficult to check that box

guessing this came from bd2e984963fc4766ad3680e127b25ab8d9447fd9

**Comment by rhodey** [comment] 2015-06-03 22:35
actually it is really easy to check that box by clicking anywhere outside the actual check box, clicking inside the check box gives a cool double ripple but no check.

**Comment by 2-4601** [comment] 2015-06-03 23:12
I noticed the scroll overlap when trying to reproduce #3234 so that issue might be related.

**Comment by 2-4601** [comment] 2015-06-12 14:49
The overlap is not so bad anymore in 2.18.0 but it's still possible to accidentally trigger the fast scroll when you try to tap a checkbox.
Also the fast scroll works only once. After you have touched the screen the fast scroll seems to get disabled. Is this intended?
Nexus 4, 5.1.1

**Comment by mcginty** [comment] 2015-06-12 20:32
Fast scroll works more than once for me. I had it auto-hide but scrolling will bring it back.

**Comment by 2-4601** [comment] 2015-06-12 21:06
Strange. It does not come back for me. It's only useable at the beginning of the view.

I tested now in portrait mode and it is more broken there. I can see similar behavior to what @rhodey posted above. The ripple effect goes sometimes in slow motion and the checkbox does not get selected.
I also experienced what @sjaeckel described in #3234: different checkboxes get selected than the one I tapped. Perhaps it scrolls and selects and scrolls back at once?

N.B. all this seems to happen only if TS is the default SMS app. Which entails that you have TS users and non-TS users in the group participant selection list.

**Comment by mcginty** [comment] 2015-06-12 21:20
I'd like to move to recyclerview (possibly with https://github.com/danoz73/RecyclerViewFastScroller) since ListViews are awful like this.

**Comment by 2-4601** [comment] 2015-06-12 21:28
Nice. Well it seems to work reasonably well in portrait now so I guess people can live with it :)
I don't use TS as my default SMS app so I don't even get to see the weirdness. Only when especially looking for trouble :)

**Comment by riyapenn** [comment] 2015-10-21 22:15
Is this still an issue?

**Comment by 2-4601** [comment] 2015-10-21 22:30
Kinda.
1. Make Signal the default SMS app
2. Create a new group
3. Tap the plus sign to go to the add contacts list
4. Try to tick a box (or just scroll up and down near the right edge of your screen)

There is overlap with ticking (or regular scrolling) and the quick scroll.
Solution: remove the quick scroll altogether. That's how it is when Signal is not the default SMS app.

Signal 3.0.3, Nexus 4, stock 5.1.1

**Comment by mcginty** [comment] 2015-11-16 21:37
fixed by recent change to contact selection

**Closed by mcginty** 2015-11-16 21:37 UTC
Labels: bug, ux
