### ISSUE TITLE
Android calling error

### ISSUE THREAD

**Issue by ajay340** [WhisperSystems/Signal-Android#5128] opened 2016-01-26 02:19 UTC
Weird error where when I call someone it gives an error saying LOGIN FAILED!

**Comment by 2-4601** [comment] 2016-01-26 02:35
Sounds like a duplicate of #4183, #4358, #4563. Check out those issues and if the workarounds there don't help you can add your debug log to #4563.
(Immediately after failed a call go to Settings -> Advanced -> Submit debug log, and paste the link to #4563)

**Closed by 2-4601** 2016-01-26 02:35 UTC
