### ISSUE TITLE
Latest Signal about to expire

### ISSUE THREAD

**Issue by djdeath** [WhisperSystems/Signal-Android#5611] opened 2016-08-08 22:01 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal is showing a banner saying the app is outdated and will expire in 9 days.

### Steps to reproduce
Just open the application.

### Screenshots
This is a screenshot of the app list (somehow taking screenshots of the app wouldn't work, because not enough space which is not the case, that's pretty odd...)

![screenshot_20160808-224147](https://cloud.githubusercontent.com/assets/434333/17497455/d6bd0eea-5db9-11e6-95ae-482c736eceab.png)

### Device info
**Device:** Google Nexus 5x
**Android version:** 6.0.1
**Signal version:** 3.16.0

### Link to debug log
Sorry, no type C cable nearby, will update the issue asap.

**Comment by wsuff** [comment] 2016-08-08 22:04
Duplicate of #5609

**Closed** 2016-08-08 22:52 UTC
