### ISSUE TITLE
Opening conversation with new messages does not scroll to new messages.

### ISSUE THREAD

**Issue by sgowris2** [WhisperSystems/Signal-Android#7068] opened 2017-10-08 07:02 UTC
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Before the latest update (4.11.2), when new messages were available in a conversation, and the user opened the conversation, it would auto-scroll to the new messages. Now, it does not do that. Instead, it scrolls only to the latest read message and the user has to scroll down to see the new messages.

### Steps to reproduce
- Receive new message
- Open Signal
- Click on conversation with new message

**Actual result:** You will see the latest read message at the bottom of the screen and you will need to scroll down to see the new messages.
**Expected result:** New messages should be immediately visible on the screen.

### Device info

**Device:** OnePlus ONEPLUS A3003 (OnePlus3)
**Android version:** 7.1.1 (113, ONEPLUS A3003_16_170923)
**Signal version:** 4.11.2

### Link to debug log
https://gist.github.com/b521d80df562b901089b94acc421abc5

**Comment by FeuRenard** [comment] 2017-10-08 07:38
This is a duplicate of #7054.

**Closed** 2017-10-08 20:53 UTC
