### ISSUE TITLE
can not scan qr code to sync with desktop

### ISSUE THREAD

**Issue by wynkoop** [WhisperSystems/Signal-Android#5479] opened 2016-05-04 15:31 UTC
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
on Motorola Droid 3 signal's qr scanner will not focus and can not scan the qrcode produced by the signal desktop app.

Third party barcode scanner works correctly with that qr code on the same phone.

### Steps to reproduce
- install signal for chrome
- start signal for chrome
- click through get started and I have signal for android
- attempt to scan QR code produced by the computer

**Actual result:**  code never scans, image on screen is out of focus.

**Expected result:** Phone should scan the code and the install should proceed.

### Screenshots
None

### Device info

**Device:** Motorola Droid 3 - xt883
**Android version:** 2.3.4
**Signal version:** Current as of this writing....seems no place in signal to obtain this info

### Link to debug log

NONE

**Comment by 2-4601** [comment] 2016-05-04 15:41
Closing as duplicate of #4637.

**Closed by 2-4601** 2016-05-04 15:41 UTC
