### ISSUE TITLE
Signal doesn't add messages sent from Android Wear to history

### ISSUE THREAD

**Issue by NickGeek** [WhisperSystems/Signal-Android#5313] opened 2016-03-04 05:15 UTC
When you reply to a Signal message via Android Wear it appears on the phone conversation history, but not when you use "Okay Google, Text ..." to send a message.

Reported with a Nexus 5x on Android 6.0.1 with a Sony Smartwatch 3 running Android 5.1.1

**Comment by cascheberg** [comment] 2016-03-04 05:23
Duplicate of #218

**Closed** 2016-03-04 05:32 UTC
