### ISSUE TITLE
Unregistered contacts don't disappear in groups

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#5076] opened 2016-01-15 16:11 UTC
If a **user unregisteres** from Signal but did not leave a group, the **user will stay in this group** forever and you will get an error for every message you send to that group.

I suggest that the all **groups of a user should be automatically updated** when he unregisters.

There are many similar issues but not the same I think (#4550 , #2408 , https://github.com/WhisperSystems/Signal-Desktop/issues/448).

I fear that this might be an issue for the server because the clients shouldn't do this(?)

**Comment by agrajaghh** [comment] 2016-01-15 18:05
afaik the server doesn't know about groups, so it has to resolved client side

to me it looks like a duplicate of #4550, what do you think is different?

**Comment by sedrubal** [comment] 2016-01-15 20:35
Oh ok its the same, but I think #4550 are 2 issues... Should we close this?

**Comment by agrajaghh** [comment] 2016-01-15 22:35
yep, #4550 should be enough I think

**Closed by agrajaghh** 2016-01-15 22:35 UTC
