### ISSUE TITLE
[UI] Low-rez contact image displayed during call

### ISSUE THREAD

**Issue by ChipWolf** [WhisperSystems/Signal-Android#4805] opened 2015-12-04 15:53 UTC
A heavily compressed/low-rez version of the contact image is displayed during a call.

**Comment by 2-4601** [comment] 2015-12-04 16:17
Duplicate of https://github.com/WhisperSystems/Signal-Android/issues?q=is%3Aissue+is%3Aopen+low+resolution+contact+call (#4245)

**Closed** 2015-12-04 18:26 UTC
