### ISSUE TITLE
improve error messages when sending message fails

### ISSUE THREAD

**Issue by madig** [WhisperSystems/Signal-Android#1485] opened 2014-05-12 20:10 UTC
I recently installed CyanogenMod but can't remember how I backed things up, in any case I reregistered my number. I think I was writing with that contact after I switched to CM, but one day, she couldn't write me anymore. My messages to her were delivered just fine and she could read them, but she couldn't reply via push (SMS was disabled). Trying to end a secure chat also didn't work, she got the termination message but the app couldn't reply. 

I just reregistered my number again and now she can text me just fine. So I'm not sure what went wrong, but I'm reporting this because I think there should be more diagnostics or messages why something couln't be delivered instead of just failing to send anything without explanation.

**Comment by FeuRenard** [comment] 2016-11-19 20:03
This seems to be a duplicate of #1321.

**Closed** 2016-11-19 20:31 UTC
Labels: ux
