### ISSUE TITLE
Energy drain?

### ISSUE THREAD

**Issue by pguth** [WhisperSystems/Signal-Android#1298] opened 2014-04-05 10:45 UTC
We here have the impression that Textsecure drains quite a bit of energy. Is that right/can I do something to provide metrics?

Sadly Textsecure is not listed in the energy consumption graph by android so it's more of a subjective impression of several people.

**Comment by devurandom** [comment] 2015-05-24 05:26
Any news about this issue?

**Comment by skulumani** [comment] 2015-06-24 20:05
I have noticed that TextSecure is at the top of the battery usage screen. I'm on a Moto X 4.4.4 with TS 2.18.1. This seems to be more prevelent with some of the newer versions. I'm also only using TextSecure data messages and it is not set as the default so the MMS issue above should not be involved.

 In spite of the high percentage I don't think it's actually affecting the battery life that greatly. I'm just curious why it has such a large awake time. 

![screenshot_2015-06-23-13-03-07](https://cloud.githubusercontent.com/assets/5266022/8340148/bfa662a8-1a79-11e5-98cd-1f548479540f.png)
![screenshot_2015-06-23-13-03-02](https://cloud.githubusercontent.com/assets/5266022/8340149/bfa7204e-1a79-11e5-85fc-5ea8b37bdc75.png)

**Comment by ghusse** [comment] 2016-06-25 06:31
Hello,

I also have an issue : signal seems to drain my battery.

Steps to reproduce:

1. Open Signal
2. Return to home screen
3. Wait (15-20 min)
4. Signal appears as an app that consumes battery. If you wait longer, it becomes the first in the list.

Here is a debug log : https://gist.github.com/anonymous/c7bf03b5f05c97ce0f9ea691d5c9f70e

This issue is very annoying, because it forces me to go to the app settings and manually kill the app every time I use it, otherwise it drains all my battery.

**Comment by ghusse** [comment] 2016-06-25 19:31
I deleted all the data from Settings > Applications > Signal > Storage. It fixed the battery issue (and delete all my messages, of course).

But at least my phone's battery last more than 1 day.

**Comment by skulumani** [comment] 2016-06-26 11:20
How many messages did you have?

Maybe there's something size related after many messages

**Comment by pguth** [comment] 2016-06-26 15:59
I currently *don't* notice battery problems having about 70,000 messages and an app size of about 1 GB.

**Comment by ghusse** [comment] 2016-06-26 18:48
I cannot know : I just deleted everything.

I'm using signal for a while now probably kept every conversation. So I
guess there was a lot of messages and conversations.
Le 26 juin 2016 1:21 PM, "Shankar Kulumani" <notifications@github.com> a
écrit :

**Comment by lyciansarpedon** [comment] 2017-01-06 15:46
Following up on this, I have been having a battery drain issue since I updated to the latest version of Signal (3.25.4). Previously, it would last nearly 2 days on a full charge, but it now drains in 4-6 hours. Force stopping the application significantly slows the drain, and starting the application from the force stop begins the drain again (I have tried this at least four times to be sure). I am using a Nexus 6P running Android 7.1.1, and the debug log (if necessary) is at: https://gist.github.com/cc598cb9801b1aff369efce9c9332094


Another note is that the drain appears to be cryptic - looking at battery usage within Android settings doesn't show Signal. I have experienced this before with two other applications where the battery would burn through after installing or updating and return to normal after uninstalling, but the battery usage listing of applications never showed them. I isolated Signal as the likely source as it was the only application that updated immediately prior to the issue, and force stopping it mostly resolved it.

**Comment by mcg** [comment] 2017-01-13 20:31
I've used Signal for a few months and today had high battery usage, "Keep Awake 3h 50m 58s". Usually Signal hardly ever even shows up as a battery "user".  I am on Signal 3.62.2 from Play Store. Android 7.1.1 and Nexus 6p. Debug log: https://gist.github.com/anonymous/dae461c520138b3c4c08fd167cf933c3

**Comment by rpgrunwald** [comment] 2017-04-19 21:15
Any progress on this?  I reported it a couple of weeks ago with logs and screenshots.   Crickets...

**Comment by moxie0** [comment] 2017-04-20 04:49
@rpgrunwald You posted logs and screenshots here? Sorry I don't see them. Under your current username?

**Comment by moxie0** [comment] 2017-04-20 04:59
As of f98c41a0136da53331c2905e74326c738da594ed all jobs that have a network requirement now use timed wakelocks instead of wakelocks that free on job completion. 

This issue is really old (most comments reference TextSecure), and a lot has changed. I'm going to close this, and if people are still experiencing battery issues let's consolidate new/fresh information into a new issue.

**Closed by moxie0** 2017-04-20 04:59 UTC
Labels: performance
