### ISSUE TITLE
Notify with a sound when call drops

### ISSUE THREAD

**Issue by jsalatiel** [WhisperSystems/Signal-Android#5794] opened 2016-10-20 14:02 UTC
### Bug description
When the call drops there is no sound and you maybe keep talking until figure it out the call dropped. A sound on call drop/end , as done in other call apps , would be very nice!

### Device info

**Device:** One Plus 3 /Nexus 5
**Android version:** 6
**Signal version:** last from today

**Comment by haffenloher** [comment] 2016-10-20 14:04
Dupe of #4319, will be fixed by #5358!

**Closed** 2016-10-20 14:57 UTC
