### ISSUE TITLE
Widget contact shortcut

### ISSUE THREAD

**Issue by Transisto** [WhisperSystems/Signal-Android#5929] opened 2016-12-06 16:09 UTC
I'm a big user of having a folder right under my finder with widget icons of every contact I use the most.

To me this is very important to use Signal over regular phone / SMS to contact people with in a rush.

**Comment by jeremymasters** [comment] 2016-12-06 16:33
This also would make it easier to share things with specific contacts instead of always having to share with signal, then choose contact.  1st world problems I guess :wink:

**Comment by FeuRenard** [comment] 2016-12-06 22:40
Duplicate of #1484?

**Comment by Hanzei** [comment] 2016-12-09 13:05
@FeuRenard Looks like. I think we can close this one

**Closed** 2016-12-09 17:35 UTC
Labels: feature
