### ISSUE TITLE
Desktop and Android Client Notifications

### ISSUE THREAD

**Issue by shakurass** [WhisperSystems/Signal-Android#5741] opened 2016-10-03 16:53 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Related to #3165 with a slight twist. I use Signal on the PC and on my Android phone. When I message people using the desktop client my phone buzzes off the hook due to faster conversations using a full keyboard.

### Steps to reproduce
- Open Signal on the desktop
- Start a conversation with someone
- Have your phone nearby
- Listen to the phone buzz or ding like crazy

**Actual result:** Signal fires off a notification on the phone for every message received while having an active conversation with the desktop app.
**Expected result:** If the desktop app window is in focus, the notifications sent to the phone should be squelched.

### Screenshots
N/A

### Device info

**Device:** LGE Nexus 5X
**PC Info:** Windows 7 Pro
**Android version:** 7.0
**Chrome version:** 53.0.2785.116
**Signal version (Android):** 3.19.1
**Signal version (Desktop):** 0.23.2

### Link to debug log
https://gist.github.com/anonymous/4feaba580ba8a2fb46eaa24774e0c246

**Comment by 2-4601** [comment] 2016-10-06 00:51
Closing as duplicate of #4905

**Closed by 2-4601** 2016-10-06 00:51 UTC
