### ISSUE TITLE
Feature request: SMS forwarding(sms sync)

### ISSUE THREAD

**Issue by himalkaya** [WhisperSystems/Signal-Android#5099] opened 2016-01-20 14:27 UTC
Hello DevTeam,
when signal used as default sms app on android, that will be great, if incoming sms are also synced on other platforms(currently signal desktop/chrome).
BR
T.Himalkaya

**Comment by agrajaghh** [comment] 2016-01-20 15:06
closing as duplicate of https://github.com/WhisperSystems/Signal-Desktop/issues/496

**Closed by agrajaghh** 2016-01-20 15:06 UTC
