### ISSUE TITLE
Backup/restore doesn't properly import group chats

### ISSUE THREAD

**Issue by rejhgadellaa** [WhisperSystems/Signal-Android#6720] opened 2017-06-09 12:40 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I installed a different ROM for my phone and made a backup of my conversations. After installing the ROM I registered my device and tried to restore the backup. That seemed to work fine but on closer inspection it turned out that group chats had been split into separate conversations, one for each person in the chat. So, for example, if I was in a group chat with Tom and Jerry, I would now have one chat with Tom (with all messages he sent to the group) and one for Jerry (with his messages). The group chat was not restored at all. 

### Steps to reproduce
- Use Signal like normal (I did use a custom build with layout changes I've been working on with my own signing key, version 4.6.0), participate in group chats
- Create a backup in Signal
- Install a custom ROM (Lineage OS in my case). I wiped everything like system, cache, etc, except the internal storage (data) partition.
- Reinstall Signal
- Import the backup you've created earlier

**Actual result:** Group chats are imported as separate chats for each person participating in the chat.
**Expected result:** Group chats should be restored the way I backed them up, so all the messages from that group should appear in that group chat. 

### Screenshots
Omitted because privacy and I don't have photoshop at hand to do some blurring.

### Device info

**Device:** Moto X 2014 (victara) xt1092
**Android version:** 6.0.0 (stock moto) -> 7.1.2 lineage os nightly june 2nd
**Signal version:** 4.6.0 / 4.6.1

### Link to debug log
Sorry, don't have that..

**Comment by FeuRenard** [comment] 2017-06-09 13:31
This is a duplicate of #3024.

**Closed** 2017-06-12 14:43 UTC
