### ISSUE TITLE
please add user's background photo 

### ISSUE THREAD

**Issue by maxlinux2000** [WhisperSystems/Signal-Android#4724] opened 2015-11-26 10:14 UTC
It would be nice to be able to change the background of Signal-android, with a photo.

This is not an essential feature, but if Signal-android is more beautiful, it will spread faster.

**Comment by haffenloher** [comment] 2015-11-26 10:48
Dupe of #809

**Closed** 2015-11-26 11:11 UTC

**Comment by cxarmonato** [comment] 2016-02-04 17:38
In case you still want it, Signal plus has it https://play.google.com/store/apps/details?id=org.privatechats.securesms
