### ISSUE TITLE
"Scan the QR code" text invisible in DeviceAddFragment

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/Signal-Android#4771] opened 2015-12-01 11:23 UTC
`DeviceAddFragment`'s instructions, "Scan the QR code displayed on the device to link," are invisible on dark theme:

![device-add-light-dark](https://cloud.githubusercontent.com/assets/11031903/11499394/2263e4d4-9869-11e5-9228-b08730d6d06a.png)

Device info: Nexus 5, stock Android 6.0 MRA58K, Signal 3.6.1 (9fe1a7c)

App state: Signal registered, SMS enabled, default SMS app

**Comment by 2-4601** [comment] 2015-12-01 14:11
Looks like a dupe of #4611 
Also :yum: :ice_cream:

**Comment by unrulygnu** [comment] 2015-12-01 16:44
Related, but not a dupe.  `device_add_fragment` has hardcoded background color and tint, but the text is left to the theme.  Until the design stuff is worked out and themed properly, we need to make the text visible, preferably the same as the light theme at this point.

PR incoming.

**Closed** 2015-12-03 19:51 UTC
