### ISSUE TITLE
exporting and importing completely breaks group chats

### ISSUE THREAD

**Issue by jeroen7s** [WhisperSystems/Signal-Android#6821] opened 2017-07-24 14:43 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
when exporting and importing data from and to signal, the imported data is completely broken, all messages i've received in a group chat are now under the conversation with the person who sent it, not under the group chat, the only messages that are still in the group chat are the ones that you've sent yourself, essentially making it impossible to piece back how the conversations went, on both the private chat and the group chat

### Steps to reproduce
- export data
- uninstall Signal
- install signal again
- import data

**Actual result:** described above
**Expected result:** all group chat messages are still under the group chat, not scattered between the messages of 1on1 conversations

### Device info
**Device:** Oneplus3T
**Android version:** 7.1.1
**Signal version:** 4.8.1 before reinstall, 4.7.4 after reinstall
(wanted to move back because notifications seem broken on 4.8.1)

### Link to debug log
https://gist.github.com/646df806f62e842efe8fe201a5544c86
{the end of the log is when i tried to deleted the messages because they're useless to me}

**Comment by FeuRenard** [comment] 2017-07-24 18:34
Duplicate of #3024

**Comment by jeroen7s** [comment] 2017-07-24 21:02
didn't look back That far for similar bug reports, it's been an issue for that long already, wow :/

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by johanw666** [comment] 2017-07-25 09:28
Root and use a tool like Titanium Backup since a proper backup has been removed from the code and even adb backups have been made difficult to do (you need to downgrade to TextSecure 2.28 or earlier first).

**Comment by piratenpanda** [comment] 2017-07-26 05:56
Don't forget to deregister and registering again after using TiBu, otherwise you might not get notifications (at least this happens here)

**Comment by McLoo** [comment] 2017-08-08 10:09
closing as duplicate

**Closed by McLoo** 2017-08-08 10:09 UTC
