### ISSUE TITLE
Can not run Project in Android Studio 1.5.1

### ISSUE THREAD

**Issue by Bekakk** [WhisperSystems/Signal-Android#5437] opened 2016-04-13 15:20 UTC
Hello
I downloaded and imported this sample in My Android Studio,but when  first time when building is finishing i have this error

`Error:CreateProcess error=2, The system cannot find the file specified`

and then when i try to clear project i have  this error

`Error:A problem occurred evaluating root project 'Signal-Android-master'.
> A problem occurred starting process 'command 'git''`

Can anyone help me?
p.s I'm using github successfully in my another android studio project
thanks

**Comment by agrajaghh** [comment] 2016-04-13 15:37
closing as duplicate of #5432 

if you still need help try the [unofficial Community Forum](https://whispersystems.discoursehosting.net/)

**Closed by agrajaghh** 2016-04-13 15:37 UTC
