### ISSUE TITLE
Support for permanent disabling of notifications for group/person

### ISSUE THREAD

**Issue by jutoft** [WhisperSystems/Signal-Android#4414] opened 2015-11-06 12:58 UTC
Currently it is possible to disable notifications for a group for up to a week, but it would be nice if it could be done permanently.

Seems like earlier work on this was done in: #757

**Comment by 2-4601** [comment] 2015-11-06 18:26
Duplicate of #3407 (but don't know if the position has changed)

**Comment by 2-4601** [comment] 2015-11-11 01:13
Can be closed now (https://github.com/WhisperSystems/Signal-Android/commit/3cb2257ffdca81d2f2ac04994225014c20a08b08)

**Closed** 2015-11-11 07:05 UTC
