### ISSUE TITLE
Feature Request: Signal as standard phone app

### ISSUE THREAD

**Issue by scroom** [WhisperSystems/Signal-Android#6466] opened 2017-03-31 20:56 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
Would be great if it would be possible to choose Signal as standard phone app (similar to the SMS functionality) -> if a contact one trying to call is using Signal the call would be made via Signal/the Internet and if not the call would be made via the mobile network.

**Comment by 2-4601** [comment] 2017-04-29 15:10
Closing as duplicate of #6222

**Closed by 2-4601** 2017-04-29 15:10 UTC
