### ISSUE TITLE
Disable the "Check safety number" entry in the conversations options instead of making it invisible as long as no messages have been exchanged

### ISSUE THREAD

**Issue by nikwen** [WhisperSystems/Signal-Android#5938] opened 2016-12-09 14:42 UTC
I found this request in a review on Google Play and thought it would probably be quite easy to implement. Probably just a matter of replacing calls to setVisibility() to setEnabled().

![gplay_rating](https://cloud.githubusercontent.com/assets/3309657/21052573/fd5f4c76-be25-11e6-8a87-fc6e163cd4f5.png)

**Comment by FeuRenard** [comment] 2016-12-09 16:01
Duplicate of #5878

**Closed** 2016-12-09 17:33 UTC
