### ISSUE TITLE
Feature Request: Add more conversation color options

### ISSUE THREAD

**Issue by Cormak** [WhisperSystems/Signal-Android#6443] opened 2017-03-26 00:39 UTC
This one is simple. Currently we have 15 different conversation colors. This seems somewhat limited for a modern app. Anybody familiar with Textra's extensive color picker knows what I'm talking about. 

![textra](https://cloud.githubusercontent.com/assets/11284950/24327278/f2dfdf36-1181-11e7-8df4-d478b22da514.png)

30 or more colors would be nice. A good way to determine a maximum number of colors is if they start becoming too indistinct from one another. 

This is especially useful as Signal gains more users and our contact lists grow.

**Comment by nonlinear** [comment] 2017-03-28 23:17
UI designer here... The more colors you have, the less differentiation, so it's a law of diminishing returns.

Google solution is to add initials on avatar, if no picture is found.

Since signal has no cloud directory, and doesn't aim to have it, one solution is to have some preset gallery... Think selected emoji, or some open source gallery out there (I can research), and assign to each user.

Assignment should be consistent per group (user A always appears with image 13) at least. No biggie if diff groups, same user users diff images. In fact it helps differentiate the groups.

**Comment by 2-4601** [comment] 2017-04-29 15:02
Looks like duplicate of #4767

**Closed by 2-4601** 2017-04-29 15:02 UTC
Labels: feature
