### ISSUE TITLE
Missing Information/button on "Some issues need your attention" screen

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/Signal-Android#3377] opened 2015-06-09 08:39 UTC
I'm using CM12.1 / Android 5.1.1 on a Nexus 5 and noticed the following problem:

One of my group messages failed to send and I got the "Some issues need your attention." Message. When tapping on the message, another screen appeared stating "Some issues need your attention." but with no further Information and no possibility to solve the Issue.
Normally, green resend buttons appear next to the group members but in this case there was nothing next to their pictures and no buttons on the screen at all.
Eventually I figured out how to resend the message. I needed to select the failed message and resend it in the top right corner options menu.

Why wasn't there a resend button in the "Some issues need your attention." Screen? Is this a bug or intentionally. Most of the time there appear individual resend buttons next to the contact pictures but not this time.

**Comment by dcherian** [comment] 2015-09-07 10:20
I think I've run into the same (or very similar) problem with failed group *media* messages. Adding text to the message does not affect the problem. 

**Version:** TextSecure 2.26.1 on 4.4.4 stock Moto G (1st gen).

**To reproduce:** Use AFWall+ to prevent TextSecure from accessing the internet. Send group media message (only tested with picture). It will fail. Tap on the failed message and you will see no resend button.

![sketch-1441620283834](https://cloud.githubusercontent.com/assets/2448579/9714697/8d94ac82-5527-11e5-9a77-463d75e53478.jpg)

**Comment by haffenloher** [comment] 2015-11-24 14:33
> Version: TextSecure 2.26.1 on 4.4.4 stock Moto G (1st gen).

>To reproduce: Use AFWall+ to prevent TextSecure from accessing the internet. Send group media message (only tested with picture). It will fail. Tap on the failed message and you will see no resend button.

I can*not* reproduce this using the exact same procedure under Signal 3.4.2. The resend buttons on a failed outgoing group media message are shown correctly. Seems like it has been fixed in the meantime?

**Comment by dcherian** [comment] 2015-11-24 14:48
Can't reproduce either. This was fixed somehow. Should be closed I guess.

**Comment by dcherian** [comment] 2015-11-24 15:57
Tested on 3.5.1 beta

**Closed** 2015-11-24 17:12 UTC
Labels: ux
