### ISSUE TITLE
R

### ISSUE THREAD

**Issue by jagular** [WhisperSystems/Signal-Android#6526] opened 2017-04-14 10:18 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Is more nice to have request ...
On devices with small display / small resolution is not possible accept QR code in linked devices as the screen in this dialog is not scrollable.

### Steps to reproduce
- having generated and displayed QR code on PC
- scan it on android device with small display/small resolution (my device RugGear RG310)
- after QR code is scanned is not possible to accept it as the button is bellow the screen edge and not visible, the screen is not scrollable.

**Actual result:** not possible to pair the PC with Cell Phone as the confirmation button is not visible
**Expected result:** Please make this dialog scrollable to be accesible from devices with small display / small resolution

### Screenshots
sorry, the language on the screenshot is czech ...

![img_20170414_115313](https://cloud.githubusercontent.com/assets/486936/25040839/22df6bf4-210c-11e7-8497-f85f544fa27a.jpg)

### Device info

**Device:** RugGear RG 310
**Android version:** 4.2.2
**Signal version:** 4.2.4

**Comment by FeuRenard** [comment] 2017-04-14 10:33
This is a duplicate of #6062.

**Comment by jeremymasters** [comment] 2017-04-14 17:02
You may want to edit the title, although "R" did grab my attention!

**Closed** 2017-04-29 14:10 UTC
