### ISSUE TITLE
[Feature Request] Search within conversation/thread

### ISSUE THREAD

**Issue by shayaknyc** [WhisperSystems/Signal-Android#6858] opened 2017-08-07 14:18 UTC
#I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Would love the ability to search for strings/text within a conversation/thread. Currently, can only search for contact names on the main Signal screen when you first open the app/after login which shows the list of conversations. Would love either a global in-thread search so I can search for all instances of a string or word (and perhaps other search operators that can search for the existence of "attachments" or even date-ranges?) across all the saved conversations on the phone, or at minimum a search function within a single thread.

**Comment by rainerzufall** [comment] 2017-08-07 14:42
This is a duplicate of #1232. In the future, please **really** search open and closed issues for duplicates.

ps. Brown University has an interesting research project - more info on their homepage: http://esl.cs.brown.edu/blog/signal/

> In this project, we set out to explore whether encrypted search could be used to add search functionality to the Signal messaging app securely and without compromising efficiency. The design we proposed incurs minimal changes to Signal's current architecture and has several advantages over the naive solutions which include using a plaintext in-memory index or using full-database encryption solutions like SQLCipher.

but also
>  we realized that adding search functionality was a non-trivial problem

So don't get your hopes up too fast. There is no official statement from OWS on this project, whether or not, let alone "when" they will implement Brown University's results.

**Comment by shayaknyc** [comment] 2017-08-07 15:04
Thanks. So sorry about that. TBH, Github's search leaves a lot to be desired....I spent 15 mins doing a search and not sure why I didn't see this in the results at all.....

**Comment by moxie0** [comment] 2017-08-07 16:54
Closing as duplicate

**Closed by moxie0** 2017-08-07 16:54 UTC
