### ISSUE TITLE
Crash after Switching to Emoji Pane

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#3721] opened 2015-07-18 20:32 UTC
I hope this is no duplicate. I've just typed a message and wanted to insert an emoji. But the plane remained blank and TS crashed.
https://gist.github.com/6a3ccd06e5635c02fb62

**Comment by merkste** [comment] 2015-07-20 03:32
This crash has happened several times now. But this debug log is different:
https://gist.github.com/faa01ac8845e48d43b70

**Comment by agrajaghh** [comment] 2015-07-20 06:25
Android must be joking:
`E/AndroidRuntime(21291): java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available`

**Comment by mcginty** [comment] 2015-11-16 21:24
There have been enough changes since this issue that we'll need new debug logs if it can still be reproduced. Closing unless anyone still experiences this.

**Closed by mcginty** 2015-11-16 21:24 UTC
Labels: bug, emoji
