### ISSUE TITLE
Crash when I press quick reply

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#4968] opened 2015-12-26 14:06 UTC
Hi. For whatever reason the app sometimes (1/50 times) crashes when I press quick reply. No clue how to reproduce. 

https://gist.github.com/anonymous/df6c9bd5e15e25f65e25
https://gist.github.com/anonymous/01f69ec3194952492e5c

**Comment by haffenloher** [comment] 2015-12-26 14:48
Duplicate of #2971. Does https://github.com/WhisperSystems/Signal-Android/issues/2971#issuecomment-152354972 apply to you?

**Comment by 2-4601** [comment] 2015-12-26 19:00
Thanks @haffenloher, closing as duplicate of #2971

**Closed by 2-4601** 2015-12-26 19:00 UTC
