### ISSUE TITLE
Contact list scroll does not work when keyboard is open

### ISSUE THREAD

**Issue by christophvarga** [WhisperSystems/Signal-Android#5487] opened 2016-05-08 16:02 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When i compose a new message to someone and i search him/her but still the list is too long for the display estate, there is a scrollbar on the side BUT i cant reach the entries on the bottom OR worst when the list is shorter, i don't get a scrollbar and the contacts on the bottom of the list are hidden behind my keyboard.

### Steps to reproduce
- compose message to
- search for one common name in your contacts

**Actual result:** The contacts on the bottom of the search list are hidden and i can't scroll to them
**Expected result:** The visible screen should be only in the visible area so that i can scroll to everything (without being hidden by the keyboard)

### Screenshots

![screenshot_20160507-123641](https://cloud.githubusercontent.com/assets/653247/15098887/78aa4516-1548-11e6-9577-b1c6e35b1bed.png)

### Device info

**Device:** Samsung Galaxy S5 (SM-G900F)
**Android version:** CyanogenMod 13 (Android 6.0.1)
**Signal version:** 0.0.0

**Comment by 2-4601** [comment] 2016-05-08 19:13
Can you scroll after you dismiss the keyboard with the Back button on your phone?

**Comment by christophvarga** [comment] 2016-05-08 19:31
yeah, that works. is it meant to work in that way?

**Comment by 2-4601** [comment] 2016-05-08 19:36
Yes, the keyboard is open by default and it will cover the last few contacts in the bottom until you dismiss it.

But you should still be able to scroll when the keyboard is open. Are you able to scroll when it's open?

**Comment by christophvarga** [comment] 2016-05-08 19:50
no

**Comment by 2-4601** [comment] 2016-05-08 19:56
Cannot reproduce on Nexus 4, stock 5.1.1, Signal 3.15.2
When the keyboard is open I can scroll normally up and down. The keyboard just covers the bottom 4 contacts and I can only see them if I dismiss the keyboard.
One strange issue is that I don't see the scroll bar at all. Tested both light and dark themes.

**Comment by christophvarga** [comment] 2016-05-08 20:07
is it the same when your search result finds 6 contacts in total (4,5 + 1,5 hidden contacts)? are you still able to scroll?

**Comment by 2-4601** [comment] 2016-05-08 20:11
If all the contacts I search for fit in one screen, I can't scroll because there's no need to scroll.

After reading your first post again I get the impression that you actually **can scroll**. And your issue is just that the keyboard hides the contacts at the bottom? Is this correct?

**Comment by 2-4601** [comment] 2016-05-08 20:51
Since the comment history on this issue is a bit confusing (sorry :) here's the tl;dr
1. open contact list (keyboard is open)
1. scroll to bottom

Which one is the expected behaviour?
a) last n contacts are hidden under the keyboard (until you dismiss the keyboard)
b) you should be able to scroll all the way to the bottom of the list in the space above the keyboard

I'm expecting a) and closing. @moxie0 please reopen if b) is the expected behaviour.

**Comment by christophvarga** [comment] 2016-05-08 21:05
as i see it now.. yes. before i had a different impression because i thought that the keyboard makes the screen smaller in size, but its a different layer

**Comment by christophvarga** [comment] 2016-05-08 21:08
i will tidy the report up and thanks for your help in making it clearer to me. i wonder if it this issue is still worth being here?
it's just that i misunderstood the design. ?

**Comment by 2-4601** [comment] 2016-05-08 21:23
>  i wonder if it this issue is still worth being here?

It's good. There's no way to remove issues. They can only be closed when they are solved etc. and this issue is closed now. Thanks for your report!

**Comment by christophvarga** [comment] 2016-05-16 09:18
I have to add an easy solution i observed in other apps:
AS soon AS you Start to scroll in the list, the keyboard gets out oft the way automatically.
?

**Comment by christophvarga** [comment] 2016-05-21 09:56
@moxie0, @2-4601: I have spottet inconsistent design: in the message section (where you write to someone) the area behind the keyboard is NOT active. That means the keyboard reduces the message window (and also the scroll bar ). Why is it different when you search for contacts?

**Comment by cascheberg** [comment] 2016-07-12 16:04
The conversation list also does not hide items behind the keyboard if you search conversations.
I think it's valid to reopen this issue.

**Comment by moxie0** [comment] 2016-09-01 22:44
Hmm this fix does not seem to work for me

**Comment by cascheberg** [comment] 2016-09-07 19:41
@moxie0 My first PR fixed the issue only for the fast scroller, but that is only used if you have more than 20 contacts. Please check #5671 for the remaining issue.

**Closed** 2016-09-14 23:37 UTC
