### ISSUE TITLE
Feature request: Share messages to other apps

### ISSUE THREAD

**Issue by egvimo** [WhisperSystems/Signal-Android#7194] opened 2017-11-15 10:22 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
It would be very useful to share messages (photos or other attachments) to other apps over the system sharing.

### Steps to reproduce
- go into conversation
- select a message

**Actual result:** There is only an option to forward a message to other Signal users.
**Expected result:** It would be nice if there were a share button like in screenshot below.

### Screenshots
![share](https://user-images.githubusercontent.com/5247100/32830898-f472c8d0-c9f6-11e7-8e0e-e57fb68094d9.png)

**Comment by FeuRenard** [comment] 2017-11-15 10:59
This is a duplicate of #4906

**Closed** 2017-11-15 11:14 UTC
