### ISSUE TITLE
[Feature Request] Additional Camera Button Options

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6970] opened 2017-09-16 14:09 UTC
When clicking the camera button at the bottom can you have the option to use either video or camera, so you can either take photos or videos to send.

Thanks

![untitled](https://user-images.githubusercontent.com/16563034/30512889-fe9c8182-9af0-11e7-9702-d724c238f664.png)

**Comment by FeuRenard** [comment] 2017-09-16 23:31
Duplicate of #3564

**Closed** 2017-09-17 19:37 UTC
