### ISSUE TITLE
[feature request] add icon for verified contact

### ISSUE THREAD

**Issue by XavierInfomaniak** [WhisperSystems/Signal-Android#5214] opened 2016-02-11 17:50 UTC
Hello,

it would be nice to have distinctive mark on contact that identity has been verified (like level of trust in gpg). A simple key logo would be nice for a start ;).

Thank you for your work!

Regards.

**Comment by agrajaghh** [comment] 2016-02-11 17:54
clsoing as dupe of #910

**Closed by agrajaghh** 2016-02-11 17:54 UTC
