### ISSUE TITLE
Contact photos disappear when turning off notifications in group

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#4760] opened 2015-11-29 10:40 UTC
Signal 3.6.0
Only happens in group threads, and the contact photos come back if you go back and open the group again.

**Comment by haffenloher** [comment] 2015-11-29 11:18
This is probably a duplicate of #4420 :)

**Comment by 2-4601** [comment] 2015-12-19 01:53
:+1: 
Closing as duplicate of #4420

**Closed by 2-4601** 2015-12-19 01:53 UTC
