### ISSUE TITLE
Startup crash since update to 4.9.0

### ISSUE THREAD

**Issue by kaizoor** [WhisperSystems/Signal-Android#6842] opened 2017-08-01 18:34 UTC
When I open the signal app it crash's instantly. And when I'm using my phone I get some time force close popups. But only since I've made the update today. 
Device Bullhead
Android linageos 7.1.2

**Comment by nrizzio** [comment] 2017-08-01 19:36
Duplicate of #6838 (probably). [Post a debug log through ADB logcat](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#debug-logs-with-adb) as a comment over there.

**Closed** 2017-08-01 21:16 UTC
