### ISSUE TITLE
Using android 4.4.4 TaskManager to close Signal does not behave correctly

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#5003] opened 2015-12-30 13:28 UTC
Hi,

On my Android 4.4.4, I can open the "Task Manager" by pressing the "Home" button for a while. Then I can slide applications on the left/right to kill/close them.

The default (and correct) behaviour is that when I kill an App, I stay in the TaskManager, so that I can kill more apps.

Unfortunately, when I kill Signal, the TaskManager itself is closed, so that if I want to kill several App, I must ensure that Signal is the last one I kill, otherwise I have to run again the TaskManager since Signal has killed it.
This is very inconvienient...

**Comment by 2-4601** [comment] 2015-12-30 13:37
Closing as duplicate of #1037.

**Closed by 2-4601** 2015-12-30 13:37 UTC
