### ISSUE TITLE
Crash when receiving and initiating Signal calls

### ISSUE THREAD

**Issue by OllyCH** [WhisperSystems/Signal-Android#5361] opened 2016-03-20 20:59 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

Crash whenever receiving or initiating a Signal call.
### Steps to reproduce

**For crash on receiving call**
- receive a signal call from another contact
- accept the call on the incoming call screen
- "Unfortunately, Signal has stopped" message is shown

**For crash on initiating call**
- make a signal call
- dialing screen is shown
- "Unfortunately, Signal has stopped" message is shown immediately
### Device info

 **Model:** bq Aquaris A4.5

 **Android version:** 6.0

 **Signal version:** 3.14.2
### Link to debug log

This log should show first the receiving of a call and then the initiating of a call.
https://gist.github.com/anonymous/adcd964fe27017cd8475

**Comment by 2-4601** [comment] 2016-03-20 21:32
Another collateral damage like #5337?
```
D RedPhoneService: Uncaught exception - releasing proximity lock
D RedPhoneService: java.lang.ExceptionInInitializerError
D RedPhoneService: 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.createKeyGenParamsJCE(KeyPairGeneratorSpi.java:189)
D RedPhoneService: 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initializeNamedCurve(KeyPairGeneratorSpi.java:231)
D RedPhoneService: 	at org.spongycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initialize(KeyPairGeneratorSpi.java:133)
D RedPhoneService: 	at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:192)
D RedPhoneService: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.initializeEC25Keys(ZRTPSocket.java:251)
D RedPhoneService: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPSocket.<init>(ZRTPSocket.java:106)
D RedPhoneService: 	at org.thoughtcrime.redphone.crypto.zrtp.ZRTPResponderSocket.<init>(ZRTPResponderSocket.java:53)
D RedPhoneService: 	at org.thoughtcrime.redphone.call.ResponderCallManager.run(ResponderCallManager.java:96)
D RedPhoneService: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=17; index=78540
D RedPhoneService: 	at org.spongycastle.math.raw.Nat.shiftDownBits(Nat.java:631)
D RedPhoneService: 	at org.spongycastle.math.ec.custom.sec.SecP521R1Field.reduce(SecP521R1Field.java:78)
D RedPhoneService: 	at org.spongycastle.math.ec.custom.sec.SecP521R1Field.square(SecP521R1Field.java:105)
D RedPhoneService: 	at org.spongycastle.math.ec.custom.sec.SecP521R1FieldElement.square(SecP521R1FieldElement.java:113)
D RedPhoneService: 	at org.spongycastle.math.ec.ECPoint$AbstractFp.satisfiesCurveEquation(ECPoint.java:539)
D RedPhoneService: 	at org.spongycastle.math.ec.ECPoint.isValid(ECPoint.java:307)
D RedPhoneService: 	at org.spongycastle.math.ec.ECCurve.validatePoint(ECCurve.java:111)
D RedPhoneService: 	at org.spongycastle.math.ec.ECCurve.decodePoint(ECCurve.java:373)
D RedPhoneService: 	at org.spongycastle.crypto.ec.CustomNamedCurves$9.createParameters(CustomNamedCurves.java:223)
D RedPhoneService: 	at org.spongycastle.asn1.x9.X9ECParametersHolder.getParameters(X9ECParametersHolder.java:11)
D RedPhoneService: 	at org.spongycastle.crypto.ec.CustomNamedCurves.getByName(CustomNamedCurves.java:278)
D RedPhoneService: 	at org.spongycastle.jcajce.provider.asymmetric.util.EC5Util.<clinit>(EC5Util.java:36)
D RedPhoneService: 	... 8 more
D LockManager: Entered Lock State: SLEEP
```

**Comment by 2-4601** [comment] 2016-03-20 21:59
> `Device  : bq Aquaris_A4.5 (Aquaris_A45)`
> `Android : 6.0 (1457492088, 2.3.0-20160309-1101)`
> `OS Host : ubuntu-server3`

@OllyCH "ubuntu-server3"? What ROM are you exactly running?

Can anyone reproduce this on Marshmallow 6.0? @unrulygnu do calls work for you?

**Comment by dcherian** [comment] 2016-03-21 00:47
It works on CM 13 here.

**Comment by unrulygnu** [comment] 2016-03-21 04:27
@2-4601:  Cannot reproduce. Calls work here on both Android 5.0 and 6.0.1.

**Comment by OllyCH** [comment] 2016-03-21 07:27
@2-4601: This is the stock ROM that came with the phone. It is Android One.

I am new to Signal on Android, so I can't say if this is a new problem or not. Signal calls have not worked on my phone since I first tried a couple of weeks ago (which was definitely a Signal version earlier than 3.14.2).

**Comment by p4nci** [comment] 2016-03-21 07:54
same as OllyCH + immediately phone reboot after signal crash.
ATM can't provide logs. Sorry.

P.S. HTC Explorer (CM 12.1)
P.P.S. will test with signal 3.13.1 and report back

**Comment by sirber** [comment] 2016-07-12 17:59
Same thing on Android 5.1.1. Can we disable RedPhone?

**Comment by OllyCH** [comment] 2016-07-16 12:41
I had not tested it recently, so I tried again with 3.16.0 and it works now.
I am able to initiate and receive calls successfully.

**Comment by 2-4601** [comment] 2017-03-13 22:05
Original reporter said it's fixed. Closing as old RedPhone issue.

**Closed by 2-4601** 2017-03-13 22:05 UTC
Labels: crash, redphone
