### ISSUE TITLE
Add local search for text in messages (chat logs)

### ISSUE THREAD

**Issue by ghsrcgh** [WhisperSystems/Signal-Android#6698] opened 2017-06-02 17:34 UTC
Add local search for text in messages (chat logs). Currently there is no possibility to search something in the few chat histories or in the only one. Just there is no any search for the messages' text. Please make an indexes (they may be encrypted) and allow users to search text in messages history.

**Comment by nrizzio** [comment] 2017-06-02 17:47
This is a duplicate of #1232. In the future, [please read the contributing guidelines](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) before creating an issue.

**Closed** 2017-06-02 19:18 UTC
