### ISSUE TITLE
"Mute notifications" causes message names, icons, colors to be incorrect

### ISSUE THREAD

**Issue by kb100** [WhisperSystems/Signal-Android#5016] opened 2016-01-02 21:46 UTC
In group messages, after hitting "Mute notifications" and then "Mute for [...]", or "Unmute"  the following happen:

- names of group members are replaced with the group name
- circles that usually contain the first letter of a poster's name are replaced with the group icon
- text blobs all turn the same color

This only happens for messages on screen, and if you scroll up a full screen an then back down everything appears as it should.

**Comment by 2-4601** [comment] 2016-01-02 22:03
Closing as duplicate of #4420 :jack_o_lantern:

**Closed by 2-4601** 2016-01-02 22:03 UTC
