### ISSUE TITLE
Multi party SMS

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#5022] opened 2016-01-04 10:27 UTC
In the default android's SMS application, it is possible to send multi-party SMS (i.e. the same SMS to hundreds of people). Would be great to have this possibility in Signal, even if it is limited to uncyphered SMSs.

**Comment by 2-4601** [comment] 2016-01-04 11:12
Closing as duplicate of #413

**Closed by 2-4601** 2016-01-04 11:12 UTC
