### ISSUE TITLE
Supress repeating alerts

### ISSUE THREAD

**Issue by metall7** [WhisperSystems/Signal-Android#5101] opened 2016-01-21 15:23 UTC
Its very anoning when signal receives a bunch of messages and beeps for every of it
Please make a option "supress alerts for" n seconds after last message

**Comment by 2-4601** [comment] 2016-01-21 16:42
You can already mute conversations for certain time periods.

**Comment by McLoo** [comment] 2016-01-21 16:52
Guess he means:
if (new_notification)
   if (last_notification_sound_played_timestamp + delay_time <= now ) ding_ding_ding
  else silence

**Comment by agrajaghh** [comment] 2016-01-21 17:23
I agree, this was disturbing me already a long time. If your phone is switched off or you dont have a mobile signal for some time messages are coming in afterwards 1 by 1, and for every message the notification tone gets played. 

@McLoo 
I guess this would be better:
if (last_notification_timestamp + delay_time <= now ) ding_ding_ding
else silence

**Comment by metall7** [comment] 2016-01-21 20:48
Yes, this is what i mean

**Comment by qwertfisch** [comment] 2016-01-31 14:31
This is not only a problem for when you had no connection for a longer time, and all messages come in at once. This could be easily fixed (e.g. Threema did that some months ago), just with a 2 second counter or similar.

The more annoying problem for me is, that if someone sends me like 10 messages in a row, the app notifies me about every single one of it. It would be very helpful if I could set the mentioned delay by myself, e.g. one minute. Global setting would be great, per-contact setting would be perfect, as there are always "chatty" persons that write three words per message, but 10 messages in a row …

**Comment by 2-4601** [comment] 2016-04-03 13:59
Closing as duplicate of #3165.

**Closed by 2-4601** 2016-04-03 13:59 UTC
