### ISSUE TITLE
Dysfunctional emoji button appearing after tapping new voice message button

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4638] opened 2015-11-20 21:39 UTC
*Updated description*

1.) Activate system emojis
2.) Open conversation and tap quickly on voice messages button
3.) A dsysfunctional emoji button will appear at the left side of the message input box

Signal 3.5.0, Android 6, Nexus 5, SwiftKey & Google keyboard

**Comment by 2-4601** [comment] 2015-11-20 21:41
Sounds like dupe of #4101, #4105, etc

**Comment by RiseT** [comment] 2015-11-20 21:51
@2-4601 My problem is (was) rather about the existence of an emoji button that does absolutely nothing rather than the vanishing of it (I believe no emoji button when using system emojis is by design and I have no problem with it).

I could imagine something changed in the code and this issue is sort of a one time "artifact" because I've had System Emojis activated prior to that change.

Other users in the same situation possibly don't know that temporarily switching to Apple emojis remedies that dysfunctional button.

Still a dupe?

**Comment by 2-4601** [comment] 2015-11-20 23:24
Can you reproduce it? How many times have you encountered it?

**Comment by RiseT** [comment] 2015-11-20 23:36
@2-4601 No, I cannot. I've encountered it once and I don't expect to encounter it another time. Like I've said, I think that users having this issue **will experience it until they temporarily switch to Apple emojis** and back. Then that button will be gone for good.

I'm posting this issue hoping that a solution can be found for users who aren't aware of this (i. e. those who have that dysfunctional button and never deactivate the system emojis). I don't know how that could be done, though. Resetting to Apple emojis once in a future update? Don't know.

**Comment by RiseT** [comment] 2015-11-21 00:16
I have some news. As soon as I tap on the new voice message button (just shortly, so that this help message comes up) that freaking dysfunctional button appears again...

**Comment by 2-4601** [comment] 2015-11-21 00:21
Does it happen without Swiftkey? I remember there were some problems with that keyboard and quick capture camera and emojis.

**Comment by RiseT** [comment] 2015-11-21 00:25
@2-4601 Yes. Just switched to Google keyboard. Same problem.

**Comment by 2-4601** [comment] 2015-11-21 00:33
Confirmed on Nexus 4 and Huawei U8800 and stock keyboards.
Tapping voice message button resurrects the emoji button even though _Use system emoji_ setting is enabled.

**Comment by mad-de** [comment] 2015-11-22 09:43
I was able to reproduce (one time after updating to TS 3.5.0)

**Closed** 2015-11-23 19:42 UTC
