### ISSUE TITLE
Swiping the app on active apps page always exits page

### ISSUE THREAD

**Issue by ethernomad** [WhisperSystems/Signal-Android#5909] opened 2016-12-01 14:01 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With all other Android apps, when I swipe to close them on the active apps page it stays on the page if there are more apps active. When I close Signal this way it always goes back to the homepage, even if there are other apps.

### Steps to reproduce
- open 2 apps including Signal
- Press the square button to go to the active apps page.
- Swipe the Signal app to close it

**Actual result:** It goes back to the Android home page.
**Expected result:** It would stay on the active apps page like it does when I close any other app.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.23.0

**Comment by 2-4601** [comment] 2016-12-01 14:08
Thanks, this is a duplicate of #1037

**Closed by 2-4601** 2016-12-01 14:08 UTC
