### ISSUE TITLE
Different notifications on incoming text messages confusing

### ISSUE THREAD

**Issue by lolstarz** [WhisperSystems/Signal-Android#5187] opened 2016-02-07 01:05 UTC
Signal 3.9.1

When I have no unread signal messages and I receive a message, I will get a notification which contains the sender's name and the message. When I have unread signal messages and I receive a message from a different contact, I will get a notification which shows "Most recent from: <Contact name>" and does not contain the text of the most recent message.

Maybe this bothers me more than others due to my use case, but as I use a pebble which receives the text of notifications, this means that whenever I receive a message and I have another unread message, I will not be able to see the text of the newest message on my pebble. It will only receive the text of the new "Most recent from <Contact>" message.

I'd like for there to be a notification setting to turn off this "summary" notification.

**Comment by 2-4601** [comment] 2016-02-07 01:39
This is a duplicate of #2525.

**Closed by 2-4601** 2016-02-07 01:39 UTC
