### ISSUE TITLE
When adding video to a call, the audio switches from headphones to speaker

### ISSUE THREAD

**Issue by brinerustle** [WhisperSystems/Signal-Android#6436] opened 2017-03-24 14:39 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When switching to video from an audio call with headphone jack inserted, the switch causes the audio to get sent through the phone's speaker and internal mike.

### Steps to reproduce
- make a call with headphone inserted
- make a video call

**Actual result:** The headphone and microphone plugged into the headphone jack are unresponsive
**Expected result:** The audio should continue to pass through the external mike and headphones which are plugged in rather switch to the internal speaker and mike when video starts. 

### Device info

**Device:** Huawei P8 lite
**Android version:** 6.0
**Signal version:** 4.0.1

**Comment by rustybird** [comment] 2017-03-24 15:18
Duplicate of #6431

**Closed** 2017-03-24 16:38 UTC
