### ISSUE TITLE
Signal voice call causes calls to be sent to voice mail

### ISSUE THREAD

**Issue by conductedfour** [WhisperSystems/Signal-Android#5770] opened 2016-10-10 17:06 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

After placing or receiving a Signal voice call, all calls are sent directly to my carriers voice mail. This is only happening now after the Android OS was upgraded to 7.

### Steps to reproduce
- Call a contact using Signal or receive a Signal voice call

**Actual result:** After the Signal voice call is ended all incoming calls are immediately sent to my providers voice mail, until the phone is rebooted. Also Signal voice calls do not ring, until a reboot.

**Expected result:**  Calls should ring after using Signal voice calls.

### Device info
Device  : Huawei Nexus 6P (angler)
Android : 7.0 (3155372, NRD90U)
Signal 3.19.1

### Link to debug log
https://gist.github.com/anonymous/a048f239f674c9e16df55266dd18f2c5

**Comment by haffenloher** [comment] 2016-10-10 17:16
Dupe of #4703.
Perhaps this would be fixed by @cascheberg's race condition fixes? (#5362)

**Comment by conductedfour** [comment] 2016-10-10 17:23
Sorry for the dupe. However this is also affecting Signal voice calls as well. Any way to work around this?

**Comment by haffenloher** [comment] 2016-10-10 17:33
Yeah your Signal call didn't get properly terminated for some reason. For a workaround see [this comment](https://github.com/WhisperSystems/Signal-Android/issues/4703#issuecomment-202648295) in the original issue

**Comment by 2-4601** [comment] 2016-10-10 17:59
Closing as duplicate.

**Closed by 2-4601** 2016-10-10 17:59 UTC
