### ISSUE TITLE
Cannot share content from other apps to Signal contacts with no existing message history 

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4919] opened 2015-12-18 22:32 UTC
- From any app that is able to share content, share content and select Signal as target app

- In Signal click the +button on the top-right

- Choose a contact

Result: Text input field is empty.

(Note that instead of clicking the +button sharing content with a contact with existing message history works as expected.)

Found in Signal 3.8.0.

**Comment by McLoo** [comment] 2015-12-18 22:40
@Norbert80 thanks
Closing as dupe of #4797

**Closed by McLoo** 2015-12-18 22:40 UTC
