### ISSUE TITLE
Tests are failing in current master branch

### ISSUE THREAD

**Issue by mitar** [WhisperSystems/Signal-Android#6274] opened 2017-02-21 22:11 UTC
At current master branch (b43beaab752f1a1cb72ef3d464ccecfe8da9f593) tests are failing with:

```
Class org.thoughtcrime.securesms.ConversationAdapterTest
testGetItemIdEquals
```

![test_results_-_class_org thoughtcrime securesms conversationadaptertest_-_2017-02-21_14 10 30](https://cloud.githubusercontent.com/assets/585279/23187425/91baa07a-f83f-11e6-8020-245a5db2fc69.png)

**Comment by 2-4601** [comment] 2017-02-21 22:13
looks like dupe of #6250

**Closed by 2-4601** 2017-02-21 22:13 UTC
