### ISSUE TITLE
user abadoned signal, workaround

### ISSUE THREAD

**Issue by OlHeNi** [WhisperSystems/Signal-Android#6718] opened 2017-06-08 20:06 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Well the problem i have is some contacts hav tested Signal (on iOS) but have stoped useing the app. Signal stil expect them to use Signal.
Since on my P9 I use Signal for all communiction SMS get to Signal conversation flow.
If the contact that have passively abadoned signal write an SMS it gets listed and Signal defaults to send them an answer over data service, which the doesent reach the Phone of the SMS message received before. This is very bad. Moste of the time I am aware the person doesnt use Signal and chose SMS to sen dthe message but sometimes I forget it and the to be receiving person is going to be upset because she doesn't receive an answer.
### Steps to reproduce
- register mobile number A for signal
- delete app from phone of user A
- send an SMS from user A to B
- B uses Signal Android as SMS App
- B receives SMS message insecure
- B knows A has removed Signal from phone and wants to write back but forgets to choose SMS for sending the message
- A doesn't receive the message because it never contacts the server  

**Actual result:** 
contact doesn't receive an answer
**Expected result:** 
Either the receiver should get the message over the way he sent it to the receiver or
the sender should be made aware the receiver probably doesn't uses signal anymore or 
sms should be a default option to chose from in contact setting

There are some workaround for this
- drop SMS on Android app altogether (which is a no brainier in myy eyes)
- make trafic type selection permanent, in user settings, which would just wire up some available functions as defaults (workaround)
- implement active database , eg a number doesn't communicate once in a (to be defined, weeks/months ) timeframe to the server (connect to server not sending receiving a message) either 

1.  drop the number from Secure user circle

2. or notify the sender of a data message the chat partner has seen no data usage recently and my not receive the message in time (optimal, but provides probably meta data leak)

### Device info

**Device:** HUaweii P9 to iPhone 6
**Android version:** 7.0.0
**Signal version:** All until to date as of writing

**Comment by OlHeNi** [comment] 2017-06-08 20:58
I know there should be an unsubscribe option for signal, but I know no one ever used that function on any messenger I used the same goes with the number change function if an messenger has implemented it somewhere in the settings.
For most people it Ist like with newsletter delete/mark As spam in the inbox means for dau and upset user to unsubscribe even though there is an option at the bottom of the newsletter.

With the bigger adoption of Signal, it needs to implement fail saves for communication failure with origin in unawareness user disuse the messenger service.

**Comment by tresacton** [comment] 2017-06-09 07:34
I am also experiencing this issue with one contact and it is incredibly frustrating.

I propose:
* ability to set SMS as a per-contact default, and
* when clicking 'reset secure session' failure to complete new key exchange between sender and receiver within n hours results in notification to sender which includes an option to switch to the SMS default.

I beleive this pair of solutions (particularly the first one) could result in minimal to no metadata retention

**Comment by tomchiverton** [comment] 2017-06-21 18:12
Other use case : phone with Signal on is broken and replaced with older phone that can't run Signal. now no one using Signal can ever message the number ever again, without remembering to select the (undiscoverable) SMS option *every single time* they send a message.

**Comment by tomchiverton** [comment] 2017-06-21 18:21
Apperently, users are meant to find https://whispersystems.org/textsecure/unregister/ using Google not the app. This URL doesn't appear to be in the app (so Signal users can help their broken friends) and use that to remove themselves ?

**Comment by tresacton** [comment] 2017-06-22 01:58
Awesome. That helps for the moment! I'll send the link to the person I'm having difficulty texting, hopefully it'll work for them. 
Thanks @tomchiverton

**Comment by OlHeNi** [comment] 2017-06-22 18:25
Yea, shure but have you ever seen a person to use an unsubscribe option if she is unsattisfied. I havent, eg. Now unwanted email are marked spam instead of unsubscribe the email notification/newsletter, or people delet an app like the millions that don't use wa anymore but havent unsubscribe, same with iMessages for iOS leavers, this list no end.
An unsubscribe button is just a bug workaround, not an feature. The solution has to be one without user interaction to be userfriendly.

**Comment by tresacton** [comment] 2017-06-23 13:40
I do agree that it isn't user friendly, but for what it's worth this did solve my problem with the individual I was trying to communicate with. I still strongly recommend that a more intuitive,and (at least) semi-automatic, approach be adopted to address this issue. This was not an obvious solution for me, so if not for the comment in this thread I'd likely still be struggling with it.

**Comment by wslack** [comment] 2017-06-24 14:25
https://github.com/WhisperSystems/Signal-Android/issues/6718#issuecomment-310163620 is not a good solution to this; at minimum that page needs to be linked from this page: https://support.whispersystems.org/hc/en-us/sections/202709868-Signal-FAQ

**Comment by bmintz** [comment] 2017-07-11 23:21
A possible solution to this:

When the user uninstalls Signal, the server unregisters them automatically. If they don't have Signal anymore there should be no reason for them to be reached over Signal anymore.

Furthermore, when people uninstall an app, the expectation is that to other people, *they no longer have the app*. The behavior of Signal (on iOS too) should match this expectation.

**Comment by tomchiverton** [comment] 2017-07-12 07:59
I don't think Google provides an unsubscribe notification. 
-- 
Tom

**Comment by bmintz** [comment] 2017-07-12 08:25
Do you mean an uninstall notification?

**Comment by tomchiverton** [comment] 2017-07-12 08:56
Yes
-- 
Tom

**Comment by bmintz** [comment] 2017-07-13 00:05
I meant that perhaps the server could somehow notice when the user uninstalls the app.
Not sure how though.

**Comment by wslack** [comment] 2017-07-18 18:43
Why can't the app have a button that says "I'm abandoning Signal" that people can click? Alternatively, the app could give notice when a message is never received (suggesting that a user has deinstalled).

**Comment by bmintz** [comment] 2017-07-19 05:20
>the app could give notice when a message is never received (suggesting that a user has deinstalled).
this already happens when there's only one checkmark

> Why can't the app have a button that says "I'm abandoning Signal"
if it's in settings, not enough people will click it before uninstalling.
also, that exact phrasing might imply that they won't come back. it could be labelled as a button that the user should press before uninstalling signal.

I would still prefer some sort of server-side detection, cause then if you want to get rid of Signal, just uninstall it.

**Comment by tomchiverton** [comment] 2017-07-19 06:48
Maybe the Whisper server could text you N weeks after the last hand shake with a reminder, link to the unregister page

**Comment by wslack** [comment] 2017-07-19 15:41
> I would still prefer some sort of server-side detection, cause then if you want to get rid of Signal, just uninstall it.

I hear that, but anything is better than status quo.

**Comment by riyapenn** [comment] 2017-07-19 17:14
Not sure if you've seen the other issues, but this issue and requested changes look to be a duplicate of: https://github.com/WhisperSystems/Signal-Android/issues/6801, https://github.com/WhisperSystems/Signal-Android/issues/6390, https://github.com/WhisperSystems/Signal-Android/issues/2285 and the issues linked within those.  Closing this issue as result of being a duplicate. 

In the mean time, share the [support page for steps to unregister within the app and for the link to the unregister page](https://support.whispersystems.org/hc/en-us/articles/213190627-How-do-I-unregister-) with contacts who are no longer using Signal.  

Do you know why your contacts are uninstalling Signal? Email support@whispersystems.org if you have feedback from them.

**Closed by riyapenn** 2017-07-19 17:14 UTC

**Comment by jordanbtucker** [comment] 2018-05-18 20:05
So is this going to get fixed? We need to be able to set certain contacts as SMS by default. We can't rely on them to unsubscribe.
