### ISSUE TITLE
Action bar wrong size

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-Android#3279] opened 2015-05-29 10:55 UTC
The black action bar is smaller than the blue one and it looks a bit strange like that... 
(TS 2.16.2, Nexus 4, Android 5.1.1)

![screenshot_2015-05-29-12-49-59](https://cloud.githubusercontent.com/assets/3447340/7881293/db9cb67e-0601-11e5-81d3-7758872ebc5f.png)

**Comment by 2-4601** [comment] 2015-05-29 13:01
Dark theme has a cyan line under the action bar. Maybe they are intentional?

**Comment by jeremymasters** [comment] 2015-05-29 20:07
It would be cool if all the aqua color was instead blue like the message bubbles.

**Comment by 2-4601** [comment] 2015-05-30 19:06
Example from Firefox for Android:
![firefox actionbar](https://cloud.githubusercontent.com/assets/174176/7898915/f4fc359c-0717-11e5-94fd-88559132b919.png)

**Comment by FeuRenard** [comment] 2016-04-14 21:50
Does this issue still occur? I cannot reproduce the cyan line using Android versions 6.0, 5.1.1 and 4.4.4. I see `signal_primary_dark` consistently.

Additionally the issue title does not refer to the actual issue. The blue line does not show because the action bar is too small but to highlight the context menu displayed inside the action bar. But this can be ignored, as the issue should be closed anyway, I think.

**Comment by 2-4601** [comment] 2016-04-14 22:07
Cannot see the cyan line either in 5.1.1 nor in 4.0.4 any more.
Closing as expected behaviour.

**Closed by 2-4601** 2016-04-14 22:07 UTC
Labels: ux
