### ISSUE TITLE
Failed to record audio message

### ISSUE THREAD

**Issue by roth-a** [WhisperSystems/Signal-Android#6571] opened 2017-04-24 17:32 UTC
20% (or so) of the times I record a voice message with signal, I release the microphone button and I get the message: "Failed to record audio message". This is really annoying, and I have not figured out how to reproduce it. I will capture the bug log next time it happens.

----------------------------------------

### Device info
**Device:** LG G3
**Android version:** 5.0
**Signal version:** 4.4.0

I also experienced the same problems in previous versions with my
**Device:** Samsung Galaxy S3 GT-I9300
**Android version:** 4.1.2
**Signal version:** <4.4.0

**Comment by AndrewPy** [comment] 2017-04-24 18:17
It looks like this is a duplicate of #6097

**Closed** 2017-04-29 14:14 UTC
