### ISSUE TITLE
First-unread-chatscreen

### ISSUE THREAD

**Issue by CormickStone** [WhisperSystems/Signal-Android#5734] opened 2016-09-30 11:08 UTC
Hi,

I would like to have the feature to enter the chat- or groupscreen by clicking on the unreadcounter in Android.
But on the first unread message's postion, not on the last.

It would simplify large groupdiscussions.

**Comment by 2-4601** [comment] 2016-09-30 18:08
Closing as duplicate of #965

**Closed by 2-4601** 2016-09-30 18:08 UTC
