### ISSUE TITLE
Not Receiving SMS messages through Signal when set as default app

### ISSUE THREAD

**Issue by espinozagabe** [WhisperSystems/Signal-Android#5044] opened 2016-01-08 22:45 UTC
Issue is in the Title. I apologize ahead if time if there is another thread with this issue Open, I searched and could not find one.

I have a Nexus 6 running Android 6.0.1 on Signal Version 3.9.1.

I use Project Fi as a carrier, here's the debug log: https://gist.github.com/43d810aec13ac95be46c

Let me know if there's anything else I can do to help.

**Comment by SkateScout** [comment] 2016-01-28 17:11
Since https://github.com/WhisperSystems/Signal-Android/issues/5033 is closed i hope here is comming an solution.

**Comment by agrajaghh** [comment] 2016-01-28 17:20
@SkateScout please don't post in issues unless you have new information to add, see https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by SkateScout** [comment] 2016-01-28 18:16
There are two information.
First one is that an similar issue was closed without resolving. Close 
reason was that "is an dual sim problem".
That is incorrect my android Nexus 5 is running 6.0.1 and have 
definitely no dual sim. Second the other
similar issue contain also debug logs and since it was the same problem 
it could help to know that there are
more debug logs.

Am 28.01.2016 um 18:21 schrieb agrajaghh:

**Comment by agrajaghh** [comment] 2016-01-28 19:58
@SkateScout, #5033 was closed because the original author had a dual sim phone (duplicate of #555) and the other peson reporting a similar issue opend this issue here (including debug log)

If you're experiencing the same problem (not receiveing SMS, although Signal is the default SMS app) on your Nexus 5, please post a debug log after receiving a SMS and check if Signal is listed as default SMS app in the system settings.

**Comment by SkateScout** [comment] 2016-01-31 22:26
1) I use an N5 Android 6.0.1 M8974A-2.0.50.2.28
2) When i open Signal goto Settings  and Select SMS und MSS (aus) i could not select signal.
  Because when i tap "SMS deaktivated" i have "Hangouts", MyPhoneExplorer", "Messenger" and "Titanium Backup" but no "Signal".
3) When i open the SMS-App change menu i receive the logcat from bellow.

01-31 23:21:24.094 26592 26608 W MessageQueue: Handler (com.android.internal.os.HandlerCaller$MyHandler) {6250e3} sending message to a Handler on a dead thread
01-31 23:21:24.094 26592 26608 W MessageQueue: java.lang.IllegalStateException: Handler (com.android.internal.os.HandlerCaller$MyHandler) {6250e3} sending message to a Handler on a dead thread
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:507)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at com.android.internal.os.HandlerCaller.sendMessage(HandlerCaller.java:86)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.onAccessibilityEvent(AccessibilityService.java:725)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.accessibilityservice.IAccessibilityServiceClient$Stub.onTransact(IAccessibilityServiceClient.java:72)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
01-31 23:21:24.159   816   826 I ActivityManager: START u0 {act=android.provider.Telephony.ACTION_CHANGE_DEFAULT cmp=com.android.settings/.SmsDefaultDialog (has extras)} from uid 10096 on display 0

**Comment by agrajaghh** [comment] 2016-02-01 07:00
@SkateScout so you're saying that you can't select Signal as default SMS app? This is a deifferent issue then. Please open a new issue...

**Comment by 2-4601** [comment] 2016-02-01 17:02
This issue could use some tidying up (i.e. deleting comments)

**Comment by agrajaghh** [comment] 2016-02-01 22:21
@2-4601 I'll delete everything non relevant since #5166 exists now...

**Comment by bbusenius** [comment] 2016-05-16 17:47
I also have this issue and I'm also using Project Fi.

**Device:** LGE Nexus 5X, on Project Fi
**Android version:** 6.0.1
**Signal version:** 3.15.2

**Comment by kskumar** [comment] 2016-05-16 18:08
I had a similar problem when I joined Fi in December 2015. If I recall, it can be solved by going to Hangouts settings, selecting the Google account you use with Fi, and switching off Messages under the heading "Project Fi calls and SMS - (XXX) XXX-XXXX".

**Comment by bbusenius** [comment] 2016-05-16 18:48
Thanks @kskumar! That seems to have resolved the problem! It's frustrating there are so many different places to alter the SMS behavior in Project Fi. Since the heading "Project Fi calls and SMS - (XXX) XXX-XXXX" is misleading, can I ask you, does this change affect wireless calling too?

**Comment by kskumar** [comment] 2016-05-16 19:01
@bbusenius I have not noticed any effects on either "normal" or Wi-Fi calling.

**Comment by bbusenius** [comment] 2016-05-16 19:04
Thanks @kskumar! It looks like this issue doesn't have anything to do with Signal. It's more of a Project Fi / Hangouts problem. In any event, thanks for helping me through it!

**Comment by kskumar** [comment] 2016-05-16 19:06
@bbusenius No problem, sir! Much agreed, this is not a Signal issue, but rather an annoying Fi/Hangouts default behavior. I imagine that users of other third-party SMS clients experience the same issue when joining Fi.

**Closed** 2016-05-16 19:45 UTC

**Comment by ryan-williams** [comment] 2018-03-27 18:55
sorry to spam, but wanted to leave a couple google-breadcrumbs since I almost filed a fresh issue for symptoms that this is actually the root-cause of.

I observed new-message-notifications all saying "New locked message… Unlock to view pending messages":

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3y1G2p10223W331k3N2N/Image%202018-03-27%20at%202.35.12%20PM.png)

on click-through on the notification – or otherwise opening the app – I could see my outbound messages but never any new/inbound msgs, and there were no obvious settings related to "locked" or "pending" messages. It took me a bit to realize hangouts/fi was interfering.

I assume [the fix above](https://github.com/signalapp/Signal-Android/issues/5044#issuecomment-219499813) would work, but I like receiving SMS's in hangouts-widgets in gmail, so for now I'm attempting leaving hangouts/fi for SMS (and calls, as also discussed above) and just using signal groups with other signal users.

**Comment by giladwolff** [comment] 2018-04-09 20:30
I have the same issue as @ryan-williams. I am using pixel 2 XL on project fi and I can't receive any signal messages on the phone, I can only send messages.
