### ISSUE TITLE
Status bar color in dark theme inconsistency

### ISSUE THREAD

**Issue by signalguest** [WhisperSystems/Signal-Android#5232] opened 2016-02-15 10:47 UTC
Status bar color is lighter than the conversation color. That apply on every color.
![screenshot_20160215](https://cloud.githubusercontent.com/assets/17174855/13046482/5d111128-d3d9-11e5-95a7-90bc650ac8a5.jpg)
I dislike this, and it's harder to use in low light.

Edit (copy/paste of a later message in the ticket)
Oh, and on Lollipop you usually get the same color, this is why i opened this bug in the first place.
I don't know what is meant by design, but Lollipop and Marshmallow are not consistent.
So it's your choice to assign the bug to one or the other.

Please consider every other message in the ticket as the main one.

**Comment by haffenloher** [comment] 2016-02-15 14:08
Thank you, but this is a dupe of #4092 and possibly more.
Please search existing issues before opening new ones.

**Comment by signalguest** [comment] 2016-02-15 14:38
I did but that title isn't going to be noticed.

**Comment by kpuljek** [comment] 2016-02-15 14:49
There, I've renamed my topic. I would perhaps do it sooner but it was closed so fast that I didn't bother.

**Comment by 2-4601** [comment] 2016-02-15 15:10
Not sure if this is even an issue or just by design?

If you make a report about colours or other visual issues please always take screenshots. It can be hard to figure out what's the problem if there's just text. This is just a general remark not directed at anyone specific.
I guess it's best to leave this issue open because it has a screenshot (thanks op). I don't know if there's a duplicate with a better illustration, couldn't find any...

**Comment by kpuljek** [comment] 2016-02-15 15:17
Every single android app that colors the status bar/notification bar paints it darker than the rest of the app. Signal makes it brighter. 

Here's how it usually looks: http://i.imgur.com/1iQCD8O.png

And here's signal: http://i.imgur.com/FU2SwqU.png

**Comment by signalguest** [comment] 2016-02-15 15:29
@kpuljek Wrong comparsion! imho

On light theme you get the status bar darker. On dark theme you get status bar lighter. 
That apparently make sense if you're looking for a contrast and nice look.

Problem is in what a dark theme should be. Something less bright, that will help you're eyes in low light condition! This is where Signal is failing!
I'd add that the reverse contrast let your attention on the status bar, instead of the content! 
This is bad, the status bar should be on the second plane  of attention, always!

I hope this will help to get my point of view.

**Comment by kpuljek** [comment] 2016-02-15 15:33
I get your point of view, but fine, here are two apps that support "dark themes":
http://i.imgur.com/6jeEcHu.png
http://i.imgur.com/T7Sub5K.png

Each one makes the status bar even darker. I could post more, but I fail to see the point, just look at google's material design guideline shots:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsUklUeG9sRTdTOEk/style_color_uiapplication_accent3.png

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsMnI0UTMxLS1yLWs/style_color_uiapplication_accent6.png

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsbmpXdzNmLTZ4ZVk/patterns_emptystates_starter.png

**Comment by signalguest** [comment] 2016-02-15 15:36
Oh, this is a great idea! They still want to save contrast, to have two different planes of focus and you get the dark theme job done.

**Comment by jeremymasters** [comment] 2016-02-15 19:11
I think in the dark theme, the Signal title area needs to be a dark signal blue and the notification bar above should be a very dark blue.

**Comment by signalguest** [comment] 2016-02-15 19:13
@jeremymasters no need to a fixed color, prefer to stick with contact one, just darker for the title and very dark for the status bar.

**Comment by jeremymasters** [comment] 2016-02-15 19:17
@signalguest sorry, I meant in the conversation list and not inside the conversation thread.

**Comment by RiseT** [comment] 2016-02-15 20:17
Haven't been following this thread, but for what it's worth, accidentally I've been fiddling the last couple of hours with an overhaul of the dark theme. Here's my current variation of the conversation list (simple paint job).

![dark theme conversation list recoloring](https://cloud.githubusercontent.com/assets/12624674/13059268/34f9598e-d429-11e5-9e4e-8b4b316d3b28.JPG)

**Comment by jeremymasters** [comment] 2016-02-15 20:24
@RiseT You're reading my mind, Rise.  Although I think it wouldn't hurt the blue to be a little darker.

**Comment by RiseT** [comment] 2016-02-15 20:38
@jeremymasters I've been using the colors Signal is already using elsewhere (the 2 shades of blue are used in the light theme and the floating action button). The primary reason I've been doing this is that I've noticed many inconsistencies in the coloring, e. g. conversation list vs. contact list, light theme vs. dark theme and various colors that differ very minimally (almost non-visible). Some standardizing throughout Signal would be a good idea. All in all, I think the dark theme needs some love.
For example, note that I've used the background color from the contact list in the conversation list for a) consistency and b) to soften the contrast a bit.

**Comment by jeremymasters** [comment] 2016-02-15 20:44
@RiseT just looked at the contact list colors (background and blue) and that looks great.  That colored bar in the conversation list really was the main lacking piece to my eyes.  Thanks for your work.

**Comment by RiseT** [comment] 2016-02-15 20:51
@jeremymasters Btw - a black status bar with a blue app bar looks great imho. Very nice contrast. But it's not very consistent with the rest of Signal ...

**Comment by 2-4601** [comment] 2016-02-15 23:16
This is getting way out of the topic of the original issue :)
@jeremymasters The issue you mention is duplicate of #2446, #3281 :)

It would probably help to get this issue fixed faster if someone would list all the dark theme colour codes and the corresponding colour codes that the status bar _should_ have. And to give a reference to Android design documentation on why those colours are the correct ones.
Hopefully the next comment will address this ;)

**Comment by signalguest** [comment] 2016-02-16 07:18
@RiseT and @jeremymasters you're way off my issue, please move somewhere else or you will make harder to follow the real topic.

I did some paint about every scenario!

Now Signal focus on status bar, really bad:
![screenshot_now](https://cloud.githubusercontent.com/assets/17174855/13069514/9a85d12c-d485-11e5-8d4d-48faab5edfd6.png)

We can darker instead the status bar, so the focus will move to the content:
![screenshot_darker](https://cloud.githubusercontent.com/assets/17174855/13069524/aacf968a-d485-11e5-859b-e91dbae9d729.png)

We can even make it the same color:
![screenshot_same](https://cloud.githubusercontent.com/assets/17174855/13069529/b341a3f8-d485-11e5-9b60-c88393a2141e.png)

Or higher the contrast and let the black in:
![screenshot_black](https://cloud.githubusercontent.com/assets/17174855/13069533/bf921066-d485-11e5-9c9d-b35433ef19c6.png)

**Comment by kpuljek** [comment] 2016-02-16 07:31
Here's my suggestion. I've downloaded the official google's mockup.ai file for creating material layouts, taken their status bar overlay and overlaid it over a screenshot of signal. I've also added the appropriate hex values for each color. It looks like this:

![](http://i.imgur.com/XosjiYu.png)

**Comment by signalguest** [comment] 2016-02-16 07:33
Can you explain better what is the meaning of the shots?

My issue is about a concept: status bar should not get a brighter color because the contrast is so high that is bad for your eyes in low light condition AND the focus is moved to the status bar instead of the content.

**Comment by kpuljek** [comment] 2016-02-16 07:35
The meaning is obviously that the top color of each circle should be the status bar color in signal?

**Comment by signalguest** [comment] 2016-02-16 07:37
Yep but what's wrong with the palette on the right?

**Comment by kpuljek** [comment] 2016-02-16 07:39
Nothing is wrong, I made both the light and the dark version to prove that this way of deciding which colors should be used for the status bar is compliant with google material design. Even though colors used in Signal's dark theme aren't anywhere in the specification, I think that the same method of making a darker shade can be used. Problem with the dark theme is that it uses the status bar color from the light theme.

**Comment by signalguest** [comment] 2016-02-16 07:41
I read the code and i think they swap the colors in dark theme and that led to reverse contrast.

**Comment by kpuljek** [comment] 2016-02-16 07:43
Okay, maybe that's the problem, I didn't check the code because I'm not a programmer. But either way, it doesn't look right and Signal is the only app that has a brighter status bar than the rest of the application.

**Comment by signalguest** [comment] 2016-02-16 07:44
Sure i agree with you, we should change that.

That discussion is maybe over, i'll wait for some Signal team answer.

**Comment by agrajaghh** [comment] 2016-02-16 07:46
currently "900" is used as darkest color (http://www.google.com/design/spec/style/color.html#color-color-palette). I guess we have to add something (custom) even darker in the res file and here:
https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/color/MaterialColor.java

**Comment by kpuljek** [comment] 2016-02-16 07:48
Or just swap the status bar color and the rest in the dark theme, as signalguest said.

**Comment by agrajaghh** [comment] 2016-02-16 07:51
yeah, but that might make the bubble to bright? I think they have the right color at the moment, or do they appear too dark for you?

**Comment by signalguest** [comment] 2016-02-16 07:54
I didn't say to swap anythinig. Watch my examples, i made the pictures.

**Comment by kpuljek** [comment] 2016-02-16 07:58
I tried swapping them on one screenshot and it doesn't look too bright to me. But that's arguable, I suppose. 

![](http://i.imgur.com/KaM9qCj.png)

**Comment by signalguest** [comment] 2016-02-16 08:00
Is way too bright in the night. It's the light theme color, how you can think is fine?

**Comment by kpuljek** [comment] 2016-02-16 08:04
Because I THINK IT'S FINE. People can have different opinions, you know? I think it looks good and that it would look better than it does now and that it's dark enough for the dark theme. And if you checked even a little, you would see that it's not the color from the bright theme. 

here you go, side by side:

![](url
![image](http://i.imgur.com/HZJzaPL.png)

**Comment by signalguest** [comment] 2016-02-16 08:04
That's not an opinion, is a fact. You're trying to say that normal light theme colors are enough dark. Where is the logic?

**Comment by agrajaghh** [comment] 2016-02-16 08:09
@signalguest it is not the light theme colors. please calm down guys...

IMHO adding a darker color for the notification bar would be best, but swapping them like in the screenshot from @kpuljek would be fine as well

**Comment by kpuljek** [comment] 2016-02-16 08:11
There are no facts in design. I've just proven that colors in the dark theme, even when swapped around, are still darker than the light theme - FACT. My OPINION is that it looks great like that. 

Also, here are some other applications that support dark themes, and check out how bright they are:

https://cdn0.vox-cdn.com/thumbor/GYSBau7KL7Xd3o-tZXHtHQeBTHc=/cdn0.vox-cdn.com/uploads/chorus_asset/file/3329506/weathertimeline-3up.0.png

https://fs01.androidpit.info/a/0f/6d/qksms-sms-mms-messenger-0f6d1c-h900.jpg

http://www.wirefresh.com/wp-content/uploads/2014/09/android-textra-app-1.jpg

**Comment by signalguest** [comment] 2016-02-16 08:11
I see, i agree with @agrajaghh , nevermind @kpuljek i didn't catch all.

**Comment by kpuljek** [comment] 2016-02-16 08:12
I think we spammed enough so I'm gonna stop now. Sorry for all the notifications.

**Comment by moxie0** [comment] 2016-02-16 16:27
I'm not willing to accept a darker color off the material palette, but I am willing to swap the status bar and action bar colors in dark theme.

**Comment by 2-4601** [comment] 2016-02-21 15:02
agrajaghh saved us with ca2457db8d85f446f4b74cf61ee73f1ea2393580

**Closed by 2-4601** 2016-02-21 15:02 UTC
Labels: easy, ux
