### ISSUE TITLE
"Link this device?" dialog text gray, hard to read

### ISSUE THREAD

**Issue by rubin110** [WhisperSystems/Signal-Android#5120] opened 2016-01-23 23:41 UTC
Nexus 6
Stock Android 6.0.1 MMB29S
Signal 3.9.1

While using the dark theme when linking my account to a Signal for Chrome instance, this dialog box had hard to read text. Please see attached screenshot.

![screenshot_20160123-153524](https://cloud.githubusercontent.com/assets/222551/12533557/ca1cc720-c1e7-11e5-8fd0-e4693248f288.png)

**Comment by 2-4601** [comment] 2016-01-24 00:03
Closing as duplicate of #4611

**Closed by 2-4601** 2016-01-24 00:03 UTC
