### ISSUE TITLE
Incoming massages are delayed by hours

### ISSUE THREAD

**Issue by belle05** [WhisperSystems/Signal-Android#5323] opened 2016-03-07 11:02 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Massages are often being received on an extreme delay (minutes to hours, sometimes).
When the receiving user is viewing the conversations, it's usually fixed few minutes later.
Can't specify a certain scenario - seems pretty random. 
It is more likely to happen after the app hasn't been used for a few hours (nighttime etc.).

### Device
**Model** : LG Nexus 5
**Android**: Marshmallow (6.0.1)
**Signal version**: 3.12.0

### Link to debug log
(at a time when the issue happend:)
Sender - https://gist.github.com/b5ab7a07e6f226f35dc1
Receiver - https://gist.github.com/34805db912f511544b43

**Comment by agrajaghh** [comment] 2016-03-07 11:14
Is the first "tick" mark displayed at the senders side? This would mean the massge has been sent.

Is the receiving phone running a custom rom? root? xposed?
Could could also check these steps: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by belle05** [comment] 2016-03-07 11:22
The first tick is checked, the second is not. 
We'll recheck the steps, but the massages are not only delayed when the user is not using the app (that makes sense), but also when he's viewing the conversation for 2-3 mins.

**Comment by agrajaghh** [comment] 2016-03-07 11:25
I guess we need a new log from the receiving side right after the messages came finally through (with a delay while the app was open and there was a network connection). The current one looks good as far as I can see...

**Comment by shiftre** [comment] 2016-03-07 11:38
Hi

Let me clarify a bit more about this problem as I'm the receiving side,
I don't have any passphrase for this account, so the application shouldn't have any notification problem.

Whenever I close the application for a period of time ,(say, 30m or so), I have to re-open it 
in order to get all the notifications, (messages), Belle05 sent. 
Once I open the application I get her messages and everything is cool, however if I keep
the application closed I do not receive any message from her up until I open.

We've tried reproducing it after she opened the bug however Signal was left open in the background and I got her messages.
We'll try to get a log later.

Do note that the log I'd upload would be with the notifications, as I've opened the application.
If you have a way to extract, (or query), the log without opening Signal, I could do that and 
in the scenario where she sends a message and I don't receive it while the application is closed.

**Comment by agrajaghh** [comment] 2016-03-07 11:42
clearly looks like a GCM problem, did you check steps 6. - 11. from the link I posted?

**Comment by shiftre** [comment] 2016-03-07 11:48
@agrajaghh I have a stock build, rooted. I've done some of the steps there ,(like relinking my account 
and reset'ing).

I do have low space on this device (about less than 1g), Push notification seem to work
I've installed PNF and hope to get it fixed, as I've lowered the threshold.

**Comment by agrajaghh** [comment] 2016-03-07 11:50
okay, closing this since it really looks like a root/gapps problem.

If you're still having trouble feel fry to ask for help at the unofficial community forum: https://whispersystems.discoursehosting.net

**Comment by shiftre** [comment] 2016-03-07 11:51
@agrajaghh :-1: 

This is a bug in Signal, not a problem with GCM...

**Closed by agrajaghh** 2016-03-07 11:50 UTC

**Comment by 2-4601** [comment] 2016-03-07 17:22
You are not receiving the GCM tick that tells your phone that a new Signal message has arrived. You said that this also happens with Telegram which AFAIK also uses GCM to some extent.

> Whenever I close the application...

What do you mean by **close**? Could be duplicate of #4965.

**Comment by shiftre** [comment] 2016-03-08 17:00
I hit the stock task manager and "kill"/close the application, it's still running if I look it up from Settings

**Comment by Dyras** [comment] 2016-03-09 21:58
@shiftre Does this also happen on WiFi? Do you have battery savings enabled?

**Comment by shiftre** [comment] 2016-03-12 08:05
WiFi and 3g, it happens both on power saving and non-power saving..
