### ISSUE TITLE
Receive only part in MMS messages

### ISSUE THREAD

**Issue by deverlex** [WhisperSystems/Signal-Android#6832] opened 2017-07-29 16:49 UTC
I send a MMS is contain 2 images, but Signal get one image.

Fix it, please!

### Device info
**Device:** Xperia M2, Nokia 5
**Android version:** 5.1 / 7.1.1
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment] 2017-07-29 17:03
Duplicate of #1300 

Maybe you can see the missing image in the "All images" view.

**Comment by McLoo** [comment] 2017-08-01 23:02
closing as duplicate

**Closed by McLoo** 2017-08-01 23:02 UTC
