### ISSUE TITLE
[Suggestion] upgrade in .../gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#5431] opened 2016-04-10 18:21 UTC
With latest Android Studio version, I got this error respectively hint how to solve it:

```
Gradle version 2.10 is required.
Current version is 2.5.
If using the gradle wrapper, try editing the distributionUrl in
.../gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
```

This fix solves the issue.

**Comment by andersk** [comment] 2016-04-25 20:21
Duplicate of #5008.

This happens if you accept Android Studio’s recommendation to upgrade the Android Gradle plugin to 2.0.0. Don’t accept that upgrade, and you won’t get this error.

**Comment by NoahAndrews** [comment] 2016-09-20 14:32
For anyone else finding this, make sure Instant Run is disabled. Running the app will not work otherwise.

**Comment by FeuRenard** [comment] 2016-11-15 00:04
https://github.com/WhisperSystems/Signal-Android/commit/848a25664b746f89b4435b01728247bf3d3135f4 fixed this. Issue can be closed.

**Closed** 2016-11-15 00:27 UTC
