### ISSUE TITLE
Crash on tapping attachment button

### ISSUE THREAD

**Issue by tree-pangolin** [WhisperSystems/Signal-Android#5585] opened 2016-07-27 15:53 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Ever since the latest update to the Android N Preview, the blue "attach" button beside the message composition bubble does not work. Tapping it does not do anything, it simply causes the app to hang. 

### Steps to reproduce
- Ensure you are running Android Beta Program 7.0 (NPD90G)
- Open any conversation in signal
- Tap blue attachment button to the right of the input bubble

**Actual result:** Material ripple effect displays on button, but app proceeds to hang without response. 
**Expected result:** Multiple buttons should display to add a specific file type of attachment. 

### Screenshots
[cannot be provided] 

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.0
**Signal version:** 3.16.0

### Link to debug log

https://gist.github.com/anonymous/e95ab8a2271c603aa343c8657633ad92

**Comment by FeuRenard** [comment] 2016-07-27 16:12
This is a duplicate of #5583.

**Comment by tree-pangolin** [comment] 2016-07-27 20:06
Sorry about that. I guess I didn't do enough searching. Hopefully this can get fixed soon, nonetheless.

**Comment by FeuRenard** [comment] 2016-07-30 21:53
This issue can/should be closed.

**Comment by arafey** [comment] 2016-07-31 08:22
Same issue as @tree-pangolin but I've also observed that using the Share menu and then selecting a conversation does work. Trying to attach an image via Google Photos works, for example.

**Closed** 2016-08-01 02:03 UTC
