### ISSUE TITLE
Feature Request: Move to SQLCipher so destination information is also encrypted

### ISSUE THREAD

**Issue by sigenc** [WhisperSystems/Signal-Android#6439] opened 2017-03-25 14:15 UTC
Improve local storage encryption. Now only the content of the messages is encrypted. If forensics can bypass androids FDE, they can collect metadata. Please don't assume that androids FDE is safer than local encryption implemented right. Android FDE is light years away from ios and even ios is not bulletproof. 

please read on the discoussion forum:

https://whispersystems.discoursehosting.net/t/passphrase-encryption-only-for-message-contents/917

Moxie commented he would want to phase it out in favor of android fde. Wich would be a mistake.

**Comment by nrizzio** [comment] 2017-03-25 15:17
Duplicate of #4

**Comment by sigenc** [comment] 2017-03-25 19:05
Oh. Sorry i didn't find that. Thx. Can be closed

**Closed** 2017-03-25 19:06 UTC
