### ISSUE TITLE
Availability on F-Droid

### ISSUE THREAD

**Issue by Malvarose** [WhisperSystems/Signal-Android#5853] opened 2016-11-12 08:24 UTC
Why is this not on F-Droid?  There is no reason for it not to be.  Or in the very least why does this REQUIRE Google Play Services?  If I am weary of my privacy, then why would I use Google?

**Comment by FeuRenard** [comment] 2016-11-12 14:16
Duplicate of #127

**Closed** 2016-11-12 17:49 UTC
