### ISSUE TITLE
Only one checkmark in group chats on Signal-Android when messaging from Signal-Desktop

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#4847] opened 2015-12-09 17:38 UTC
Group chat. Sending a message with Signal-Android shows two checkmarks on both clients. Sending a message with Signal-Desktop shows two checkmarks on Signal-Desktop but only one on Signal-Android.

**Comment by moxie0** [comment] 2015-12-09 18:12
duplicate of #3479

**Closed by moxie0** 2015-12-09 18:12 UTC
