### ISSUE TITLE
CrashBrowser: ApnDatabase corrupted

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/Signal-Android#2760] opened 2015-03-23 21:01 UTC
`````
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26)
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
at org.thoughtcrime.securesms.database.ApnDatabase.getDefaultApnParameters(ApnDatabase.java:138)
at org.thoughtcrime.securesms.database.ApnDatabase.getMmsConnectionParameters(ApnDatabase.java:159)
at org.thoughtcrime.securesms.mms.MmsConnection.getApn(MmsConnection.java:69)
at org.thoughtcrime.securesms.mms.OutgoingMmsConnection.isConnectionPossible(OutgoingMmsConnection.java:114)
at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:667)
at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:664)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
`````

**Comment by mcginty** [comment] 2015-11-16 21:35
we've been choosing not to address crashes caused by FS corruption - closing for that reason unless there's evidence it's still happening to the point where it seems like *we're* the ones corrupting it

**Closed by mcginty** 2015-11-16 21:35 UTC
Labels: crash
