### ISSUE TITLE
Place an unencrypted voice call with long press on phone icon (just like signal message/mms toggle)

### ISSUE THREAD

**Issue by jonathanernst** [WhisperSystems/Signal-Android#5160] opened 2016-01-31 11:28 UTC
It would be nice to be able to long press the phone icon in a signal conversation to issue a 'normal' (i.e. unencrypted) call, just like it is currently possible to send an unencrypted SMS.

As Signal calls for me still have a high latency/not very good voice quality I often find myself having to switch application from Signal to my contact list to be able to call my Signal-using contacts.

Regarding the quality of calls, are you looking for additional servers/ressources in Europe (Switzerland for example)?

Thanks a lot for this great application!

**Comment by ChaoticMind** [comment] 2016-01-31 12:26
Duplicate of #4857

**Closed** 2016-01-31 12:27 UTC
