### ISSUE TITLE
not smartwatch friendly

### ISSUE THREAD

**Issue by revanistT3** [WhisperSystems/Signal-Android#5086] opened 2016-01-17 14:30 UTC
When one person sends a message it appears correctly on my pebble, But when another person sends a message it appears as "<name> sent a message" (paraphrasing). It only fixes its self after one person's messages are marked as read, than the right message suddenly appears on my watch.

Pebble doesn't require any special notifications, but I think signal's long notifications are giving it problems

**Comment by agrajaghh** [comment] 2016-01-17 14:58
closing as duplicate of #5085 and #2525 

please search for exisiting issues before opening new ones. Thanks

**Closed by agrajaghh** 2016-01-17 14:58 UTC
