### ISSUE TITLE
Remember the last used message mode per contact

### ISSUE THREAD

**Issue by drws** [WhisperSystems/Signal-Android#6771] opened 2017-06-28 10:26 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

I have some people in my contact list that have uninstalled Signal, but didn't do a proper unregistration so my Signal app always defaults to sending them Signal messages, which they never receive. I have to manually select "SMS mode" each time I open the conversation. It would be great if the last used way of contacting a specific contact was remembered by the app.

**Comment by FeuRenard** [comment] 2017-06-28 11:55
Duplicate of #2285

**Comment by p4nci** [comment] 2017-06-28 11:55
duplication of https://github.com/WhisperSystems/Signal-Android/issues/2329

**Comment by drws** [comment] 2017-06-28 17:08
I was actually going to search for "method" but I was "nah, English is not my mother's tongue, no one would call it method". Sorry for the inconvenience and next time I'll check.

**Closed** 2017-06-28 17:09 UTC
