### ISSUE TITLE
SMS to Non-Signal Users No Longer Sending

### ISSUE THREAD

**Issue by H0bb1tM1ndTr1x** [WhisperSystems/Signal-Android#5977] opened 2016-12-20 19:30 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal will not send SMS to non-Signal users. It was working fine last night.

### Steps to reproduce
No steps taken. It is simply failing to fulfill its primary role.

### Screenshots
![screenshot_20161220-142629](https://cloud.githubusercontent.com/assets/20560357/21364874/b15ddce0-c6c0-11e6-90fa-2b657585257a.png)

### Device info
Nextbit Robin
Android - 6.0.1
Signal - 3.24.1

### Link to debug log
https://gist.github.com/f4730b208ecfd0e97461ef843c4d5ee7

**Comment by H0bb1tM1ndTr1x** [comment] 2016-12-20 19:38
I should add that I have rebooted several times AND I've cleared cache/data AND I've reinstalled the app twice.

**Comment by riyapenn** [comment] 2016-12-20 19:42
Duplicate of https://github.com/WhisperSystems/Signal-Android/issues/3096. Contact support@whispersystems.org for troubleshooting.

**Comment by H0bb1tM1ndTr1x** [comment] 2016-12-20 20:08
I found the problem. It's not Signal's issue. I checked the Nextbit subreddit and apparently our phones are experiencing an issue with T-Mobile's enhanced LTE. Turning it off fixed the issue. I wonder what they screwed up this time...

**Closed** 2016-12-20 22:14 UTC
