### ISSUE TITLE
Play the notification sound once for new messages

### ISSUE THREAD

**Issue by ImAnnoying** [WhisperSystems/Signal-Android#5616] opened 2016-08-14 09:54 UTC
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Notifications are played for every message Signal downloads since you were offline.

### Steps to reproduce
- turn off Wi-Fi or cellular data
- let people text you and discuss things in groups
- turn on Wi-Fi or cellular data

**Actual result:** The notification sound never ends, unless you tap "Mark all read", but even after tapping it Signal will keep downloading messages and display alerts, including the "Mark all read" button.
**Expected result:** It would be nice if there was at least a preference that makes Signal only play the alert once to let you know you have unread messages.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 5.1.1
**Signal version:** 3.16.1

**Comment by FeuRenard** [comment] 2016-08-14 12:17
This issue is a duplicate of #3165.

**Closed** 2016-08-14 18:10 UTC
