### ISSUE TITLE
Read Receipts & an Animation to show when someone is typing

### ISSUE THREAD

**Issue by mattu12** [WhisperSystems/Signal-Android#4376] opened 2015-11-04 15:01 UTC
I'd really like to see an option for read receipts and an animation or something else to show when someone is typing in the conversation. Much like the features WhatsApp or iMessage possess.

**Comment by heyimgay** [comment] 2015-11-04 15:27
Duplicate of #2667 and others. Please search for issues before creating them.

**Comment by Dyras** [comment] 2015-11-04 15:40
Read receipts = Add it and I leave for something else. If I want them to know I've read their message I will damn well respond to it!
I really want to see when people are typing though.

**Comment by heyimgay** [comment] 2015-11-04 16:07
#1121 is already open

**Closed** 2015-11-04 16:35 UTC
