### ISSUE TITLE
"Permanent Signal communication failure!" since updated to 3.29.6

### ISSUE THREAD

**Issue by juneyao** [WhisperSystems/Signal-Android#6392] opened 2017-03-15 11:39 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since updating to Signal 3.29.6 I get, several times a day, a failure notification saying: "Permanent Signal communication failure! Signal was unable to register with Google Play Services. Signal messages and calls..."
Also I no longer receive messages unless i open Signal.
I dont have Google apps on my phone but before updating (which i was forced to do) signal was working fine with MicroG core.
Since then I have updated microG core, but this has not fixed the issue.
I guess I am going to be told to report this issue to microG devs rather than here, but since it's a signal update what resulted in this issue, I would like to know if we are gonna see Signal go further into the road of being incompatible with phones not monitored by google.
We are forced to update Signal too often. (not too often would be once every 1 or 2 years). if every update is going to bring problems, I will move on

### Steps to reproduce
- normal Signal usage. The failure notifications usually come when network state changes and when opening Signal

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** receiving notifications of messages without having to open the app. not receiving notifications of communication failure with Google.

### Device info

**Device:** Samsung Galaxy S4
**Android version:** 4.4.2
**Signal version:** 3.29.6

**Comment by p4nci** [comment] 2017-03-15 12:28
"Don't Worry, Be Happy" 😄 
now you can download a official Signal apk outside of Playstore:
[community forum: how-to-get-signal-apks-outside-of-the-google-play-store](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808/15)
respectively
https://signal.org/android/apk/

**Comment by vvug** [comment] 2017-03-15 13:43
@juneyao Signal now works fine without google play services or microG, your rant is not justified. The release cycle of Signal is great. I think you can close this issue.

**Comment by moxie0** [comment] 2017-03-15 16:48
That release updated the version of GMS we use, so I assume microG isn't properly reporting that it is API compatible with the updated version.  We do this very rarely (every one or two years).

Alternately you can uninstall microG and reregister. Signal will work by maintaining a persistent connection, but it won't be as reliable as microG and it will use more of your battery.

**Closed by moxie0** 2017-03-15 16:48 UTC

**Comment by ale5000-git** [comment] 2017-06-07 11:33
The problem is usually that if one install microG from F-Droid also if he/she select manually the latest preview build (which is updated and working) usually it get the latest release build (which is quite old).

**Comment by SwedishForenger** [comment] 2022-04-09 05:09
permanent signal communication failure
In Signal Android APK 5.34.10

**Comment by UserX404** [comment] 2022-04-09 08:11
@SwedishForenger 
You should provide a debug log and  more details of your issues.
Due to this is a 5y old closed issue please consider to search for a newer one or open a new ticked.

**Comment by SwedishForenger** [comment] 2022-04-09 13:53
Here is the log:

https://github.com/signalapp/Signal-Android/files/8457050/d8eff8cf9baeb2e1b8313c68842d443fb480f31b5f4389b305ee2674b8fd3f22.gz
