### ISSUE TITLE
Proximity sensor not enabled while dialing

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#4519] opened 2015-11-13 16:57 UTC
The screen does not turn black while an outgoing call is still dialing. It will turn black as soon as the call is answered. Tested on two different phones running Signal 3.3.2.

Steps to reproduce:
1. make an outgoing call, called person should not answer the call
2. put your phone to your ear to hear the dialing sound

Expected:
- screen should be locked to avoid accidentally pressing anything

Result:
- screen is not locked

I think this is a problem in the code, see [here](https://github.com/WhisperSystems/Signal-Android/blob/HEAD/src/org/thoughtcrime/redphone/RedPhoneService.java#L210) and [here](https://github.com/WhisperSystems/Signal-Android/blob/HEAD/src/org/thoughtcrime/redphone/call/LockManager.java#L89).
I can still provide a debug log on request.

**Comment by outbacker** [comment] 2015-11-16 12:55
I agree, many accidental settings changes make the otherwise superb call quality a lot less useful. Especially on lollipop, where there are pulldown quick settings by default.

**Comment by generalmanager** [comment] 2015-11-16 13:08
@cascheberg Seems like this is a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/4519.
Could you copy & paste your report there and close this issue? Thanks!

**Comment by heyimgay** [comment] 2015-12-09 22:53
this has been implemented and can be closed

**Closed** 2015-12-10 13:04 UTC
