### ISSUE TITLE
Fingeprint Exchange

### ISSUE THREAD

**Issue by IlonkaPingel** [WhisperSystems/Signal-Android#826] opened 2014-02-27 12:57 UTC
Currently you can only confirm a fingerprint, if you read a QR-Code from anothers phone. This requires both chatters to be in the same place. This is at least the safest way, but there are other ways to do this nearly as secure as this. You could e.g. talk with someone on the phone, who dictates his fingerprint, so that you can confirm it by simply checking, if the code he's dictating matches the one, your phone is showing. So there should be an option, to confirm another ones fingerprint by simply telling the app "Yes, I've checked/confirmed the fingerprint of my opposite." This would be similar to the way PGP fingerprint exchanges can work.

**Comment by Aeronaut** [comment] 2016-04-16 10:44
Simply checking if the fingerprints are the same isn't enough! The way how it's implemented yet is practically unusable. If the fingerprint is altered by a man in the middle you would never now if you don't check frequently....

So doing it like in OTR: Saving each fingerprint and display the trusted state in Chat...

**Comment by 2-4601** [comment] 2016-04-16 11:36
This seems to be about two different issues: 1) sharing the fingerprint and 2) saving the verification status
1) is a duplicate of #817
2) is the same as #910

**Closed by 2-4601** 2016-04-16 11:36 UTC
Labels: feature
