### ISSUE TITLE
Swiping to Close Signal in Recent Apps List Causes an Exit

### ISSUE THREAD

**Issue by Zer0Nin3r** [WhisperSystems/Signal-Android#5152] opened 2016-01-29 01:33 UTC
Swiping to close Signal in the recent apps list causes the Recent Apps List to close instead of staying open as expected.

[Debug Log](https://gist.github.com/anonymous/972b349bc9bb325d0d53)

**Comment by 2-4601** [comment] 2016-01-29 02:00
This is a duplicate of #1037.

**Closed by 2-4601** 2016-01-29 02:00 UTC
