### ISSUE TITLE
Indicating read messages

### ISSUE THREAD

**Issue by fbruetting** [WhisperSystems/Signal-Android#6133] opened 2017-01-31 22:26 UTC
The one thing I miss mostly in Signal is the ability to see if the recipient has read my message or not. Like e.g. the blue checkmarks of WhatsApp. Could this be implemented, please? Can't believe I found no feature request like this.

**Comment by rainerzufall** [comment] 2017-01-31 22:51
please close your issue. dupe of https://github.com/WhisperSystems/Signal-Android/issues/2667

moxie wrote: 

> Thanks but we've decided not to do this for now.

> 

 https://github.com/WhisperSystems/Signal-Android/issues/2667#issuecomment-79051895

**Comment by fbruetting** [comment] 2017-01-31 22:55
Thanks, but sad for moxie not giving a reason for this reglementation other messenger don't have…

**Closed** 2017-01-31 22:56 UTC

**Comment by moxie0** [comment] 2017-02-01 03:54
We might do it eventually, but any change that needs to be coordinated across platforms (android, ios, desktop) will take time

**Comment by fbruetting** [comment] 2017-02-09 23:05
Thanks, I assumed that this isn't wanted, but great to read that it might come in the future! :)
