### ISSUE TITLE
Rear camera not woring during video call ..in Signal app...could you help us...? Even application is very nice.

### ISSUE THREAD

**Issue by negi17** [WhisperSystems/Signal-Android#7003] opened 2017-09-28 23:40 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by FaizKhan5** [comment] 2017-09-29 00:25
close this issue and post on https://whispersystems.discoursehosting.net/

**Comment by nrizzio** [comment] 2017-09-29 01:10
Duplicate of #6279?

**Closed** 2017-09-29 01:21 UTC

**Comment by negi17** [comment] 2017-09-29 23:41
when using video call only working rear facing camera ...not working front camera although both camera working in whatsapp and FB messenger..
