### ISSUE TITLE
Argentina phone number schemes

### ISSUE THREAD

**Issue by drzraf** [WhisperSystems/Signal-Android#5270] opened 2016-02-21 00:38 UTC
Non-international phone number are not supported (contact does not appears during a search)

A mobile [phone number](https://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#Mobile_phone_numbers) can appear in multiple way here:
* +54 9 (area) (number)    
* 0054 9 (area) (number)
* (area) 15 (number) (if inside Argentina, whatever the caller area code is) 
* 15 (number) [if both numbers share the same area]

Where
* "9" is the magic number for mobile (equivalent to the local "15) and "1" for land-lines
* "15" is the magic number for mobile
* (number) contains 6 to 8 digits
* (area) can (optionally?) be prefixed by a trunk code of value "0", eg: 223 == 0223, or 11 == 011 (don't know about the cases of the trunk code being mandatory)

The area is somehow part of the number (since the number is registered for a unique and given area).
But it can be omitted if calling from a device from the same area (similarly to the country code 54 which can be omitted if we call from a national device)
Most contact's phone numbers are registered using the 4th scheme excepting contacts from other regions.

The Android API already provides the country code.
From this, it **may** be possible to know the area code (depending on the Android API?)
From the above two it should be fairly easy to map phones number from one scheme to another.

I don't know if heavy modifications are needed, but I could at least provide a PR to add test case.
https://github.com/WhisperSystems/Signal-Android/blob/master/test/unitTest/java/org/thoughtcrime/securesms/util/PhoneNumberFormatterTest.java ?

[edit]
It seems that most of the country-specific logic should be handled by the libphonenumber, and more specifically https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/test/com/google/i18n/phonenumbers/data/PhoneNumberMetadataProtoForTesting_AR
If it turns to be true, then what keeps the different notation to be understand as a unique contact?

**Comment by 2-4601** [comment] 2016-02-21 15:16
Is this different from #1511?

**Comment by drzraf** [comment] 2016-02-21 23:12
No.
I just did not found it (but can't believe I overlooked it)

the general issue could be stated:
"improve efforts in order to understand the various numbering schemes (optionally using libphonenumber data files)"

**Comment by 2-4601** [comment] 2016-02-21 23:19
Thanks for confirming. This seems quite complicated and probably needs a contribution from someone who understand how the Argentinian numbers work :)
Closing as dupe of #1511, so let's continue there (please add your research to that issue, thanks)

**Closed by 2-4601** 2016-02-21 23:19 UTC
