### ISSUE TITLE
A version without dependence on Google Play Services

### ISSUE THREAD

**Issue by androclus** [WhisperSystems/Signal-Android#5450] opened 2016-04-18 22:27 UTC
I love Signal, and have used it for some time and gotten several friends to start using it.

But recently I switched my Motorola Nexus 6 to (AOSP-based) [CyanogenMod](http://www.cyanogenmod.org/) 13.0.1 (Android 6.0.1 r17), and I don't want to install any Google-compiled proprietary software on it.

I see that when I try to install a Signal 3.15.2 .apk from [APK Mirror](http://www.apkmirror.com/apk/open-whisper-systems/signal-private-messenger/signal-private-messenger-3-15-2-release/signal-private-messenger-3-15-2-3-android-apk-download/), it does install, and starts.  But when I get to the first screen, "Connect with Signal" where it is asking me for verification of my phone number so that it can register me, and I press the "Register" button, it then pops up a white message box saying, "Get Google Play services -- Signal won't run without Google Play services, which are missing from your phone." And gives me a link (which doesn't work -- no doubt to the Google Play Store) to "GET GOOGLE PLAY SERVICES".

Might it be possible to have a version of Signal without this dependency on having [Google Play services](https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en) installed?

Thanks!

**Comment by agrajaghh** [comment] 2016-04-18 22:56
duplicate of several issues, e.g. #127 #1000 #1106

**Closed by agrajaghh** 2016-04-18 22:56 UTC

**Comment by dumblob** [comment] 2016-04-23 20:28
Because all the refernced duplicate discussion threads trying to solve this are locked (**why?**), I'm raising my voice for this here.

By the way, it would be very beneficial also for other devices running only Android VM, but not Android itself (like BlackBerry 10, Jolla OS, etc.).

**Comment by jgkamat** [comment] 2016-04-25 16:39
Have you looked at [libresignal?](https://github.com/LibreSignal/LibreSignal), I think that would solve your issue.
