### ISSUE TITLE
Don't send me friend suggestions in the middle of the night

### ISSUE THREAD

**Issue by nh2** [WhisperSystems/Signal-Android#4904] opened 2015-12-17 03:01 UTC
I just got a `XXX is on Signal, say hey!`, with vibration, at 03:52 am while in bed.

Please don't do that.

**Comment by jeremymasters** [comment] 2015-12-17 03:50
Does that notification not obey the system settings for do not disturb?  Seems like this wouldn't be the only app that could potentially notify in the night.

**Comment by moxie0** [comment] 2015-12-17 07:29
duplicate of #4572

**Closed by moxie0** 2015-12-17 07:29 UTC
