### ISSUE TITLE
App is not usable without Google Play Services

### ISSUE THREAD

**Issue by folsfols** [WhisperSystems/Signal-Android#4508] opened 2015-11-12 23:46 UTC
I realize this feature is likely necessary to have anything close to sane battery usage/savings, but for those of us who run Cyanogen without any google service installed, it makes it impossible to benefit from the Signal app.

It would be awesome if you were to make an option/version that would function without the push notifications of google.

Keep up the good work!

**Comment by moxie0** [comment] 2015-11-12 23:48
duplicate of #127

**Closed by moxie0** 2015-11-12 23:48 UTC
