### ISSUE TITLE
Facility to set user status and photo which all friends can see is missing. I think this is must

### ISSUE THREAD

**Issue by arunhappiest** [WhisperSystems/Signal-Android#6359] opened 2017-03-10 18:30 UTC
### Bug description
Facility to set user status and photo which all friends can see is missing. I think this is must
Any chat app should allow user to set their photo and status message which increases any app usage.
 
### Steps to reproduce
-- Click on any signal friend and what I see is what i stored in my Phonebook and not the status or photo set by user/friend.
This feature can take signal to next level.

**Actual result:** Just colors assigned to each friend and name as in my phonebook.
**Expected result:** Need something like whatsapp status , facebook status, telegram status and photos in each user profile, This will make signal no.1 app.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by p4nci** [comment] 2017-03-10 20:15
profile: duplicate of https://github.com/WhisperSystems/Signal-Android/issues/706
status: duplicate of https://github.com/WhisperSystems/Signal-Android/issues/3252

**Closed** 2017-03-13 20:08 UTC
