### ISSUE TITLE
Add support for a TOR connection using Orbot Proxy application

### ISSUE THREAD

**Issue by ghsrcgh** [WhisperSystems/Signal-Android#6697] opened 2017-06-02 17:32 UTC
Please add a support for a TOR connection using pre-installed Orbot Proxy application. I.e. user in options will be able to select connection using a TOR proxy (Orbot).

It is required to use on non-rooted devices, without any VPN/etc mode.

This option is available in ChatSecure, Antox (Tox), Xabbix and so on.

**Comment by nrizzio** [comment] 2017-06-02 17:46
This is a duplicate of #1187. In the future, [please read the contributing guidelines](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) before creating an issue.

**Closed** 2017-06-02 19:18 UTC
